import {
  AlertOutlined, ArrowDownOutlined, ArrowLeftOutlined, ArrowRightOutlined, ArrowUpOutlined, AudioOutlined, BarChartOutlined, BellOutlined, BlockOutlined, CalendarOutlined, CheckOutlined, ClockCircleOutlined, CloseOutlined, ContainerOutlined, CopyOutlined, DeleteOutlined, DownOutlined, DownloadOutlined, EditOutlined, EllipsisOutlined, EyeInvisibleOutlined, EyeOutlined, FileAddOutlined, FilterOutlined, GithubOutlined, GlobalOutlined, HeartOutlined, HomeOutlined, InboxOutlined, InfoCircleOutlined, LayoutOutlined, LeftOutlined, LinkOutlined, LoadingOutlined, LockOutlined, LoginOutlined, LogoutOutlined, MenuOutlined, MessageOutlined, MinusOutlined, MoonOutlined, MoreOutlined, PaperClipOutlined, PlayCircleOutlined, PlusOutlined, QuestionCircleOutlined, RadarChartOutlined, ReloadOutlined, RightOutlined, RobotOutlined, SearchOutlined, SendOutlined, SettingOutlined, ShoppingCartOutlined, SlidersOutlined, SmileOutlined, StarOutlined, SunOutlined, TagOutlined, TeamOutlined, ThunderboltOutlined, ToolOutlined, UpOutlined, UploadOutlined, UserOutlined, CheckSquareOutlined, UnorderedListOutlined,
} from "@ant-design/icons"
import { Icon as SharedIcon } from "@ui-gallery/icons-react"
import type { ReactNode } from "react"

const native: Record<string, React.ComponentType<{ style?: React.CSSProperties; className?: string }>> = {
  activity: RadarChartOutlined, "alert-circle": AlertOutlined, archive: ContainerOutlined, "arrow-down": ArrowDownOutlined, "arrow-left": ArrowLeftOutlined, "arrow-right": ArrowRightOutlined, "arrow-up": ArrowUpOutlined, "bar-chart": BarChartOutlined, bell: BellOutlined, bot: RobotOutlined, boxes: BlockOutlined, calendar: CalendarOutlined, check: CheckOutlined, "chevron-down": DownOutlined, "chevron-left": LeftOutlined, "chevron-right": RightOutlined, "chevron-up": UpOutlined, "circle-help": QuestionCircleOutlined, clipboard: CopyOutlined, clock: ClockCircleOutlined, copy: CopyOutlined, download: DownloadOutlined, edit: EditOutlined, "ellipsis-horizontal": EllipsisOutlined, "eye-off": EyeInvisibleOutlined, eye: EyeOutlined, "file-plus": FileAddOutlined, filter: FilterOutlined, github: GithubOutlined, globe: GlobalOutlined, grid: BlockOutlined, heart: HeartOutlined, home: HomeOutlined, inbox: InboxOutlined, info: InfoCircleOutlined, "layout-dashboard": LayoutOutlined, link: LinkOutlined, list: UnorderedListOutlined, loader: LoadingOutlined, lock: LockOutlined, "log-in": LoginOutlined, "log-out": LogoutOutlined, menu: MenuOutlined, "message-circle": MessageOutlined, "message-square": MessageOutlined, mic: AudioOutlined, minus: MinusOutlined, "more-horizontal": MoreOutlined, moon: MoonOutlined, paperclip: PaperClipOutlined, pencil: EditOutlined, play: PlayCircleOutlined, plug: ToolOutlined, plus: PlusOutlined, refresh: ReloadOutlined, search: SearchOutlined, send: SendOutlined, settings: SettingOutlined, shield: CheckSquareOutlined, "shopping-cart": ShoppingCartOutlined, sliders: SlidersOutlined, sparkles: SmileOutlined, star: StarOutlined, sun: SunOutlined, tag: TagOutlined, trash: DeleteOutlined, type: UnorderedListOutlined, upload: UploadOutlined, user: UserOutlined, users: TeamOutlined, x: CloseOutlined, zap: ThunderboltOutlined,
}
const family = () => new URLSearchParams(window.location.search).get("icons") ?? "native"
export function Icon({ name, size = 16, className }: { name: string; size?: number | string; className?: string }): ReactNode {
  if (family() !== "native") return <SharedIcon name={name} size={size} className={className} />
  const Component = native[name] ?? QuestionCircleOutlined
  return <Component style={{ fontSize: size }} className={className} />
}
