import { Link } from "react-router-dom"
import { Avatar, AvatarGroup, Button, Card, Collapse, Col, Image, Menu, Row, Select, Space, Swiper, Switch, Tag, Typography } from "tdesign-react"
import { Icon } from "@/components/icon"
import landing from "@ui-gallery/spec/mock/landing.json"
import plans from "@ui-gallery/spec/mock/plans.json"

export function LandingPage() {
  return <div>
    <LayoutHeader />
    <main>
      <section className="landing-section landing-hero"><div className="stack"><Tag theme="primary">ACME CONSOLE · 2026</Tag><Typography.Title level="h1">{landing.hero.title}</Typography.Title><Typography.Paragraph>{landing.hero.subtitle}</Typography.Paragraph><Space><Link to="/login"><Button theme="primary" size="large">{landing.hero.primary} <Icon name="arrow-right" /></Button></Link><Button variant="outline" size="large">{landing.hero.secondary}</Button></Space><div className="inline"><AvatarGroup max={3}><Avatar>林</Avatar><Avatar>王</Avatar><Avatar>A</Avatar><Avatar>M</Avatar></AvatarGroup><Typography.Text>{landing.hero.social}</Typography.Text></div></div><Card><Image src={productImage} alt="产品截图" fit="cover" style={{ width: "100%", height: 280 }} /></Card></section>
      <section className="landing-section" style={{ paddingTop: 24 }}><div className="grid-three">{["Northwind", "Contoso", "Globex", "Fabrikam", "Initech", "Umbrella"].map((name) => <Typography.Text key={name} style={{ textAlign: "center", color: "var(--td-text-color-secondary)" }}>{name}</Typography.Text>)}</div></section>
      <section id="features" className="landing-section"><div className="page-heading"><div><Typography.Title level="h2">一个地方，完成所有工作</Typography.Title><Typography.Paragraph>从数据到决策，让每一步都更清晰。</Typography.Paragraph></div></div><div className="grid-three">{landing.features.map((item) => <Card key={item.title}><div className="stack"><Tag shape="round"><Icon name={item.icon} /></Tag><Typography.Title level="h4">{item.title}</Typography.Title><Typography.Paragraph>{item.desc}</Typography.Paragraph></div></Card>)}</div></section>
      <section className="landing-section"><div className="stack">{["看见全局", "自动化协作", "AI 就在身边"].map((title, index) => <Row gutter={[32, 24]} align="middle" key={title}><Col xs={24} md={12}><Card><Image src={productImage} alt={title} fit="cover" style={{ width: "100%", height: 220 }} /></Card></Col><Col xs={24} md={12}><div className="stack"><Tag>0{index + 1} / WORKSPACE</Tag><Typography.Title level="h2">{title}</Typography.Title><Typography.Paragraph>{landing.features[index + 1].desc} 汇聚有用的洞察，让团队快速行动并持续交付。</Typography.Paragraph><Button variant="text">了解更多 <Icon name="arrow-right" /></Button></div></Col></Row>)}</div></section>
      <section className="landing-section"><div className="grid-four">{landing.numbers.map((item) => <div style={{ textAlign: "center" }} key={item.label}><Typography.Title level="h2">{item.value}</Typography.Title><Typography.Text>{item.label}</Typography.Text></div>)}</div></section>
      <section id="pricing" className="landing-section"><div className="page-heading"><div><Typography.Title level="h2">选择适合你的方案</Typography.Title><Typography.Paragraph>简单透明，随时升级。</Typography.Paragraph></div><Switch label={["月", "年"]} /></div><div className="grid-three">{plans.map((plan) => <Card key={plan.name} title={<div className="inline" style={{ justifyContent: "space-between" }}><span>{plan.name}</span>{plan.recommended && <Tag theme="primary">推荐</Tag>}</div>} bordered><Typography.Title level="h2">{plan.price === null ? "定制" : plan.price === 0 ? "免费" : `¥${plan.price}`}<Typography.Text> / 月</Typography.Text></Typography.Title><div className="stack">{plan.features.map((feature) => <Typography.Text key={feature}><Icon name="check" /> {feature}</Typography.Text>)}</div><Button block theme={plan.recommended ? "primary" : "default"} style={{ marginTop: 20 }}>开始使用</Button></Card>)}</div></section>
      <section className="landing-section"><Typography.Title level="h2">他们已经在改变工作方式</Typography.Title><Swiper className="landing-testimonials" height={180} autoplay={false} type="card">{landing.testimonials.map((item) => <Swiper.SwiperItem key={item.name}><Card><Typography.Paragraph>“{item.quote}”</Typography.Paragraph><Typography.Text>{item.name} · {item.company}</Typography.Text></Card></Swiper.SwiperItem>)}</Swiper></section>
      <section id="faq" className="landing-section"><Typography.Title level="h2">常见问题</Typography.Title><Collapse>{landing.faq.map((item) => <Collapse.Panel key={item.q} header={item.q} value={item.q}>{item.a}</Collapse.Panel>)}</Collapse></section>
      <section className="landing-section"><Card theme="poster1"><div className="stack"><Typography.Title level="h2">准备好让团队更高效了吗？</Typography.Title><Typography.Paragraph>从今天开始，把工作放进一个控制台。</Typography.Paragraph><Link to="/login"><Button theme="primary">免费开始</Button></Link></div></Card></section>
    </main>
    <footer className="landing-section" style={{ paddingTop: 24, paddingBottom: 24 }}><div className="grid-four"><div><Typography.Title level="h4">Acme Console</Typography.Title><Typography.Text>© 2026 Acme Console</Typography.Text><div className="inline"><Button shape="circle" icon={<Icon name="github" />} /><Button shape="circle" icon={<Icon name="globe" />} /></div></div>{["产品", "资源", "公司", "社交"].map((title) => <div className="stack" key={title}><Typography.Text strong>{title}</Typography.Text><Link to="/dashboard">概览</Link><Link to="/components">组件</Link><Link to="/settings">设置</Link></div>)}<Select options={[{ label: "简体中文", value: "zh-CN" }]} defaultValue="zh-CN" /></div></footer>
  </div>
}

const productImage = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='960' height='540'%3E%3Crect width='960' height='540' fill='%23e8f0ff'/%3E%3Crect x='48' y='48' width='864' height='444' rx='24' fill='%23ffffff'/%3E%3Crect x='92' y='100' width='300' height='24' rx='12' fill='%235c8df6'/%3E%3Crect x='92' y='160' width='720' height='16' rx='8' fill='%23dbe6fb'/%3E%3Crect x='92' y='220' width='320' height='180' rx='16' fill='%23eef3ff'/%3E%3Crect x='440' y='220' width='372' height='180' rx='16' fill='%23f5f7fa'/%3E%3C/svg%3E"

function LayoutHeader() {
  return <header className="app-header" style={{ position: "sticky", top: 0, zIndex: 2 }}><Link className="app-brand" to="/landing"><span className="app-brand-mark">A</span><span>Acme Console</span></Link><div className="app-header-spacer" /><Menu.HeadMenu className="desktop-only" value="features"><Menu.MenuItem value="features"><a href="#features">产品</a></Menu.MenuItem><Menu.MenuItem value="pricing"><a href="#pricing">价格</a></Menu.MenuItem><Menu.MenuItem value="faq"><a href="#faq">帮助中心</a></Menu.MenuItem></Menu.HeadMenu><Link to="/login"><Button theme="primary">免费开始</Button></Link></header>
}
