<script setup lang="ts">
import { ref } from "vue"
import { RouterLink } from "vue-router"
import landing from "@ui-gallery/spec/mock/landing.json"
import plans from "@ui-gallery/spec/mock/plans.json"
import { Icon } from "./shared"
const mobileOpen = ref(false)
const yearly = ref(false)
</script>
<template>
  <div class="landing">
    <nav class="landing-nav"><RouterLink class="brand" to="/"><span class="brand-mark">A</span><span>Acme Console</span></RouterLink><div class="landing-nav-links"><a href="#features">特性</a><a href="#product">产品</a><a href="#pricing">定价</a><a href="#faq">FAQ</a><a href="#contact">联系我们</a></div><a-space><a-button type="primary" href="/apps/ant-design-vue/login">立即开始</a-button><a-button class="mobile-menu" type="text" @click="mobileOpen = true"><Icon name="menu" /></a-button></a-space></nav>
    <a-drawer v-model:open="mobileOpen" title="导航"><a-menu><a-menu-item>特性</a-menu-item><a-menu-item>产品</a-menu-item><a-menu-item>定价</a-menu-item><a-menu-item>FAQ</a-menu-item><a-menu-item>联系我们</a-menu-item></a-menu></a-drawer>
    <section class="hero"><div><a-tag color="blue">Acme Console</a-tag><h1>{{ landing.hero.title }}</h1><p class="hero-subtitle">{{ landing.hero.subtitle }}</p><a-space><a-button type="primary" size="large">{{ landing.hero.primary }}</a-button><a-button size="large">{{ landing.hero.secondary }}</a-button></a-space><p class="muted"><a-avatar-group><a-avatar v-for="name in ['林', '王', 'A', 'M', '陈']" :key="name">{{ name }}</a-avatar></a-avatar-group> {{ landing.hero.social }}</p></div><div class="hero-shot">产品截图占位</div></section>
    <section class="landing-section"><a-row :gutter="[16, 16]"><a-col v-for="i in 6" :key="i" :xs="12" :md="4"><div class="placeholder" style="min-height:80px">Logo</div></a-col></a-row></section>
    <section id="features" class="landing-section"><a-typography-title :level="2">为团队而生的控制台</a-typography-title><a-row :gutter="[16, 16]"><a-col v-for="feature in landing.features" :key="feature.title" :xs="24" :sm="12" :md="8"><a-card class="feature-card"><Icon :name="feature.icon" :size="28" /><a-typography-title :level="4">{{ feature.title }}</a-typography-title><p>{{ feature.desc }}</p></a-card></a-col></a-row></section>
    <section id="product" class="landing-section"><div v-for="(feature, i) in landing.features.slice(0, 3)" :key="feature.title" class="split section"><div :style="{ order: i % 2 ? 2 : 1 }"><a-typography-title :level="2">{{ feature.title }}</a-typography-title><p class="muted">{{ feature.desc }}</p><a-typography-link href="#">了解更多 →</a-typography-link></div><div class="placeholder">产品模块 {{ i + 1 }}</div></div></section>
    <section class="landing-section"><a-row :gutter="[16, 16]"><a-col v-for="number in landing.numbers" :key="number.label" :xs="12" :md="6"><a-statistic :value="number.value" :title="number.label" /></a-col></a-row></section>
    <section id="pricing" class="landing-section"><div class="section-title"><a-typography-title :level="2">简单透明的定价</a-typography-title><a-switch v-model:checked="yearly" checked-children="年付" un-checked-children="月付" /></div><a-row :gutter="[16, 16]"><a-col v-for="plan in plans" :key="plan.name" :xs="24" :md="8"><a-badge-ribbon v-if="plan.recommended" text="推荐" color="blue"><a-card class="feature-card" :title="plan.name"><a-statistic :value="plan.price === null ? '联系销售' : yearly ? plan.price * 10 : plan.price" :prefix="plan.price === null ? '' : '¥'" :suffix="plan.price === null ? '' : '/月'" /><a-list size="small" :data-source="plan.features"><template #renderItem="{ item }"><a-list-item>✓ {{ item }}</a-list-item></template></a-list><a-button block :type="plan.recommended ? 'primary' : 'default'">选择 {{ plan.name }}</a-button></a-card></a-badge-ribbon><a-card v-else class="feature-card" :title="plan.name"><a-statistic :value="plan.price === null ? '联系销售' : yearly ? plan.price * 10 : plan.price" :prefix="plan.price === null ? '' : '¥'" /><a-list size="small" :data-source="plan.features"><template #renderItem="{ item }"><a-list-item>✓ {{ item }}</a-list-item></template></a-list></a-card></a-col></a-row></section>
    <section class="landing-section"><a-typography-title :level="2">客户怎么说</a-typography-title><a-row :gutter="[16, 16]"><a-col v-for="item in landing.testimonials" :key="item.name" :xs="24" :sm="12" :md="8"><a-card><a-comment :author="`${item.name} · ${item.company}`" :content="item.quote" /></a-card></a-col></a-row></section>
    <section id="faq" class="landing-section"><a-typography-title :level="2">常见问题</a-typography-title><a-collapse accordion><a-collapse-panel v-for="item in landing.faq" :key="item.q" :header="item.q">{{ item.a }}</a-collapse-panel></a-collapse></section>
    <section id="contact" class="landing-section"><a-card class="cta"><a-typography-title :level="2">准备好开始了吗？</a-typography-title><a-button type="primary" size="large">免费开始</a-button></a-card></section>
    <footer class="landing-section"><a-row :gutter="[16, 16]"><a-col v-for="column in ['产品', '资源', '公司', '支持']" :key="column" :xs="12" :md="6"><strong>{{ column }}</strong><p><a href="#">概览</a></p><p><a href="#">文档</a></p><p><a href="#">联系我们</a></p></a-col></a-row><a-divider /><div class="muted">© 2026 Acme Console · <a-select size="small" default-value="zh-CN"><a-select-option value="zh-CN">简体中文</a-select-option><a-select-option value="en">English</a-select-option></a-select></div></footer>
  </div>
</template>
<style scoped>.hero-subtitle { font-size:18px; max-width:560px; margin-bottom:28px; color:var(--ant-color-text-secondary); }.section-title { display:flex; justify-content:space-between; align-items:center; }.cta { text-align:center; padding:32px; }</style>
