<script setup lang="ts">
import { ref } from "vue"
import { Modal, message } from "ant-design-vue"
import sessions from "@ui-gallery/spec/mock/sessions.json"
import team from "@ui-gallery/spec/mock/team.json"
import plans from "@ui-gallery/spec/mock/plans.json"
import invoices from "@ui-gallery/spec/mock/invoices.json"
import { initials, statusColor, statusLabel } from "./shared"
const tab = ref("profile")
const deleteText = ref("")
function deleteAccount() { Modal.confirm({ title: "删除账户", content: "此操作不可撤销，确定继续吗？", okType: "danger", onOk: () => message.success("删除请求已提交") }) }
</script>
<template>
  <div class="page"><a-typography-title :level="1">设置</a-typography-title><a-tabs v-model:active-key="tab" tab-position="left" class="settings-tabs">
    <a-tab-pane key="profile" tab="个人资料"><a-card title="个人资料"><a-form layout="vertical"><a-form-item label="头像"><a-upload><a-avatar :size="72">林</a-avatar><a-button>更换头像</a-button></a-upload></a-form-item><a-form-item label="姓名"><a-input value="林晓" /></a-form-item><a-form-item label="简介"><a-textarea value="Acme Console 管理员" /></a-form-item><a-form-item label="语言"><a-select value="zh-CN"><a-select-option value="zh-CN">简体中文</a-select-option><a-select-option value="en-US">English</a-select-option></a-select></a-form-item><a-form-item label="时区"><a-select show-search value="Asia/Shanghai"><a-select-option value="Asia/Shanghai">Asia/Shanghai</a-select-option><a-select-option value="Europe/Berlin">Europe/Berlin</a-select-option></a-select></a-form-item><a-button type="primary">保存更改</a-button></a-form></a-card></a-tab-pane>
    <a-tab-pane key="security" tab="账号安全"><a-card title="修改密码"><a-form layout="vertical"><a-form-item label="当前密码"><a-input-password /></a-form-item><a-form-item label="新密码"><a-input-password /></a-form-item><a-button type="primary">更新密码</a-button></a-form></a-card><a-card title="两步验证" class="section"><a-switch checked /> 已启用<a-qrcode value="https://acme.dev/security" class="section" /></a-card><a-card title="活跃会话" class="section"><a-list :data-source="sessions"><template #renderItem="{ item }"><a-list-item><a-list-item-meta :title="item.device" :description="`${item.location} · ${item.time}`" /><a-tag v-if="item.current" color="success">当前设备</a-tag><a-button v-else>注销</a-button></a-list-item></template></a-list></a-card></a-tab-pane>
    <a-tab-pane key="notifications" tab="通知"><a-card title="通知偏好"><a-segmented :options="['邮件', '推送', '站内']" /><a-list class="section"><a-list-item v-for="label in ['订单状态更新', '团队活动', '产品公告']" :key="label"><span>{{ label }}</span><a-switch checked /></a-list-item></a-list></a-card></a-tab-pane>
    <a-tab-pane key="team" tab="团队"><a-card title="团队成员"><div class="table-wrap"><a-table :data-source="team" :pagination="false" :scroll="{ x: 650 }" row-key="email"><a-table-column title="成员"><template #default="{ record }"><a-avatar size="small">{{ initials(record.name) }}</a-avatar> {{ record.name }}</template></a-table-column><a-table-column title="角色"><template #default="{ record }"><a-select :value="record.role" style="width:120px"><a-select-option value="owner">所有者</a-select-option><a-select-option value="admin">管理员</a-select-option><a-select-option value="member">成员</a-select-option><a-select-option value="viewer">查看者</a-select-option></a-select></template></a-table-column><a-table-column title="最近活跃" data-index="lastActive" /><a-table-column title="操作"><template #default="{ record }"><a-button danger type="link" :disabled="record.role === 'owner'">移除</a-button></template></a-table-column></a-table></div><a-space class="section"><a-input placeholder="输入邮箱邀请成员" /><a-button type="primary">邀请</a-button></a-space></a-card></a-tab-pane>
    <a-tab-pane key="billing" tab="计费"><a-card title="当前计划"><a-statistic title="Pro" prefix="¥" :value="99" suffix="/月" /><a-progress :percent="68" /></a-card><div class="card-grid section"><a-card v-for="plan in plans" :key="plan.name" :title="plan.name"><a-badge-ribbon v-if="plan.recommended" text="推荐" color="blue"><span /></a-badge-ribbon><a-statistic :value="plan.price ?? '联系销售'" :prefix="plan.price !== null ? '¥' : ''" /><a-list size="small" :data-source="plan.features"><template #renderItem="{ item }"><a-list-item>✓ {{ item }}</a-list-item></template></a-list><a-button block :type="plan.recommended ? 'primary' : 'default'">选择计划</a-button></a-card></div><a-card title="发票" class="section"><a-table :data-source="invoices" :pagination="false" row-key="id"><a-table-column title="编号" data-index="id" /><a-table-column title="日期" data-index="date" /><a-table-column title="金额"><template #default="{ record }">¥{{ record.amount }}</template></a-table-column><a-table-column title="状态"><template #default="{ record }"><a-tag :color="statusColor[record.status]">{{ statusLabel[record.status] }}</a-tag></template></a-table-column></a-table></a-card></a-tab-pane>
  </a-tabs><a-card title="危险区" class="danger-zone section"><p>删除账户将永久移除工作区数据。</p><a-input v-model:value="deleteText" placeholder="输入 &quot;DELETE&quot; 以启用按钮" style="max-width:280px" /><a-button danger :disabled="deleteText !== 'DELETE'" @click="deleteAccount">删除账户</a-button></a-card></div>
</template>
<style scoped>.settings-tabs :deep(.ant-tabs-content-holder) { min-width: 0; }.danger-zone { border-color: var(--app-color-error); }.danger-zone .ant-btn { margin-left: 12px; }</style>
