import type { ComponentType, SVGProps } from "react"
import {
  ArchiveIcon,
  BellIcon,
  CalendarIcon,
  ChatBubbleIcon,
  CheckCircledIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ClipboardCopyIcon,
  ComponentInstanceIcon,
  CopyIcon,
  Cross2Icon,
  CubeIcon,
  DashboardIcon,
  DotsHorizontalIcon,
  DownloadIcon,
  EyeClosedIcon,
  EyeOpenIcon,
  FilePlusIcon,
  GearIcon,
  GlobeIcon,
  HamburgerMenuIcon,
  InfoCircledIcon,
  LockClosedIcon,
  MagnifyingGlassIcon,
  MinusIcon,
  MoonIcon,
  MixerHorizontalIcon,
  PersonIcon,
  PlusIcon,
  QuestionMarkCircledIcon,
  StarFilledIcon,
  StarIcon,
  SunIcon,
  TrashIcon,
  UpdateIcon,
  UploadIcon,
} from "@radix-ui/react-icons"
import { Icon as SharedIcon } from "@ui-gallery/icons-react"

type IconType = ComponentType<SVGProps<SVGSVGElement>>
type Props = SVGProps<SVGSVGElement> & { name: string; size?: number | string }

const native = {
  activity: UpdateIcon,
  "alert-circle": InfoCircledIcon,
  archive: ArchiveIcon,
  "arrow-down": ChevronDownIcon,
  "arrow-left": ChevronLeftIcon,
  "arrow-right": ChevronRightIcon,
  "arrow-up": ChevronUpIcon,
  "bar-chart": DashboardIcon,
  bell: BellIcon,
  bot: ComponentInstanceIcon,
  boxes: ComponentInstanceIcon,
  calendar: CalendarIcon,
  check: CheckIcon,
  "check-circle": CheckCircledIcon,
  "chevron-down": ChevronDownIcon,
  "chevron-left": ChevronLeftIcon,
  "chevron-right": ChevronRightIcon,
  "chevron-up": ChevronUpIcon,
  clipboard: ClipboardCopyIcon,
  clock: UpdateIcon,
  copy: CopyIcon,
  download: DownloadIcon,
  edit: GearIcon,
  "external-link": GlobeIcon,
  eye: EyeOpenIcon,
  "eye-off": EyeClosedIcon,
  "file-plus": FilePlusIcon,
  file: ArchiveIcon,
  filter: MixerHorizontalIcon,
  globe: GlobeIcon,
  grid: ComponentInstanceIcon,
  heart: StarIcon,
  home: DashboardIcon,
  inbox: ArchiveIcon,
  image: ComponentInstanceIcon,
  info: InfoCircledIcon,
  "layout-dashboard": DashboardIcon,
  loader: UpdateIcon,
  lock: LockClosedIcon,
  "log-in": PersonIcon,
  "log-out": PersonIcon,
  menu: HamburgerMenuIcon,
  "message-circle": ChatBubbleIcon,
  "message-square": ChatBubbleIcon,
  mail: ChatBubbleIcon,
  mic: ChatBubbleIcon,
  minus: MinusIcon,
  "more-horizontal": DotsHorizontalIcon,
  moon: MoonIcon,
  paperclip: UploadIcon,
  pencil: GearIcon,
  plus: PlusIcon,
  plug: ComponentInstanceIcon,
  refresh: UpdateIcon,
  search: MagnifyingGlassIcon,
  send: UploadIcon,
  settings: GearIcon,
  shield: LockClosedIcon,
  "shopping-cart": CubeIcon,
  sliders: MixerHorizontalIcon,
  sparkles: StarFilledIcon,
  star: StarIcon,
  sun: SunIcon,
  tag: ArchiveIcon,
  trash: TrashIcon,
  upload: UploadIcon,
  user: PersonIcon,
  users: PersonIcon,
  x: Cross2Icon,
  zap: UpdateIcon,
  "chevrons-up-down": MixerHorizontalIcon,
  "alert-triangle": InfoCircledIcon,
  "x-circle": Cross2Icon,
  "inbox-icon": ArchiveIcon,
} as unknown as Record<string, IconType>

export function Icon({ name, size = 18, ...props }: Props) {
  const params = new URLSearchParams(window.location.search)
  const family = params.get("icons") ?? params.get("icon")
  if (family && ["lucide", "tabler", "phosphor", "heroicons"].includes(family)) {
    return <SharedIcon name={name} size={size} />
  }
  const Component = native[name] ?? QuestionMarkCircledIcon
  return <Component width={size} height={size} {...(props as SVGProps<SVGSVGElement>)} />
}
