import { Component, signal } from '@angular/core';
import landing from '@ui-gallery/spec/mock/landing.json';
import { SHARED_IMPORTS } from '../shared/material';

@Component({
  selector: 'app-landing',
  standalone: true,
  imports: SHARED_IMPORTS,
  template: `
    <main class="landing-page">
      <mat-toolbar class="landing-nav"><a class="brand" routerLink="/landing"><span class="brand-mark"><mat-icon svgIcon="sparkles"></mat-icon></span>Acme Console</a><nav class="desktop-nav"><a mat-button href="#features">产品</a><a mat-button href="#stories">客户案例</a><a mat-button href="#faq">FAQ</a><a mat-button routerLink="/components">组件</a><a mat-button routerLink="/chat">AI 助手</a></nav><div class="nav-actions"><button mat-button routerLink="/login">登录</button><button mat-flat-button color="primary" routerLink="/login">开始使用</button><button class="mobile-only" mat-icon-button (click)="menuOpen.set(!menuOpen())" aria-label="打开菜单"><mat-icon svgIcon="menu"></mat-icon></button></div></mat-toolbar>
      @if (menuOpen()) {<div class="mobile-menu"><a mat-button href="#features" (click)="menuOpen.set(false)">产品</a><a mat-button href="#stories" (click)="menuOpen.set(false)">客户案例</a><a mat-button href="#faq" (click)="menuOpen.set(false)">FAQ</a><a mat-button routerLink="/components" (click)="menuOpen.set(false)">组件</a><a mat-button routerLink="/chat" (click)="menuOpen.set(false)">AI 助手</a><button mat-flat-button color="primary" routerLink="/login">开始使用</button></div>}
      <section class="landing-hero"><div class="hero-copy"><span class="chip"><mat-icon svgIcon="sparkles"></mat-icon> 新一代业务工作台</span><h1>{{ content.hero.title }}</h1><p class="hero-subtitle">{{ content.hero.subtitle }}</p><div class="demo-row"><button mat-flat-button color="primary" routerLink="/login">免费开始 <mat-icon svgIcon="arrow-right"></mat-icon></button><button mat-stroked-button routerLink="/components">探索组件</button></div><div class="avatar-proof"><div class="avatar-stack">@for (initial of ['林', '陈', '周', '王']; track initial) {<span class="avatar">{{ initial }}</span>}</div><span class="muted">已有 2,000+ 团队加入</span></div></div><div class="hero-visual"><div class="hero-window"><div class="window-bar"><span></span><span></span><span></span></div><div class="hero-dashboard"><div class="hero-dashboard-title"><b>本月收入</b><mat-icon svgIcon="more-vertical"></mat-icon></div><strong>¥128,430</strong><span class="status status-success">+12.4%</span><div class="hero-bars">@for (bar of [38, 55, 48, 74, 62, 88, 78]; track $index) {<span [style.height.%]="bar"></span>}</div></div></div></div></section>
      <section class="number-strip">@for (number of content.numbers; track number.label) {<div><strong>{{ number.value }}</strong><span class="muted">{{ number.label }}</span></div>}</section>
      <section id="features" class="landing-section"><div class="section-heading"><p class="eyebrow">EVERYTHING IN ONE PLACE</p><h2>让复杂工作变得简单</h2><p class="muted">从数据到协作，所有工具都在一个清晰、可扩展的工作台里。</p></div><div class="feature-grid">@for (feature of content.features; track feature.title) {<mat-card><mat-card-content><span class="feature-icon"><mat-icon [svgIcon]="feature.icon"></mat-icon></span><h3>{{ feature.title }}</h3><p class="muted">{{ feature.desc }}</p><a mat-button href="#stories">了解更多 <mat-icon svgIcon="arrow-right"></mat-icon></a></mat-card-content></mat-card>}</div></section>
      <section id="stories" class="landing-section testimonials-section"><div class="section-heading"><p class="eyebrow">LOVED BY TEAMS</p><h2>他们这样评价 Acme Console</h2></div><div class="testimonial-grid">@for (testimonial of content.testimonials; track testimonial.name) {<mat-card><mat-card-content><div class="stars">★★★★★</div><p>“{{ testimonial.quote }}”</p><div class="testimonial-author"><span class="avatar">{{ testimonial.name.slice(0, 1) }}</span><span><b>{{ testimonial.name }}</b><small class="muted">{{ testimonial.company }}</small></span></div></mat-card-content></mat-card>}</div></section>
      <section id="faq" class="landing-section faq-section"><div class="section-heading"><p class="eyebrow">FAQ</p><h2>常见问题</h2></div><mat-accordion>@for (item of content.faq; track item.q) {<mat-expansion-panel><mat-expansion-panel-header><mat-panel-title>{{ item.q }}</mat-panel-title></mat-expansion-panel-header><p class="muted">{{ item.a }}</p></mat-expansion-panel>}</mat-accordion></section>
      <section class="landing-cta"><div><p class="eyebrow">READY WHEN YOU ARE</p><h2>今天就开始构建更好的工作流</h2><p>无需信用卡，14 天免费试用。</p></div><button mat-flat-button routerLink="/login">开始免费试用 <mat-icon svgIcon="arrow-right"></mat-icon></button></section>
      <footer class="landing-footer"><div class="footer-brand"><a class="brand" routerLink="/landing"><span class="brand-mark"><mat-icon svgIcon="sparkles"></mat-icon></span>Acme Console</a><p class="muted">清晰、快速、可扩展的业务工作台。</p><div class="socials"><button mat-icon-button aria-label="微博"><mat-icon svgIcon="globe"></mat-icon></button><button mat-icon-button aria-label="邮件"><mat-icon svgIcon="mail"></mat-icon></button><button mat-icon-button aria-label="链接"><mat-icon svgIcon="link"></mat-icon></button></div></div><div class="footer-links"><div><b>产品</b><a href="#features">功能</a><a routerLink="/components">组件</a><a routerLink="/chat">AI 助手</a></div><div><b>资源</b><a href="#faq">帮助中心</a><a href="#stories">客户案例</a><a routerLink="/landing">更新日志</a></div><div><b>公司</b><a routerLink="/landing">关于我们</a><a routerLink="/landing">联系我们</a><a routerLink="/landing">招聘</a></div><div><b>语言</b><mat-form-field appearance="outline" subscriptSizing="dynamic"><mat-select value="zh-CN"><mat-option value="zh-CN">简体中文</mat-option><mat-option value="en-US">English</mat-option></mat-select></mat-form-field></div></div><div class="footer-bottom"><span class="muted">© 2026 Acme Console. All rights reserved.</span><span class="muted">隐私政策 · 服务条款</span></div></footer>
    </main>
  `,
})
export class LandingPage {
  readonly content = landing;
  readonly menuOpen = signal(false);
}
