import { Component, signal } from '@angular/core';
import landing from '@ui-gallery/spec/mock/landing.json';
import plans from '@ui-gallery/spec/mock/plans.json';
import { SHARED_IMPORTS } from '../shared/material';

type Plan = { name: string; price: number | null; recommended?: boolean; features: string[] };

@Component({
  selector: 'app-landing',
  standalone: true,
  imports: SHARED_IMPORTS,
  template: `
    <main class="landing-page">
      <mat-toolbar class="landing-nav"><a class="brand" routerLink="/landing"><span class="brand-mark"><mat-icon svgIcon="sparkles"></mat-icon></span>Acme Console</a><nav class="desktop-nav">@for (link of navLinks; track link.href) {<a mat-button [href]="link.href">{{ link.label }}</a>}</nav><div class="nav-actions"><a mat-button class="nav-login" routerLink="/login">登录</a><a mat-flat-button color="primary" routerLink="/login">{{ content.hero.primary }}</a><button class="mobile-only" mat-icon-button (click)="menuOpen.set(!menuOpen())" [attr.aria-expanded]="menuOpen()" aria-label="打开菜单"><mat-icon [svgIcon]="menuOpen() ? 'x' : 'menu'"></mat-icon></button></div></mat-toolbar>
      @if (menuOpen()) {<nav class="mobile-menu">@for (link of navLinks; track link.href) {<a mat-button [href]="link.href" (click)="menuOpen.set(false)">{{ link.label }}</a>}<a mat-button routerLink="/login">登录</a><a mat-flat-button color="primary" routerLink="/login">{{ content.hero.primary }}</a></nav>}
      <section class="landing-hero"><div class="hero-copy"><span class="chip"><mat-icon svgIcon="sparkles"></mat-icon> ACME CONSOLE · 2026</span><h1>{{ content.hero.title }}</h1><p class="hero-subtitle">{{ content.hero.subtitle }}</p><div class="demo-row"><a mat-flat-button color="primary" routerLink="/login">{{ content.hero.primary }} <mat-icon svgIcon="arrow-right"></mat-icon></a><a mat-stroked-button routerLink="/">{{ content.hero.secondary }}</a></div><div class="avatar-proof"><div class="avatar-stack">@for (testimonial of content.testimonials.slice(0, 4); track testimonial.name) {<span class="avatar">{{ testimonial.name.slice(0, 1) }}</span>}</div><span class="muted">{{ content.hero.social }}</span></div></div><div class="hero-visual"><div class="hero-window"><div class="window-bar"><span></span><span></span><span></span></div><div class="hero-dashboard"><div class="hero-dashboard-title"><b>{{ content.numbers[1].label }}</b><mat-icon svgIcon="more-vertical"></mat-icon></div><strong>{{ content.numbers[1].value }}</strong><span class="chip positive"><mat-icon svgIcon="trending-up"></mat-icon>{{ content.numbers[0].value }} {{ content.numbers[0].label }}</span><div class="hero-bars">@for (bar of [38, 55, 48, 74, 62, 88, 78]; track $index) {<span [style.height.%]="bar"></span>}</div></div></div></div></section>
      <section class="logo-cloud-section" aria-label="客户"><p class="muted logo-cloud-title">{{ content.hero.social }}</p><div class="logo-cloud">@for (testimonial of content.testimonials; track testimonial.company) {<div>{{ testimonial.company }}</div>}</div></section>
      <section id="features" class="landing-section"><div class="section-heading"><p class="eyebrow">FEATURES</p><h2>为团队打造的一站式工作台</h2><p class="muted">{{ content.hero.subtitle }}</p></div><div class="feature-grid">@for (feature of content.features; track feature.title) {<mat-card><mat-card-content><span class="feature-icon"><mat-icon [svgIcon]="feature.icon"></mat-icon></span><h3>{{ feature.title }}</h3><p class="muted">{{ feature.desc }}</p></mat-card-content></mat-card>}</div></section>
      <section id="product" class="landing-section split-section">@for (feature of content.features.slice(1, 4); track feature.title; let i = $index) {<div class="split" [class.reverse]="i % 2 === 1"><div class="split-copy"><span class="chip">0{{ i + 1 }} / WORKSPACE</span><h2>{{ feature.title }}</h2><p class="muted">{{ feature.desc }}</p><a mat-button routerLink="/">{{ content.hero.secondary }} <mat-icon svgIcon="arrow-right"></mat-icon></a></div><mat-card class="split-shot"><mat-card-content><div class="split-art"><mat-icon [svgIcon]="feature.icon"></mat-icon></div></mat-card-content></mat-card></div>}</section>
      <section class="number-strip">@for (number of content.numbers; track number.label) {<div><strong>{{ number.value }}</strong><span class="muted">{{ number.label }}</span></div>}</section>
      <section id="pricing" class="landing-section pricing-section"><div class="section-heading centered"><p class="eyebrow">PRICING</p><h2>选择适合你的方案</h2><div class="billing-toggle"><span [class.muted]="yearly()">按月</span><mat-slide-toggle [checked]="yearly()" (change)="yearly.set($event.checked)" aria-label="按年付费"></mat-slide-toggle><span [class.muted]="!yearly()">按年 <span class="chip">省 2 个月</span></span></div></div><div class="pricing-grid">@for (plan of plans; track plan.name) {<mat-card [class.recommended]="plan.recommended" [appearance]="plan.recommended ? 'raised' : 'outlined'"><mat-card-header><mat-card-title>{{ plan.name }}</mat-card-title>@if (plan.recommended) {<span class="chip">最受欢迎</span>}</mat-card-header><mat-card-content><p class="price">{{ priceLabel(plan.price) }}@if (plan.price) {<small class="muted"> / {{ yearly() ? '年' : '月' }}</small>}</p><mat-list>@for (feature of plan.features; track feature) {<mat-list-item><mat-icon matListItemIcon svgIcon="check"></mat-icon><span matListItemTitle>{{ feature }}</span></mat-list-item>}</mat-list></mat-card-content><mat-card-actions>@if (plan.recommended) {<a class="full" mat-flat-button color="primary" routerLink="/login">{{ content.hero.primary }}</a>} @else {<a class="full" mat-stroked-button routerLink="/login">{{ plan.price === null ? '联系销售' : content.hero.primary }}</a>}</mat-card-actions></mat-card>}</div></section>
      <section id="stories" class="landing-section testimonials-section"><div class="section-heading"><p class="eyebrow">LOVED BY TEAMS</p><h2>他们这样评价 Acme Console</h2></div><div class="testimonial-grid">@for (testimonial of content.testimonials; track testimonial.name) {<mat-card><mat-card-content><div class="stars" aria-label="5 星评价">★★★★★</div><p>“{{ testimonial.quote }}”</p><div class="testimonial-author"><span class="avatar">{{ testimonial.name.slice(0, 1) }}</span><span><b>{{ testimonial.name }}</b><small class="muted">{{ testimonial.company }}</small></span></div></mat-card-content></mat-card>}</div></section>
      <section id="faq" class="landing-section faq-section"><div class="section-heading"><p class="eyebrow">FAQ</p><h2>常见问题</h2></div><mat-accordion>@for (item of content.faq; track item.q) {<mat-expansion-panel><mat-expansion-panel-header><mat-panel-title>{{ item.q }}</mat-panel-title></mat-expansion-panel-header><p class="muted">{{ item.a }}</p></mat-expansion-panel>}</mat-accordion></section>
      <section class="landing-cta"><div><p class="eyebrow">READY WHEN YOU ARE</p><h2>{{ content.hero.title }}</h2><p>{{ content.faq[0].a }}</p></div><a mat-flat-button routerLink="/login">{{ content.hero.primary }} <mat-icon svgIcon="arrow-right"></mat-icon></a></section>
      <footer class="landing-footer"><div class="footer-brand"><a class="brand" routerLink="/landing"><span class="brand-mark"><mat-icon svgIcon="sparkles"></mat-icon></span>Acme Console</a><p class="muted">{{ content.hero.subtitle }}</p><div class="socials"><a mat-icon-button href="#features" aria-label="网站"><mat-icon svgIcon="globe"></mat-icon></a><a mat-icon-button href="#features" aria-label="邮件"><mat-icon svgIcon="mail"></mat-icon></a><a mat-icon-button href="#features" aria-label="链接"><mat-icon svgIcon="link"></mat-icon></a></div></div><div class="footer-links"><div><b>产品</b><a href="#features">功能</a><a href="#product">产品介绍</a><a href="#pricing">价格</a></div><div><b>资源</b><a href="#faq">帮助中心</a><a href="#stories">客户案例</a><a routerLink="/components">组件</a></div><div><b>公司</b><a routerLink="/landing">关于我们</a><a routerLink="/chat">AI 助手</a><a routerLink="/login">登录</a></div><div><b>语言</b><mat-form-field appearance="outline" subscriptSizing="dynamic"><mat-select value="zh-CN"><mat-option value="zh-CN">简体中文</mat-option><mat-option value="en-US">English</mat-option></mat-select></mat-form-field></div></div><div class="footer-bottom"><span class="muted">© 2026 Acme Console</span><span class="muted">隐私政策 · 服务条款</span></div></footer>
    </main>
  `,
})
export class LandingPage {
  readonly content = landing;
  readonly plans: Plan[] = plans;
  readonly menuOpen = signal(false);
  readonly yearly = signal(false);
  readonly navLinks = [
    { href: '#features', label: '功能' }, { href: '#product', label: '产品' }, { href: '#pricing', label: '价格' },
    { href: '#stories', label: '客户案例' }, { href: '#faq', label: 'FAQ' },
  ];

  priceLabel(price: number | null): string {
    if (price === null) return '定制';
    if (price === 0) return '免费';
    return `¥${this.yearly() ? price * 10 : price}`;
  }
}
