packages:
  - apps/*
  - packages/*
  - gallery
  - tools/*

allowBuilds:
  esbuild: true
  playwright: true
  playwright-core: true
  sharp: true
  "@parcel/watcher": true
  workerd: true
  core-js: false
  vue-demi: false
