import { useState } from "react"
import ReactMarkdown from "react-markdown"
import remarkGfm from "remark-gfm"
import { Icon as GalleryIcon } from "@ui-gallery/icons-react"
import chat from "@ui-gallery/spec/mock/chat.json"
import { Avatar, Badge, Box, Button, Card, Clipboard, Collapsible, Drawer, Flex, Heading, IconButton, Input, InputGroup, Portal, Select, Skeleton, Spinner, Stack, Table, Tag, Text, Textarea } from "@chakra-ui/react"
import { createListCollection } from "@chakra-ui/react"
import { PageHeader } from "./shared"

function Icon({ name, width, height, size }: { name: string; width?: string; height?: string; size?: string | number }) {
  return <GalleryIcon name={name} size={size ?? width ?? height} />
}

const models = createListCollection({ items: chat.models.map((value) => ({ label: value, value })) })

export function ChatPage() {
  const [draft, setDraft] = useState("")
  const [active, setActive] = useState<string | null>(chat.conversations[0]?.id ?? null)
  const [mobileOpen, setMobileOpen] = useState(false)
  return <Stack gap="6"><PageHeader title="AI 对话" description="与团队智能助手协作，保留完整上下文。" /><Flex borderWidth="1px" rounded="l3" minH="620px" overflow="hidden" direction={{ base: "column", lg: "row" }}><Drawer.Root open={mobileOpen} onOpenChange={(details) => setMobileOpen(details.open)} placement="start"><Drawer.Trigger asChild><Button hideFrom="lg" m="3" alignSelf="start" variant="outline"><Icon name="menu" width="16" height="16" />会话列表</Button></Drawer.Trigger><Portal><Drawer.Backdrop /><Drawer.Positioner><Drawer.Content><Drawer.Header><Drawer.Title>对话</Drawer.Title></Drawer.Header><Drawer.Body><ConversationList active={active} onSelect={(id) => { setActive(id); setMobileOpen(false) }} /></Drawer.Body></Drawer.Content></Drawer.Positioner></Portal></Drawer.Root><Box width={{ base: "full", lg: "280px" }} borderEndWidth={{ lg: "1px" }} borderBottomWidth={{ base: "1px", lg: "0" }} p="4" hideBelow="lg"><ConversationList active={active} onSelect={setActive} /></Box><Flex flex="1" minW="0" direction="column"><Flex px="4" py="3" borderBottomWidth="1px" justify="space-between" align="center" gap="3"><Box minW="0"><Text fontWeight="medium" truncate>{active ? chat.conversations.find((item) => item.id === active)?.title : "新建对话"}</Text><Text fontSize="xs" color="fg.muted">模型已连接</Text></Box><Select.Root collection={models} defaultValue={[models.items[0].value]} width="180px"><Select.HiddenSelect /><Select.Control><Select.Trigger><Select.ValueText /></Select.Trigger><Select.IndicatorGroup><Select.Indicator /></Select.IndicatorGroup></Select.Control><Select.Positioner><Select.Content>{models.items.map((item) => <Select.Item item={item} key={item.value}>{item.label}</Select.Item>)}</Select.Content></Select.Positioner></Select.Root></Flex>{active ? <><Box flex="1" overflowY="auto" p="4"><Stack gap="6">{chat.messages.map((message, index) => <Message key={`${message.role}-${index}`} message={message} />)}<Flex gap="3" align="center"><Avatar.Root size="sm"><Avatar.Fallback name="AI" /></Avatar.Root><Stack gap="2"><Skeleton height="3" width="220px" /><Skeleton height="3" width="150px" /></Stack><Spinner size="sm" /></Flex></Stack></Box><Composer draft={draft} setDraft={setDraft} /></> : <EmptyChat onStart={() => setActive(chat.conversations[0]?.id ?? null)} />}</Flex></Flex></Stack>
}

function ConversationList({ active, onSelect }: { active: string | null; onSelect: (id: string | null) => void }) {
  return <Stack gap="3"><Flex justify="space-between" align="center"><Text fontWeight="semibold">对话</Text><IconButton aria-label="新建对话" variant="ghost" onClick={() => onSelect(null)}><Icon name="plus" width="16" height="16" /></IconButton></Flex><InputGroup startElement={<Icon name="search" width="16" height="16" />}><Input placeholder="搜索对话" /></InputGroup><Button onClick={() => onSelect(null)}><Icon name="plus" width="16" height="16" />新建对话</Button><Stack gap="1">{chat.conversations.map((item) => <Button key={item.id} variant={active === item.id ? "subtle" : "ghost"} justifyContent="start" height="auto" py="3" onClick={() => onSelect(item.id)}><Box textAlign="start" flex="1" minW="0"><Text truncate>{item.title}</Text><Text fontSize="xs" color="fg.muted">{item.time}</Text></Box>{item.unread ? <Badge>{item.unread}</Badge> : null}</Button>)}</Stack></Stack>
}

function Message({ message }: { message: typeof chat.messages[number] }) {
  const isUser = message.role === "user"
  return <Flex gap="3" align="start" direction={isUser ? "row-reverse" : "row"}><Avatar.Root size="sm"><Avatar.Fallback name={isUser ? "林晓" : "AI 助手"} /></Avatar.Root><Stack maxW="min(720px, 85%)" alignItems={isUser ? "flex-end" : "flex-start"}><Text fontSize="xs" color="fg.muted">{isUser ? "林晓" : "AI 助手"} · 刚刚</Text><Box rounded="l2" bg={isUser ? "colorPalette.subtle" : "bg.subtle"} px="4" py="3" fontSize="sm"><ReactMarkdown remarkPlugins={[remarkGfm]} components={{ code({ children }) { const text = String(children).replace(/\n$/, ""); return <Clipboard.Root value={text}><Box position="relative"><Clipboard.Trigger asChild><Button size="xs" position="absolute" top="0" right="0" variant="ghost">复制</Button></Clipboard.Trigger><Box as="pre" overflowX="auto" pt="6"><code>{children}</code></Box></Box></Clipboard.Root> }, table({ children }) { return <Table.Root size="sm" variant="outline">{children}</Table.Root> }, thead({ children }) { return <Table.Header>{children}</Table.Header> }, tbody({ children }) { return <Table.Body>{children}</Table.Body> }, tr({ children }) { return <Table.Row>{children}</Table.Row> }, th({ children }) { return <Table.ColumnHeader>{children}</Table.ColumnHeader> }, td({ children }) { return <Table.Cell>{children}</Table.Cell> } }}>{message.content}</ReactMarkdown></Box>{message.sources ? <Flex gap="2" wrap="wrap">{message.sources.map((source) => <Tag.Root key={source} size="sm"><Tag.Label>{source}</Tag.Label></Tag.Root>)}</Flex> : null}{message.tool ? <Collapsible.Root width="full"><Collapsible.Trigger asChild><Button variant="outline" size="sm">工具调用 · {message.tool.name}</Button></Collapsible.Trigger><Collapsible.Content><Card.Root mt="2"><Card.Body><Box as="pre" fontSize="xs" overflowX="auto">{JSON.stringify(message.tool.args, null, 2)}</Box></Card.Body></Card.Root></Collapsible.Content></Collapsible.Root> : null}</Stack></Flex>
}

function Composer({ draft, setDraft }: { draft: string; setDraft: (value: string) => void }) {
  return <Stack borderTopWidth="1px" p="4" gap="3"><Flex gap="2" wrap="wrap">{chat.suggestions.map((item) => <Tag.Root key={item} asChild><Button size="sm" variant="outline" onClick={() => setDraft(item)}><Tag.Label>{item}</Tag.Label></Button></Tag.Root>)}</Flex><Flex gap="2" align="end"><IconButton aria-label="添加附件" variant="outline"><Icon name="paperclip" width="18" height="18" /></IconButton><Textarea value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="向 AI 助手提问..." autoresize minH="20" maxH="36" /><IconButton aria-label="发送" colorPalette="blue"><Icon name="send" width="18" height="18" /></IconButton></Flex><Flex justify="space-between"><Text fontSize="xs" color="fg.muted">{draft.length}/2000</Text><Text fontSize="xs" color="fg.muted">Enter 发送 · <kbd>⌘ Enter</kbd> · {draft.length}/2000</Text></Flex></Stack>
}

function EmptyChat({ onStart }: { onStart: () => void }) {
  return <Flex flex="1" align="center" justify="center" p="6"><Stack align="center" gap="5" textAlign="center"><Heading size="lg">开始一段新对话</Heading><Text color="fg.muted">选择一个建议，或直接告诉 AI 你想完成什么。</Text><Flex gap="3" wrap="wrap" justify="center">{chat.suggestions.map((item) => <Card.Root key={item} width="220px" cursor="pointer" onClick={onStart}><Card.Body><Text fontSize="sm">{item}</Text></Card.Body></Card.Root>)}</Flex><Button onClick={onStart}>打开最近对话</Button></Stack></Flex>
}
