import { useMemo, useState } from "react"
import { Icon as GalleryIcon } from "@ui-gallery/icons-react"
import orders from "@ui-gallery/spec/mock/orders.json"
import { Alert, Button, Card, Checkbox, DatePicker, DataList, Dialog, Drawer, EmptyState, Flex, IconButton, Input, Menu, Pagination, Portal, Select, Separator, Skeleton, Stack, Table, Tabs, Tag, Text, Textarea } from "@chakra-ui/react"
import { createListCollection } from "@chakra-ui/react"
import { toaster } from "@/components/toaster"
import { DataTable, PageHeader, StatusBadge } from "./shared"

function Icon({ name, width, height, size }: { name: string; width?: string; height?: string; size?: string | number }) {
  return <GalleryIcon name={name} size={size ?? width ?? height} />
}

const statuses = createListCollection({ items: [{ label: "全部状态", value: "all" }, ...["paid", "pending", "shipped", "failed", "refunded"].map((value) => ({ label: value, value }))] })
const channels = createListCollection({ items: ["web", "ios", "android", "api"].map((value) => ({ label: value, value })) })

export function OrdersPage() {
  const [query, setQuery] = useState("")
  const [status, setStatus] = useState("all")
  const [selected, setSelected] = useState<typeof orders[number] | null>(null)
  const [sortAsc, setSortAsc] = useState(true)
  const [state, setState] = useState("data")
  const filtered = useMemo(() => orders.filter((order) => order.id.toLowerCase().includes(query.toLowerCase()) && (status === "all" || order.status === status)).sort((a, b) => sortAsc ? a.id.localeCompare(b.id) : b.id.localeCompare(a.id)), [query, status, sortAsc])
  const remove = () => { setSelected(null); toaster.create({ type: "success", title: "订单已删除", description: "订单已从本地演示数据中移除。" }) }
  return (
    <Stack gap="6">
      <PageHeader title="订单管理" description="搜索、筛选并查看全部订单。" action={<Button variant="outline"><Icon name="download" width="16" height="16" />导出</Button>} />
      <Alert.Root status="info"><Alert.Indicator /><Alert.Content><Alert.Title>本地数据集</Alert.Title><Alert.Description>所有订单来自本地 mock JSON，无运行时网络请求。</Alert.Description></Alert.Content></Alert.Root>
      <SegmentState value={state} onChange={setState} />
      {state === "loading" ? <Card.Root><Card.Body><Stack gap="3"><Skeleton height="10" /><Skeleton height="10" /><Skeleton height="10" /></Stack></Card.Body></Card.Root> : state === "error" ? <Alert.Root status="error"><Alert.Indicator /><Alert.Content><Alert.Title>订单加载失败</Alert.Title><Alert.Description>演示错误状态，请稍后重试。</Alert.Description><Button mt="3" size="sm" onClick={() => setState("data")}>重试</Button></Alert.Content></Alert.Root> : state === "empty" ? <Card.Root><Card.Body><EmptyState.Root><EmptyState.Content><EmptyState.Indicator><Icon name="inbox" width="24" height="24" /></EmptyState.Indicator><EmptyState.Title>没有找到订单</EmptyState.Title><EmptyState.Description>调整搜索或筛选条件后重试。</EmptyState.Description><Button onClick={() => setState("data")}>清除筛选</Button></EmptyState.Content></EmptyState.Root></Card.Body></Card.Root> : <Card.Root><Card.Body><Stack gap="4">
        <Flex gap="3" wrap="wrap"><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索订单号..." flex="1" minW="180px" /><Select.Root collection={statuses} value={[status]} onValueChange={(details) => setStatus(details.value[0] ?? "all")} width="180px"><Select.HiddenSelect /><Select.Control><Select.Trigger><Select.ValueText placeholder="状态" /></Select.Trigger><Select.IndicatorGroup><Select.Indicator /></Select.IndicatorGroup></Select.Control><Portal><Select.Positioner><Select.Content>{statuses.items.map((item) => <Select.Item item={item} key={item.value}>{item.label}<Select.ItemIndicator /></Select.Item>)}</Select.Content></Select.Positioner></Portal></Select.Root><Select.Root collection={channels} multiple width="220px"><Select.HiddenSelect /><Select.Control><Select.Trigger><Select.ValueText placeholder="渠道（多选）" /></Select.Trigger><Select.IndicatorGroup><Select.Indicator /></Select.IndicatorGroup></Select.Control><Portal><Flex gap="1" wrap="wrap"><Tag.Root size="sm"><Tag.Label>web</Tag.Label></Tag.Root><Tag.Root size="sm"><Tag.Label>ios</Tag.Label></Tag.Root></Flex><Select.Positioner><Select.Content>{channels.items.map((item) => <Select.Item item={item} key={item.value}>{item.label}<Select.ItemIndicator /></Select.Item>)}</Select.Content></Select.Positioner></Portal></Select.Root><DatePicker.Root selectionMode="range" width="240px"><DatePicker.Control><DatePicker.Input placeholder="选择日期范围" /><DatePicker.Trigger asChild><IconButton aria-label="打开日历" variant="ghost" minH="10"><Icon name="calendar" width="18" height="18" /></IconButton></DatePicker.Trigger></DatePicker.Control><DatePicker.Positioner><DatePicker.Content /></DatePicker.Positioner></DatePicker.Root><Menu.Root><Menu.Trigger asChild><Button variant="outline"><Icon name="sliders" width="16" height="16" />列</Button></Menu.Trigger><Portal><Menu.Positioner><Menu.Content><Menu.Item value="customer">客户 ✓</Menu.Item><Menu.Item value="amount">金额 ✓</Menu.Item><Menu.Item value="status">状态 ✓</Menu.Item></Menu.Content></Menu.Positioner></Portal></Menu.Root></Flex>
        {filtered.length ? <DataTable><Table.Root minW="760px"><Table.Header><Table.Row><Table.ColumnHeader><Checkbox.Root><Checkbox.HiddenInput /><Checkbox.Control /></Checkbox.Root></Table.ColumnHeader><Table.ColumnHeader onClick={() => setSortAsc((value) => !value)} cursor="pointer">订单号 {sortAsc ? "↑" : "↓"}</Table.ColumnHeader><Table.ColumnHeader>客户</Table.ColumnHeader><Table.ColumnHeader>状态</Table.ColumnHeader><Table.ColumnHeader>日期</Table.ColumnHeader><Table.ColumnHeader textAlign="end">金额</Table.ColumnHeader><Table.ColumnHeader>操作</Table.ColumnHeader></Table.Row></Table.Header><Table.Body>{filtered.slice(0, 10).map((order) => <Table.Row key={order.id} onClick={() => setSelected(order)} cursor="pointer"><Table.Cell><Checkbox.Root onClick={(event) => event.stopPropagation()}><Checkbox.HiddenInput /><Checkbox.Control /></Checkbox.Root></Table.Cell><Table.Cell fontWeight="medium">{order.id}</Table.Cell><Table.Cell>{order.customer}</Table.Cell><Table.Cell><StatusBadge value={order.status} /></Table.Cell><Table.Cell>{order.date}</Table.Cell><Table.Cell textAlign="end">¥{order.amount.toLocaleString()}</Table.Cell><Table.Cell><Menu.Root><Menu.Trigger asChild><Button size="sm" variant="ghost" onClick={(event) => event.stopPropagation()}><Icon name="more-horizontal" width="16" height="16" /></Button></Menu.Trigger><Portal><Menu.Positioner><Menu.Content><Menu.Item value="edit">编辑</Menu.Item><Menu.Item value="delete" color="fg.error">删除</Menu.Item></Menu.Content></Menu.Positioner></Portal></Menu.Root></Table.Cell></Table.Row>)}</Table.Body></Table.Root></DataTable> : <EmptyState.Root><EmptyState.Content><EmptyState.Indicator><Icon name="inbox" width="24" height="24" /></EmptyState.Indicator><EmptyState.Title>没有找到订单</EmptyState.Title><EmptyState.Description>调整搜索或筛选条件后重试。</EmptyState.Description></EmptyState.Content></EmptyState.Root>}
        <Flex justify="space-between" align="center" wrap="wrap" gap="3"><Text fontSize="sm" color="fg.muted">共 {filtered.length} 条订单</Text><Pagination.Root count={filtered.length || 1} pageSize={10} defaultPage={1}><Pagination.PageText /><Pagination.PrevTrigger asChild><Button size="sm" variant="outline">上一页</Button></Pagination.PrevTrigger><Pagination.NextTrigger asChild><Button size="sm" variant="outline">下一页</Button></Pagination.NextTrigger></Pagination.Root><Select.Root collection={createListCollection({ items: ["10", "20", "50"].map((value) => ({ label: `${value} / 页`, value })) })} width="110px"><Select.HiddenSelect /><Select.Control><Select.Trigger><Select.ValueText placeholder="10 / 页" /></Select.Trigger><Select.IndicatorGroup><Select.Indicator /></Select.IndicatorGroup></Select.Control><Select.Positioner><Select.Content /></Select.Positioner></Select.Root></Flex>
      </Stack></Card.Body></Card.Root>}
      <Drawer.Root open={!!selected} onOpenChange={(details) => !details.open && setSelected(null)} placement="end"><Portal><Drawer.Backdrop /><Drawer.Positioner><Drawer.Content><Drawer.Header><Drawer.Title>{selected?.id ?? "订单详情"}</Drawer.Title><Drawer.Description>查看订单的完整信息与操作。</Drawer.Description></Drawer.Header><Drawer.Body>{selected ? <Stack gap="5"><DataList.Root orientation="horizontal"><DataList.Item><DataList.ItemLabel>客户</DataList.ItemLabel><DataList.ItemValue>{selected.customer}</DataList.ItemValue></DataList.Item><DataList.Item><DataList.ItemLabel>产品</DataList.ItemLabel><DataList.ItemValue>{selected.product}</DataList.ItemValue></DataList.Item><DataList.Item><DataList.ItemLabel>金额</DataList.ItemLabel><DataList.ItemValue>¥{selected.amount.toLocaleString()}</DataList.ItemValue></DataList.Item><DataList.Item><DataList.ItemLabel>状态</DataList.ItemLabel><DataList.ItemValue><StatusBadge value={selected.status} /></DataList.ItemValue></DataList.Item></DataList.Root><Separator /><Tabs.Root defaultValue="detail"><Tabs.List><Tabs.Trigger value="detail">详情</Tabs.Trigger><Tabs.Trigger value="notes">备注</Tabs.Trigger></Tabs.List><Tabs.Content value="detail"><Text color="fg.muted" mt="3">{selected.email}</Text></Tabs.Content><Tabs.Content value="notes"><Textarea placeholder="添加备注..." mt="3" /></Tabs.Content></Tabs.Root><Dialog.Root role="alertdialog"><Dialog.Trigger asChild><Button colorPalette="red">删除订单</Button></Dialog.Trigger><Portal><Dialog.Backdrop /><Dialog.Positioner><Dialog.Content><Dialog.Header><Dialog.Title>确认删除订单？</Dialog.Title><Dialog.Description>此操作无法撤销。</Dialog.Description></Dialog.Header><Dialog.Footer><Dialog.ActionTrigger asChild><Button variant="outline">取消</Button></Dialog.ActionTrigger><Button colorPalette="red" onClick={remove}>确认删除</Button></Dialog.Footer><Dialog.CloseTrigger /></Dialog.Content></Dialog.Positioner></Portal></Dialog.Root></Stack> : null}</Drawer.Body><Drawer.CloseTrigger /></Drawer.Content></Drawer.Positioner></Portal></Drawer.Root>
    </Stack>
  )
}

function SegmentState({ value, onChange }: { value: string; onChange: (value: string) => void }) {
  return <Flex gap="2" align="center" wrap="wrap"><Text fontSize="sm" fontWeight="medium">演示状态</Text>{["data", "loading", "error", "empty"].map((item) => <Button key={item} size="sm" variant={item === value ? "solid" : "outline"} onClick={() => onChange(item)}>{item === "data" ? "数据" : item === "loading" ? "加载中" : item === "error" ? "错误" : "空"}</Button>)}</Flex>
}
