import { useState } from "react"
import { Icon as GalleryIcon } from "@ui-gallery/icons-react"
import sessions from "@ui-gallery/spec/mock/sessions.json"
import team from "@ui-gallery/spec/mock/team.json"
import plans from "@ui-gallery/spec/mock/plans.json"
import invoices from "@ui-gallery/spec/mock/invoices.json"
import { Avatar, Badge, Box, Button, Card, Combobox, Dialog, Field, FileUpload, Flex, Heading, Input, Portal, QrCode, SegmentGroup, Select, Separator, Stack, Switch, Table, Tabs, Text, Textarea } from "@chakra-ui/react"
import { createListCollection } from "@chakra-ui/react"
import { PageHeader, StatusBadge } from "./shared"

function Icon({ name, width, height, size }: { name: string; width?: string; height?: string; size?: string | number }) {
  return <GalleryIcon name={name} size={size ?? width ?? height} />
}

const languages = createListCollection({ items: [{ label: "中文", value: "zh" }, { label: "English", value: "en" }] })

export function SettingsPage() {
  const [tab, setTab] = useState("profile")
  return <Stack gap="6"><PageHeader title="设置" description="管理你的账户、团队与订阅设置。" /><Tabs.Root value={tab} onValueChange={(details) => setTab(details.value)} orientation="vertical" display={{ md: "grid" }} gridTemplateColumns={{ md: "180px minmax(0, 1fr)" }} gap="6"><Tabs.List flexDirection={{ md: "column" }} alignItems="stretch" overflowX="auto"><Tabs.Trigger value="profile">个人资料</Tabs.Trigger><Tabs.Trigger value="security">账号安全</Tabs.Trigger><Tabs.Trigger value="notifications">通知</Tabs.Trigger><Tabs.Trigger value="team">团队</Tabs.Trigger><Tabs.Trigger value="billing">计费</Tabs.Trigger></Tabs.List><Box minW="0"><Tabs.Content value="profile"><Profile /></Tabs.Content><Tabs.Content value="security"><Security /></Tabs.Content><Tabs.Content value="notifications"><Notifications /></Tabs.Content><Tabs.Content value="team"><Team /></Tabs.Content><Tabs.Content value="billing"><Billing /></Tabs.Content></Box></Tabs.Root><DangerZone /></Stack>
}

function Profile() {
  return <Card.Root><Card.Header><Card.Title>个人资料</Card.Title><Card.Description>更新你的公开账户信息。</Card.Description></Card.Header><Card.Body><Stack gap="5"><Flex align="center" gap="4" wrap="wrap"><Avatar.Root size="lg"><Avatar.Fallback name="林晓" /></Avatar.Root><Box><Text fontWeight="medium">林晓</Text><Text fontSize="sm" color="fg.muted">{team[0].email}</Text></Box><FileUpload.Root><FileUpload.HiddenInput /><FileUpload.Trigger asChild><Button variant="outline" ms="auto"><Icon name="upload" width="16" height="16" />上传头像</Button></FileUpload.Trigger></FileUpload.Root></Flex><Separator /><Flex gap="4" direction={{ base: "column", md: "row" }}><Field.Root flex="1"><Field.Label>姓名</Field.Label><Input defaultValue="林晓" /></Field.Root><Field.Root flex="1"><Field.Label>简介</Field.Label><Textarea defaultValue="产品负责人" /></Field.Root></Flex><Flex gap="4" direction={{ base: "column", md: "row" }}><Field.Root flex="1"><Field.Label>语言</Field.Label><Select.Root collection={languages} defaultValue={["zh"]}><Select.HiddenSelect /><Select.Control><Select.Trigger><Select.ValueText /></Select.Trigger></Select.Control><Select.Positioner><Select.Content>{languages.items.map((item) => <Select.Item item={item} key={item.value}>{item.label}</Select.Item>)}</Select.Content></Select.Positioner></Select.Root></Field.Root><Field.Root flex="1"><Field.Label>时区</Field.Label><Combobox.Root collection={createListCollection({ items: ["Asia/Shanghai", "America/Los_Angeles", "Europe/London"].map((value) => ({ label: value, value })) })} defaultValue={["Asia/Shanghai"]}><Combobox.Control><Combobox.Input /></Combobox.Control><Combobox.Positioner><Combobox.Content /></Combobox.Positioner></Combobox.Root></Field.Root></Flex><Button alignSelf="start">保存更改</Button></Stack></Card.Body></Card.Root>
}

function Security() {
  return <Stack gap="4"><Card.Root><Card.Header><Card.Title>账号安全</Card.Title><Card.Description>保护你的账户与登录会话。</Card.Description></Card.Header><Card.Body><Stack gap="5"><Flex justify="space-between" align="center"><Box><Text fontWeight="medium">两步验证</Text><Text fontSize="sm" color="fg.muted">登录时要求额外的验证码</Text></Box><Switch.Root defaultChecked><Switch.HiddenInput /><Switch.Control><Switch.Thumb /></Switch.Control></Switch.Root></Flex><QrCode.Root value="https://acme.local/2fa" width="120px" height="120px"><QrCode.Frame /><QrCode.Overlay><Text fontSize="xs">QR</Text></QrCode.Overlay></QrCode.Root><Dialog.Root><Dialog.Trigger asChild><Button variant="outline" alignSelf="start">修改密码</Button></Dialog.Trigger><Portal><Dialog.Backdrop /><Dialog.Positioner><Dialog.Content><Dialog.Header><Dialog.Title>修改密码</Dialog.Title><Dialog.Description>设置一个新的账户密码。</Dialog.Description></Dialog.Header><Dialog.Body><Stack><Input type="password" placeholder="当前密码" /><Input type="password" placeholder="新密码" /></Stack></Dialog.Body><Dialog.Footer><Dialog.ActionTrigger asChild><Button variant="outline">取消</Button></Dialog.ActionTrigger><Button>保存</Button></Dialog.Footer><Dialog.CloseTrigger /></Dialog.Content></Dialog.Positioner></Portal></Dialog.Root></Stack></Card.Body></Card.Root><Card.Root><Card.Header><Card.Title>活跃会话</Card.Title></Card.Header><Card.Body><Stack gap="3">{sessions.map((session) => <Flex key={session.device} justify="space-between" align="center" gap="3" wrap="wrap"><Box><Text fontSize="sm">{session.device}</Text><Text fontSize="xs" color="fg.muted">{session.location} · {session.time}</Text></Box>{session.current ? <Badge colorPalette="green">当前会话</Badge> : <Button size="sm" variant="outline">注销</Button>}</Flex>)}</Stack></Card.Body></Card.Root></Stack>
}

function Notifications() {
  return <Card.Root><Card.Header><Card.Title>通知偏好</Card.Title><Card.Description>选择你希望接收的通知。</Card.Description></Card.Header><Card.Body><Stack gap="4"><SegmentGroup.Root defaultValue="email"><SegmentGroup.Indicator /><SegmentGroup.Item value="email"><SegmentGroup.ItemText>邮件</SegmentGroup.ItemText><SegmentGroup.ItemHiddenInput /></SegmentGroup.Item><SegmentGroup.Item value="push"><SegmentGroup.ItemText>推送</SegmentGroup.ItemText><SegmentGroup.ItemHiddenInput /></SegmentGroup.Item><SegmentGroup.Item value="inapp"><SegmentGroup.ItemText>站内</SegmentGroup.ItemText><SegmentGroup.ItemHiddenInput /></SegmentGroup.Item></SegmentGroup.Root>{["项目更新", "账单提醒", "团队活动", "产品新闻"].map((label, index) => <Flex key={label} justify="space-between" align="center" borderBottomWidth="1px" pb="3"><Box><Text fontWeight="medium">{label}</Text><Text fontSize="sm" color="fg.muted">通过邮件接收重要提醒</Text></Box><Switch.Root defaultChecked={index < 3}><Switch.HiddenInput /><Switch.Control><Switch.Thumb /></Switch.Control></Switch.Root></Flex>)}</Stack></Card.Body></Card.Root>
}

function Team() {
  return <Card.Root><Card.Header><Card.Title>团队成员</Card.Title><Card.Description>管理团队访问权限。</Card.Description></Card.Header><Card.Body><Box overflowX="auto"><Table.Root minW="600px"><Table.Header><Table.Row><Table.ColumnHeader>成员</Table.ColumnHeader><Table.ColumnHeader>角色</Table.ColumnHeader><Table.ColumnHeader>最近活跃</Table.ColumnHeader><Table.ColumnHeader>操作</Table.ColumnHeader></Table.Row></Table.Header><Table.Body>{team.map((member) => <Table.Row key={member.email}><Table.Cell><Flex align="center" gap="2"><Avatar.Root size="xs"><Avatar.Fallback name={member.name} /></Avatar.Root>{member.name}</Flex></Table.Cell><Table.Cell><Select.Root collection={createListCollection({ items: ["owner", "admin", "member", "viewer"].map((value) => ({ label: value, value })) })} width="130px" defaultValue={[member.role]}><Select.HiddenSelect /><Select.Control><Select.Trigger><Select.ValueText /></Select.Trigger><Select.IndicatorGroup><Select.Indicator /></Select.IndicatorGroup></Select.Control><Select.Positioner><Select.Content /></Select.Positioner></Select.Root></Table.Cell><Table.Cell>{member.lastActive}</Table.Cell><Table.Cell><Button size="sm" variant="ghost"><Icon name="edit" width="16" height="16" />编辑</Button></Table.Cell></Table.Row>)}</Table.Body></Table.Root></Box><Button mt="4"><Icon name="plus" width="16" height="16" />邀请成员</Button></Card.Body></Card.Root>
}

function Billing() {
  return <Stack gap="4"><Card.Root><Card.Header><Card.Title>当前计划</Card.Title><Card.Description>你的订阅与可用方案。</Card.Description></Card.Header><Card.Body><Text fontSize="2xl" fontWeight="bold">Pro · ¥99 / 月</Text></Card.Body></Card.Root><Box display="grid" gridTemplateColumns={{ base: "1fr", md: "repeat(3, 1fr)" }} gap="3">{plans.map((plan) => <Card.Root key={plan.name}><Card.Header><Flex justify="space-between"><Card.Title>{plan.name}</Card.Title>{plan.recommended ? <Badge colorPalette="purple">推荐</Badge> : null}</Flex><Heading size="lg">{plan.price === null ? "定制" : plan.price === 0 ? "免费" : `¥${plan.price}`}</Heading></Card.Header><Card.Body><Stack gap="2">{plan.features.map((feature) => <Text key={feature} fontSize="sm">✓ {feature}</Text>)}</Stack></Card.Body><Card.Footer><Button width="full" variant={plan.recommended ? "solid" : "outline"}>选择方案</Button></Card.Footer></Card.Root>)}</Box><Card.Root><Card.Header><Card.Title>发票记录</Card.Title></Card.Header><Card.Body><Box overflowX="auto"><Table.Root minW="500px"><Table.Header><Table.Row><Table.ColumnHeader>编号</Table.ColumnHeader><Table.ColumnHeader>日期</Table.ColumnHeader><Table.ColumnHeader>金额</Table.ColumnHeader><Table.ColumnHeader>状态</Table.ColumnHeader></Table.Row></Table.Header><Table.Body>{invoices.map((invoice) => <Table.Row key={invoice.id}><Table.Cell>{invoice.id}</Table.Cell><Table.Cell>{invoice.date}</Table.Cell><Table.Cell>¥{invoice.amount}</Table.Cell><Table.Cell><StatusBadge value={invoice.status} /></Table.Cell></Table.Row>)}</Table.Body></Table.Root></Box></Card.Body></Card.Root></Stack>
}

function DangerZone() {
  return <Card.Root borderWidth="1px" borderColor="border.error"><Card.Header><Card.Title color="fg.error">危险区</Card.Title><Card.Description>删除账号后所有数据将永久移除。</Card.Description></Card.Header><Card.Body><DangerDialog /></Card.Body></Card.Root>
}

function DangerDialog() { const [value, setValue] = useState(""); return <Dialog.Root role="alertdialog"><Dialog.Trigger asChild><Button colorPalette="red">删除账号</Button></Dialog.Trigger><Portal><Dialog.Backdrop /><Dialog.Positioner><Dialog.Content><Dialog.Header><Dialog.Title>确定删除账号？</Dialog.Title><Dialog.Description>请输入 DELETE 以确认此操作。</Dialog.Description></Dialog.Header><Dialog.Body><Input placeholder="DELETE" value={value} onChange={(event) => setValue(event.target.value)} /></Dialog.Body><Dialog.Footer><Dialog.ActionTrigger asChild><Button variant="outline">取消</Button></Dialog.ActionTrigger><Button colorPalette="red" disabled={value !== "DELETE"}>确认删除</Button></Dialog.Footer><Dialog.CloseTrigger /></Dialog.Content></Dialog.Positioner></Portal></Dialog.Root> }
