import { Avatar, Badge, Box, Button, Card, Carousel, DataList, EmptyState, Flex, Image, Popover, QrCode, SegmentGroup, Stack, Stat, Table, Tag, Text, Timeline, Tooltip } from "@chakra-ui/react"
import type { ComponentDemo } from "./typography"
import { Icon as GalleryIcon } from "@ui-gallery/icons-react"
import { DatePickerField } from "../shared"

function Icon({ name, size = "18" }: { name: string; size?: string }) { return <GalleryIcon name={name} size={size} /> }
function People() { return <Flex gap="-2"><Avatar.Root size="sm"><Avatar.Fallback name="林晓" /></Avatar.Root><Avatar.Root size="sm"><Avatar.Fallback name="Alex Chen" /></Avatar.Root><Avatar.Root size="sm"><Avatar.Fallback name="Maria" /></Avatar.Root><Badge>+3</Badge></Flex> }

export const dataDisplayDemos: ComponentDemo[] = [
  { name: "Table", node: <Box overflowX="auto"><Table.ScrollArea><Table.Root variant="outline" size="sm" striped interactive minW="520px"><Table.Header><Table.Row><Table.ColumnHeader>项目</Table.ColumnHeader><Table.ColumnHeader>负责人</Table.ColumnHeader><Table.ColumnHeader>状态</Table.ColumnHeader></Table.Row></Table.Header><Table.Body>{["增长分析", "移动端改版", "季度报告"].map((item, index) => <Table.Row key={item}><Table.Cell>{item}</Table.Cell><Table.Cell>{["林晓", "Alex Chen", "Maria García"][index]}</Table.Cell><Table.Cell><Badge colorPalette={index === 1 ? "yellow" : "green"}>{index === 1 ? "进行中" : "已完成"}</Badge></Table.Cell></Table.Row>)}</Table.Body></Table.Root></Table.ScrollArea></Box> },
  { name: "DataGrid", node: <Stack gap="3"><Table.Root size="sm" variant="line"><Table.Header><Table.Row><Table.ColumnHeader>可排序列 ↑</Table.ColumnHeader><Table.ColumnHeader>可选择行</Table.ColumnHeader></Table.Row></Table.Header><Table.Body><Table.Row><Table.Cell>Grid row 1</Table.Cell><Table.Cell><input type="checkbox" aria-label="选择行" /></Table.Cell></Table.Row><Table.Row><Table.Cell>Grid row 2</Table.Cell><Table.Cell><input type="checkbox" aria-label="选择行 2" /></Table.Cell></Table.Row></Table.Body></Table.Root><Button size="sm" variant="outline">分页 1 / 3</Button></Stack> },
  { name: "Descriptions", node: <DataList.Root orientation="horizontal"><DataList.Item><DataList.ItemLabel>订单号</DataList.ItemLabel><DataList.ItemValue>ORD-2026-001</DataList.ItemValue></DataList.Item><DataList.Item><DataList.ItemLabel>状态</DataList.ItemLabel><DataList.ItemValue><Badge colorPalette="green">已支付</Badge></DataList.ItemValue></DataList.Item><DataList.Item><DataList.ItemLabel>金额</DataList.ItemLabel><DataList.ItemValue>¥12,800</DataList.ItemValue></DataList.Item></DataList.Root> },
  { name: "List", node: <Stack><Text>最近活动</Text>{["完成季度报告", "邀请新成员", "创建项目"].map((item) => <Flex key={item} gap="2" align="center"><Box width="2" height="2" rounded="full" bg="colorPalette.solid" /><Text>{item}</Text></Flex>)}</Stack> },
  { name: "Card", node: <Flex gap="3" wrap="wrap"><Card.Root variant="elevated" width="180px"><Card.Header><Card.Title>Elevated</Card.Title></Card.Header><Card.Body>卡片内容</Card.Body></Card.Root><Card.Root variant="outline" width="180px"><Card.Header><Card.Title>Outline</Card.Title></Card.Header><Card.Body>卡片内容</Card.Body></Card.Root><Card.Root variant="subtle" width="180px"><Card.Header><Card.Title>Subtle</Card.Title></Card.Header><Card.Body>卡片内容</Card.Body></Card.Root></Flex> },
  { name: "Avatar", node: <Flex gap="3" align="center"><Avatar.Root size="xs" shape="rounded"><Avatar.Fallback name="小" /></Avatar.Root><Avatar.Root size="md"><Avatar.Fallback name="林晓" /></Avatar.Root><Avatar.Root size="lg" variant="solid"><Avatar.Fallback name="Alex Chen" /></Avatar.Root></Flex> },
  { name: "AvatarGroup", node: <People /> },
  { name: "Badge", node: <Flex gap="2" wrap="wrap">{["solid", "subtle", "outline", "surface", "plain"].map((variant) => <Badge key={variant} variant={variant as "solid"} colorPalette="blue">{variant}</Badge>)}</Flex> },
  { name: "Tag", node: <Flex gap="2" wrap="wrap"><Tag.Root size="sm"><Tag.StartElement><Icon name="check" size="12" /></Tag.StartElement><Tag.Label>已完成</Tag.Label><Tag.EndElement><Tag.CloseTrigger /></Tag.EndElement></Tag.Root><Tag.Root variant="outline" size="lg"><Tag.Label>设计</Tag.Label></Tag.Root><Tag.Root><Tag.StartElement><Avatar.Root size="2xs"><Avatar.Fallback name="林" /></Avatar.Root></Tag.StartElement><Tag.Label>林晓</Tag.Label></Tag.Root></Flex> },
  { name: "Statistic", node: <Flex gap="5" wrap="wrap"><Stat.Root><Stat.Label>总收入</Stat.Label><Stat.ValueText>¥128,430</Stat.ValueText><Stat.UpIndicator>12.4%</Stat.UpIndicator></Stat.Root><Stat.Root><Stat.Label>退款率</Stat.Label><Stat.ValueText>2.1%</Stat.ValueText><Stat.DownIndicator>0.8%</Stat.DownIndicator></Stat.Root></Flex> },
  { name: "Timeline", node: <Timeline.Root variant="subtle">{["林晓 创建了增长分析", "Alex 更新了季度报告", "Maria 完成了设计评审"].map((item, index) => <Timeline.Item key={item}><Timeline.Connector><Timeline.Separator /><Timeline.Indicator>{index + 1}</Timeline.Indicator></Timeline.Connector><Timeline.Content><Timeline.Title>{item}</Timeline.Title><Timeline.Description>{index + 1} 小时前</Timeline.Description></Timeline.Content></Timeline.Item>)}</Timeline.Root> },
  { name: "Tree", node: <Stack gap="2"><Text fontWeight="medium">工作区</Text><Box pl="4"><Text>▾ 产品团队</Text><Text pl="4">• 增长分析</Text><Text pl="4">• 季度报告</Text></Box></Stack> },
  { name: "Calendar", node: <DatePickerField inline /> },
  { name: "Image", node: <DialogImage /> },
  { name: "Carousel", node: <Carousel.Root slideCount={3} width="full"><Carousel.ItemGroup>{["仪表盘", "订单分析", "团队协作"].map((item, index) => <Carousel.Item key={item} index={index}><Box height="120px" bg="bg.subtle" display="grid" placeItems="center" width="full"><Text>{item}</Text></Box></Carousel.Item>)}</Carousel.ItemGroup><Flex mt="3" justify="center" gap="2"><Carousel.PrevTrigger /><Carousel.Indicators /><Carousel.NextTrigger /></Flex></Carousel.Root> },
  { name: "Empty", node: <EmptyState.Root><EmptyState.Content><EmptyState.Indicator><Icon name="inbox" /></EmptyState.Indicator><EmptyState.Title>暂无项目</EmptyState.Title><EmptyState.Description>创建第一个项目开始协作。</EmptyState.Description><Button>创建项目</Button></EmptyState.Content></EmptyState.Root> },
  { name: "Tooltip", node: <Flex gap="3"><Tooltip.Root positioning={{ placement: "top" }}><Tooltip.Trigger asChild><Button>顶部提示</Button></Tooltip.Trigger><Tooltip.Positioner><Tooltip.Content><Tooltip.Arrow />帮助说明</Tooltip.Content></Tooltip.Positioner></Tooltip.Root><Tooltip.Root positioning={{ placement: "right" }}><Tooltip.Trigger asChild><Button variant="outline">右侧提示</Button></Tooltip.Trigger><Tooltip.Positioner><Tooltip.Content>更多信息</Tooltip.Content></Tooltip.Positioner></Tooltip.Root></Flex> },
  { name: "Popover", node: <Popover.Root><Popover.Trigger asChild><Button variant="outline">打开 Popover</Button></Popover.Trigger><Popover.Positioner><Popover.Content><Popover.Arrow /><Popover.Header>通知设置</Popover.Header><Popover.Body>你有 3 条未读通知。</Popover.Body><Popover.Footer><Button size="sm">查看全部</Button></Popover.Footer></Popover.Content></Popover.Positioner></Popover.Root> },
  { name: "QRCode", node: <QrCode.Root value="https://acme.local/invite" size="sm"><QrCode.Frame /><QrCode.Overlay><Text fontSize="xs">ACME</Text></QrCode.Overlay></QrCode.Root> },
  { name: "Segmented", node: <SegmentGroup.Root defaultValue="month" size="sm"><SegmentGroup.Indicator /><SegmentGroup.Item value="day"><SegmentGroup.ItemText>日</SegmentGroup.ItemText><SegmentGroup.ItemHiddenInput /></SegmentGroup.Item><SegmentGroup.Item value="month"><SegmentGroup.ItemText>月</SegmentGroup.ItemText><SegmentGroup.ItemHiddenInput /></SegmentGroup.Item><SegmentGroup.Item value="year"><SegmentGroup.ItemText>年</SegmentGroup.ItemText><SegmentGroup.ItemHiddenInput /></SegmentGroup.Item></SegmentGroup.Root> },
]

function DialogImage() {
  return <Popover.Root><Popover.Trigger asChild><Image src="/apps/chakra-ui/vite.svg" alt="预览占位图" boxSize="80px" rounded="l2" objectFit="contain" cursor="pointer" /></Popover.Trigger><Popover.Positioner><Popover.Content><Popover.Body><Image src="/apps/chakra-ui/vite.svg" alt="图片预览" boxSize="220px" objectFit="contain" /></Popover.Body></Popover.Content></Popover.Positioner></Popover.Root>
}
