import { Alert, Button, Dialog, Drawer, EmptyState, Flex, Popover, Progress, ProgressCircle, Skeleton, SkeletonCircle, SkeletonText, Spinner, Stack, Text } from "@chakra-ui/react"
import { toaster } from "@/components/toaster"
import type { ComponentDemo } from "./typography"

const statuses = ["info", "success", "warning", "error"] as const
const variants = ["subtle", "surface", "outline", "solid"] as const

export const feedbackDemos: ComponentDemo[] = [
  { name: "Alert", node: <Stack gap="2">{statuses.map((status) => <Flex key={status} gap="2" wrap="wrap">{variants.map((variant) => <Alert.Root key={variant} status={status} variant={variant} flex="1" minW="180px"><Alert.Indicator /><Alert.Content><Alert.Title>{status} / {variant}</Alert.Title><Alert.Description>操作已同步到本地数据。</Alert.Description></Alert.Content></Alert.Root>)}</Flex>)}</Stack> },
  { name: "Toast", node: <Flex gap="2" wrap="wrap"><Button onClick={() => toaster.create({ type: "success", title: "保存成功" })}>成功</Button><Button onClick={() => toaster.create({ type: "error", title: "保存失败" })}>错误</Button><Button onClick={() => toaster.create({ type: "warning", title: "请注意" })}>警告</Button><Button onClick={() => toaster.create({ type: "info", title: "提示", action: { label: "撤销", onClick: () => undefined } })}>通知 + 操作</Button></Flex> },
  { name: "Notification", node: <Button onClick={() => toaster.create({ type: "info", title: "新通知", description: "你的报告已经生成。", action: { label: "打开", onClick: () => undefined }, closable: true })}>发送通知</Button> },
  { name: "Dialog", node: <Flex gap="2" wrap="wrap"><Dialog.Root><Dialog.Trigger asChild><Button>普通 Dialog</Button></Dialog.Trigger><Dialog.Backdrop /><Dialog.Positioner><Dialog.Content><Dialog.Header><Dialog.Title>确认操作</Dialog.Title><Dialog.Description>这是一个带标题和描述的 Dialog。</Dialog.Description></Dialog.Header><Dialog.Body><Text>对话框内容</Text></Dialog.Body><Dialog.Footer><Dialog.CloseTrigger asChild><Button variant="outline">取消</Button></Dialog.CloseTrigger><Button>确认</Button></Dialog.Footer><Dialog.CloseTrigger /></Dialog.Content></Dialog.Positioner></Dialog.Root><Dialog.Root role="alertdialog"><Dialog.Trigger asChild><Button colorPalette="red">Alertdialog</Button></Dialog.Trigger><Dialog.Backdrop /><Dialog.Positioner><Dialog.Content><Dialog.Header><Dialog.Title>删除数据？</Dialog.Title><Dialog.Description>此操作无法撤销。</Dialog.Description></Dialog.Header><Dialog.Footer><Dialog.ActionTrigger asChild><Button variant="outline">取消</Button></Dialog.ActionTrigger><Button colorPalette="red">删除</Button></Dialog.Footer></Dialog.Content></Dialog.Positioner></Dialog.Root><Dialog.Root size="full"><Dialog.Trigger asChild><Button variant="outline">Full</Button></Dialog.Trigger><Dialog.Backdrop /><Dialog.Positioner><Dialog.Content><Dialog.Header><Dialog.Title>全屏 Dialog</Dialog.Title><Dialog.Description>适合编辑长内容。</Dialog.Description></Dialog.Header><Dialog.Body><Text>全屏内容</Text></Dialog.Body></Dialog.Content></Dialog.Positioner></Dialog.Root></Flex> },
  { name: "Drawer", node: <Flex gap="2" wrap="wrap">{(["start", "end", "top", "bottom"] as const).map((placement) => <Drawer.Root key={placement} placement={placement}><Drawer.Trigger asChild><Button variant="outline">{placement} Drawer</Button></Drawer.Trigger><Drawer.Backdrop /><Drawer.Positioner><Drawer.Content><Drawer.Header><Drawer.Title>{placement} Drawer</Drawer.Title><Drawer.Description>抽屉内容。</Drawer.Description></Drawer.Header><Drawer.Body>可以放置表单或详情内容。</Drawer.Body><Drawer.CloseTrigger /></Drawer.Content></Drawer.Positioner></Drawer.Root>)}</Flex> },
  { name: "Progress", node: <Stack gap="4"><Progress.Root value={64} size="sm"><Progress.Track><Progress.Range /></Progress.Track></Progress.Root><Progress.Root value={72} variant="subtle" striped animated><Progress.Track><Progress.Range /></Progress.Track></Progress.Root><ProgressCircle.Root value={68} size="md"><ProgressCircle.Circle><ProgressCircle.Track /><ProgressCircle.Range /></ProgressCircle.Circle></ProgressCircle.Root></Stack> },
  { name: "Skeleton", node: <Stack gap="3"><Skeleton height="4" /><SkeletonText noOfLines={3} /><SkeletonCircle size="10" /></Stack> },
  { name: "Spinner", node: <Flex gap="5"><Spinner size="xs" /><Spinner size="sm" colorPalette="blue" /><Spinner size="lg" colorPalette="green" /></Flex> },
  { name: "Result", node: <EmptyState.Root><EmptyState.Content><EmptyState.Indicator><Text fontSize="2xl">✓</Text></EmptyState.Indicator><EmptyState.Title>操作成功</EmptyState.Title><EmptyState.Description>你的项目已经创建。</EmptyState.Description><Flex gap="2"><Button>查看项目</Button><Button variant="outline">返回列表</Button></Flex></EmptyState.Content></EmptyState.Root> },
  { name: "Popconfirm", node: <Popover.Root><Popover.Trigger asChild><Button colorPalette="red">删除项目</Button></Popover.Trigger><Popover.Positioner><Popover.Content><Popover.Arrow /><Popover.Header>确认删除？</Popover.Header><Popover.Body>删除后无法恢复。</Popover.Body><Popover.Footer><Popover.CloseTrigger asChild><Button size="sm" variant="outline">取消</Button></Popover.CloseTrigger><Button size="sm" colorPalette="red">确认</Button></Popover.Footer></Popover.Content></Popover.Positioner></Popover.Root> },
]
