import { Button, Checkbox, CheckboxCard, Combobox, ColorPicker, createListCollection, Field, Fieldset, FileUpload, Flex, Input, InputGroup, Menu, NumberInput, PinInput, Portal, RadioCard, RadioGroup, RatingGroup, Select, Slider, Stack, Switch, TagsInput, Text, Textarea, parseColor } from "@chakra-ui/react"
import nav from "@ui-gallery/spec/mock/nav.json"
import team from "@ui-gallery/spec/mock/team.json"
import type { ComponentDemo } from "./typography"
import { DatePickerField } from "../shared"

const options = createListCollection({ items: ["React", "Vue", "Svelte", "Solid"].map((value) => ({ label: value, value })) })
const times = createListCollection({ items: ["09:00", "12:00", "15:00", "18:00"].map((value) => ({ label: value, value })) })

function SelectDemo({ multiple = false }: { multiple?: boolean }) {
  return <Select.Root collection={options} multiple={multiple} width="full"><Select.HiddenSelect /><Select.Label>{multiple ? "多选 Select" : "Select"}</Select.Label><Select.Control><Select.Trigger><Select.ValueText placeholder="选择项目" /></Select.Trigger><Select.IndicatorGroup><Select.Indicator /></Select.IndicatorGroup></Select.Control><Select.Positioner><Select.Content>{options.items.map((item) => <Select.Item item={item} key={item.value}>{item.label}<Select.ItemIndicator /></Select.Item>)}</Select.Content></Select.Positioner></Select.Root>
}

function ComboDemo({ allowCustomValue = false }: { allowCustomValue?: boolean }) {
  return <Combobox.Root collection={options} allowCustomValue={allowCustomValue} width="full"><Combobox.Label>{allowCustomValue ? "Autocomplete" : "Combobox"}</Combobox.Label><Combobox.Control><Combobox.Input placeholder="搜索选项..." /><Combobox.IndicatorGroup><Combobox.ClearTrigger /><Combobox.Trigger /></Combobox.IndicatorGroup></Combobox.Control><Combobox.Positioner><Combobox.Content>{options.items.map((item) => <Combobox.Item item={item} key={item.value}>{item.label}<Combobox.ItemIndicator /></Combobox.Item>)}</Combobox.Content></Combobox.Positioner></Combobox.Root>
}

export const formDemos: ComponentDemo[] = [
  { name: "Input", node: <Stack gap="3"><Input size="sm" placeholder="小尺寸" /><Input placeholder="默认输入" /><Input size="lg" disabled placeholder="禁用输入" /><Field.Root invalid><Input placeholder="无效输入" /><Field.ErrorText>格式不正确</Field.ErrorText></Field.Root><InputGroup startElement="https://" endElement=".com"><Input placeholder="website" /></InputGroup><InputGroup startElement="⌕" endElement="清除"><Input type="search" placeholder="搜索" /></InputGroup><Input type="password" placeholder="密码" /></Stack> },
  { name: "Textarea", node: <Stack gap="3"><Textarea autoresize placeholder="自动增高文本区域..." /><Textarea resize="none" placeholder="不可调整大小" maxLength={120} /></Stack> },
  { name: "NumberInput", node: <NumberInput.Root defaultValue="10" min={0} max={100}><NumberInput.Label>数量</NumberInput.Label><NumberInput.Input /><NumberInput.Control><NumberInput.IncrementTrigger /><NumberInput.DecrementTrigger /></NumberInput.Control></NumberInput.Root> },
  { name: "Select", node: <Stack gap="3"><SelectDemo /><SelectDemo /></Stack> },
  { name: "MultiSelect", node: <SelectDemo multiple /> },
  { name: "Combobox", node: <ComboDemo /> },
  { name: "Autocomplete", node: <ComboDemo allowCustomValue /> },
  { name: "Checkbox", node: <Stack gap="3"><Checkbox.Root size="sm"><Checkbox.HiddenInput /><Checkbox.Control /><Checkbox.Label>小尺寸复选框</Checkbox.Label></Checkbox.Root><Checkbox.Root defaultChecked variant="outline"><Checkbox.HiddenInput /><Checkbox.Control /><Checkbox.Label>已选中</Checkbox.Label></Checkbox.Root><Checkbox.Root checked="indeterminate"><Checkbox.HiddenInput /><Checkbox.Control /><Checkbox.Label>部分选中</Checkbox.Label></Checkbox.Root><Checkbox.Group defaultValue={["a"]}><Checkbox.Root value="a"><Checkbox.HiddenInput /><Checkbox.Control /><Checkbox.Label>团队</Checkbox.Label></Checkbox.Root><Checkbox.Root value="b"><Checkbox.HiddenInput /><Checkbox.Control /><Checkbox.Label>产品</Checkbox.Label></Checkbox.Root></Checkbox.Group><CheckboxCard.Root><CheckboxCard.HiddenInput /><CheckboxCard.Control><CheckboxCard.Label>Checkbox Card</CheckboxCard.Label><CheckboxCard.Description>带说明的选项卡</CheckboxCard.Description></CheckboxCard.Control></CheckboxCard.Root></Stack> },
  { name: "Radio", node: <Stack gap="3"><RadioGroup.Root defaultValue="a"><RadioGroup.Label>工作区</RadioGroup.Label><Flex gap="4"><RadioGroup.Item value="a"><RadioGroup.ItemHiddenInput /><RadioGroup.ItemIndicator /><RadioGroup.ItemText>个人</RadioGroup.ItemText></RadioGroup.Item><RadioGroup.Item value="b"><RadioGroup.ItemHiddenInput /><RadioGroup.ItemIndicator /><RadioGroup.ItemText>团队</RadioGroup.ItemText></RadioGroup.Item></Flex></RadioGroup.Root><RadioCard.Root><RadioCard.Item value="pro"><RadioCard.ItemHiddenInput /><RadioCard.ItemControl><RadioCard.ItemIndicator /><RadioCard.ItemText>Pro 方案</RadioCard.ItemText></RadioCard.ItemControl></RadioCard.Item></RadioCard.Root></Stack> },
  { name: "Switch", node: <Stack gap="3"><Switch.Root size="sm"><Switch.HiddenInput /><Switch.Control><Switch.Thumb /></Switch.Control><Switch.Label>小尺寸通知</Switch.Label></Switch.Root><Switch.Root variant="solid" defaultChecked><Switch.HiddenInput /><Switch.Control><Switch.Thumb /></Switch.Control><Switch.Label>已开启</Switch.Label></Switch.Root><Switch.Root disabled><Switch.HiddenInput /><Switch.Control><Switch.Thumb /></Switch.Control><Switch.Label>禁用</Switch.Label></Switch.Root></Stack> },
  { name: "Slider", node: <Stack gap="5"><Slider.Root defaultValue={[40]}><Slider.Label>单值 40</Slider.Label><Slider.Control><Slider.Track><Slider.Range /></Slider.Track><Slider.Thumb index={0} /></Slider.Control></Slider.Root><Slider.Root defaultValue={[20, 60]}><Slider.Control><Slider.Track><Slider.Range /></Slider.Track><Slider.Thumb index={0} /><Slider.Thumb index={1} /></Slider.Control><Slider.Marks marks={[{ value: 0, label: "0" }, { value: 50, label: "50" }, { value: 100, label: "100" }]} /></Slider.Root></Stack> },
  { name: "Rating", node: <RatingGroup.Root count={5} defaultValue={3} allowHalf><RatingGroup.HiddenInput /><RatingGroup.Control /></RatingGroup.Root> },
  { name: "TimePicker", node: <Select.Root collection={times} width="full"><Select.HiddenSelect /><Select.Label>时间</Select.Label><Select.Control><Select.Trigger><Select.ValueText placeholder="选择时间" /></Select.Trigger><Select.IndicatorGroup><Select.Indicator /></Select.IndicatorGroup></Select.Control><Select.Positioner><Select.Content>{times.items.map((item) => <Select.Item item={item} key={item.value}>{item.label}</Select.Item>)}</Select.Content></Select.Positioner></Select.Root> },
  { name: "ColorPicker", node: <ColorPicker.Root defaultValue={parseColor("#3182ce")}><ColorPicker.Control><ColorPicker.Trigger><ColorPicker.ValueSwatch /></ColorPicker.Trigger></ColorPicker.Control><ColorPicker.Positioner><ColorPicker.Content><ColorPicker.Area /><ColorPicker.ChannelSlider channel="hue" /><ColorPicker.ChannelSlider channel="alpha" /><ColorPicker.EyeDropperTrigger /></ColorPicker.Content></ColorPicker.Positioner></ColorPicker.Root> },
  { name: "Upload", node: <FileUpload.Root maxFiles={3}><FileUpload.HiddenInput /><FileUpload.Dropzone><FileUpload.DropzoneContent><Text>拖拽文件到此处，或点击上传</Text><Text fontSize="sm" color="fg.muted">PNG、PDF，最大 10MB</Text></FileUpload.DropzoneContent></FileUpload.Dropzone><FileUpload.ItemGroup><FileUpload.Context>{({ acceptedFiles }) => acceptedFiles.map((file) => <FileUpload.Item key={file.name} file={file}><FileUpload.ItemName /><FileUpload.ItemDeleteTrigger /></FileUpload.Item>)}</FileUpload.Context></FileUpload.ItemGroup></FileUpload.Root> },
  { name: "PinInput", node: <PinInput.Root otp mask size="lg"><PinInput.HiddenInput /><PinInput.Control>{[0, 1, 2, 3, 4, 5].map((index) => <PinInput.Input key={index} index={index} />)}</PinInput.Control></PinInput.Root> },
  { name: "Form", node: <Stack gap="4"><Fieldset.Root><Fieldset.Legend>账户信息</Fieldset.Legend><Field.Root orientation="horizontal" required><Field.Label width="24">姓名<Field.RequiredIndicator /></Field.Label><Input placeholder="林晓" /></Field.Root><Field.Root orientation="vertical" invalid><Field.Label>邮箱</Field.Label><Input placeholder="name@example.com" /><Field.ErrorText>请输入有效邮箱</Field.ErrorText></Field.Root></Fieldset.Root></Stack> },
  { name: "DatePicker", node: <DatePickerField /> },
  { name: "DateRangePicker", node: <DatePickerField selectionMode="range" /> },
  { name: "Cascader", node: <Menu.Root><Menu.Trigger asChild><Button>选择工作区路径</Button></Menu.Trigger><Portal><Menu.Positioner><Menu.Content><Menu.Root positioning={{ placement: "right-start" }}><Menu.TriggerItem>工作区</Menu.TriggerItem><Portal><Menu.Positioner><Menu.Content><Menu.Root positioning={{ placement: "right-start" }}><Menu.TriggerItem>团队 · {team[0].name}</Menu.TriggerItem><Portal><Menu.Positioner><Menu.Content>{nav.slice(0, 3).map((item) => <Menu.Item value={item.key} key={item.key}>{item.label}</Menu.Item>)}</Menu.Content></Menu.Positioner></Portal></Menu.Root></Menu.Content></Menu.Positioner></Portal></Menu.Root></Menu.Content></Menu.Positioner></Portal></Menu.Root> },
  { name: "Transfer", node: <Flex gap="3"><Stack borderWidth="1px" p="3"><Text fontWeight="medium">未分配</Text><Text>设计</Text><Text>工程</Text></Stack><Text alignSelf="center">→</Text><Stack borderWidth="1px" p="3"><Text fontWeight="medium">已分配</Text><Text>产品</Text></Stack></Flex> },
  { name: "Mention", node: <Textarea placeholder="输入 @ 召唤团队成员" /> },
  { name: "TagsInput", node: <TagsInput.Root defaultValue={["react", "chakra"]}><TagsInput.Label>标签</TagsInput.Label><TagsInput.Control><TagsInput.Items /><TagsInput.Input placeholder="添加标签" /></TagsInput.Control></TagsInput.Root> },
]
