import { useState } from "react"
import nav from "@ui-gallery/spec/mock/nav.json"
import { Box, Breadcrumb, Button, ButtonGroup, Combobox, Dialog, Flex, Link, Menu, Pagination, Stack, Steps, Tabs, Text } from "@chakra-ui/react"
import type { ComponentDemo } from "./typography"
import { createListCollection } from "@chakra-ui/react"

const commands = createListCollection({ items: nav.map((item) => ({ label: item.label, value: item.path })) })

export const navigationDemos: ComponentDemo[] = [
  { name: "Menu", node: <Stack gap="3"><Menu.Root><Menu.Trigger asChild><Button>垂直菜单</Button></Menu.Trigger><Menu.Positioner><Menu.Content><Menu.ItemGroup><Menu.ItemGroupLabel>项目</Menu.ItemGroupLabel><Menu.Item value="new">新建项目</Menu.Item><Menu.Item value="edit">编辑项目</Menu.Item></Menu.ItemGroup><Menu.Separator /><Menu.CheckboxItem checked value="show">显示已完成<Menu.ItemIndicator /></Menu.CheckboxItem><Menu.RadioItemGroup defaultValue="all"><Menu.RadioItem value="all">全部</Menu.RadioItem><Menu.RadioItem value="mine">我的</Menu.RadioItem></Menu.RadioItemGroup><Menu.Root><Menu.TriggerItem>更多操作</Menu.TriggerItem><Menu.Positioner><Menu.Content><Menu.Item value="archive">归档</Menu.Item><Menu.Item value="duplicate">复制</Menu.Item></Menu.Content></Menu.Positioner></Menu.Root></Menu.Content></Menu.Positioner></Menu.Root><Flex gap="2"><Menu.Root><Menu.Trigger asChild><Button variant="outline">水平菜单</Button></Menu.Trigger><Menu.Positioner><Menu.Content><Menu.Item value="one">菜单一</Menu.Item><Menu.Item value="two">菜单二</Menu.Item></Menu.Content></Menu.Positioner></Menu.Root><Button variant="subtle">Dropdown</Button></Flex></Stack> },
  { name: "Dropdown", node: <Menu.Root><Menu.Trigger asChild><Button variant="subtle">Dropdown 操作</Button></Menu.Trigger><Menu.Positioner><Menu.Content><Menu.Item value="share">分享</Menu.Item><Menu.Item value="export">导出</Menu.Item></Menu.Content></Menu.Positioner></Menu.Root> },
  { name: "Breadcrumb", node: <Stack gap="3"><Breadcrumb.Root size="sm"><Breadcrumb.List><Breadcrumb.Item><Breadcrumb.Link href="#">工作区</Breadcrumb.Link></Breadcrumb.Item><Breadcrumb.Separator /><Breadcrumb.Item><Breadcrumb.Link href="#">项目</Breadcrumb.Link></Breadcrumb.Item><Breadcrumb.Separator /><Breadcrumb.CurrentLink>详情</Breadcrumb.CurrentLink></Breadcrumb.List></Breadcrumb.Root><Breadcrumb.Root size="lg"><Breadcrumb.List><Breadcrumb.Item><Breadcrumb.Link href="#">首页</Breadcrumb.Link></Breadcrumb.Item><Breadcrumb.Separator /><Breadcrumb.Ellipsis /><Breadcrumb.Separator /><Breadcrumb.CurrentLink>当前页面</Breadcrumb.CurrentLink></Breadcrumb.List></Breadcrumb.Root></Stack> },
  { name: "Tabs", node: <Stack gap="5"><Tabs.Root defaultValue="line" variant="line"><Tabs.List><Tabs.Trigger value="line">Line</Tabs.Trigger><Tabs.Trigger value="subtle">Subtle</Tabs.Trigger><Tabs.Trigger value="enclosed">Enclosed</Tabs.Trigger><Tabs.Trigger value="outline">Outline</Tabs.Trigger><Tabs.Trigger value="plain">Plain</Tabs.Trigger></Tabs.List><Tabs.Content value="line">Tabs 内容</Tabs.Content></Tabs.Root><Tabs.Root defaultValue="one" fitted orientation="vertical"><Tabs.List><Tabs.Trigger value="one">概览</Tabs.Trigger><Tabs.Trigger value="two">设置</Tabs.Trigger></Tabs.List><Tabs.Content value="one">垂直 Tabs</Tabs.Content></Tabs.Root></Stack> },
  { name: "Pagination", node: <Pagination.Root count={30} pageSize={10} defaultPage={1}><ButtonGroup attached><Pagination.PrevTrigger asChild><Button variant="outline">上一页</Button></Pagination.PrevTrigger><Pagination.Items render={(page) => <Pagination.Item {...page} asChild><Button variant={page.value === 1 ? "solid" : "outline"}>{page.value}</Button></Pagination.Item>} /><Pagination.NextTrigger asChild><Button variant="outline">下一页</Button></Pagination.NextTrigger></ButtonGroup><Pagination.PageText /></Pagination.Root> },
  { name: "Steps", node: <Steps.Root count={3} defaultStep={0} orientation="vertical"><Steps.List><Steps.Item index={0}><Steps.Indicator /><Steps.Title>开始</Steps.Title><Steps.Separator /></Steps.Item><Steps.Item index={1}><Steps.Indicator /><Steps.Title>进行中</Steps.Title><Steps.Separator /></Steps.Item><Steps.Item index={2}><Steps.Indicator /><Steps.Title>完成</Steps.Title></Steps.Item></Steps.List></Steps.Root> },
  { name: "Anchor", node: <Stack position="sticky" top="2" gap="1"><Link href="#component-Button">Button</Link><Link href="#component-Table">Table</Link><Link href="#component-Alert">Alert</Link></Stack> },
  { name: "BackTop", node: <Button position="relative" onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}>返回顶部 ↑</Button> },
  { name: "Affix", node: <Box position="sticky" top="2" borderWidth="1px" rounded="l2" p="3">Sticky Affix 导航</Box> },
  { name: "Navbar", node: <Flex borderWidth="1px" rounded="l2" p="3" align="center" justify="space-between"><Text fontWeight="bold">Acme Console</Text><Flex gap="3"><Link href="#component-Grid">产品</Link><Link href="#component-Card">价格</Link><Button size="sm">开始使用</Button></Flex></Flex> },
  { name: "Sidebar", node: <Stack width="220px" borderWidth="1px" rounded="l2" p="3"><Text fontWeight="bold" mb="2">Workspace</Text>{["概览", "订单", "设置"].map((item) => <Button key={item} justifyContent="start" variant={item === "概览" ? "subtle" : "ghost"}>{item}</Button>)}</Stack> },
  { name: "CommandPalette", node: <CommandDemo /> },
]

function CommandDemo() {
  const [open, setOpen] = useState(false)
  return <><Button onClick={() => setOpen(true)}>⌘ K 命令面板</Button><Dialog.Root open={open} onOpenChange={(details) => setOpen(details.open)}><Dialog.Backdrop /><Dialog.Positioner><Dialog.Content><Dialog.Header><Dialog.Title>快速导航</Dialog.Title><Dialog.Description>搜索页面和操作。</Dialog.Description></Dialog.Header><Dialog.Body><Combobox.Root collection={commands}><Combobox.Control><Combobox.Input placeholder="搜索命令..." /><Combobox.Trigger /></Combobox.Control><Combobox.Positioner><Combobox.Content>{commands.items.map((item) => <Combobox.Item item={item} key={item.value}>{item.label}<Combobox.ItemIndicator /></Combobox.Item>)}</Combobox.Content></Combobox.Positioner></Combobox.Root></Dialog.Body></Dialog.Content></Dialog.Positioner></Dialog.Root></>
}
