<script setup lang="ts">
import { computed, ref } from "vue"
import { marked } from "marked"
import { ElMessage } from "element-plus"
import chat from "@ui-gallery/spec/mock/chat.json"
import Icon from "@/icons/Icon.vue"
import { useMobile } from "@/composables/useMobile"
const mobile = useMobile(); const conversationsOpen = ref(false); const active = ref(chat.conversations[0].id); const draft = ref(""); const model = ref(chat.models[0]); const copied = ref(false)
const selected = computed(() => chat.conversations.find((item) => item.id === active.value))
const render = (content: string) => marked.parse(content) as string
const send = () => { if (!draft.value.trim()) return; ElMessage.success("消息已发送（演示）"); draft.value = "" }
const copy = (text: string) => { navigator.clipboard?.writeText(text); copied.value = true; window.setTimeout(() => copied.value = false, 1200) }
</script>

<template>
  <div class="page chat-page"><div class="page-header"><div><h1 class="page-title">AI 对话</h1><p class="page-subtitle">与团队智能助手协作，保留完整上下文。</p></div><el-button v-if="mobile" @click="conversationsOpen = true"><Icon name="message-square" />对话列表</el-button></div>
    <el-drawer v-if="mobile" v-model="conversationsOpen" title="对话" direction="ltr" size="290px"><div class="conversation-list"><el-input placeholder="搜索对话"><template #prefix><Icon name="search" /></template></el-input><el-button type="primary" class="full-width new-chat"><Icon name="plus" />新建对话</el-button><el-button v-for="item in chat.conversations" :key="item.id" class="conversation" :type="active === item.id ? 'primary' : 'default'" plain @click="active = item.id; conversationsOpen = false"><span>{{ item.title }}<small>{{ item.time }}</small></span><el-badge v-if="item.unread" :value="item.unread" /></el-button></div></el-drawer>
    <el-card class="chat-card"><aside v-if="!mobile" class="conversation-pane"><div class="conversation-heading"><b>对话</b><el-button text><Icon name="plus" /></el-button></div><el-input placeholder="搜索对话"><template #prefix><Icon name="search" /></template></el-input><el-button type="primary" class="full-width new-chat"><Icon name="plus" />新建对话</el-button><div class="conversation-list"><el-button v-for="item in chat.conversations" :key="item.id" class="conversation" :type="active === item.id ? 'primary' : 'default'" plain @click="active = item.id"><span>{{ item.title }}<small>{{ item.time }}</small></span><el-badge v-if="item.unread" :value="item.unread" /></el-button></div></aside>
      <section class="chat-main"><header class="chat-header"><div><b>{{ selected?.title }}</b><small>GPT-5 · 已连接</small></div><el-select v-model="model" size="small" style="width: 150px"><el-option v-for="item in chat.models" :key="item" :label="item" :value="item" /></el-select></header><div class="messages"><template v-if="selected?.id === chat.conversations[0].id"><div v-for="(message, index) in chat.messages" :key="index" class="message" :class="message.role"><el-avatar>{{ message.role === 'user' ? '林' : 'AI' }}</el-avatar><div class="message-body"><div class="message-meta">{{ message.role === 'user' ? '林晓' : 'AI 助手' }} · 刚刚</div><div v-if="message.role === 'assistant'" class="bubble markdown" v-html="render(message.content)" /><div v-else class="bubble">{{ message.content }}</div><div v-if="message.role === 'assistant' && message.content.includes('```')" class="code-actions"><el-button size="small" @click="copy(message.content)"><Icon name="copy" />{{ copied ? '已复制' : '复制代码' }}</el-button></div><div v-if="message.sources" class="sources"><el-tag v-for="source in message.sources" :key="source" size="small" effect="plain"><Icon name="paperclip" />{{ source }}</el-tag></div><el-collapse v-if="message.tool" class="tool"><el-collapse-item :title="`工具调用 · ${message.tool.name}`"><pre>{{ JSON.stringify(message.tool.args, null, 2) }}</pre></el-collapse-item></el-collapse><span v-if="message.streaming" class="typing">● ● ●</span></div></div></template><el-empty v-else description="这个会话还没有消息"><template #image><Icon name="sparkles" :size="36" /></template></el-empty></div><div class="composer"><div class="suggestions"><el-tag v-for="suggestion in chat.suggestions" :key="suggestion" round effect="plain" @click="draft = suggestion">{{ suggestion }}</el-tag></div><el-input v-model="draft" type="textarea" :autosize="{ minRows: 3, maxRows: 7 }" maxlength="2000" show-word-limit placeholder="向 AI 助手提问..." @keydown.enter.exact.prevent="send"><template #append><el-button @click="send"><Icon name="send" />发送</el-button></template></el-input><div class="composer-foot"><span class="muted"><Icon name="paperclip" /> 附件 · <kbd>Enter</kbd> 发送</span><el-button text><Icon name="paperclip" /></el-button></div></div></section>
    </el-card>
  </div>
</template>

<style scoped>.chat-card { min-height: 680px; padding: 0; overflow: hidden; }.chat-card :deep(.el-card__body) { display: grid; grid-template-columns: 260px minmax(0, 1fr); min-height: 680px; padding: 0; }.conversation-pane { padding: 16px; border-right: 1px solid var(--el-border-color); }.conversation-heading, .chat-header, .composer-foot { display: flex; align-items: center; justify-content: space-between; gap: 12px; }.new-chat { margin: 12px 0; }.conversation-list { display: grid; gap: 6px; margin-top: 12px; }.conversation { display: flex; width: 100%; height: auto; justify-content: space-between; padding: 10px; text-align: left; }.conversation span { display: grid; gap: 4px; min-width: 0; flex: 1; }.conversation small { color: var(--el-text-color-secondary); }.chat-main { display: flex; min-width: 0; flex-direction: column; }.chat-header { padding: 16px; border-bottom: 1px solid var(--el-border-color); }.chat-header div { display: grid; gap: 4px; }.chat-header small { color: var(--el-text-color-secondary); }.messages { flex: 1; overflow: auto; padding: 24px; }.message { display: flex; gap: 10px; max-width: 850px; margin-bottom: 24px; }.message.user { flex-direction: row-reverse; margin-left: auto; text-align: right; }.message-body { max-width: 80%; }.message-meta { margin-bottom: 6px; color: var(--el-text-color-secondary); font-size: 12px; }.bubble { padding: 12px 15px; border-radius: 12px; background: var(--el-fill-color-light); text-align: left; line-height: 1.65; }.user .bubble { background: var(--el-color-primary); color: white; }.markdown :deep(pre) { overflow: auto; padding: 12px; border-radius: 8px; background: var(--el-bg-color-overlay); }.markdown :deep(table) { border-collapse: collapse; }.markdown :deep(th), .markdown :deep(td) { padding: 6px 10px; border: 1px solid var(--el-border-color); }.sources { display: flex; gap: 6px; margin-top: 8px; }.tool { margin-top: 10px; }.tool pre { overflow: auto; font-size: 12px; }.code-actions { margin-top: 5px; }.typing { display: inline-block; margin-top: 8px; color: var(--el-color-primary); animation: pulse 1.2s infinite; }.composer { padding: 16px; border-top: 1px solid var(--el-border-color); }.suggestions { display: flex; gap: 6px; flex-wrap: wrap; margin-bottom: 10px; }.suggestions .el-tag { cursor: pointer; }.composer-foot { padding-top: 8px; }.muted :deep(.el-icon) { vertical-align: middle; }kbd { padding: 2px 5px; border: 1px solid var(--el-border-color); border-radius: 4px; }@keyframes pulse { 0%,100% { opacity: .35; } 50% { opacity: 1; } }@media (max-width: 767px) { .chat-card :deep(.el-card__body) { display: block; min-height: 650px; }.messages { padding: 16px; }.message-body { max-width: 88%; } }</style>
