<script setup lang="ts">
import { computed, reactive, ref } from "vue"
import { ElMessage } from "element-plus"
import Icon from "@/icons/Icon.vue"
const step = ref(0); const submitted = ref(false); const agreed = ref(false)
const form = reactive({ name: "", count: 1, email: "", phone: "", intro: "", gender: "team", skills: ["分析"], active: true, category: "", tags: ["控制台"], date: "", time: "", range: [], score: 4, color: "#409eff", files: [] as any[] })
const rules = { name: [{ required: true, message: "请输入项目名称", trigger: "blur" }], email: [{ required: true, message: "请输入邮箱", trigger: "blur" }, { type: "email" as const, message: "邮箱格式不正确", trigger: "blur" }] }
const summary = computed(() => [{ label: "项目名称", value: form.name || "暂无数据" }, { label: "邮箱", value: form.email || "暂无数据" }, { label: "类别", value: form.category || "暂无数据" }, { label: "标签", value: form.tags.join("、") }])
const next = () => { if (step.value < 2) step.value += 1 }
const submit = () => { if (!agreed.value) return ElMessage.warning("请先同意条款"); submitted.value = true }
</script>

<template>
  <div class="page"><div class="page-header"><div><h1 class="page-title">新建项目</h1><p class="page-subtitle">用三步完成项目配置，所有信息都可稍后修改。</p></div></div>
    <el-card><el-steps :active="step" finish-status="success" align-center><el-step title="基本信息" description="名称与联系方式" /><el-step title="详细配置" description="偏好与资源" /><el-step title="确认" description="检查并提交" /></el-steps>
      <el-form v-if="!submitted" :model="form" :rules="rules" label-position="top" class="wizard-form">
        <template v-if="step === 0"><el-row :gutter="16"><el-col :xs="24" :md="12"><el-form-item label="项目名称" prop="name" required><el-input v-model="form.name" placeholder="例如：增长看板" /></el-form-item></el-col><el-col :xs="24" :md="12"><el-form-item label="席位数量"><el-input-number v-model="form.count" :min="1" :max="100" class="full-width" /></el-form-item></el-col><el-col :xs="24" :md="12"><el-form-item label="邮箱" prop="email"><el-input v-model="form.email" placeholder="team@example.com" /></el-form-item></el-col><el-col :xs="24" :md="12"><el-form-item label="电话"><el-input v-model="form.phone"><template #prepend><el-select model-value="+86" style="width: 80px"><el-option label="+86" value="+86" /><el-option label="+1" value="+1" /><el-option label="+81" value="+81" /></el-select></template></el-input></el-form-item></el-col></el-row><el-form-item label="项目简介"><el-input v-model="form.intro" type="textarea" maxlength="160" show-word-limit :rows="4" /></el-form-item><el-form-item label="项目类型"><el-radio-group v-model="form.gender"><el-radio value="personal">个人</el-radio><el-radio value="team">团队</el-radio><el-radio value="enterprise">企业</el-radio></el-radio-group></el-form-item><el-form-item label="能力标签"><el-checkbox-group v-model="form.skills"><el-checkbox value="分析" /><el-checkbox value="协作" /><el-checkbox value="自动化" /></el-checkbox-group></el-form-item><el-form-item label="启用项目"><el-switch v-model="form.active" /></el-form-item></template>
        <template v-else-if="step === 1"><el-row :gutter="16"><el-col :xs="24" :md="12"><el-form-item label="分类"><el-select v-model="form.category" filterable allow-create class="full-width" placeholder="选择或创建分类"><el-option label="增长" value="增长" /><el-option label="运营" value="运营" /><el-option label="研发" value="研发" /></el-select></el-form-item></el-col><el-col :xs="24" :md="12"><el-form-item label="标签"><el-select v-model="form.tags" multiple filterable allow-create class="full-width"><el-option v-for="tag in ['控制台','高优先级','季度目标']" :key="tag" :label="tag" :value="tag" /></el-select><small class="muted">可输入自定义标签</small></el-form-item></el-col><el-col :xs="24" :md="12"><el-form-item label="开始日期"><el-date-picker v-model="form.date" type="date" class="full-width" /></el-form-item></el-col><el-col :xs="24" :md="12"><el-form-item label="提醒时间"><el-time-picker v-model="form.time" class="full-width" /></el-form-item></el-col></el-row><el-form-item label="日期范围"><el-date-picker v-model="form.range" type="daterange" class="full-width" /></el-form-item><el-form-item label="预算区间"><el-slider v-model="form.count" range :max="100" /></el-form-item><el-form-item label="评分"><el-rate v-model="form.score" /></el-form-item><el-form-item label="主题色"><el-color-picker v-model="form.color" /></el-form-item><el-form-item label="项目文件"><el-upload drag action="#" :auto-upload="false" v-model:file-list="form.files"><Icon name="upload" :size="28" /><div>拖拽文件到这里，或<em>点击上传</em></div><template #tip><div class="el-upload__tip">支持常见文档格式</div></template></el-upload></el-form-item></template>
        <template v-else><el-descriptions title="配置摘要" :column="1" border><el-descriptions-item v-for="item in summary" :key="item.label" :label="item.label">{{ item.value }}</el-descriptions-item></el-descriptions><el-alert title="请确认信息无误后提交。" type="info" show-icon class="confirm-alert" /><el-checkbox v-model="agreed">我已阅读并同意服务条款</el-checkbox></template>
        <div class="wizard-actions"><el-button v-if="step > 0" @click="step -= 1">上一步</el-button><el-button v-if="step < 2" type="primary" @click="next">下一步</el-button><el-button v-else type="primary" @click="submit">提交项目</el-button></div>
      </el-form><el-result v-else icon="success" title="项目创建成功" sub-title="你可以在设置中继续完善团队信息。"><template #extra><el-button type="primary" @click="submitted = false">创建另一个</el-button></template></el-result>
    </el-card>
  </div>
</template>

<style scoped>.wizard-form { max-width: 900px; margin: 36px auto 0; }.wizard-actions { display: flex; justify-content: flex-end; gap: 10px; margin-top: 28px; }.confirm-alert { margin: 24px 0; }</style>
