<script setup lang="ts">
import { ref } from "vue"
import landing from "@ui-gallery/spec/mock/landing.json"
import plans from "@ui-gallery/spec/mock/plans.json"
import Icon from "@/components/Icon.vue"

const mobileNav = ref(false)
const yearly = ref(false)
</script>

<template>
  <div>
    <v-app-bar flat class="px-2 px-sm-6"><v-avatar color="primary" size="34" rounded="lg">A</v-avatar><v-app-bar-title>Acme Console</v-app-bar-title><v-spacer /><div class="d-none d-md-flex ga-1"><v-btn v-for="item in ['产品', '方案', '客户', '文档', '定价']" :key="item" variant="text">{{ item }}</v-btn></div><v-btn color="primary" class="d-none d-sm-flex">免费开始</v-btn><v-btn icon class="d-md-none" aria-label="打开菜单" @click="mobileNav = true"><Icon name="menu" /></v-btn></v-app-bar>
    <v-navigation-drawer v-model="mobileNav" temporary location="right"><v-list><v-list-item v-for="item in ['产品', '方案', '客户', '文档', '定价']" :key="item" :title="item" /></v-list></v-navigation-drawer>
    <v-main>
      <v-container class="py-10 py-sm-16">
        <v-row align="center" class="mb-10"><v-col cols="12" md="6"><v-chip color="primary" variant="tonal" class="mb-4">为现代团队打造</v-chip><h1 class="text-h3 text-sm-h2 font-weight-bold">{{ landing.hero.title }}</h1><p class="text-h6 text-medium-emphasis mt-5">{{ landing.hero.subtitle }}</p><div class="d-flex flex-wrap ga-3 mt-7"><v-btn color="primary" size="large">{{ landing.hero.primary }}</v-btn><v-btn variant="outlined" size="large">{{ landing.hero.secondary }}</v-btn></div><div class="d-flex align-center ga-3 mt-6"><v-avatar-group><v-avatar v-for="n in 4" :key="n" color="primary" variant="tonal">{{ n }}</v-avatar></v-avatar-group><span class="text-body-2">{{ landing.hero.social }}</span></div></v-col><v-col cols="12" md="6"><v-sheet border rounded="xl" height="320" class="d-flex align-center justify-center bg-surface-variant"><div class="text-center"><Icon name="layout-dashboard" size="56" color="primary" /><div class="text-subtitle-1 mt-3">产品界面预览</div></div></v-sheet></v-col></v-row>
        <div class="text-center mb-10"><div class="text-overline text-medium-emphasis mb-4">被优秀团队信赖</div><div class="d-flex flex-wrap justify-center ga-3"><v-sheet v-for="n in 6" :key="n" border rounded class="pa-4 px-8 text-medium-emphasis">Logo {{ n }}</v-sheet></div></div>
        <v-row class="mb-10"><v-col v-for="feature in landing.features" :key="feature.title" cols="12" sm="6" md="4"><v-card height="100%" variant="tonal" class="pa-5"><Icon :name="feature.icon as 'zap'" size="28" color="primary" /><div class="text-h6 mt-4">{{ feature.title }}</div><p class="text-body-2 text-medium-emphasis mt-2 mb-0">{{ feature.desc }}</p></v-card></v-col></v-row>
        <v-row v-for="(feature, index) in landing.features.slice(0, 3)" :key="feature.title" align="center" class="py-8 py-sm-12"><v-col cols="12" md="6" :order="index % 2 ? 2 : 1"><v-sheet border rounded="xl" height="220" class="d-flex align-center justify-center bg-surface-variant"><Icon :name="feature.icon as 'zap'" size="52" color="primary" /></v-sheet></v-col><v-col cols="12" md="6" :order="index % 2 ? 1 : 2" :class="index % 2 ? 'ps-md-10' : 'pe-md-10'"><div class="text-overline text-primary">Acme Console</div><h2 class="text-h4 mt-2">{{ feature.title }}</h2><p class="text-body-1 text-medium-emphasis mt-3">{{ feature.desc }} 让团队更快协作、更清晰地做出决策。</p><v-btn variant="text" class="px-0">了解更多 <Icon name="arrow-right" size="16" /></v-btn></v-col></v-row>
        <v-sheet color="primary" rounded="xl" class="pa-6 pa-sm-10 my-10"><v-row class="text-center text-sm-left"><v-col v-for="item in landing.numbers" :key="item.label" cols="6" sm="3"><div class="text-h4 font-weight-bold">{{ item.value }}</div><div class="text-body-2 mt-1">{{ item.label }}</div></v-col></v-row></v-sheet>
        <div class="text-center mb-6"><h2 class="text-h4">选择适合你的计划</h2><v-switch v-model="yearly" label="按年计费（省 2 个月）" color="primary" hide-details class="d-inline-flex mt-3" /></div><v-row class="mb-12"><v-col v-for="plan in plans" :key="plan.name" cols="12" md="4"><v-card height="100%" :variant="plan.recommended ? 'elevated' : 'outlined'" :elevation="plan.recommended ? 6 : 0" class="pa-5"><div class="d-flex justify-space-between"><span class="text-h6">{{ plan.name }}</span><v-chip v-if="plan.recommended" color="primary" size="small">推荐</v-chip></div><div class="text-h4 my-5">{{ plan.price === null ? '联系我们' : `¥${yearly ? plan.price * 10 : plan.price}` }}<span v-if="plan.price !== null" class="text-body-2 text-medium-emphasis">/月</span></div><v-list density="compact"><v-list-item v-for="item in plan.features" :key="item" :title="item"><template #prepend><Icon name="check" size="16" /></template></v-list-item></v-list><v-btn block :color="plan.recommended ? 'primary' : undefined" :variant="plan.recommended ? 'flat' : 'outlined'" class="mt-4">开始使用</v-btn></v-card></v-col></v-row>
        <h2 class="text-h4 text-center mb-6">客户这样说</h2><v-row class="mb-12"><v-col v-for="item in landing.testimonials" :key="item.name" cols="12" sm="6" md="4"><v-card height="100%" class="pa-5"><div class="d-flex ga-1 mb-4"><Icon v-for="n in 5" :key="n" name="star" size="16" color="warning" /></div><p class="text-body-1">“{{ item.quote }}”</p><div class="d-flex align-center ga-2 mt-5"><v-avatar color="primary" variant="tonal">{{ item.name.slice(0, 1) }}</v-avatar><div><div class="font-weight-medium">{{ item.name }}</div><div class="text-caption text-medium-emphasis">{{ item.company }}</div></div></div></v-card></v-col></v-row>
        <h2 class="text-h4 text-center mb-6">常见问题</h2><v-expansion-panels class="mb-12"><v-expansion-panel v-for="item in landing.faq" :key="item.q" :title="item.q" :text="item.a" /></v-expansion-panels>
        <v-sheet color="primary" rounded="xl" class="text-center pa-8 pa-sm-12 mb-12"><h2 class="text-h4">准备好开始了吗？</h2><p class="mt-3">让团队把更多时间用在真正重要的事情上。</p><v-btn color="surface" class="mt-5">免费开始</v-btn></v-sheet>
      </v-container>
    </v-main>
    <v-footer border class="pa-6"><v-container><v-row><v-col cols="12" sm="4"><div class="text-h6">Acme Console</div><p class="text-body-2 text-medium-emphasis mt-2">让团队在一个控制台高效协作。</p></v-col><v-col v-for="group in ['产品', '资源', '公司']" :key="group" cols="4" sm="2"><div class="font-weight-medium">{{ group }}</div><v-btn v-for="item in ['概览', '文档', '联系']" :key="item" variant="text" size="small" class="d-block px-0">{{ item }}</v-btn></v-col><v-col cols="12" sm="2"><v-select label="语言" :items="['简体中文', 'English']" density="compact" hide-details /></v-col></v-row><v-divider class="my-5" /><div class="text-caption text-medium-emphasis">© 2026 Acme Console</div></v-container></v-footer>
  </div>
</template>
