import { useState } from "react"
import { Link } from "react-router-dom"
import landing from "@ui-gallery/spec/mock/landing.json"
import nav from "@ui-gallery/spec/mock/nav.json"
import plans from "@ui-gallery/spec/mock/plans.json"
import { Accordion, AccordionTab } from "primereact/accordion"
import { Avatar } from "primereact/avatar"
import { AvatarGroup } from "primereact/avatargroup"
import { Button } from "primereact/button"
import { Card } from "primereact/card"
import { Carousel } from "primereact/carousel"
import { Dropdown } from "primereact/dropdown"
import { InputSwitch } from "primereact/inputswitch"
import { Sidebar } from "primereact/sidebar"
import { Skeleton } from "primereact/skeleton"
import { Tag } from "primereact/tag"
import { Icon } from "@/components/icon"

export function LandingPage() {
  const [annual, setAnnual] = useState(false), [menuOpen, setMenuOpen] = useState(false)
  const featureSlides = landing.features.slice(0, 3)
  const links = [{ label: "产品", href: "#features" }, { label: "价格", href: "#pricing" }, { label: "FAQ", href: "#faq" }, { label: "客户", href: "#stories" }, { label: "关于", href: "#about" }]
  return <div>
    <header className="surface-card border-bottom-1 surface-border sticky top-0 z-5"><div className="max-w-screen-xl mx-auto p-3 flex align-items-center justify-content-between gap-3"><Link to="/" className="flex align-items-center gap-2 no-underline text-color font-semibold"><Avatar label="A" shape="circle" />Acme Console</Link><nav className="hidden md:flex gap-4">{links.map((item) => <a className="hit" href={item.href} key={item.href}>{item.label}</a>)}</nav><div className="flex gap-2"><Button text icon={<Icon name="menu" />} aria-label="菜单" className="md:hidden" onClick={() => setMenuOpen(true)} /><div className="hidden md:flex gap-2"><Link to="/login"><Button text label="登录" /></Link><Link to="/login"><Button label="开始使用" /></Link></div></div></div></header>
    <Sidebar visible={menuOpen} position="right" onHide={() => setMenuOpen(false)}><div className="flex flex-column gap-2">{links.map((item) => <a className="hit no-underline text-color" href={item.href} onClick={() => setMenuOpen(false)} key={item.href}>{item.label}</a>)}<Link className="hit no-underline" to="/login" onClick={() => setMenuOpen(false)}><Button text label="登录" /></Link><Link to="/login" onClick={() => setMenuOpen(false)}><Button className="w-full" label="开始使用" /></Link></div></Sidebar>
    <main>
      <section className="marketing-section grid align-items-center"><div className="col-12 lg:col-6"><Tag value="ACME CONSOLE · 2026" /><h1 className="hero-title mt-4">{landing.hero.title}</h1><p className="text-xl muted line-height-3">{landing.hero.subtitle}</p><div className="flex flex-wrap gap-2"><Link to="/login"><Button size="large" label={landing.hero.primary} icon={<Icon name="arrow-right" />} /></Link><Button size="large" outlined label={landing.hero.secondary} /></div><div className="flex align-items-center gap-3 mt-5 muted"><AvatarGroup><Avatar label="林" shape="circle" /><Avatar label="王" shape="circle" /><Avatar label="A" shape="circle" /><Avatar label="M" shape="circle" /></AvatarGroup><span>{landing.hero.social}</span></div></div><div className="col-12 lg:col-6"><Card><div className="surface-ground border-round p-3" style={{ height: 360 }}><div className="grid h-full"><div className="col-3"><Skeleton className="h-full" borderRadius="12px" /></div><div className="col-9 flex flex-column gap-3"><Skeleton height="45%" borderRadius="12px" /><div className="grid flex-1"><div className="col"><Skeleton className="h-full" borderRadius="12px" /></div><div className="col"><Skeleton className="h-full" borderRadius="12px" /></div><div className="col"><Skeleton className="h-full" borderRadius="12px" /></div></div></div></div></div></Card></div></section>
      <section className="surface-ground py-5"><div className="max-w-screen-lg mx-auto grid text-center muted">{landing.testimonials.map((item) => <strong className="col-6 md:col-2" key={item.company}>{item.company}</strong>)}</div></section>
      <section id="features" className="marketing-section"><div className="text-center mb-6"><h2>功能</h2><p className="muted">{landing.hero.subtitle}</p></div><div className="grid">{landing.features.map((item) => <div className="col-12 md:col-4" key={item.title}><Card title={<span className="flex align-items-center gap-2"><Icon name={item.icon} />{item.title}</span>}><p className="muted m-0">{item.desc}</p></Card></div>)}</div></section>
      <section id="about" className="marketing-section flex flex-column gap-6">{featureSlides.map((item, index) => <div className="grid align-items-center" key={item.title}><div className={`col-12 md:col-6 ${index % 2 ? "md:order-2" : ""}`}><Tag value={`0${index + 1}`} /><h2>{item.title}</h2><p className="muted text-lg">{item.desc}</p><Button link label={landing.hero.secondary} icon={<Icon name="arrow-right" />} /></div><div className={`col-12 md:col-6 ${index % 2 ? "md:order-1" : ""}`}><Card><div className="surface-ground flex align-items-center justify-content-center" style={{ height: 240 }}><Icon name={item.icon} size={58} /></div></Card></div></div>)}</section>
      <section className="surface-ground py-6"><div className="marketing-section py-0 grid text-center">{landing.numbers.map((item) => <div className="col-6 md:col-3" key={item.label}><div className="text-4xl font-bold">{item.value}</div><div className="muted">{item.label}</div></div>)}</div></section>
      <section id="pricing" className="marketing-section"><div className="text-center mb-5"><h2>方案</h2><div className="flex align-items-center justify-content-center gap-2">按年计费 <InputSwitch checked={annual} onChange={(event) => setAnnual(Boolean(event.value))} /></div></div><div className="grid">{plans.map((plan) => <div className="col-12 md:col-4" key={plan.name}><Card className={plan.recommended ? "border-primary" : ""} title={<span className="flex justify-content-between">{plan.name}{plan.recommended ? <Tag value="推荐" severity="success" /> : null}</span>}><div className="text-3xl font-bold">{plan.price === null ? "定制" : plan.price === 0 ? "免费" : `¥${annual ? plan.price * 10 : plan.price}`}<small className="text-sm muted"> / 月</small></div><ul className="pl-3">{plan.features.map((feature) => <li className="mb-2" key={feature}><Icon name="check" className="mr-2" />{feature}</li>)}</ul><Button className="w-full" label={landing.hero.primary} outlined={!plan.recommended} /></Card></div>)}</div></section>
      <section id="stories" className="marketing-section"><h2 className="text-center">评价</h2><Carousel value={landing.testimonials} numVisible={1} numScroll={1} circular itemTemplate={(item) => <Card className="m-2"><p className="text-lg">“{item.quote}”</p><div className="flex align-items-center gap-2"><Avatar label={item.name.slice(0, 1)} shape="circle" /><div><strong>{item.name}</strong><small className="block muted">{item.company}</small></div></div></Card>} /></section>
      <section id="faq" className="marketing-section"><h2 className="text-center">常见问题</h2><Accordion>{landing.faq.map((item) => <AccordionTab header={item.q} key={item.q}><p>{item.a}</p></AccordionTab>)}</Accordion></section>
      <section className="marketing-section"><Card className="text-center"><h2>{landing.hero.title}</h2><p>{landing.hero.subtitle}</p><Link to="/login"><Button label={landing.hero.primary} /></Link></Card></section>
    </main>
    <footer className="surface-ground p-5"><div className="max-w-screen-xl mx-auto grid"><div className="col-12 md:col-3"><strong>Acme Console</strong><Dropdown className="mt-3" options={["简体中文", "English"]} value="简体中文" /><p className="muted">© 2026 Acme Console</p><div className="flex gap-2 mt-3"><Button text rounded icon={<Icon name="github" />} aria-label="GitHub" /><Button text rounded icon={<Icon name="globe" />} aria-label="网站" /><Button text rounded icon={<Icon name="mail" />} aria-label="邮件" /></div></div><div className="col-12 md:col-3"><strong>导航</strong><div className="flex flex-column gap-2 mt-3">{nav.slice(0, 4).map((item) => <Link className="hit" to={item.path} key={item.path}>{item.label}</Link>)}</div></div><div className="col-12 md:col-3"><strong>功能</strong><div className="flex flex-column gap-2 mt-3">{landing.features.slice(0, 4).map((item) => <a className="hit" href="#features" key={item.title}>{item.title}</a>)}</div></div><div className="col-12 md:col-3"><strong>方案</strong><div className="flex flex-column gap-2 mt-3">{plans.map((plan) => <a className="hit" href="#pricing" key={plan.name}>{plan.name}</a>)}</div></div></div></footer>
  </div>
}
