import type { ComponentType } from "react"
import { Icon as AdapterIcon } from "@ui-gallery/icons-react"
import * as F from "@fluentui/react-icons"
import { readIconFamily } from "./settings"

type FluentIconComponent = ComponentType<F.FluentIconsProps>

const native: Record<string, FluentIconComponent> = {
  activity: F.PulseRegular,
  "alert-circle": F.ErrorCircleRegular,
  archive: F.ArchiveRegular,
  "arrow-down": F.ArrowDownRegular,
  "arrow-left": F.ArrowLeftRegular,
  "arrow-right": F.ArrowRightRegular,
  "arrow-up": F.ArrowUpRegular,
  "arrow-up-right": F.ArrowUpRightRegular,
  "bar-chart": F.DataBarVerticalRegular,
  bell: F.AlertRegular,
  bot: F.BotRegular,
  boxes: F.CubeRegular,
  calendar: F.CalendarRegular,
  check: F.CheckmarkRegular,
  "check-circle": F.CheckmarkCircleRegular,
  "chevron-down": F.ChevronDownRegular,
  "chevron-left": F.ChevronLeftRegular,
  "chevron-right": F.ChevronRightRegular,
  "chevron-up": F.ChevronUpRegular,
  "circle-help": F.QuestionCircleRegular,
  clipboard: F.ClipboardRegular,
  clock: F.ClockRegular,
  code: F.CodeRegular,
  copy: F.CopyRegular,
  "credit-card": F.PaymentRegular,
  desktop: F.DesktopRegular,
  download: F.ArrowDownloadRegular,
  edit: F.EditRegular,
  "ellipsis-horizontal": F.MoreHorizontalRegular,
  eye: F.EyeRegular,
  "eye-off": F.EyeOffRegular,
  "file-plus": F.DocumentAddRegular,
  file: F.DocumentRegular,
  filter: F.FilterRegular,
  github: F.CodeRegular,
  globe: F.GlobeRegular,
  grid: F.GridRegular,
  heart: F.HeartRegular,
  home: F.HomeRegular,
  image: F.ImageRegular,
  inbox: F.MailRegular,
  info: F.InfoRegular,
  key: F.KeyRegular,
  "layout-dashboard": F.GridRegular,
  link: F.LinkRegular,
  list: F.ListRegular,
  loader: F.ArrowSyncRegular,
  lock: F.LockClosedRegular,
  "log-in": F.PersonArrowRightRegular,
  "log-out": F.SignOutRegular,
  mail: F.MailRegular,
  menu: F.NavigationRegular,
  "message-circle": F.ChatMultipleRegular,
  "message-square": F.ChatRegular,
  mic: F.MicRegular,
  minus: F.SubtractRegular,
  "more-horizontal": F.MoreHorizontalRegular,
  moon: F.WeatherMoonRegular,
  paperclip: F.AttachRegular,
  pencil: F.EditRegular,
  phone: F.PhoneRegular,
  play: F.PlayRegular,
  plus: F.AddRegular,
  plug: F.PlugConnectedRegular,
  "qr-code": F.QrCodeRegular,
  refresh: F.ArrowSyncRegular,
  search: F.SearchRegular,
  send: F.SendRegular,
  settings: F.SettingsRegular,
  shield: F.ShieldRegular,
  "shopping-cart": F.CartRegular,
  sliders: F.OptionsRegular,
  sparkles: F.SparkleRegular,
  star: F.StarRegular,
  sun: F.WeatherSunnyRegular,
  tag: F.TagRegular,
  trash: F.DeleteRegular,
  "trending-down": F.ArrowTrendingDownRegular,
  "trending-up": F.ArrowTrendingRegular,
  upload: F.ArrowUploadRegular,
  user: F.PersonRegular,
  users: F.PeopleRegular,
  warning: F.WarningRegular,
  x: F.DismissRegular,
  zap: F.FlashRegular,
  "alert-triangle": F.WarningRegular,
  box: F.BoxRegular,
  columns: F.ColumnTripleRegular,
  "thumbs-down": F.ThumbDislikeRegular,
  "thumbs-up": F.ThumbLikeRegular,
  twitter: F.ShareRegular,
  "user-plus": F.PersonAddRegular,
  wrench: F.WrenchRegular,
  command: F.KeyCommandRegular,
  folder: F.FolderRegular,
  "help-circle": F.QuestionCircleRegular,
}

export type IconProps = { name: string; size?: number; className?: string }

export function Icon({ name, size = 20, className }: IconProps) {
  if (readIconFamily() !== "native") return <AdapterIcon name={name} size={size} className={className} />
  const Component = native[name] ?? F.QuestionCircleRegular
  return <Component aria-hidden="true" fontSize={size} className={className} />
}

export const icon = (name: string, size?: number) => <Icon name={name} size={size} />
