import { Icon as BpIcon, type IconName } from "@blueprintjs/core"
import { Icon as PackIcon } from "@ui-gallery/icons-react"
import { iconFamily } from "./settings"

/** Shared icon keys (icons-react vocabulary) → Blueprint native icon names. */
const native: Record<string, IconName> = {
  activity: "pulse",
  "alert-circle": "warning-sign",
  archive: "archive",
  "arrow-down": "arrow-down",
  "arrow-left": "arrow-left",
  "arrow-right": "arrow-right",
  "arrow-up": "arrow-up",
  "bar-chart": "timeline-bar-chart",
  bell: "notifications",
  bot: "predictive-analysis",
  boxes: "cube",
  calendar: "calendar",
  check: "tick",
  "chevron-down": "chevron-down",
  "chevron-left": "chevron-left",
  "chevron-right": "chevron-right",
  "chevron-up": "chevron-up",
  "circle-help": "help",
  clipboard: "clipboard",
  clock: "time",
  copy: "duplicate",
  download: "download",
  edit: "edit",
  "ellipsis-horizontal": "more",
  "eye-off": "eye-off",
  eye: "eye-open",
  "file-plus": "folder-new",
  filter: "filter",
  github: "git-repo",
  globe: "globe",
  grid: "grid-view",
  heart: "heart",
  home: "home",
  inbox: "inbox",
  key: "key",
  "layout-dashboard": "dashboard",
  link: "link",
  list: "list",
  loader: "refresh",
  lock: "lock",
  "log-in": "log-in",
  "log-out": "log-out",
  mail: "envelope",
  menu: "menu",
  "message-circle": "chat",
  "message-square": "comment",
  mic: "microphone",
  minus: "minus",
  "more-horizontal": "more",
  moon: "moon",
  paperclip: "paperclip",
  pencil: "edit",
  play: "play",
  plug: "data-connection",
  plus: "plus",
  refresh: "refresh",
  search: "search",
  send: "send-message",
  settings: "cog",
  shield: "shield",
  "shopping-cart": "shopping-cart",
  sliders: "settings",
  sparkles: "clean",
  star: "star",
  sun: "flash",
  tag: "tag",
  trash: "trash",
  upload: "upload",
  user: "user",
  users: "people",
  x: "cross",
  zap: "lightning",
}

export function AppIcon({ name, size = 16 }: { name: string; size?: number }) {
  if (iconFamily() === "native") return <BpIcon icon={native[name] ?? "help"} size={size} />
  return <PackIcon name={name} size={size} />
}

/** Element form for Blueprint `icon` / `rightIcon` props. */
export const icon = (name: string, size = 16) => <AppIcon name={name} size={size} />
