import {
  Activity,
  AlertCircle,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  BarChart3,
  Bell,
  Bot,
  Boxes,
  CalendarDays,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleHelp,
  Clipboard,
  Clock3,
  Copy,
  Download,
  Edit3,
  Ellipsis,
  FilePlus,
  Filter,
  Globe,
  Grid2X2,
  Heart,
  Home,
  LayoutDashboard,
  Link2,
  List,
  LoaderCircle,
  Lock,
  LogIn,
  LogOut,
  Menu,
  MessageCircle,
  MessageSquare,
  Mic,
  Minus,
  MoreHorizontal,
  Moon,
  Paperclip,
  Pencil,
  Play,
  Plus,
  Plug,
  RefreshCw,
  Search,
  Send,
  Settings,
  Shield,
  ShoppingCart,
  SlidersHorizontal,
  Sparkles,
  Star,
  Sun,
  Tag,
  Trash2,
  Upload,
  User,
  Users,
  X,
  Zap,
} from "lucide-react"
import {
  IconActivity,
  IconAlertCircle,
  IconArchive,
  IconArrowDown,
  IconArrowLeft,
  IconArrowRight,
  IconArrowUp,
  IconBell,
  IconBox,
  IconCalendar,
  IconChartBar,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconInfoCircle,
  IconClipboard,
  IconClock,
  IconCopy,
  IconDownload,
  IconEdit,
  IconExternalLink,
  IconFilePlus,
  IconFilter,
  IconGlobe,
  IconGrid3x3,
  IconHeart,
  IconHome,
  IconLayoutDashboard,
  IconLink,
  IconList,
  IconLoader2,
  IconLock,
  IconLogin,
  IconLogout,
  IconMenu2,
  IconMessage,
  IconMessageCircle,
  IconMicrophone,
  IconMinus,
  IconDots,
  IconMoon,
  IconPaperclip,
  IconPencil,
  IconPlayerPlay,
  IconPlus,
  IconRefresh,
  IconSearch,
  IconSend,
  IconSettings,
  IconShield,
  IconShoppingCart,
  IconAdjustmentsHorizontal,
  IconSparkles,
  IconStar,
  IconSun,
  IconTag,
  IconTrash,
  IconUpload,
  IconUser,
  IconUsers,
  IconX,
  IconZzz,
} from "@tabler/icons-react"
import {
  Archive as PhArchive,
  ArrowDown as PhArrowDown,
  ArrowLeft as PhArrowLeft,
  ArrowRight as PhArrowRight,
  ArrowUp as PhArrowUp,
  Bell as PhBell,
  Cube as PhBoxes,
  Calendar as PhCalendar,
  ChartBar as PhChartBar,
  Check as PhCheck,
  CaretDown as PhCaretDown,
  CaretLeft as PhCaretLeft,
  CaretRight as PhCaretRight,
  CaretUp as PhCaretUp,
  ChatCircle as PhChatCircle,
  ChatText as PhChatText,
  CheckCircle as PhCheckCircle,
  Clipboard as PhClipboard,
  Clock as PhClock,
  Copy as PhCopy,
  DownloadSimple as PhDownload,
  DotsThree as PhDotsThree,
  FilePlus as PhFilePlus,
  Faders as PhFaders,
  Gear as PhGear,
  Globe as PhGlobe,
  GridFour as PhGridFour,
  Heart as PhHeart,
  House as PhHouse,
  Link as PhLink,
  List as PhList,
  Lock as PhLock,
  MagicWand as PhMagicWand,
  MagnifyingGlass as PhMagnifyingGlass,
  Microphone as PhMicrophone,
  Minus as PhMinus,
  Moon as PhMoon,
  Paperclip as PhPaperclip,
  Pencil as PhPencil,
  Play as PhPlay,
  Plus as PhPlus,
  Plugs as PhPlugs,
  Power as PhPower,
  Repeat as PhRepeat,
  PaperPlaneTilt as PhSend,
  Pulse as PhPulse,
  Shield as PhShield,
  ShoppingCart as PhShoppingCart,
  SlidersHorizontal as PhSliders,
  Sparkle as PhSparkle,
  Star as PhStar,
  Sun as PhSun,
  Tag as PhTag,
  Trash as PhTrash,
  UploadSimple as PhUpload,
  User as PhUser,
  Users as PhUsers,
  X as PhX,
  Lightning as PhLightning,
} from "@phosphor-icons/react"
import {
  ArrowDownIcon as HeroArrowDown,
  ArrowLeftIcon as HeroArrowLeft,
  ArrowRightIcon as HeroArrowRight,
  ArrowUpIcon as HeroArrowUp,
  BellIcon as HeroBell,
  CalendarDaysIcon as HeroCalendar,
  ChartBarIcon as HeroChart,
  CheckIcon as HeroCheck,
  ChevronDownIcon as HeroChevronDown,
  ChevronLeftIcon as HeroChevronLeft,
  ChevronRightIcon as HeroChevronRight,
  ChevronUpIcon as HeroChevronUp,
  ClipboardIcon as HeroClipboard,
  ClockIcon as HeroClock,
  CloudArrowUpIcon as HeroUpload,
  Cog6ToothIcon as HeroSettings,
  EllipsisHorizontalIcon as HeroDots,
  FolderPlusIcon as HeroFilePlus,
  FunnelIcon as HeroFilter,
  GlobeAltIcon as HeroGlobe,
  HomeIcon as HeroHome,
  InformationCircleIcon as HeroInfo,
  LinkIcon as HeroLink,
  ListBulletIcon as HeroList,
  LockClosedIcon as HeroLock,
  MagnifyingGlassIcon as HeroSearch,
  MegaphoneIcon as HeroMegaphone,
  MicrophoneIcon as HeroMicrophone,
  MinusIcon as HeroMinus,
  MoonIcon as HeroMoon,
  PaperClipIcon as HeroPaperclip,
  PencilIcon as HeroPencil,
  PlayIcon as HeroPlay,
  PlusIcon as HeroPlus,
  PowerIcon as HeroPower,
  RectangleGroupIcon as HeroBoxes,
  RocketLaunchIcon as HeroRocket,
  ServerIcon as HeroServer,
  ShareIcon as HeroShare,
  ShoppingCartIcon as HeroCart,
  SparklesIcon as HeroSparkles,
  StarIcon as HeroStar,
  SunIcon as HeroSun,
  TagIcon as HeroTag,
  TrashIcon as HeroTrash,
  UserIcon as HeroUser,
  UserGroupIcon as HeroUsers,
  XMarkIcon as HeroX,
} from "@heroicons/react/24/outline"

type IconProps = {
  size?: number | string
  className?: string
  strokeWidth?: number
  weight?: string
  color?: string
}

type IconComponent = any

const lucide: Record<string, IconComponent> = {
  activity: Activity,
  "alert-circle": AlertCircle,
  archive: Archive,
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  "bar-chart": BarChart3,
  bell: Bell,
  bot: Bot,
  boxes: Boxes,
  calendar: CalendarDays,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "circle-help": CircleHelp,
  clipboard: Clipboard,
  clock: Clock3,
  copy: Copy,
  download: Download,
  edit: Edit3,
  "ellipsis-horizontal": Ellipsis,
  "file-plus": FilePlus,
  filter: Filter,
  globe: Globe,
  grid: Grid2X2,
  heart: Heart,
  home: Home,
  "layout-dashboard": LayoutDashboard,
  link: Link2,
  list: List,
  loader: LoaderCircle,
  lock: Lock,
  "log-in": LogIn,
  "log-out": LogOut,
  menu: Menu,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  mic: Mic,
  minus: Minus,
  "more-horizontal": MoreHorizontal,
  moon: Moon,
  paperclip: Paperclip,
  pencil: Pencil,
  play: Play,
  plus: Plus,
  plug: Plug,
  refresh: RefreshCw,
  search: Search,
  send: Send,
  settings: Settings,
  shield: Shield,
  "shopping-cart": ShoppingCart,
  sliders: SlidersHorizontal,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  tag: Tag,
  trash: Trash2,
  upload: Upload,
  user: User,
  users: Users,
  x: X,
  zap: Zap,
}

const tabler: Record<string, IconComponent> = {
  activity: IconActivity,
  "alert-circle": IconAlertCircle,
  archive: IconArchive,
  "arrow-down": IconArrowDown,
  "arrow-left": IconArrowLeft,
  "arrow-right": IconArrowRight,
  "arrow-up": IconArrowUp,
  "bar-chart": IconChartBar,
  bell: IconBell,
  bot: IconZzz,
  boxes: IconBox,
  calendar: IconCalendar,
  check: IconCheck,
  "chevron-down": IconChevronDown,
  "chevron-left": IconChevronLeft,
  "chevron-right": IconChevronRight,
  "chevron-up": IconChevronUp,
  "circle-help": IconInfoCircle,
  clipboard: IconClipboard,
  clock: IconClock,
  copy: IconCopy,
  download: IconDownload,
  edit: IconEdit,
  "ellipsis-horizontal": IconDots,
  "file-plus": IconFilePlus,
  filter: IconFilter,
  globe: IconGlobe,
  github: IconGlobe,
  grid: IconGrid3x3,
  heart: IconHeart,
  home: IconHome,
  inbox: IconArchive,
  "layout-dashboard": IconLayoutDashboard,
  link: IconLink,
  list: IconList,
  loader: IconLoader2,
  lock: IconLock,
  "log-in": IconLogin,
  "log-out": IconLogout,
  menu: IconMenu2,
  "message-circle": IconMessageCircle,
  "message-square": IconMessage,
  mic: IconMicrophone,
  minus: IconMinus,
  "more-horizontal": IconDots,
  moon: IconMoon,
  paperclip: IconPaperclip,
  pencil: IconPencil,
  play: IconPlayerPlay,
  plus: IconPlus,
  plug: IconExternalLink,
  refresh: IconRefresh,
  search: IconSearch,
  send: IconSend,
  settings: IconSettings,
  shield: IconShield,
  "shopping-cart": IconShoppingCart,
  sliders: IconAdjustmentsHorizontal,
  sparkles: IconSparkles,
  star: IconStar,
  sun: IconSun,
  tag: IconTag,
  type: IconList,
  trash: IconTrash,
  upload: IconUpload,
  user: IconUser,
  users: IconUsers,
  x: IconX,
  zap: IconZzz,
}

const phosphor: Record<string, IconComponent> = {
  activity: PhPulse,
  "alert-circle": PhCheckCircle,
  archive: PhArchive,
  "arrow-down": PhArrowDown,
  "arrow-left": PhArrowLeft,
  "arrow-right": PhArrowRight,
  "arrow-up": PhArrowUp,
  "bar-chart": PhChartBar,
  bell: PhBell,
  bot: PhMagicWand,
  boxes: PhBoxes,
  calendar: PhCalendar,
  check: PhCheck,
  "chevron-down": PhCaretDown,
  "chevron-left": PhCaretLeft,
  "chevron-right": PhCaretRight,
  "chevron-up": PhCaretUp,
  "circle-help": PhCheckCircle,
  clipboard: PhClipboard,
  clock: PhClock,
  copy: PhCopy,
  download: PhDownload,
  edit: PhPencil,
  "ellipsis-horizontal": PhDotsThree,
  "file-plus": PhFilePlus,
  filter: PhFaders,
  globe: PhGlobe,
  github: PhGlobe,
  grid: PhGridFour,
  heart: PhHeart,
  home: PhHouse,
  inbox: PhArchive,
  "layout-dashboard": PhGridFour,
  link: PhLink,
  list: PhList,
  loader: PhRepeat,
  lock: PhLock,
  "log-in": PhPower,
  "log-out": PhPower,
  menu: PhList,
  "message-circle": PhChatCircle,
  "message-square": PhChatText,
  mic: PhMicrophone,
  minus: PhMinus,
  "more-horizontal": PhDotsThree,
  moon: PhMoon,
  paperclip: PhPaperclip,
  pencil: PhPencil,
  play: PhPlay,
  plus: PhPlus,
  plug: PhPlugs,
  refresh: PhRepeat,
  search: PhMagnifyingGlass,
  send: PhSend,
  settings: PhGear,
  shield: PhShield,
  "shopping-cart": PhShoppingCart,
  sliders: PhSliders,
  sparkles: PhSparkle,
  star: PhStar,
  sun: PhSun,
  tag: PhTag,
  type: PhList,
  trash: PhTrash,
  upload: PhUpload,
  user: PhUser,
  users: PhUsers,
  x: PhX,
  zap: PhLightning,
}

const heroicons: Record<string, IconComponent> = {
  activity: HeroChart,
  "alert-circle": HeroInfo,
  archive: HeroList,
  "arrow-down": HeroArrowDown,
  "arrow-left": HeroArrowLeft,
  "arrow-right": HeroArrowRight,
  "arrow-up": HeroArrowUp,
  bell: HeroBell,
  bot: HeroSparkles,
  calendar: HeroCalendar,
  "bar-chart": HeroChart,
  check: HeroCheck,
  "chevron-down": HeroChevronDown,
  "chevron-left": HeroChevronLeft,
  "chevron-right": HeroChevronRight,
  "chevron-up": HeroChevronUp,
  "circle-help": HeroInfo,
  clipboard: HeroClipboard,
  clock: HeroClock,
  copy: HeroClipboard,
  download: HeroUpload,
  edit: HeroPencil,
  "ellipsis-horizontal": HeroDots,
  "file-plus": HeroFilePlus,
  filter: HeroFilter,
  globe: HeroGlobe,
  github: HeroGlobe,
  boxes: HeroBoxes,
  home: HeroHome,
  heart: HeroStar,
  inbox: HeroList,
  info: HeroInfo,
  grid: HeroList,
  link: HeroLink,
  list: HeroList,
  "layout-dashboard": HeroHome,
  loader: HeroArrowRight,
  lock: HeroLock,
  "log-in": HeroPower,
  "log-out": HeroPower,
  menu: HeroList,
  "message-circle": HeroList,
  "message-square": HeroList,
  mic: HeroMicrophone,
  minus: HeroMinus,
  "more-horizontal": HeroDots,
  moon: HeroMoon,
  paperclip: HeroPaperclip,
  pencil: HeroPencil,
  play: HeroPlay,
  plus: HeroPlus,
  plug: HeroShare,
  refresh: HeroArrowRight,
  search: HeroSearch,
  send: HeroMegaphone,
  settings: HeroSettings,
  shield: HeroServer,
  "shopping-cart": HeroCart,
  sparkles: HeroSparkles,
  star: HeroStar,
  sun: HeroSun,
  tag: HeroTag,
  type: HeroList,
  trash: HeroTrash,
  upload: HeroUpload,
  user: HeroUser,
  users: HeroUsers,
  x: HeroX,
  zap: HeroRocket,
}

function family() {
  if (typeof window === "undefined") return "lucide"
  const value = new URLSearchParams(window.location.search).get("icons")
  return value === "tabler" || value === "phosphor" || value === "heroicons"
    ? value
    : "lucide"
}

export function useIcon(name: string): IconComponent {
  const map = family() === "tabler" ? tabler : family() === "phosphor" ? phosphor : family() === "heroicons" ? heroicons : lucide
  return map[name] ?? map["circle-help"] ?? CircleHelp
}

export function Icon({ name, ...props }: IconProps & { name: string }) {
  const Component = useIcon(name)
  return <Component aria-hidden="true" {...props} />
}
