import { Link } from "react-router-dom"
import landing from "@ui-gallery/spec/mock/landing.json"
import plans from "@ui-gallery/spec/mock/plans.json"
import { Avatar, Button, Heading, Label, Text } from "@primer/react"
import { Icon, iconFor } from "@/lib/icon"
import { avatarSrc } from "@/lib/avatar"

export function LandingPage() {
  return (
    <div>
      <header className="shell-header flex items-center justify-between gap-3"><Link className="brand flex items-center gap-2" to="/"><span className="brand-mark">A</span>Acme Console</Link><nav className="desktop-only flex gap-4"><a href="#features">产品</a><a href="#pricing">价格</a><a href="#faq">FAQ</a></nav><div className="flex gap-2"><Button variant="invisible" as={Link} to="/login">登录</Button><Button variant="primary" as={Link} to="/login">开始使用</Button></div></header>
      <main>
        <section className="hero"><div className="hero-grid"><div className="stack-4"><Label>ACME CONSOLE · 2026</Label><Heading as="h1">{landing.hero.title}</Heading><Text as="p" style={{ fontSize: 20 }}>{landing.hero.subtitle}</Text><div className="flex wrap gap-2"><Button size="large" variant="primary" as={Link} to="/login" trailingVisual={iconFor("arrow-right")}>{landing.hero.primary}</Button><Button size="large">{landing.hero.secondary}</Button></div><div className="flex items-center gap-3 muted"><div className="flex">{["林", "王", "A", "M"].map((name) => <span className="brand-mark" style={{ marginLeft: -4, border: "2px solid var(--bgColor-default)" }} key={name}>{name}</span>)}</div>{landing.hero.social}</div></div><div className="card"><div className="feature-visual"><div className="grid grid-2" style={{ width: "80%", height: "70%" }}><div className="card" /><div className="stack-3"><div className="card" style={{ flex: 1 }} /><div className="grid grid-2"><div className="card" /><div className="card" /></div></div></div></div></div></div></section>
        <section className="logo-row" style={{ borderBlock: "1px solid var(--borderColor-default)", color: "var(--fgColor-muted)" }}>{["Northwind", "Contoso", "Globex", "Fabrikam", "Initech", "Umbrella"].map((name) => <span key={name}>{name}</span>)}</section>
        <section id="features" className="landing-section stack-5"><div style={{ textAlign: "center" }}><Text className="muted">为团队打造</Text><Heading as="h2">一个地方，完成所有工作</Heading><Text className="muted">从数据到决策，让每一步都更清晰。</Text></div><div className="grid grid-3">{landing.features.map((item) => <section className="card" key={item.title}><div className="brand-mark"><Icon name={item.icon} /></div><Heading as="h3">{item.title}</Heading><Text className="muted">{item.desc}</Text></section>)}</div></section>
        <section className="landing-section stack-5">{["看见全局", "自动化协作", "AI 就在身边"].map((title, index) => <div className="grid grid-2 items-center" key={title}><div className={index % 2 ? "desktop-only" : ""}><Label>0{index + 1} / WORKSPACE</Label><Heading as="h2">{title}</Heading><Text as="p" className="muted">把分散的信息汇聚为有用的洞察，让团队快速行动并持续交付。</Text><Button variant="link" trailingVisual={iconFor("arrow-right")}>了解更多</Button></div><div className="feature-visual"><Icon name={landing.features[index + 1].icon} size={52} /></div></div>)}</section>
        <section className="stat-row" style={{ borderBlock: "1px solid var(--borderColor-default)" }}>{landing.numbers.map((item) => <div key={item.label}><Heading as="h2">{item.value}</Heading><Text className="muted">{item.label}</Text></div>)}</section>
        <section id="pricing" className="landing-section stack-5"><div style={{ textAlign: "center" }}><Heading as="h2">选择适合你的方案</Heading><Text className="muted">简单透明，随时升级。</Text></div><div className="grid grid-3">{plans.map((plan) => <section className="card stack-3" key={plan.name}><div className="flex justify-between"><Heading as="h3">{plan.name}</Heading>{plan.recommended ? <Label variant="accent">最受欢迎</Label> : null}</div><Heading as="h2">{plan.price === null ? "定制" : plan.price === 0 ? "免费" : `¥${plan.price}`}</Heading><Text className="muted">{plan.features.join(" · ")}</Text><Button variant={plan.recommended ? "primary" : "default"} block>开始使用</Button></section>)}</div></section>
        <section className="landing-section stack-4"><Heading as="h2" style={{ textAlign: "center" }}>他们已经在改变工作方式</Heading><div className="grid grid-2">{landing.testimonials.slice(0, 4).map((item) => <section className="card stack-3" key={item.name}><Text as="p">“{item.quote}”</Text><div className="flex items-center gap-2"><Avatar src={avatarSrc} alt={item.name} size={32} /><div><Text>{item.name}</Text><Text as="p" className="muted">{item.company}</Text></div></div></section>)}</div></section>
        <section id="faq" className="landing-section stack-4" style={{ maxWidth: 800 }}><Heading as="h2" style={{ textAlign: "center" }}>常见问题</Heading>{landing.faq.map((item) => <details key={item.q}><summary>{item.q}</summary><Text as="p">{item.a}</Text></details>)}</section>
        <section className="landing-section" style={{ textAlign: "center", background: "var(--bgColor-accent-emphasis)", color: "var(--fgColor-onEmphasis)" }}><Heading as="h2">准备好让团队更高效了吗？</Heading><Text as="p">从今天开始，把工作放进一个控制台。</Text><Button size="large" as={Link} to="/login" trailingVisual={iconFor("arrow-right")}>免费开始</Button></section>
      </main>
      <footer className="shell-header flex items-center justify-between gap-3 muted"><span>© 2026 Acme Console</span><div className="flex gap-3"><a href="#features">产品</a><a href="#pricing">价格</a><a href="#faq">帮助中心</a></div></footer>
    </div>
  )
}
