import { useState } from "react"
import sessions from "@ui-gallery/spec/mock/sessions.json"
import team from "@ui-gallery/spec/mock/team.json"
import plans from "@ui-gallery/spec/mock/plans.json"
import invoices from "@ui-gallery/spec/mock/invoices.json"
import { Avatar, Button, Dialog, FormControl, Heading, Label, Select, Text, TextInput, ToggleSwitch, UnderlineNav } from "@primer/react"
import { KeybindingHint, Table } from "@primer/react/experimental"
import { iconFor } from "@/lib/icon"
import { avatarSrc } from "@/lib/avatar"
import { PageHeader } from "./shared"

export function SettingsPage() {
  const [tab, setTab] = useState("profile")
  const tabs = [["profile", "个人资料"], ["security", "安全"], ["notifications", "通知"], ["team", "团队"], ["billing", "账单"]]
  return (
    <div className="page-stack">
      <PageHeader title="设置" description="管理你的账户、团队与订阅设置。" />
      <div className="grid settings-layout" style={{ gridTemplateColumns: "180px minmax(0, 1fr)", gap: 24 }}>
        <UnderlineNav aria-label="设置分类" variant="flush">{tabs.map(([value, label]) => <UnderlineNav.Item key={value} aria-current={tab === value ? "page" : undefined} onSelect={() => setTab(value)}>{label}</UnderlineNav.Item>)}</UnderlineNav>
        <div className="min-width-0">
          {tab === "profile" ? <section className="card stack-4"><Heading as="h2">个人资料</Heading><Text className="muted">更新你的公开账户信息。</Text><div className="flex items-center gap-3"><Avatar src={avatarSrc} alt="林晓" size={64} /><div><Text>林晓</Text><Text as="p" className="muted">admin@acme.dev</Text></div><Button style={{ marginLeft: "auto" }}>更换头像</Button></div><div className="grid grid-2"><FormControl><FormControl.Label>姓名</FormControl.Label><TextInput defaultValue="林晓" block /></FormControl><FormControl><FormControl.Label>邮箱</FormControl.Label><TextInput defaultValue="admin@acme.dev" block /></FormControl><FormControl><FormControl.Label>时区</FormControl.Label><Select defaultValue="china" block><Select.Option value="china">中国时区</Select.Option><Select.Option value="utc">UTC</Select.Option></Select></FormControl><FormControl><FormControl.Label>职位</FormControl.Label><TextInput defaultValue="产品负责人" block /></FormControl></div><Button variant="primary">保存更改</Button></section> : null}
          {tab === "security" ? <div className="page-stack"><section className="card stack-4"><Heading as="h2">安全设置</Heading><Text className="muted">保护你的账户与登录会话。</Text><div className="flex items-center justify-between card"><div><Text>双因素认证</Text><Text as="p" className="muted">登录时要求额外的验证码</Text></div><ToggleSwitch defaultChecked aria-labelledby="two-factor-label" /><span id="two-factor-label" hidden>双因素认证</span></div><div className="card muted" style={{ textAlign: "center" }}>二维码占位 · 使用身份验证器扫描</div><Dialog title="修改密码" subtitle="设置一个新的账户密码。" footerButtons={[{ content: "保存", buttonType: "primary" }]} onClose={() => {}}><div className="stack-3"><TextInput type="password" placeholder="当前密码" block /><TextInput type="password" placeholder="新密码" block /></div></Dialog></section><section className="card stack-4"><Heading as="h2">登录会话</Heading><div className="table-scroll"><Table gridTemplateColumns="minmax(120px, 1fr) minmax(120px, 1fr) auto"><Table.Head><Table.Row><Table.Header>设备</Table.Header><Table.Header>位置</Table.Header><Table.Header>状态</Table.Header></Table.Row></Table.Head><Table.Body>{sessions.map((session) => <Table.Row key={session.device}><Table.Cell>{session.device}</Table.Cell><Table.Cell>{session.location}</Table.Cell><Table.Cell><Label variant={session.current ? "success" : "secondary"}>{session.current ? "当前会话" : "已登录"}</Label></Table.Cell></Table.Row>)}</Table.Body></Table></div></section></div> : null}
          {tab === "notifications" ? <section className="card stack-4"><Heading as="h2">通知偏好</Heading><Text className="muted">选择你希望接收的通知。</Text>{["项目更新", "账单提醒", "团队活动", "产品新闻"].map((label, index) => <div className="flex items-center justify-between" key={label}><div><Text>{label}</Text><Text as="p" className="muted">通过邮件接收重要提醒</Text></div><ToggleSwitch defaultChecked={index < 3} aria-labelledby={`notification-${index}`} /><span id={`notification-${index}`} hidden>{label}</span></div>)}</section> : null}
          {tab === "team" ? <section className="card stack-4"><Heading as="h2">团队成员</Heading><Text className="muted">管理团队访问权限。</Text><div className="table-scroll"><Table gridTemplateColumns="minmax(160px, 1fr) minmax(120px, 1fr) minmax(120px, 1fr) auto"><Table.Head><Table.Row><Table.Header>成员</Table.Header><Table.Header>角色</Table.Header><Table.Header>最近活跃</Table.Header><Table.Header align="end">操作</Table.Header></Table.Row></Table.Head><Table.Body>{team.map((member) => <Table.Row key={member.email}><Table.Cell><div className="flex items-center gap-2"><Avatar src={avatarSrc} alt={member.name} size={32} />{member.name}</div></Table.Cell><Table.Cell><Label>{member.role}</Label></Table.Cell><Table.Cell>{member.lastActive}</Table.Cell><Table.Cell align="end"><Button variant="invisible" aria-label={`编辑 ${member.name}`} leadingVisual={iconFor("edit")} /></Table.Cell></Table.Row>)}</Table.Body></Table></div><Button variant="primary" leadingVisual={iconFor("plus")}>邀请成员</Button></section> : null}
          {tab === "billing" ? <div className="page-stack"><section className="card stack-4"><Heading as="h2">订阅方案</Heading><Text className="muted">当前与可用方案。</Text><div className="grid grid-3">{plans.map((plan) => <div className="card" key={plan.name}><div className="flex justify-between"><Text>{plan.name}</Text>{plan.recommended ? <Label variant="accent">推荐</Label> : null}</div><Heading as="h3">{plan.price === null ? "定制" : plan.price === 0 ? "免费" : `¥${plan.price}`}</Heading><Text className="muted">{plan.features.join(" · ")}</Text></div>)}</div></section><section className="card stack-4"><Heading as="h2">发票记录</Heading><div className="table-scroll"><Table gridTemplateColumns="minmax(120px, 1fr) minmax(120px, 1fr) auto"><Table.Head><Table.Row><Table.Header>编号</Table.Header><Table.Header>日期</Table.Header><Table.Header>金额</Table.Header></Table.Row></Table.Head><Table.Body>{invoices.map((invoice) => <Table.Row key={invoice.id}><Table.Cell>{invoice.id}</Table.Cell><Table.Cell>{invoice.date}</Table.Cell><Table.Cell>¥{invoice.amount}</Table.Cell></Table.Row>)}</Table.Body></Table></div></section><div className="flex items-center justify-between card"><Text>快捷键帮助</Text><KeybindingHint keys="Meta K" /></div><Button variant="danger">删除账户</Button></div> : null}
        </div>
      </div>
    </div>
  )
}
