import { useState } from "react"
import { Link, useNavigate } from "react-router-dom"
import { Avatar, Button, Card, Carousel, Collapse, Drawer, Grid, Menu, Select, Space, Tag, Typography } from "@arco-design/web-react"
import landing from "@ui-gallery/spec/mock/landing.json"
import plans from "@ui-gallery/spec/mock/plans.json"
import { Icon } from "@/components/icon"

export function LandingPage() {
  const navigate = useNavigate()
  const [menuOpen, setMenuOpen] = useState(false)
  return <div className="landing-page">
    <header className="landing-nav"><Link className="brand" to="/"><span className="brand-mark">A</span>Acme Console</Link><nav className="desktop-only"><Space><a href="#features">产品</a><a href="#pricing">价格</a><a href="#faq">FAQ</a><Link to="/login">登录</Link></Space></nav><Button type="primary" size="small" className="desktop-only" onClick={() => navigate("/login")}>免费开始</Button><Button className="mobile-only hit-area" size="large" type="text" icon={<Icon name="menu" />} aria-label="打开菜单" onClick={() => setMenuOpen(true)} /></header>
    <Drawer placement="right" width={280} visible={menuOpen} onCancel={() => setMenuOpen(false)} footer={null} title="菜单"><Menu mode="vertical" onClickMenuItem={() => setMenuOpen(false)}><Menu.Item key="features"><a href="#features">产品</a></Menu.Item><Menu.Item key="pricing"><a href="#pricing">价格</a></Menu.Item><Menu.Item key="faq"><a href="#faq">FAQ</a></Menu.Item><Menu.Item key="login"><Link to="/login">登录</Link></Menu.Item></Menu><Button type="primary" long onClick={() => navigate("/login")}>免费开始</Button></Drawer>
    <main>
      <section className="landing-hero"><div><Tag color="arcoblue">ACME CONSOLE · 2026</Tag><Typography.Title heading={1}>{landing.hero.title}</Typography.Title><Typography.Paragraph>{landing.hero.subtitle}</Typography.Paragraph><Space wrap><Button type="primary" size="large" onClick={() => navigate("/login")}>{landing.hero.primary} <Icon name="arrow-right" /></Button><Button size="large">{landing.hero.secondary}</Button></Space><div className="row"><div className="avatar-stack">{["林", "王", "A", "M"].map((name) => <Avatar key={name}>{name}</Avatar>)}</div><Typography.Text type="secondary">{landing.hero.social}</Typography.Text></div></div><Card className="hero-preview"><div className="aspect-box"><Icon name="layout-dashboard" size={52} /></div></Card></section>
      <section className="logo-cloud">{["Northwind", "Contoso", "Globex", "Fabrikam", "Initech", "Umbrella"].map((name) => <Typography.Text type="secondary" key={name}>{name}</Typography.Text>)}</section>
      <section id="features" className="landing-section"><Typography.Title heading={2}>一个地方，完成所有工作</Typography.Title><Typography.Paragraph type="secondary">从数据到决策，让每一步都更清晰。</Typography.Paragraph><Grid.Row gutter={[16, 16]}>{landing.features.map((item) => <Grid.Col xs={24} sm={12} md={8} key={item.title}><Card hoverable><div className="feature-icon"><Icon name={item.icon} /></div><Typography.Title heading={4}>{item.title}</Typography.Title><Typography.Text type="secondary">{item.desc}</Typography.Text></Card></Grid.Col>)}</Grid.Row></section>
      <section className="landing-section split-sections">{["看见全局", "自动化协作", "AI 就在身边"].map((title, index) => <Grid.Row gutter={32} align="center" key={title}><Grid.Col xs={24} md={12} order={index % 2 ? 2 : 1}><Tag>0{index + 1} / WORKSPACE</Tag><Typography.Title heading={2}>{title}</Typography.Title><Typography.Paragraph type="secondary">把分散的信息汇聚为有用的洞察，让团队快速行动并持续交付。</Typography.Paragraph><Button type="text">了解更多 <Icon name="arrow-right" /></Button></Grid.Col><Grid.Col xs={24} md={12} order={index % 2 ? 1 : 2}><Card><div className="aspect-box"><Icon name={landing.features[index + 1].icon} size={48} /></div></Card></Grid.Col></Grid.Row>)}</section>
      <section className="numbers">{landing.numbers.map((item) => <div key={item.label}><Typography.Title heading={2}>{item.value}</Typography.Title><Typography.Text type="secondary">{item.label}</Typography.Text></div>)}</section>
      <section id="pricing" className="landing-section"><Typography.Title heading={2}>选择适合你的方案</Typography.Title><Typography.Paragraph type="secondary">简单透明，随时升级。</Typography.Paragraph><Grid.Row gutter={16}>{plans.map((plan) => <Grid.Col xs={24} md={8} key={plan.name}><Card title={<div className="between"><span>{plan.name}</span>{plan.recommended ? <Tag color="arcoblue">最受欢迎</Tag> : null}</div>} className={plan.recommended ? "recommended" : ""}><Typography.Title heading={2}>{plan.price === null ? "定制" : plan.price === 0 ? "免费" : `¥${plan.price}`}</Typography.Title><Typography.Paragraph type="secondary">{plan.features.join(" · ")}</Typography.Paragraph><Button long type={plan.recommended ? "primary" : "secondary"}>开始使用</Button></Card></Grid.Col>)}</Grid.Row></section>
      <section className="landing-section"><Typography.Title heading={2}>他们已经在改变工作方式</Typography.Title><Carousel autoPlay indicatorType="dot"><div className="carousel-card">{landing.testimonials.map((item) => <Card key={item.name}><Typography.Paragraph>“{item.quote}”</Typography.Paragraph><div className="row"><Avatar>{item.name.slice(0, 1)}</Avatar><Typography.Text>{item.name} · {item.company}</Typography.Text></div></Card>)}</div></Carousel></section>
      <section id="faq" className="landing-section faq"><Typography.Title heading={2}>常见问题</Typography.Title><Collapse accordion>{landing.faq.map((item) => <Collapse.Item key={item.q} name={item.q} header={item.q}>{item.a}</Collapse.Item>)}</Collapse></section>
      <section className="landing-cta"><Typography.Title heading={2}>准备好让团队更高效了吗？</Typography.Title><Typography.Paragraph>从今天开始，把工作放进一个控制台。</Typography.Paragraph><Button type="primary" size="large" onClick={() => navigate("/login")}>免费开始 <Icon name="arrow-right" /></Button></section>
    </main>
    <footer className="landing-footer"><Typography.Text>© 2026 Acme Console</Typography.Text><Space><a href="#features">产品</a><a href="#pricing">价格</a><a href="#faq">帮助中心</a><Select defaultValue="zh" options={[{ label: "中文", value: "zh" }, { label: "English", value: "en" }]} /></Space></footer>
  </div>
}
