/* eslint-disable */
import { createSignal, For } from "solid-js"
import { DemoCard, DemoFrame, DemoLabel, IconButton, MiniTable } from "./shared"
import { Icon } from "@/icons"
import { Avatar } from "@/ui/avatar"
import { Badge } from "@/ui/badge"
import { Button } from "@/ui/button"
import { Card, CardContent } from "@/ui/card"
import { Image } from "@kobalte/core/image"
import { Dialog } from "@/ui/dialog"
import { Popover } from "@/ui/popover"
import { Accordion } from "@/ui/accordion"

const placeholderSvg = `data:image/svg+xml;utf8,${encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 224 128"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#bae6fd"/><stop offset="1" stop-color="#a5b4fc"/></linearGradient></defs><rect width="224" height="128" fill="url(#g)"/><circle cx="176" cy="34" r="16" fill="#fcd34d"/><path d="M0 128 L64 60 L104 100 L140 72 L224 128 Z" fill="#10b981" fill-opacity=".85"/><path d="M0 128 L40 96 L88 128 Z" fill="#047857" fill-opacity=".85"/></svg>')}`

function PlaceholderImage(props: { class?: string }) {
  return <Image fallbackDelay={300} class={`block overflow-hidden ${props.class ?? ""}`}><Image.Img src={placeholderSvg} alt="示意图占位" class="size-full object-cover" /><Image.Fallback class="grid size-full place-items-center bg-zinc-200 text-xs text-zinc-500 dark:bg-zinc-800">图片加载中</Image.Fallback></Image>
}

export function DataDisplayDemo(props: { name: string; status: string }) {
  const [preview, setPreview] = createSignal(false)
  const [selected, setSelected] = createSignal("全部")
  if (props.name === "Table") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="space-y-4"><MiniTable striped /><MiniTable rows={[["A", "边框表格", "¥1,200"], ["B", "紧凑行", "¥880"]]} /></div></DemoFrame></DemoCard>
  if (props.name === "DataGrid") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="max-h-48 overflow-auto"><table class="min-w-[620px] w-full text-left text-sm"><thead class="sticky top-0 bg-zinc-100 dark:bg-zinc-800"><tr><th class="p-2">选择</th><th class="p-2">订单号 ↕</th><th class="p-2">客户</th><th class="p-2">状态</th><th class="p-2">金额</th></tr></thead><tbody>{["ORD-1001","ORD-1002","ORD-1003","ORD-1004"].map((id) => <tr class="border-t dark:border-zinc-800"><td class="p-2"><input type="checkbox" /></td><td class="p-2">{id}</td><td class="p-2">林晓</td><td class="p-2"><Badge>已支付</Badge></td><td class="p-2">¥2,480</td></tr>)}</tbody></table></div></DemoFrame></DemoCard>
  if (props.name === "Descriptions") return <DemoCard name={props.name} status={props.status}><DemoFrame><dl class="grid grid-cols-2 overflow-hidden rounded border border-zinc-200 text-sm dark:border-zinc-700"><For each={[["订单号","ORD-2420"],["客户","刘欣怡"],["状态","paid"],["金额","¥4,880.99"]]}>{(item) => <><dt class="border-b border-r bg-zinc-50 p-3 font-medium dark:border-zinc-700 dark:bg-zinc-800">{item[0]}</dt><dd class="border-b p-3 dark:border-zinc-700">{item[1]}</dd></>}</For></dl></DemoFrame></DemoCard>
  if (props.name === "List") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="divide-y rounded border dark:divide-zinc-800 dark:border-zinc-700">{["林晓","王子涵","Alex Chen"].map((name) => <div class="flex items-center gap-3 p-3"><Avatar name={name} /><span class="flex-1">{name}</span><Button size="sm" variant="ghost">查看</Button></div>)}</div></DemoFrame></DemoCard>
  if (props.name === "Card") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="grid gap-3 sm:grid-cols-3"><Card><div class="h-16 bg-gradient-to-r from-blue-500 to-indigo-500" /><CardContent><p class="font-medium">Basic card</p></CardContent></Card><Card><CardContent><p class="font-medium">Horizontal card</p><p class="text-sm text-zinc-500 dark:text-zinc-400">带 footer</p><Button size="sm" class="mt-2">操作</Button></CardContent></Card><Card><div class="h-16 bg-zinc-200 dark:bg-zinc-800" /><CardContent><p class="font-medium">Image header</p></CardContent></Card></div></DemoFrame></DemoCard>
  if (props.name === "Avatar") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="grid gap-3"><div class="flex items-end gap-4"><DemoLabel>sizes</DemoLabel><For each={["xs","sm","md","lg","xl"]}>{(size) => <div class="text-center"><Avatar name="林晓" size={size === "xl" || size === "lg" ? "lg" : size === "xs" || size === "sm" ? "sm" : "md"} /><p class="mt-1 text-xs">{size}</p></div>}</For></div><div class="flex items-center gap-3"><DemoLabel>status</DemoLabel><span class="relative"><Avatar name="林晓" /><span class="absolute bottom-0 right-0 size-3 rounded-full bg-emerald-500 ring-2 ring-white dark:ring-zinc-950" /></span></div><div class="flex items-center gap-3"><DemoLabel>square</DemoLabel><Avatar name="AC" size="lg" class="rounded-lg" /></div></div></DemoFrame></DemoCard>
  if (props.name === "AvatarGroup") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="grid gap-3"><DemoLabel>overlap · max 3</DemoLabel><div class="flex items-center"><Avatar name="A" size="sm" /><Avatar name="王" size="sm" class="-ml-3" /><Avatar name="M" size="sm" class="-ml-3" /><span class="-ml-2 grid size-6 place-items-center rounded-full border-2 border-white bg-zinc-200 text-[10px] dark:border-zinc-900 dark:bg-zinc-700">+3</span></div><div class="flex items-center"><Avatar name="A" /><Avatar name="王" class="-ml-3" /><Avatar name="M" class="-ml-3" /><span class="-ml-2 grid size-8 place-items-center rounded-full border-2 border-white bg-zinc-200 text-xs dark:border-zinc-900 dark:bg-zinc-700">+3</span></div></div></DemoFrame></DemoCard>
  if (props.name === "Badge") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="flex flex-wrap items-center gap-3"><Badge>默认</Badge><Badge variant="secondary">次要</Badge><Badge variant="outline">描边</Badge><Badge variant="destructive">危险</Badge><Badge><span class="mr-1 size-1.5 rounded-full bg-emerald-300" />在线</Badge><Badge>99+</Badge><span class="relative inline-flex"><Button variant="outline" size="icon" aria-label="通知"><Icon name="bell" /></Button><Badge variant="destructive" class="absolute -right-1 -top-1 px-1.5 py-0">3</Badge></span></div></DemoFrame></DemoCard>
  if (props.name === "Tag") { const [selectedTags, setSelectedTags] = createSignal<string[]>(["蓝色"]); const tags = [{ label: "蓝色", class: "bg-blue-100 text-blue-700 dark:bg-blue-900 dark:text-blue-100" }, { label: "绿色", class: "bg-emerald-100 text-emerald-700 dark:bg-emerald-900 dark:text-emerald-100" }, { label: "黄色", class: "bg-amber-100 text-amber-700 dark:bg-amber-900 dark:text-amber-100" }]; return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="grid gap-3"><div class="flex flex-wrap gap-2">{tags.map((tag) => <span class={`inline-flex items-center rounded-full px-3 py-1 text-xs ${tag.class}`}>{tag.label}<button aria-label="移除" class="ml-1 inline-grid size-5 place-items-center rounded-full hover:bg-blue-200">×</button></span>)}<button class="rounded-full border border-dashed px-3 py-1 text-xs">+ 添加标签</button></div><div class="flex flex-wrap gap-2">{tags.map((tag) => <button aria-pressed={selectedTags().includes(tag.label)} class={`rounded-full px-3 py-1 text-xs ${tag.class} ${selectedTags().includes(tag.label) ? "ring-2 ring-current ring-offset-1" : ""}`} onClick={() => setSelectedTags((items) => items.includes(tag.label) ? items.filter((item) => item !== tag.label) : [...items, tag.label])}>{tag.label}</button>)}</div></div></DemoFrame></DemoCard> }
  if (props.name === "Statistic") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="grid gap-3 sm:grid-cols-4">{[["收入","¥128,430","↑ 12.4%"],["订单","1,024","↑ 8.2%"],["退款率","2.4%","↓ 0.8%"],["活跃用户","8,492","↑ 3.1%"]].map((item) => <div class="rounded border p-3"><p class="text-sm text-zinc-500 dark:text-zinc-400">{item[0]}</p><p class="mt-1 text-xl font-semibold">{item[1]}</p><p class={`text-xs ${item[2].startsWith("↓") ? "text-red-600" : "text-emerald-600"}`}>{item[2]}</p></div>)}</div></DemoFrame></DemoCard>
  if (props.name === "Timeline") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="space-y-4 border-l-2 border-blue-200 pl-5 dark:border-blue-900">{["订单 ORD-2420 已支付","林晓更新了项目","报表导出完成"].map((item, index) => <div class="relative"><span class="absolute -left-[1.65rem] top-1 size-3 rounded-full border-2 border-blue-600 bg-white dark:bg-zinc-900" /><p class="font-medium">{item}</p><p class="text-xs text-zinc-500 dark:text-zinc-400">{index + 1} 小时前</p></div>)}</div></DemoFrame></DemoCard>
  if (props.name === "Tree") return <DemoCard name={props.name} status={props.status}><DemoFrame><Accordion multiple defaultValue={["console","workspace"]}><Accordion.Item value="console"><Accordion.Trigger class="flex w-full items-center gap-2 py-2 text-left text-sm [&[data-expanded]>svg:first-child]:rotate-90"><Icon name="chevron-right" size={14} class="transition-transform" /><Icon name="folder" size={16} />Acme Console</Accordion.Trigger><Accordion.Content><Accordion multiple defaultValue={["workspace"]} class="ml-4 border-l pl-2 dark:border-zinc-700"><Accordion.Item value="workspace"><Accordion.Trigger class="flex w-full items-center gap-2 py-2 text-left text-sm [&[data-expanded]>svg:first-child]:rotate-90"><Icon name="chevron-right" size={14} class="transition-transform" />工作区</Accordion.Trigger><Accordion.Content class="pl-5 text-sm"><div class="flex items-center gap-2 py-1"><Icon name="file" size={14} />仪表盘</div><div class="flex items-center gap-2 py-1"><Icon name="file" size={14} />订单</div><div class="flex items-center gap-2 py-1"><Icon name="file" size={14} />设置</div></Accordion.Content></Accordion.Item><Accordion.Item value="team"><Accordion.Trigger class="flex w-full items-center gap-2 py-2 text-left text-sm [&[data-expanded]>svg:first-child]:rotate-90"><Icon name="chevron-right" size={14} class="transition-transform" />团队</Accordion.Trigger><Accordion.Content class="pl-5 text-sm">成员 · 权限</Accordion.Content></Accordion.Item></Accordion></Accordion.Content></Accordion.Item></Accordion></DemoFrame></DemoCard>
  if (props.name === "Calendar") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="max-w-sm"><div class="mb-2 flex items-center justify-between font-medium"><button>‹</button><span>2026 年 9 月</span><button>›</button></div><div class="grid grid-cols-7 gap-1 text-center text-xs">{["一","二","三","四","五","六","日"].map((d) => <span class="p-1 text-zinc-500 dark:text-zinc-400">{d}</span>)}{Array.from({length:30},(_,i)=><button class={`rounded p-1 ${i===14?"bg-blue-600 text-white":"hover:bg-zinc-200 dark:hover:bg-zinc-800"}`}>{i+1}</button>)}</div></div></DemoFrame></DemoCard>
  if (props.name === "Image") return <DemoCard name={props.name} status={props.status}><DemoFrame><button onClick={() => setPreview(true)} class="overflow-hidden rounded-lg border"><PlaceholderImage class="h-32 w-56" /></button><Dialog.Root open={preview()} onOpenChange={setPreview}><Dialog.Portal><Dialog.Overlay class="fixed inset-0 z-50 bg-black/60" /><Dialog.Content class="fixed left-1/2 top-1/2 z-50 -translate-x-1/2 -translate-y-1/2 rounded bg-white p-2 dark:bg-zinc-900"><Dialog.Title class="sr-only">图片预览</Dialog.Title><Dialog.Description class="sr-only">放大的图片</Dialog.Description><PlaceholderImage class="h-[60vh] w-[80vw] max-w-3xl" /></Dialog.Content></Dialog.Portal></Dialog.Root></DemoFrame></DemoCard>
  if (props.name === "Carousel") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="flex gap-2 overflow-x-auto snap-x snap-mandatory">{["from-blue-500 to-indigo-600","from-emerald-500 to-teal-600","from-amber-400 to-orange-600"].map((gradient, index) => <div class={`grid h-28 min-w-[80%] snap-center place-items-center rounded-lg bg-gradient-to-br ${gradient} text-xl font-bold text-white`}>Slide {index + 1}</div>)}</div><div class="mt-2 flex justify-center gap-1">{[1,2,3].map((item) => <button aria-label={`幻灯片 ${item}`} class={`size-2 rounded-full ${item===1?"bg-blue-600":"bg-zinc-300"}`} />)}</div></DemoFrame></DemoCard>
  if (props.name === "Empty") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="grid place-items-center gap-2 py-5 text-center"><Icon name="inbox" size={32} class="text-zinc-400" /><p class="font-medium">暂无数据</p><p class="text-sm text-zinc-500 dark:text-zinc-400">创建第一条记录开始工作</p><Button size="sm">新建</Button></div></DemoFrame></DemoCard>
  if (props.name === "Tooltip") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="flex flex-wrap gap-3"><Button title="顶部提示">Top</Button><Button variant="outline" title="右侧提示">Right</Button><Button variant="ghost" title="底部提示">Bottom</Button><Button variant="outline" title="左侧提示">Left</Button></div></DemoFrame></DemoCard>
  if (props.name === "Popover") return <DemoCard name={props.name} status={props.status}><DemoFrame><Popover.Root><Popover.Trigger as={Button}>打开 Popover</Popover.Trigger><Popover.Portal><Popover.Content class="z-50 w-64 rounded-lg border bg-white p-4 shadow-lg dark:border-zinc-700 dark:bg-zinc-900"><Popover.Arrow /><p class="font-medium">帮助中心</p><p class="mt-1 text-sm text-zinc-500 dark:text-zinc-400">标题、描述、关闭和箭头。</p><Popover.CloseButton class="mt-3 text-sm text-blue-600">关闭</Popover.CloseButton></Popover.Content></Popover.Portal></Popover.Root></DemoFrame></DemoCard>
  if (props.name === "Segmented") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="space-y-3"><For each={["sm","md"]}>{(size) => <div class="flex items-center gap-3"><DemoLabel>{size}</DemoLabel><div class="flex rounded-md border p-1">{["日","周","月"].map((item) => <button class={`rounded px-3 py-1 text-sm ${selected()===item && size==="md" ? "bg-zinc-900 text-white" : ""}`} onClick={() => setSelected(item)}>{item}</button>)}</div></div>}</For><Button disabled>禁用状态</Button></div></DemoFrame></DemoCard>
  return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="flex flex-wrap items-center gap-2"><IconButton name="eye" label="查看" /><IconButton name="download" label="下载" variant="ghost" /><span class="text-sm text-zinc-500 dark:text-zinc-400">包含基础、密集和交互状态演示。</span></div></DemoFrame></DemoCard>
}
