/* eslint-disable */
import { createSignal, For } from "solid-js"
import { DemoCard, DemoFrame, DemoLabel } from "./shared"
import { Alert } from "@/ui/alert"
import { Badge } from "@/ui/badge"
import { Button } from "@/ui/button"
import { Dialog } from "@/ui/dialog"
import { Drawer } from "@/ui/dialog"
import { Popover } from "@/ui/popover"
import { Progress } from "@/ui/progress"
import { Skeleton } from "@/ui/skeleton"
import { toast } from "@/ui/toast"
import { Icon } from "@/icons"

export function FeedbackDemo(props: { name: string; status: string }) {
  const [dialog, setDialog] = createSignal(false)
  const [drawer, setDrawer] = createSignal<string | null>(null)
  if (props.name === "Alert") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="grid gap-2"><Alert level="info"><Icon name="info" />信息提示 <Button size="sm" variant="outline">了解</Button></Alert><Alert level="success"><Icon name="circle-check" />操作成功</Alert><Alert level="warning"><Icon name="alert-triangle" />需要注意</Alert><Alert level="error"><Icon name="circle-x" />操作失败 <button class="ml-auto">×</button></Alert></div></DemoFrame></DemoCard>
  if (props.name === "Toast" || props.name === "Notification") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="flex flex-wrap gap-2"><Button onClick={() => toast.info("通知标题", "这里是描述信息")}>Info</Button><Button onClick={() => toast.success("保存成功")}>Success</Button><Button onClick={() => toast.warning("请注意")}>Warning</Button><Button variant="destructive" onClick={() => toast.error("发生错误")}>Error</Button><Button variant="outline" onClick={() => toast.success("带操作的通知", "可以撤销",)}>带 action</Button><Badge>标题 + 描述 + 关闭</Badge></div></DemoFrame></DemoCard>
  if (props.name === "Dialog") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="flex flex-wrap gap-2"><Button onClick={() => setDialog(true)}>普通 Dialog</Button><Button variant="outline" onClick={() => setDialog(true)}>AlertDialog confirm</Button><Button variant="ghost" onClick={() => setDialog(true)}>全屏 / 滚动内容</Button></div><Dialog.Root open={dialog()} onOpenChange={setDialog}><Dialog.Portal><Dialog.Overlay class="fixed inset-0 z-50 bg-black/40" /><Dialog.Content class="fixed left-1/2 top-1/2 z-50 max-h-[80vh] w-[calc(100%-2rem)] max-w-lg -translate-x-1/2 -translate-y-1/2 overflow-auto rounded-lg border bg-white p-6 shadow-xl dark:border-zinc-700 dark:bg-zinc-900"><Dialog.Title class="text-lg font-semibold">确认操作</Dialog.Title><Dialog.Description class="mt-2 text-sm text-zinc-500 dark:text-zinc-400">这是一个包含标题、描述、操作和长内容的 Dialog。</Dialog.Description><div class="my-4 space-y-2 text-sm">{Array.from({length:5}, (_,i)=><p>滚动内容 {i+1}：请确认当前操作及其影响。</p>)}</div><div class="flex justify-end gap-2"><Dialog.CloseButton class="rounded border px-3 py-2 text-sm">取消</Dialog.CloseButton><Button onClick={() => { setDialog(false); toast.success("已确认") }}>确认</Button></div></Dialog.Content></Dialog.Portal></Dialog.Root></DemoFrame></DemoCard>
  if (props.name === "Drawer") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="flex flex-wrap gap-2">{["左侧","右侧","顶部","底部"].map((side) => <Button variant="outline" onClick={() => setDrawer(side)}>{side} Drawer</Button>)}</div><Drawer open={drawer() !== null} onOpenChange={(open) => !open && setDrawer(null)} title={`${drawer() ?? ""} Drawer`} description="Dialog anchored to a side"><p class="text-sm text-zinc-500 dark:text-zinc-400">抽屉内容区域。</p></Drawer></DemoFrame></DemoCard>
  if (props.name === "Progress") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="grid gap-4 sm:grid-cols-2"><Progress value={25} label="开始" /><Progress value={68} label="处理中" /><Progress value={100} label="完成" /><div><DemoLabel>Meter / ring / steps</DemoLabel><div class="mt-2 h-2 rounded bg-zinc-200 dark:bg-zinc-700"><div class="h-2 w-2/3 rounded bg-blue-600" /></div><div class="mt-3 flex items-center gap-2"><svg viewBox="0 0 36 36" class="size-12 -rotate-90"><circle cx="18" cy="18" r="15" fill="none" stroke="currentColor" stroke-width="3" class="text-zinc-200 dark:text-zinc-700" /><circle cx="18" cy="18" r="15" fill="none" stroke="currentColor" stroke-width="3" stroke-dasharray="70 100" class="text-blue-600" /></svg><span>70%</span><span class="text-xs text-zinc-500">indeterminate · Meter · steps</span></div></div></div></DemoFrame></DemoCard>
  if (props.name === "Skeleton") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="flex items-center gap-3 rounded border p-4"><Skeleton class="size-10 rounded-full" /><div class="flex-1 space-y-2"><Skeleton class="h-3 w-2/3" /><Skeleton class="h-3 w-full" /><Skeleton class="h-3 w-1/2" /></div></div></DemoFrame></DemoCard>
  if (props.name === "Spinner") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="flex items-center gap-5"><For each={["size-4","size-6","size-10"]}>{(size) => <span class={`${size} animate-spin rounded-full border-2 border-zinc-300 border-t-blue-600`} />}</For></div></DemoFrame></DemoCard>
  if (props.name === "Result") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="grid gap-3 sm:grid-cols-3">{[["success","完成","返回首页"],["error","失败","重试"],["404","页面不存在","返回"]].map((item) => <div class="rounded border p-4 text-center"><Icon name={item[0]==="success"?"circle-check":item[0]==="error"?"circle-x":"search"} class="mx-auto" /><p class="mt-2 font-medium">{item[1]}</p><Button size="sm" class="mt-2" variant="outline">{item[2]}</Button></div>)}</div></DemoFrame></DemoCard>
  if (props.name === "Popconfirm") return <DemoCard name={props.name} status={props.status}><DemoFrame><Popover.Root><Popover.Trigger as={Button} variant="destructive">删除项目</Popover.Trigger><Popover.Portal><Popover.Content class="z-50 w-56 rounded border bg-white p-3 shadow-lg dark:border-zinc-700 dark:bg-zinc-900"><p class="font-medium">确认删除？</p><p class="mt-1 text-xs text-zinc-500 dark:text-zinc-400">此操作无法撤销。</p><div class="mt-3 flex justify-end gap-2"><Popover.CloseButton class="rounded border px-2 py-1 text-xs">取消</Popover.CloseButton><Button size="sm" onClick={() => toast.success("已删除")}>确认</Button></div></Popover.Content></Popover.Portal></Popover.Root></DemoFrame></DemoCard>
  return <DemoCard name={props.name} status={props.status}><DemoFrame><Button onClick={() => toast.info(props.name, "交互反馈已触发")}>触发 {props.name}</Button></DemoFrame></DemoCard>
}
