/* eslint-disable */
import { createSignal, Show } from "solid-js"
import { DemoCard, DemoFrame, DemoLabel, IconButton } from "./shared"
import { Icon } from "@/icons"
import { Button } from "@/ui/button"
import { Checkbox } from "@/ui/checkbox"
import { Combobox } from "@/ui/combobox"
import { Select } from "@/ui/select"
import { Slider } from "@kobalte/core/slider"
import { RadioGroup } from "@/ui/radio-group"
import { TextArea, TextField } from "@/ui/text-field"
import { toast } from "@/ui/toast"

const options = [{ value: "a", label: "选项 A" }, { value: "b", label: "选项 B" }, { value: "c", label: "选项 C" }]

export function FormsDemo(props: { name: string; status: string }) {
  const [slider, setSlider] = createSignal(42)
  const [range, setRange] = createSignal([20, 70])
  if (props.name === "Mention") return <DemoCard name={props.name} status="missing"><DemoFrame><p class="text-sm text-zinc-500">Kobalte 无此原语，未实现；可用 Combobox 实现 @ 提及体验。</p></DemoFrame></DemoCard>
  if (props.name === "PinInput") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="flex gap-2">{Array.from({ length: 6 }, (_, index) => <TextField label={`验证码 ${index + 1}`} class="w-10" />)}</div></DemoFrame></DemoCard>
  if (props.name === "Form") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="grid gap-4 md:grid-cols-3"><div class="space-y-2"><DemoLabel>Horizontal</DemoLabel><TextField label="姓名" value="林晓" /><Button size="sm">保存</Button></div><div class="space-y-2"><DemoLabel>Vertical</DemoLabel><TextField label="邮箱" placeholder="name@example.com" /><Button size="sm">提交</Button></div><div class="flex items-end gap-2"><div class="flex-1"><DemoLabel>Inline</DemoLabel><TextField label="邀请码" /></div><Button size="sm">验证</Button></div></div></DemoFrame></DemoCard>
  if (props.name === "Upload") return <DemoCard name={props.name} status={props.status}><DemoFrame><label class="grid min-h-28 cursor-pointer place-items-center rounded-lg border-2 border-dashed border-zinc-300 text-center text-sm hover:border-blue-500 dark:border-zinc-700"><input type="file" class="sr-only" /><span><Icon name="upload" class="mx-auto mb-2" />拖拽文件到这里，或点击上传</span></label><p class="mt-3 text-xs text-zinc-500">report.csv · 24 KB <button class="ml-2 text-red-600">移除</button></p></DemoFrame></DemoCard>
  if (props.name === "Transfer") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="flex items-center gap-3"><select multiple class="h-28 min-w-32 rounded border bg-white p-2 text-sm dark:bg-zinc-900"><option>订单</option><option>客户</option><option>发票</option></select><div class="grid gap-1"><Button size="icon" aria-label="移动到右侧">→</Button><Button size="icon" variant="outline" aria-label="移动到左侧">←</Button></div><select multiple class="h-28 min-w-32 rounded border bg-white p-2 text-sm dark:bg-zinc-900"><option>报表</option></select></div></DemoFrame></DemoCard>
  if (props.name === "Cascader") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="flex flex-wrap items-end gap-3"><Select label="省" options={[{ value: "zj", label: "浙江省" }, { value: "gd", label: "广东省" }]} value="zj" /><span class="pb-2">›</span><Select label="市" options={[{ value: "hz", label: "杭州市" }, { value: "sz", label: "深圳市" }]} value="hz" /></div></DemoFrame></DemoCard>
  if (props.name === "ColorPicker") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="flex flex-wrap items-center gap-4"><div class="size-32 rounded border border-zinc-300 bg-[linear-gradient(135deg,#fff,#ef4444),linear-gradient(45deg,transparent,#111)]" /><input aria-label="色相" type="range" class="accent-red-500" /><input aria-label="颜色值" value="#ef4444" class="h-9 w-28 rounded border px-2 font-mono text-sm dark:bg-zinc-900" /><span class="size-8 rounded-full bg-red-500 ring-2 ring-offset-2 ring-red-500" /></div><p class="mt-2 text-xs text-zinc-500">ColorArea · ColorSlider · ColorWheel · ColorField · ColorSwatch</p></DemoFrame></DemoCard>
  if (props.name === "DatePicker" || props.name === "DateRangePicker") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="flex flex-wrap gap-3"><TextField label="开始日期" type="date" value="2026-09-01" /><Show when={props.name === "DateRangePicker"}><TextField label="结束日期" type="date" value="2026-09-30" /></Show><Button variant="outline" onClick={() => toast.info("日历", "当前月份日历已打开")}>日历月视图</Button></div><div class="mt-4 grid max-w-sm grid-cols-7 gap-1 text-center text-xs">{["一","二","三","四","五","六","日"].map((day) => <span class="font-medium text-zinc-500">{day}</span>)}{Array.from({ length: 30 }, (_, i) => <button class={`rounded p-1 ${i === 14 ? "bg-blue-600 text-white" : "hover:bg-zinc-200 dark:hover:bg-zinc-800"}`}>{i + 1}</button>)}</div></DemoFrame></DemoCard>
  if (props.name === "TimePicker") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="flex items-end gap-2"><TextField label="小时" value="09" /><span class="pb-2">:</span><TextField label="分钟" value="30" /><span class="ml-2 rounded border px-2 py-2 text-sm">TimeField segments</span></div></DemoFrame></DemoCard>
  if (props.name === "Rating") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="space-y-3"><div class="flex items-center text-amber-500">{[1,2,3,4,5].map((item) => <button aria-label={`${item} 星`}><Icon name="star" size={24} /></button>)}</div><div class="flex items-center text-amber-500">{[1,2,3].map(() => <Icon name="star" size={20} />)}<span class="ml-2 text-sm text-zinc-500">3.5 / 5 · readonly · disabled</span></div></div></DemoFrame></DemoCard>
  if (props.name === "Slider") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="grid gap-5 sm:grid-cols-2"><Slider value={[slider()]} onChange={(value) => setSlider(value[0] ?? 0)} minValue={0} maxValue={100}><Slider.Label>单值 {slider()}</Slider.Label><Slider.Track class="relative h-2 rounded bg-zinc-200 dark:bg-zinc-700"><Slider.Fill class="absolute h-full rounded bg-blue-600" /><Slider.Thumb class="absolute top-1/2 size-4 -translate-y-1/2 rounded-full border-2 border-blue-600 bg-white" /></Slider.Track></Slider><Slider value={range()} onChange={setRange} minValue={0} maxValue={100}><Slider.Label>范围 {range().join("–")}</Slider.Label><Slider.Track class="relative h-2 rounded bg-zinc-200 dark:bg-zinc-700"><Slider.Fill class="absolute h-full rounded bg-blue-600" /><Slider.Thumb class="absolute top-1/2 size-4 -translate-y-1/2 rounded-full border-2 border-blue-600 bg-white" /></Slider.Track></Slider></div><div class="mt-3 flex gap-2 text-xs text-zinc-500"><span>步进标记</span><span>垂直</span><span>禁用</span></div></DemoFrame></DemoCard>
  if (props.name === "Radio") return <DemoCard name={props.name} status={props.status}><DemoFrame><RadioGroup label="项目类型" options={[{ value: "web", label: "Web" }, { value: "mobile", label: "移动端" }, { value: "internal", label: "内部" }]} value="web" /><p class="mt-2 text-xs text-red-600">invalid 示例：请选择一个项目类型</p></DemoFrame></DemoCard>
  if (props.name === "Checkbox") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="flex flex-wrap gap-4"><Checkbox label="未选中" /><Checkbox label="已选中" checked /><Checkbox label="不确定" indeterminate /><Checkbox label="禁用" disabled /><Checkbox label="错误" class="text-red-600" /></div><div class="mt-3 flex gap-3 text-sm"><Checkbox label="功能模块 A" checked /><Checkbox label="功能模块 B" /></div></DemoFrame></DemoCard>
  if (props.name === "Switch") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="grid gap-3 sm:grid-cols-3"><label class="flex items-center gap-2 text-sm"><input type="checkbox" class="accent-blue-600" checked />小号</label><label class="flex items-center gap-2 text-sm"><input type="checkbox" class="accent-blue-600" />中号</label><label class="flex items-center gap-2 text-sm"><input type="checkbox" class="accent-blue-600" checked />大号</label><label class="flex items-center gap-2 text-sm text-zinc-500"><input type="checkbox" disabled />禁用 · 带描述</label></div></DemoFrame></DemoCard>
  if (props.name === "NumberInput") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="grid gap-3 sm:grid-cols-4"><TextField label="默认" type="number" value="12" /><TextField label="1–100 · 步进 5" type="number" value="25" description="min 1 · max 100 · step 5" /><TextField label="金额" prefix="¥" type="number" value="12,480" /><TextField label="禁用/错误" type="number" disabled error="范围不正确" /></div></DemoFrame></DemoCard>
  if (props.name === "Textarea") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="grid gap-3 sm:grid-cols-3"><TextArea label="默认" rows={3} placeholder="写点内容..." /><TextArea label="带计数" rows={3} maxLength={200} value="已输入的描述" description="12 / 200" /><TextArea label="错误/禁用" rows={3} disabled error="内容不能为空" /></div></DemoFrame></DemoCard>
  if (props.name === "MultiSelect") return <DemoCard name={props.name} status={props.status}><DemoFrame><Select label="渠道（多选）" options={options} value={["a", "b"]} multiple /></DemoFrame></DemoCard>
  if (props.name === "Combobox" || props.name === "Autocomplete") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="grid max-w-md gap-3"><Combobox label={props.name === "Autocomplete" ? "可自定义值" : "过滤城市"} options={[{ value: "hangzhou", label: "杭州" }, { value: "shanghai", label: "上海" }, { value: "shenzhen", label: "深圳" }]} placeholder="输入过滤..." /><p class="text-xs text-zinc-500">输入内容后过滤选项，{props.name === "Autocomplete" ? "允许自定义值" : "仅选择已有值"}。</p></div></DemoFrame></DemoCard>
  return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="grid gap-3 sm:grid-cols-3"><TextField label="默认" placeholder="请输入" prefix={<Icon name="search" size={16} />} /><TextField label="密码" type="password" value="secret" /><TextField label="只读/禁用" value="readonly" disabled description="说明文字" /><TextField label="错误" value="bad" error="请输入有效内容" suffix={<IconButton name="x" label="清除" size="sm" variant="ghost" />} /></div><div class="mt-3 flex flex-wrap gap-2"><Button size="sm">搜索</Button><Button size="sm" variant="outline">3 sizes: sm / md / lg</Button></div></DemoFrame></DemoCard>
}
