/* eslint-disable */
import { For } from "solid-js"
import { DemoCard, DemoFrame, DemoLabel } from "./shared"
import { Accordion } from "@/ui/accordion"
import { Button } from "@/ui/button"
import { Icon } from "@/icons"

export function LayoutDemo(props: { name: string; status: string }) {
  if (props.name === "Grid") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-6">{Array.from({length:12},(_,i)=><div class="grid h-12 place-items-center rounded bg-blue-100 text-xs text-blue-700 dark:bg-blue-950 dark:text-blue-300">{i+1}</div>)}</div></DemoFrame></DemoCard>
  if (props.name === "Stack") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="flex flex-wrap items-end gap-8"><div><DemoLabel>vertical / gap 2</DemoLabel><div class="mt-2 grid gap-2"><Button size="sm">One</Button><Button size="sm">Two</Button></div></div><div><DemoLabel>horizontal / gap 4</DemoLabel><div class="mt-2 flex gap-4"><Button size="sm">One</Button><Button size="sm">Two</Button></div></div></div></DemoFrame></DemoCard>
  if (props.name === "Layout") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="grid min-h-44 grid-rows-[auto_1fr_auto] overflow-hidden rounded border"><header class="bg-zinc-100 p-3 text-sm font-medium dark:bg-zinc-800">Header</header><div class="grid grid-cols-[100px_1fr]"><aside class="border-r p-3 text-xs dark:border-zinc-700">Sidebar</aside><main class="p-4 text-sm">Content</main></div><footer class="border-t p-2 text-xs dark:border-zinc-700">Footer</footer></div></DemoFrame></DemoCard>
  if (props.name === "Container") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="space-y-2"><For each={["max-w-sm","max-w-2xl","max-w-5xl"]}>{(width) => <div class={`mx-auto ${width} rounded bg-zinc-200 p-3 text-center text-xs dark:bg-zinc-800`}>{width}</div>}</For></div></DemoFrame></DemoCard>
  if (props.name === "AspectRatio") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="grid gap-3 sm:grid-cols-3">{["16 / 9","4 / 3","1 / 1"].map((ratio) => <div><div class="grid aspect-video place-items-center rounded bg-gradient-to-br from-blue-500 to-indigo-600 text-white">{ratio}</div><p class="mt-1 text-xs">{ratio}</p></div>)}</div></DemoFrame></DemoCard>
  if (props.name === "Resizable") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="flex h-32"><div class="flex-1 rounded-l border p-3 text-sm">Pane A</div><div class="w-2 cursor-col-resize bg-zinc-200 dark:bg-zinc-700" onPointerDown={(event) => event.currentTarget.setPointerCapture(event.pointerId)} /><div class="flex-1 rounded-r border p-3 text-sm">Pane B</div></div></DemoFrame></DemoCard>
  if (props.name === "ScrollArea") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="h-32 overflow-auto rounded border p-3 [scrollbar-color:#71717a_transparent]">{Array.from({length:10},(_,i)=><p class="py-2 text-sm">Scrollable row {i+1}</p>)}</div></DemoFrame></DemoCard>
  return <DemoCard name={props.name} status={props.status}><DemoFrame><Accordion multiple defaultValue={["one"]} class="divide-y rounded-lg border dark:divide-zinc-700 dark:border-zinc-700"><Accordion.Item value="one"><Accordion.Trigger class="flex w-full items-center justify-between px-4 py-3 text-left text-sm font-medium hover:bg-zinc-100 disabled:opacity-50 dark:hover:bg-zinc-800 [&[data-expanded]>svg]:rotate-180">单项展开<Icon name="chevron-down" size={16} class="shrink-0 transition-transform" /></Accordion.Trigger><Accordion.Content class="px-4 pb-3 text-sm text-zinc-600 dark:text-zinc-300">Accordion content</Accordion.Content></Accordion.Item><Accordion.Item value="two"><Accordion.Trigger class="flex w-full items-center justify-between px-4 py-3 text-left text-sm font-medium hover:bg-zinc-100 disabled:opacity-50 dark:hover:bg-zinc-800 [&[data-expanded]>svg]:rotate-180">多项展开<Icon name="chevron-down" size={16} class="shrink-0 transition-transform" /></Accordion.Trigger><Accordion.Content class="px-4 pb-3 text-sm text-zinc-600 dark:text-zinc-300">第二项内容</Accordion.Content></Accordion.Item><Accordion.Item value="disabled" disabled><Accordion.Trigger class="flex w-full items-center justify-between px-4 py-3 text-left text-sm font-medium hover:bg-zinc-100 disabled:opacity-50 dark:hover:bg-zinc-800 [&[data-expanded]>svg]:rotate-180">禁用项<Icon name="chevron-down" size={16} class="shrink-0 transition-transform" /></Accordion.Trigger><Accordion.Content class="px-4 pb-3 text-sm text-zinc-600 dark:text-zinc-300">不可用</Accordion.Content></Accordion.Item></Accordion></DemoFrame></DemoCard>
}
