/* eslint-disable */
import { createSignal, Show } from "solid-js"
import { DemoCard, DemoFrame } from "./shared"
import { Icon } from "@/icons"
import { Button } from "@/ui/button"
import { Checkbox } from "@/ui/checkbox"
import { Dialog } from "@/ui/dialog"
import { Pagination } from "@/ui/pagination"
import { Tabs } from "@/ui/tabs"
import { toast } from "@/ui/toast"
import { Badge } from "@/ui/badge"

export function NavigationDemo(props: { name: string; status: string }) {
  const [palette, setPalette] = createSignal(false)
  const [page, setPage] = createSignal(1)
  if (props.name === "Menu" || props.name === "Navbar") return <DemoCard name={props.name} status={props.status}><DemoFrame><nav class="flex flex-wrap items-center gap-4 rounded border p-3"><span class="font-bold">A</span><a class="text-sm hover:text-blue-600" href="#component-Button">产品</a><a class="text-sm hover:text-blue-600" href="#component-Grid">解决方案</a><a class="text-sm hover:text-blue-600" href="#component-Table">资源</a><Button size="sm" class="ml-auto">开始使用</Button></nav><div class="mt-3 grid gap-2 sm:grid-cols-3"><button class="rounded bg-zinc-100 p-2 text-left text-sm dark:bg-zinc-800">文件 <kbd class="float-right text-xs">⌘F</kbd></button><button class="rounded p-2 text-left text-sm hover:bg-zinc-100 dark:hover:bg-zinc-800">编辑</button><button class="rounded p-2 text-left text-sm hover:bg-zinc-100 dark:hover:bg-zinc-800">帮助</button></div></DemoFrame></DemoCard>
  if (props.name === "Dropdown") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="flex gap-3"><Button variant="outline">菜单 <Icon name="chevron-down" size={14} /></Button><div class="w-64 rounded border bg-white p-1 text-sm shadow dark:border-zinc-700 dark:bg-zinc-900"><button class="flex w-full justify-between rounded px-2 py-1.5 hover:bg-zinc-100 dark:hover:bg-zinc-800">新建 <span>⌘N</span></button><button class="flex w-full gap-2 rounded px-2 py-1.5 hover:bg-zinc-100 dark:hover:bg-zinc-800"><Icon name="folder" size={14} />打开</button><Checkbox label="显示侧边栏" checked /><div class="my-1 border-t dark:border-zinc-700" /><button class="w-full rounded px-2 py-1.5 text-left text-red-600">删除</button></div></div></DemoFrame></DemoCard>
  if (props.name === "Breadcrumb") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="flex flex-wrap items-center gap-2 text-sm"><a href="#component-Navbar">首页</a><span>/</span><Icon name="folder" size={14} /><a href="#component-Table">项目</a><span>/</span><span class="font-medium">当前页面</span><span class="mx-2">…</span><span class="text-zinc-500">已折叠</span></div></DemoFrame></DemoCard>
  if (props.name === "Tabs") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="space-y-4"><Tabs.Root defaultValue="one"><Tabs.List class="flex gap-1 overflow-x-auto border-b"><Tabs.Trigger value="one" class="whitespace-nowrap px-3 py-2 data-[selected]:border-b-2 data-[selected]:border-blue-600">默认</Tabs.Trigger><Tabs.Trigger value="two" class="whitespace-nowrap px-3 py-2 data-[selected]:border-b-2 data-[selected]:border-blue-600">带图标</Tabs.Trigger><Tabs.Trigger value="disabled" disabled class="whitespace-nowrap px-3 py-2">禁用</Tabs.Trigger></Tabs.List><Tabs.Content value="one" class="p-3">下划线样式内容</Tabs.Content><Tabs.Content value="two" class="rounded p-3">Pills / vertical / scrollable</Tabs.Content></Tabs.Root></div></DemoFrame></DemoCard>
  if (props.name === "Pagination") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="space-y-3"><Pagination page={page()} count={97} pageSize={10} onPageChange={setPage} /><div class="flex items-center gap-2 text-sm"><span>紧凑</span><button class="rounded border px-2 py-1">‹</button><span>{page()} / 10</span><button class="rounded border px-2 py-1">›</button><span class="ml-4">每页 10 / 页</span></div></div></DemoFrame></DemoCard>
  if (props.name === "Steps") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="grid gap-5 md:grid-cols-2"><div class="flex items-center">{["提交","审核","完成"].map((item,index)=><div class="flex items-center"><span class={`grid size-8 place-items-center rounded-full ${index<2?"bg-blue-600 text-white":"border"}`}>{index+1}</span><span class="mx-2 text-sm">{item}</span>{index<2?<span class="h-px w-8 bg-zinc-300" />:null}</div>)}</div><div class="space-y-2 border-l pl-4"><p>✓ 提交申请</p><p>● 审核中</p><p class="text-red-600">× 错误步骤</p></div></div></DemoFrame></DemoCard>
  if (props.name === "CommandPalette") return <DemoCard name={props.name} status={props.status}><DemoFrame><Button onClick={() => setPalette(true)}>打开命令面板 <kbd class="ml-2">⌘K</kbd></Button><Dialog.Root open={palette()} onOpenChange={setPalette}><Dialog.Portal><Dialog.Overlay class="fixed inset-0 z-50 bg-black/40" /><Dialog.Content class="fixed left-1/2 top-1/4 z-50 w-[calc(100%-2rem)] max-w-lg -translate-x-1/2 rounded-lg border bg-white p-3 shadow-xl dark:border-zinc-700 dark:bg-zinc-900"><Dialog.Title class="sr-only">命令面板</Dialog.Title><Dialog.Description class="sr-only">搜索导航项</Dialog.Description><input autofocus placeholder="搜索命令..." class="w-full rounded border p-2 dark:bg-zinc-900" /><div class="mt-2 grid gap-1">{["仪表盘","订单","设置","组件全集"].map((item) => <button class="rounded p-2 text-left hover:bg-zinc-100 dark:hover:bg-zinc-800">{item}</button>)}</div></Dialog.Content></Dialog.Portal></Dialog.Root></DemoFrame></DemoCard>
  if (props.name === "Anchor" || props.name === "BackTop" || props.name === "Affix") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="relative max-h-40 overflow-auto rounded border p-3"><div class="sticky top-0 z-10 flex gap-3 bg-white/90 p-2 text-sm dark:bg-zinc-900/90"><a href="#anchor-a" class="text-blue-600">Section A</a><a href="#anchor-b">Section B</a><Show when={props.name === "Affix"}><Badge>sticky</Badge></Show></div><div class="space-y-16 p-3"><p id="anchor-a">Section A content</p><p id="anchor-b">Section B content</p><p>Scroll box content</p></div><Show when={props.name === "BackTop"}><Button size="icon" class="sticky bottom-2 float-right" onClick={() => toast.info("已回到顶部")} aria-label="回到顶部">↑</Button></Show></div></DemoFrame></DemoCard>
  if (props.name === "Sidebar") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="flex gap-3"><aside class="grid gap-2 rounded border p-2"><Icon name="layout-dashboard" /><Icon name="shopping-cart" /><Icon name="settings" /></aside><aside class="w-48 rounded border p-3"><p class="font-semibold">Acme Console</p><p class="mt-3 text-sm">仪表盘</p><p class="text-sm">订单</p><p class="text-sm">设置</p></aside></div></DemoFrame></DemoCard>
  return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="flex flex-wrap gap-2"><Button>首页</Button><Button variant="outline">上一页</Button><Button variant="ghost">下一页</Button><span class="text-sm text-zinc-500">交互导航演示</span></div></DemoFrame></DemoCard>
}
