/* eslint-disable solid/prefer-for */
import { Link as KobalteLink } from "@kobalte/core/link"
import { Icon } from "@/icons"
import { Separator } from "@/ui/separator"
import { toast } from "@/ui/toast"
import { DemoCard, DemoFrame, DemoLabel } from "./shared"

const code = `const total = orders.reduce((sum, order) => sum + order.amount, 0)
return { total, count: orders.length }
`
const kbdClass = "inline-flex min-w-6 items-center justify-center rounded border border-zinc-300 bg-white px-1.5 py-0.5 font-mono text-xs shadow-[inset_0_-1px_0_var(--color-zinc-300)] dark:border-zinc-700 dark:bg-zinc-900 dark:shadow-[inset_0_-1px_0_var(--color-zinc-700)]"

export function TypographyDemo(props: { name: string; status: string }) {
  if (props.name === "Typography") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="grid gap-4 sm:grid-cols-2"><div class="space-y-2"><DemoLabel>Headings</DemoLabel><h1 class="text-3xl font-bold">Heading 1</h1><h2 class="text-2xl font-semibold">Heading 2</h2><h3 class="text-xl font-semibold">Heading 3</h3><h4 class="text-lg font-semibold">Heading 4</h4><h5 class="font-semibold">Heading 5</h5><h6 class="text-sm font-semibold">Heading 6</h6></div><div class="space-y-3"><DemoLabel>Body</DemoLabel><p class="text-lg">Lead paragraph for an important introduction.</p><p>Regular paragraph with <a class="text-blue-600 underline dark:text-blue-400" href="#component-Link">inline link</a>.</p><p class="text-sm text-zinc-500 dark:text-zinc-400">Muted helper text.</p><blockquote class="border-l-2 border-blue-600 pl-3 italic">A short blockquote for context.</blockquote><ul class="list-disc pl-5"><li>Unordered item</li><li>Another item</li></ul><ol class="list-decimal pl-5"><li>Ordered item</li><li>Another item</li></ol></div></div></DemoFrame></DemoCard>
  if (props.name === "Kbd") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="grid gap-4"><div><DemoLabel>单键</DemoLabel><div class="mt-2 flex flex-wrap gap-2">{["⌘", "Ctrl", "Shift", "Esc", "↑", "↓", "Enter"].map((key) => <kbd class={kbdClass}>{key}</kbd>)}</div></div><div><DemoLabel>组合</DemoLabel><div class="mt-2 flex flex-wrap items-center gap-1">{["⌘", "K"].map((key, index) => <>{index ? <span>+</span> : null}<kbd class={kbdClass}>{key}</kbd></>)}<span class="mx-2">·</span>{["Ctrl", "Shift", "P"].map((key, index) => <>{index ? <span>+</span> : null}<kbd class={kbdClass}>{key}</kbd></>)}</div></div><div><DemoLabel>句内</DemoLabel><p class="mt-2 text-sm">使用 <kbd class={kbdClass}>⌘ K</kbd> 打开搜索。</p></div><div><DemoLabel>尺寸</DemoLabel><div class="mt-2 flex items-center gap-2"><kbd class={`${kbdClass} text-[10px]`}>sm</kbd><kbd class={kbdClass}>md</kbd><kbd class={`${kbdClass} text-sm`}>lg</kbd></div></div></div></DemoFrame></DemoCard>
  if (props.name === "Code") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="grid gap-4"><div><DemoLabel>行内</DemoLabel><p class="mt-2 text-sm">运行 <code class="rounded bg-zinc-200 px-1.5 py-0.5 font-mono text-xs dark:bg-zinc-800">pnpm build</code> 检查项目。</p></div><div><DemoLabel>代码块</DemoLabel><div class="mt-2 overflow-hidden rounded-lg bg-zinc-900 text-xs text-zinc-100"><div class="flex items-center justify-between border-b border-zinc-700 px-4 py-1"><span class="text-zinc-400">ts</span><button type="button" class="min-h-10 min-w-10 rounded px-2 text-zinc-200 hover:bg-zinc-800" onClick={() => { navigator.clipboard?.writeText(code); toast.success("已复制") }}>复制</button></div><pre class="overflow-x-auto p-4">{code}</pre></div></div><div><DemoLabel>带行号</DemoLabel><pre class="mt-2 overflow-x-auto rounded-lg bg-zinc-900 p-4 text-xs text-zinc-100"><span class="select-none text-zinc-500">1 </span>const ready = true{"\n"}<span class="select-none text-zinc-500">2 </span>if (ready) start(){"\n"}<span class="select-none text-zinc-500">3 </span>console.log("done")</pre></div></div></DemoFrame></DemoCard>
  if (props.name === "Divider") return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="grid gap-4"><div><DemoLabel>水平</DemoLabel><p class="mt-2 text-sm">上方文字</p><Separator class="my-3" /><p class="text-sm">下方文字</p></div><div><DemoLabel>带文字</DemoLabel><div class="mt-2 flex items-center gap-3"><Separator class="flex-1" /><span class="text-xs text-zinc-500 dark:text-zinc-400">或</span><Separator class="flex-1" /></div></div><div><DemoLabel>垂直</DemoLabel><div class="mt-2 flex h-6 items-center gap-3 text-sm"><span>文档</span><Separator orientation="vertical" /><span>API</span><Separator orientation="vertical" /><span>更新日志</span></div></div><div><DemoLabel>虚线 / 加粗</DemoLabel><div class="mt-2 grid gap-3"><Separator class="h-px border-0 bg-transparent border-t border-dashed border-zinc-300 dark:border-zinc-700" /><Separator class="h-0.5" /></div></div></div></DemoFrame></DemoCard>
  return <DemoCard name={props.name} status={props.status}><DemoFrame><div class="grid gap-4"><div><DemoLabel>默认 / 悬停下划线 / 常显下划线</DemoLabel><div class="mt-2 flex flex-wrap gap-4"><KobalteLink href="#component-Button" class="inline-flex min-h-10 items-center text-blue-600 dark:text-blue-400">默认</KobalteLink><KobalteLink href="#component-Button" class="inline-flex min-h-10 items-center text-blue-600 hover:underline dark:text-blue-400">悬停下划线</KobalteLink><KobalteLink href="#component-Button" class="inline-flex min-h-10 items-center text-blue-600 underline dark:text-blue-400">常显下划线</KobalteLink></div></div><div class="grid justify-items-start gap-2"><DemoLabel>外部</DemoLabel><KobalteLink href="https://example.com" target="_blank" rel="noreferrer" class="inline-flex min-h-10 items-center gap-1 text-blue-600 hover:underline dark:text-blue-400">外部链接 <Icon name="arrow-up-right" size={14} /></KobalteLink></div><div class="grid justify-items-start gap-2"><DemoLabel>禁用</DemoLabel><KobalteLink disabled href="#" class="inline-flex min-h-10 items-center text-zinc-400 aria-disabled:cursor-not-allowed aria-disabled:no-underline dark:text-zinc-600">禁用链接</KobalteLink></div><div><DemoLabel>按钮样 / 弱化 / 句内</DemoLabel><div class="mt-2 flex flex-wrap items-center gap-4"><KobalteLink href="#component-Button" class="inline-flex min-h-10 items-center rounded-md border border-zinc-300 bg-white px-4 text-sm font-medium hover:bg-zinc-100 dark:border-zinc-700 dark:bg-zinc-900 dark:hover:bg-zinc-800">按钮样链接</KobalteLink><KobalteLink href="#component-Button" class="inline-flex min-h-10 items-center text-zinc-500 hover:text-zinc-900 dark:text-zinc-400 dark:hover:text-zinc-100">弱化链接</KobalteLink><p class="text-sm">这是一句包含 <KobalteLink href="#component-Button" class="inline-flex min-h-10 items-center text-blue-600 hover:underline dark:text-blue-400">句内链接</KobalteLink> 的正文。</p></div></div></div></DemoFrame></DemoCard>
}
