import { useRef, useState, type ReactNode } from "react"
import { Link } from "react-router-dom"
import {
  Anchor, AutoComplete, Avatar, AvatarGroup, BackTop, Badge, Banner, Breadcrumb, Button, ButtonGroup, Calendar, Card, Carousel, Cascader, Checkbox, CheckboxGroup, CodeHighlight, Collapse, Collapsible, ColorPicker, ConfigProvider, DatePicker, Descriptions, Divider, Dropdown, Empty, FloatButton, FloatButtonGroup, Form, IconButton, Image, Input, InputNumber, Layout, List, Modal, Nav, Notification, OverflowList, Pagination, PinCode, Popconfirm, Popover, Progress, Radio, RadioGroup, Rating, Resizable, ScrollList, ScrollItem, Select, SideSheet, Skeleton, Slider, Space, Spin, SplitButtonGroup, Steps, Switch, Table, Tabs, Tag, TagGroup, TextArea, TimePicker, Timeline, Toast, Tooltip, Transfer, Tree, TreeSelect, Typography, Upload, UserGuide,
} from "@douyinfe/semi-ui"
import { IllustrationNoContent, IllustrationNoContentDark } from "@douyinfe/semi-illustrations"
import contract from "@ui-gallery/spec/contract.json"
import nav from "@ui-gallery/spec/mock/nav.json"
import orders from "@ui-gallery/spec/mock/orders.json"
import team from "@ui-gallery/spec/mock/team.json"
import { coverage, type CoverageStatus } from "@/coverage"
import { Icon } from "@/icons"
import { PageHeader, StatusTag, money } from "./shared"

const { Title, Text, Paragraph, Numeral } = Typography
const statusMeta: Record<CoverageStatus, { color: "green" | "orange" | "red"; label: string }> = { implemented: { color: "green", label: "implemented" }, composed: { color: "orange", label: "composed" }, missing: { color: "red", label: "missing" } }
const sizes = ["small", "default", "large"] as const
const btnTypes = ["primary", "secondary", "tertiary", "warning", "danger"] as const
const btnThemes = ["light", "solid", "borderless", "outline"] as const
const treeData = [{ label: "Acme", value: "acme", key: "acme", children: [{ label: "产品", value: "product", key: "product", children: [{ label: "控制台", value: "console", key: "console" }, { label: "API", value: "api", key: "api" }] }, { label: "市场", value: "marketing", key: "marketing" }] }]
const options = ["web", "ios", "android", "api"].map((value) => ({ value, label: value }))

function Demo({ label, children }: { label?: string; children: ReactNode }) {
  return <div className="acme-demo-block">{label ? <Text type="tertiary" size="small" style={{ display: "block", marginBottom: 6 }}>{label}</Text> : null}<div className="acme-row">{children}</div></div>
}

function Section({ name, children }: { name: string; children?: ReactNode }) {
  const status = coverage[name] ?? "missing"
  const meta = statusMeta[status]
  return (
    <div id={`c-${name}`} style={{ scrollMarginTop: 80, minWidth: 0 }}>
      <Card title={<span className="acme-row"><span>{name}</span><Tag color={meta.color} type="light" size="small">{meta.label}</Tag></span>} bodyStyle={{ minWidth: 0 }}>
        {status === "missing" ? <Banner type="warning" closeIcon={null} description={`Semi Design 未提供 ${name} 对应的官方组件，此处不做自造替代。`} /> : children}
      </Card>
    </div>
  )
}

function FeedbackDemos() {
  const [modal, setModal] = useState(false)
  const [sheet, setSheet] = useState(false)
  const [guide, setGuide] = useState(false)
  const guideRef = useRef<HTMLDivElement>(null)
  return (
    <>
      <Section name="Toast"><Demo>{(["info", "success", "warning", "error"] as const).map((type) => <Button key={type} onClick={() => Toast[type](`${type} toast`)}>{type}</Button>)}</Demo></Section>
      <Section name="Notification"><Demo><Button onClick={() => Notification.info({ title: "新订单", content: "ORD-2401 已支付", duration: 3 })}>info</Button><Button onClick={() => Notification.success({ title: "导出完成", content: "orders.csv 已生成", duration: 3 })}>success</Button></Demo></Section>
      <Section name="Dialog"><Demo><Button onClick={() => setModal(true)}>打开 Modal</Button><Button onClick={() => Modal.confirm({ title: "确认操作", content: "确定继续吗？" })}>Modal.confirm</Button></Demo><Modal title="示例对话框" visible={modal} onOk={() => setModal(false)} onCancel={() => setModal(false)} centered>这是一个居中的 Semi Modal。</Modal></Section>
      <Section name="Drawer"><Demo><Button onClick={() => setSheet(true)}>打开 SideSheet</Button></Demo><SideSheet title="侧边抽屉" visible={sheet} onCancel={() => setSheet(false)} width="min(400px, 100vw)"><Paragraph>SideSheet 内容区域。</Paragraph></SideSheet></Section>
      <Section name="Tour"><Demo><div ref={guideRef} style={{ display: "inline-block" }}><Button onClick={() => setGuide(true)}>开始引导</Button></div></Demo><UserGuide mode="popup" visible={guide} steps={[{ target: () => guideRef.current!, title: "第一步", description: "UserGuide 用于新手引导。" }]} onFinish={() => setGuide(false)} onSkip={() => setGuide(false)} /></Section>
    </>
  )
}

export function ComponentsPage() {
  const [collapsed, setCollapsed] = useState(false)
  const [tab, setTab] = useState("1")
  const counts = (["implemented", "composed", "missing"] as CoverageStatus[]).map((status) => ({ status, count: contract.components.filter((name) => coverage[name] === status).length }))
  return (
    <div className="acme-page">
      <PageHeader title="组件总览" description={`Semi Design 2.103 · contract.json ${contract.components.length} 个组件`} action={<div className="acme-row">{counts.map((item) => <Tag key={item.status} color={statusMeta[item.status].color} type="light">{item.status} {item.count}</Tag>)}</div>} />
      <div className="acme-components-grid">
        <div className="acme-anchor-index acme-desktop-only">
          <Anchor maxHeight="calc(100vh - 120px)" showTooltip>{contract.components.map((name) => <Anchor.Link key={name} href={`#c-${name}`} title={name} />)}</Anchor>
        </div>
        <div className="acme-page" style={{ gap: 16, minWidth: 0 }}>
          <Section name="Typography"><Space vertical align="start"><Title heading={1}>标题 H1</Title><Title heading={3}>标题 H3</Title><Paragraph>正文段落 Paragraph，<Text strong>加粗</Text>、<Text underline>下划线</Text>、<Text delete>删除线</Text>、<Text mark>高亮</Text>、<Text code>code</Text>、<Text link>链接</Text>。</Paragraph><Text type="secondary">secondary</Text><Text type="tertiary">tertiary</Text><Text type="success">success</Text><Text type="warning">warning</Text><Text type="danger">danger</Text><Numeral precision={2} rule="numbers">¥128430.5</Numeral></Space></Section>
          <Section name="Button">{btnThemes.map((theme) => <Demo key={theme} label={`theme=${theme}`}>{btnTypes.map((type) => <Button key={type} theme={theme} type={type}>{type}</Button>)}<Button theme={theme} disabled>disabled</Button><Button theme={theme} loading>loading</Button></Demo>)}<Demo label="size">{sizes.map((size) => <Button key={size} size={size} theme="solid">{size}</Button>)}<Button block>block</Button></Demo></Section>
          <Section name="ButtonGroup"><Demo><ButtonGroup><Button>日</Button><Button>周</Button><Button>月</Button></ButtonGroup><ButtonGroup size="small" theme="solid"><Button>保存</Button><Button>另存为</Button></ButtonGroup><SplitButtonGroup><Button theme="solid">主操作</Button><Dropdown render={<Dropdown.Menu><Dropdown.Item>选项 A</Dropdown.Item></Dropdown.Menu>}><Button theme="solid" icon={<Icon name="chevron-down" />} /></Dropdown></SplitButtonGroup></Demo></Section>
          <Section name="IconButton"><Demo>{sizes.map((size) => <IconButton key={size} size={size} icon={<Icon name="settings" />} aria-label="设置" />)}<IconButton theme="solid" icon={<Icon name="plus" />} aria-label="新增" /><IconButton theme="borderless" icon={<Icon name="trash" />} type="danger" aria-label="删除" /><IconButton disabled icon={<Icon name="edit" />} aria-label="编辑" /></Demo></Section>
          <Section name="Input"><Demo>{sizes.map((size) => <Input key={size} size={size} placeholder={size} style={{ width: 160 }} />)}</Demo><Demo><Input prefix={<Icon name="search" />} placeholder="prefix" showClear style={{ width: 200 }} /><Input addonBefore="https://" addonAfter=".com" style={{ width: 240 }} /><Input mode="password" placeholder="密码" style={{ width: 160 }} /><Input validateStatus="error" defaultValue="错误态" style={{ width: 160 }} /><Input validateStatus="warning" defaultValue="警告态" style={{ width: 160 }} /><Input disabled defaultValue="disabled" style={{ width: 160 }} /></Demo></Section>
          <Section name="Textarea"><Demo><TextArea placeholder="autosize" autosize maxCount={100} style={{ width: 280 }} /><TextArea disabled defaultValue="disabled" style={{ width: 200 }} /></Demo></Section>
          <Section name="NumberInput"><Demo>{sizes.map((size) => <InputNumber key={size} size={size} defaultValue={size === "small" ? 1 : 10} min={0} />)}<InputNumber defaultValue={1024} formatter={(value) => `¥ ${value}`} parser={(value) => value.replace(/¥\s?/, "")} /><InputNumber disabled defaultValue={0} /></Demo></Section>
          <Section name="Select"><Demo>{sizes.map((size) => <Select key={size} size={size} defaultValue="web" optionList={options} style={{ width: 140 }} />)}<Select placeholder="filter" filter optionList={options} style={{ width: 160 }} /><Select disabled placeholder="disabled" style={{ width: 140 }} /><Select validateStatus="error" placeholder="error" optionList={options} style={{ width: 140 }} /></Demo></Section>
          <Section name="MultiSelect"><Demo><Select multiple defaultValue={["web", "ios"]} optionList={options} style={{ width: 240 }} /><Select multiple maxTagCount={1} defaultValue={["web", "ios", "api"]} optionList={options} style={{ width: 200 }} /></Demo></Section>
          <Section name="Combobox"><Demo><Select filter allowCreate multiple placeholder="搜索或创建" optionList={options} style={{ width: 260 }} /></Demo></Section>
          <Section name="Autocomplete"><Demo><AutoComplete data={["上海", "杭州", "北京", "深圳"]} placeholder="输入城市" showClear style={{ width: 200 }} /></Demo></Section>
          <Section name="Checkbox"><Demo><Checkbox>默认</Checkbox><Checkbox defaultChecked>已选</Checkbox><Checkbox indeterminate>部分</Checkbox><Checkbox disabled>禁用</Checkbox><Checkbox defaultChecked disabled>禁用已选</Checkbox></Demo><Demo label="Card 样式"><CheckboxGroup type="card" defaultValue={["a"]} direction="horizontal" options={[{ label: "选项 A", value: "a", extra: "描述" }, { label: "选项 B", value: "b", extra: "描述" }]} /></Demo></Section>
          <Section name="Radio"><Demo><RadioGroup defaultValue={1}><Radio value={1}>默认</Radio><Radio value={2}>选项</Radio><Radio value={3} disabled>禁用</Radio></RadioGroup><RadioGroup type="button" defaultValue="a" buttonSize="small"><Radio value="a">日</Radio><Radio value="b">周</Radio><Radio value="c">月</Radio></RadioGroup><RadioGroup type="card" defaultValue="x" direction="horizontal"><Radio value="x" extra="卡片说明">卡片 A</Radio><Radio value="y" extra="卡片说明">卡片 B</Radio></RadioGroup></Demo></Section>
          <Section name="Switch"><Demo><Switch size="small" defaultChecked aria-label="small" /><Switch aria-label="default" /><Switch size="large" defaultChecked aria-label="large" /><Switch loading aria-label="loading" /><Switch disabled aria-label="disabled" /><Switch checkedText="开" uncheckedText="关" defaultChecked aria-label="文字" /></Demo></Section>
          <Section name="Slider"><div style={{ display: "grid", gap: 16 }}><Slider defaultValue={40} /><Slider range defaultValue={[20, 60]} marks={{ 0: "0", 50: "50", 100: "100" }} /><Slider defaultValue={30} disabled /><Slider defaultValue={30} step={10} showBoundary /></div></Section>
          <Section name="Rating"><Demo><Rating defaultValue={3} /><Rating allowHalf defaultValue={2.5} size="small" /><Rating defaultValue={4} disabled /><Rating character={<Icon name="heart" />} defaultValue={2} /></Demo></Section>
          <Section name="DatePicker"><Demo><DatePicker placeholder="日期" /><DatePicker type="dateTime" placeholder="日期时间" /><DatePicker type="month" placeholder="月份" /><DatePicker size="small" placeholder="small" /><DatePicker disabled placeholder="disabled" /></Demo></Section>
          <Section name="TimePicker"><Demo><TimePicker placeholder="时间" /><TimePicker use12Hours format="hh:mm a" placeholder="12 小时" /><TimePicker type="timeRange" placeholder="开始 - 结束" /><TimePicker disabled /></Demo></Section>
          <Section name="DateRangePicker"><Demo><DatePicker type="dateRange" placeholder={["开始", "结束"]} /><DatePicker type="dateTimeRange" placeholder={["开始", "结束"]} style={{ width: 360, maxWidth: "100%" }} /><DatePicker type="dateRange" presetPosition="left" presets={[{ text: "9 月上旬", start: new Date(2026, 8, 1), end: new Date(2026, 8, 10) }]} /></Demo></Section>
          <Section name="ColorPicker"><Demo><ColorPicker alpha defaultValue={ColorPicker.colorStringToValue("#0064fa")} onChange={() => {}} usePopover /><ColorPicker alpha={false} defaultValue={ColorPicker.colorStringToValue("#3bb346")} onChange={() => {}} usePopover /></Demo></Section>
          <Section name="Upload"><Demo><Upload action="" uploadTrigger="custom"><Button icon={<Icon name="upload" />} theme="light">点击上传</Button></Upload><Upload action="" uploadTrigger="custom" listType="picture" accept="image/*"><Icon name="plus" size={20} /></Upload></Demo><Upload action="" uploadTrigger="custom" draggable dragMainText="拖拽文件到此处" dragSubText="支持任意格式" /></Section>
          <Section name="Cascader"><Demo><Cascader treeData={treeData} placeholder="单选" style={{ width: 220 }} /><Cascader treeData={treeData} multiple placeholder="多选" style={{ width: 240 }} /><Cascader treeData={treeData} filterTreeNode placeholder="可搜索" style={{ width: 220 }} /><Cascader treeData={treeData} disabled placeholder="disabled" style={{ width: 160 }} /></Demo></Section>
          <Section name="Transfer"><div className="acme-scroll-x"><Transfer style={{ width: 560, minWidth: 320 }} dataSource={team.map((member, index) => ({ label: member.name, value: index, key: index }))} defaultValue={[0, 1]} /></div></Section>
          <Section name="Mention"><Demo><TextArea placeholder="输入 @ 提及成员（用 TextArea + Dropdown 组合模拟）" autosize style={{ width: 320 }} /><Dropdown trigger="click" render={<Dropdown.Menu>{team.slice(0, 3).map((member) => <Dropdown.Item key={member.email}>@{member.name}</Dropdown.Item>)}</Dropdown.Menu>}><Button theme="light">@ 成员</Button></Dropdown></Demo></Section>
          <Section name="PinInput"><Demo><PinCode count={6} format="number" autoFocus={false} onComplete={() => Toast.success("验证码已填写")} /><PinCode count={4} size="small" autoFocus={false} defaultValue="1234" /></Demo></Section>
          <Section name="Form"><Form layout="horizontal" labelPosition="inset" onSubmit={() => Toast.success("提交成功")} style={{ flexWrap: "wrap" }}><Form.Input field="name" label="姓名" rules={[{ required: true, message: "必填" }]} style={{ width: 160 }} /><Form.Select field="role" label="角色" optionList={[{ value: "admin", label: "admin" }, { value: "member", label: "member" }]} style={{ width: 160 }} /><Form.Switch field="active" label="启用" /><Button htmlType="submit" theme="solid" style={{ alignSelf: "flex-end" }}>提交</Button></Form></Section>
          <Section name="Table"><div className="acme-scroll-x"><Table size="small" scroll={{ x: 560 }} rowKey="id" dataSource={orders.slice(0, 4)} pagination={false} rowSelection={{}} columns={[{ title: "订单", dataIndex: "id", sorter: (a, b) => (a?.id ?? "").localeCompare(b?.id ?? "") }, { title: "客户", dataIndex: "customer" }, { title: "状态", dataIndex: "status", render: (value: string) => <StatusTag value={value} /> }, { title: "金额", dataIndex: "amount", align: "right", render: (value: number) => money(value) }]} /></div><Demo label="loading / empty"><Table size="small" loading dataSource={[]} columns={[{ title: "列", dataIndex: "a" }]} pagination={false} style={{ width: 240 }} /><Table size="small" dataSource={[]} columns={[{ title: "列", dataIndex: "a" }]} pagination={false} style={{ width: 240 }} /></Demo></Section>
          <Section name="DataGrid"><div className="acme-scroll-x"><Table size="small" rowKey="id" bordered dataSource={orders.slice(0, 5)} pagination={{ pageSize: 3 }} scroll={{ x: 640 }} columns={[{ title: "订单", dataIndex: "id", fixed: true, width: 110 }, { title: "客户", dataIndex: "customer", filters: [{ text: "林晓", value: "林晓" }], onFilter: (value, record) => record?.customer === value }, { title: "商品", dataIndex: "product" }, { title: "渠道", dataIndex: "channel" }, { title: "金额", dataIndex: "amount", align: "right", sorter: (a, b) => (a?.amount ?? 0) - (b?.amount ?? 0), render: (value: number) => money(value) }]} /></div></Section>
          <Section name="Descriptions"><Descriptions align="left" data={[{ key: "客户", value: orders[0].customer }, { key: "商品", value: orders[0].product }, { key: "金额", value: money(orders[0].amount) }]} /><Descriptions row size="small" data={[{ key: "订单数", value: "1,024" }, { key: "转化率", value: "3.6%" }, { key: "退款率", value: "1.2%" }]} /></Section>
          <Section name="List"><List size="small" bordered dataSource={team.slice(0, 3)} renderItem={(item) => <List.Item header={<Avatar size="small" color="light-blue">{item.name.slice(0, 1)}</Avatar>} main={<div><Text strong>{item.name}</Text><br /><Text type="tertiary" size="small">{item.email}</Text></div>} extra={<Tag>{item.role}</Tag>} />} /></Section>
          <Section name="Card"><div className="acme-grid-3 acme-grid"><Card title="标准卡片" headerExtraContent={<Text link>更多</Text>}>内容</Card><Card shadows="hover" title="悬浮阴影">hover 我</Card><Card cover={<div style={{ height: 80, background: "var(--semi-color-fill-0)" }} />} title="带封面" footer={<Button size="small">操作</Button>}>footer</Card><Card loading title="加载中">skeleton</Card></div></Section>
          <Section name="Avatar"><Demo>{(["extra-small", "small", "default", "large", "extra-large"] as const).map((size) => <Avatar key={size} size={size} color="light-blue">林</Avatar>)}<Avatar shape="square" color="orange">方</Avatar><Avatar color="grey"><Icon name="user" /></Avatar><Badge dot position="rightBottom"><Avatar size="small" color="green">在</Avatar></Badge></Demo></Section>
          <Section name="AvatarGroup"><Demo><AvatarGroup maxCount={3} size="small">{team.map((member) => <Avatar key={member.email} color="light-blue">{member.name.slice(0, 1)}</Avatar>)}</AvatarGroup><AvatarGroup overlapFrom="end" size="default">{team.slice(0, 3).map((member) => <Avatar key={member.email} color="violet">{member.name.slice(0, 1)}</Avatar>)}</AvatarGroup></Demo></Section>
          <Section name="Badge"><Demo><Badge count={5}><Avatar shape="square" color="light-blue" size="small">A</Avatar></Badge><Badge count={120} overflowCount={99}><Avatar shape="square" color="light-blue" size="small">B</Avatar></Badge><Badge dot><Avatar shape="square" color="light-blue" size="small">C</Avatar></Badge><Badge count="NEW" type="primary" /><Badge count={3} type="success" /><Badge count={3} type="warning" /><Badge count={3} type="danger" /><Badge count={3} type="tertiary" /></Demo></Section>
          <Section name="Tag"><Demo>{(["light", "solid", "ghost"] as const).map((type) => <Tag key={type} type={type} color="blue">{type}</Tag>)}{(["green", "orange", "red", "violet", "grey"] as const).map((color) => <Tag key={color} color={color}>{color}</Tag>)}<Tag closable>可关闭</Tag><Tag size="large" shape="circle">circle</Tag><Tag avatarSrc="" avatarShape="circle">头像</Tag></Demo><TagGroup maxTagCount={3} tagList={["web", "ios", "android", "api", "wechat"].map((tag) => ({ children: tag }))} size="large" showPopover /></Section>
          <Section name="Statistic"><div className="acme-grid-3 acme-grid"><Card bodyStyle={{ padding: 16 }}><Text type="tertiary">本月收入</Text><br /><Numeral precision={0} rule="numbers" style={{ fontSize: 24, fontWeight: 600 }}>¥128430</Numeral><br /><Text type="success" size="small"><Icon name="trending-up" size={12} /> +12.4%</Text></Card><Card bodyStyle={{ padding: 16 }}><Text type="tertiary">订单数</Text><br /><Numeral rule="numbers" style={{ fontSize: 24, fontWeight: 600 }}>1024</Numeral><br /><Text type="danger" size="small"><Icon name="trending-down" size={12} /> -3.2%</Text></Card></div></Section>
          <Section name="Timeline"><Timeline mode="alternate">{["创建订单", "支付成功", "已发货", "已签收"].map((title, index) => <Timeline.Item key={title} time={`09-0${index + 1}`} type={index === 3 ? "success" : index === 2 ? "ongoing" : "default"}>{title}</Timeline.Item>)}</Timeline></Section>
          <Section name="Tree"><Demo><Tree treeData={treeData} defaultExpandAll style={{ width: 240 }} /><Tree treeData={treeData} multiple defaultExpandAll defaultValue={["console"]} style={{ width: 240 }} /><TreeSelect treeData={treeData} placeholder="TreeSelect" style={{ width: 220 }} /></Demo></Section>
          <Section name="Calendar"><div className="acme-scroll-x"><Calendar mode="month" style={{ minWidth: 640, height: 420 }} events={[{ key: "1", start: new Date(2026, 8, 5, 9), end: new Date(2026, 8, 5, 11), children: <Tag color="blue" size="small">发布会</Tag> }]} /></div></Section>
          <Section name="Image"><Demo><Image width={160} height={100} src="data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='320' height='200'><rect width='320' height='200' fill='%230064fa'/><circle cx='160' cy='100' r='60' fill='white'/></svg>" alt="示例" /><Image width={160} height={100} src="data:image/png;base64,AAAA" alt="加载失败" /></Demo></Section>
          <Section name="Carousel"><Carousel style={{ height: 160, borderRadius: 8 }} theme="primary" showArrow arrowType="always">{["一", "二", "三"].map((slide) => <div key={slide} style={{ height: "100%", display: "grid", placeItems: "center", background: "var(--semi-color-primary)", color: "#fff", fontSize: 20 }}>幻灯片 {slide}</div>)}</Carousel></Section>
          <Section name="Empty"><Demo><Empty image={<IllustrationNoContent style={{ width: 120, height: 120 }} />} darkModeImage={<IllustrationNoContentDark style={{ width: 120, height: 120 }} />} title="暂无内容" description="创建第一条记录开始使用。"><Button theme="solid">新建</Button></Empty></Demo></Section>
          <Section name="Tooltip"><Demo>{(["top", "right", "bottom", "left"] as const).map((position) => <Tooltip key={position} content={`提示 · ${position}`} position={position}><Button theme="light">{position}</Button></Tooltip>)}<Tooltip content="点击触发" trigger="click"><Button>click</Button></Tooltip></Demo></Section>
          <Section name="Popover"><Demo><Popover content={<div style={{ padding: 12 }}>Popover 内容</div>} showArrow><Button theme="light">hover</Button></Popover><Popover trigger="click" position="bottomLeft" content={<div style={{ padding: 12, width: 220 }}><Title heading={6}>标题</Title><Text type="secondary">点击弹出的浮层，可承载更复杂的内容。</Text></div>}><Button>click</Button></Popover></Demo></Section>
          <Section name="QRCode" />
          <Section name="Segmented"><Demo><RadioGroup type="button" defaultValue="list" buttonSize="middle"><Radio value="list"><Icon name="list" /> 列表</Radio><Radio value="grid"><Icon name="grid" /> 网格</Radio><Radio value="kanban" disabled>看板</Radio></RadioGroup><Tabs type="button" size="small" activeKey={tab} onChange={setTab}><Tabs.TabPane tab="日" itemKey="1" /><Tabs.TabPane tab="周" itemKey="2" /><Tabs.TabPane tab="月" itemKey="3" /></Tabs></Demo></Section>
          <Section name="Alert"><Space vertical align="start" style={{ width: "100%" }}>{(["info", "success", "warning", "danger"] as const).map((type) => <Banner key={type} fullMode={false} type={type} title={`${type} 标题`} description="Banner 用于页面内的提示反馈。" style={{ width: "100%" }} />)}<Banner type="info" bordered closeIcon={null} description="不可关闭 · bordered" style={{ width: "100%" }} /></Space></Section>
          <FeedbackDemos />
          <Section name="Progress"><div style={{ display: "grid", gap: 12 }}><Progress percent={30} showInfo aria-label="30%" /><Progress percent={70} stroke="var(--semi-color-success)" size="large" showInfo aria-label="70%" /><Progress percent={100} showInfo aria-label="100%" /><Demo><Progress percent={64} type="circle" showInfo aria-label="64%" /><Progress percent={64} type="circle" size="small" aria-label="64%" /><Progress percent={40} type="circle" stroke="var(--semi-color-warning)" width={60} showInfo aria-label="40%" /></Demo></div></Section>
          <Section name="Skeleton"><Skeleton loading active placeholder={<div className="acme-row" style={{ alignItems: "flex-start" }}><Skeleton.Avatar /><div style={{ flex: 1 }}><Skeleton.Title style={{ width: "40%", marginBottom: 8 }} /><Skeleton.Paragraph rows={3} /></div></div>}><Text>加载完成</Text></Skeleton><Demo><Skeleton.Button /><Skeleton.Image style={{ width: 120, height: 80 }} /></Demo></Section>
          <Section name="Spinner"><Demo><Spin size="small" /><Spin /><Spin size="large" /><Spin tip="加载中..." size="large" style={{ width: 120, height: 80 }} /><Spin spinning><Card style={{ width: 200 }}>被覆盖的内容</Card></Spin></Demo></Section>
          <Section name="Result"><Card style={{ textAlign: "center" }} bodyStyle={{ padding: 32 }}><div style={{ color: "var(--semi-color-success)" }}><Icon name="circle-check" size={48} /></div><Title heading={4}>操作成功</Title><Text type="secondary">Semi 没有独立 Result 组件，此处由 Card + Icon + Typography 组合而成。</Text><div className="acme-row" style={{ justifyContent: "center", marginTop: 16 }}><Button theme="solid">返回</Button><Button>查看详情</Button></div></Card></Section>
          <Section name="Popconfirm"><Demo><Popconfirm title="确定删除？" content="此操作不可撤销。" okType="danger" onConfirm={() => { Toast.success("已删除") }}><Button type="danger" theme="light">删除</Button></Popconfirm><Popconfirm title="保存更改" content="将覆盖之前版本。" position="right"><Button>保存</Button></Popconfirm></Demo></Section>
          <Section name="Menu"><Demo><Dropdown trigger="click" render={<Dropdown.Menu><Dropdown.Title>分组</Dropdown.Title><Dropdown.Item icon={<Icon name="edit" />}>编辑</Dropdown.Item><Dropdown.Item icon={<Icon name="copy" />}>复制</Dropdown.Item><Dropdown.Item disabled>禁用项</Dropdown.Item><Dropdown.Divider /><Dropdown.Item type="danger" icon={<Icon name="trash" />}>删除</Dropdown.Item></Dropdown.Menu>}><Button theme="light">打开菜单 <Icon name="chevron-down" /></Button></Dropdown></Demo><Nav mode="horizontal" defaultSelectedKeys={["dashboard"]} items={nav.slice(0, 4).map((item) => ({ itemKey: item.key, text: item.label, icon: <Icon name={item.icon} /> }))} /></Section>
          <Section name="Dropdown"><Demo>{(["hover", "click"] as const).map((trigger) => <Dropdown key={trigger} trigger={trigger} position="bottomLeft" render={<Dropdown.Menu><Dropdown.Item>选项 1</Dropdown.Item><Dropdown.Item>选项 2</Dropdown.Item></Dropdown.Menu>}><Button>{trigger}</Button></Dropdown>)}<Dropdown trigger="click" render={<Dropdown.Menu><Dropdown.Item>普通</Dropdown.Item><Dropdown.Item type="primary">primary</Dropdown.Item><Dropdown.Item type="secondary">secondary</Dropdown.Item><Dropdown.Item type="warning">warning</Dropdown.Item><Dropdown.Item type="danger">danger</Dropdown.Item></Dropdown.Menu>}><Button theme="solid">类型</Button></Dropdown></Demo></Section>
          <Section name="Breadcrumb"><Breadcrumb><Breadcrumb.Item icon={<Icon name="home" />}>首页</Breadcrumb.Item><Breadcrumb.Item>订单</Breadcrumb.Item><Breadcrumb.Item>ORD-2401</Breadcrumb.Item></Breadcrumb><Breadcrumb separator=">" compact={false} style={{ marginTop: 8 }} routes={["工作区", "产品", "控制台", "设置", "计费"]} maxItemCount={3} /></Section>
          <Section name="Tabs"><Tabs type="line"><Tabs.TabPane tab="line" itemKey="1"><Text type="tertiary">line 内容</Text></Tabs.TabPane><Tabs.TabPane tab="第二个" itemKey="2" /><Tabs.TabPane tab="禁用" itemKey="3" disabled /></Tabs><Tabs type="card" style={{ marginTop: 12 }}><Tabs.TabPane tab="card" itemKey="1"><Text type="tertiary">card 内容</Text></Tabs.TabPane><Tabs.TabPane tab="可关闭" itemKey="2" closable /></Tabs><Tabs type="button" size="small" style={{ marginTop: 12 }}><Tabs.TabPane tab="button" itemKey="1" /><Tabs.TabPane tab="小号" itemKey="2" /></Tabs><Tabs tabPosition="left" style={{ marginTop: 12 }}><Tabs.TabPane tab="纵向" itemKey="1"><Text type="tertiary">tabPosition=left</Text></Tabs.TabPane><Tabs.TabPane tab="第二" itemKey="2" /></Tabs></Section>
          <Section name="Pagination"><div className="acme-scroll-x"><Space vertical align="start"><Pagination total={200} showSizeChanger showQuickJumper /><Pagination total={50} size="small" /><Pagination total={80} hoverShowPageSelect /><Pagination total={80} pageSize={10} disabled /></Space></div></Section>
          <Section name="Steps"><Space vertical align="start" style={{ width: "100%" }}><Steps current={1}><Steps.Step title="完成" description="已完成步骤" /><Steps.Step title="进行中" description="当前步骤" /><Steps.Step title="等待" description="后续步骤" /></Steps><Steps type="basic" current={1} status="error"><Steps.Step title="完成" /><Steps.Step title="出错" /><Steps.Step title="等待" /></Steps><Steps type="nav" current={2}><Steps.Step title="登录" /><Steps.Step title="填写" /><Steps.Step title="确认" /></Steps><Steps direction="vertical" current={1} size="small"><Steps.Step title="纵向" description="第一步" /><Steps.Step title="纵向" description="第二步" /></Steps></Space></Section>
          <Section name="Anchor"><Anchor style={{ maxWidth: 240 }} size="small"><Anchor.Link href="#c-Typography" title="Typography" /><Anchor.Link href="#c-Button" title="Button"><Anchor.Link href="#c-ButtonGroup" title="ButtonGroup" /></Anchor.Link><Anchor.Link href="#c-Table" title="Table" /></Anchor></Section>
          <Section name="BackTop"><Text type="secondary">页面滚动超过 400px 后右下角会出现返回顶部按钮。</Text><BackTop visibilityHeight={400} style={{ bottom: 88 }} /></Section>
          <Section name="Affix"><Text type="secondary">Semi 未提供 Affix 组件；本页左侧锚点索引与应用顶栏用 CSS position: sticky 组合实现吸附效果。</Text><div style={{ position: "sticky", top: 72, marginTop: 8 }}><Tag color="blue">sticky 示例</Tag></div></Section>
          <Section name="Navbar"><Nav mode="horizontal" header={{ logo: <span className="acme-brand-mark">A</span>, text: "Acme Console" }} footer={<div className="acme-row"><Button theme="borderless" type="tertiary" icon={<Icon name="bell" />} aria-label="通知" /><Avatar size="small" color="light-blue">林</Avatar></div>} items={[{ itemKey: "home", text: "首页" }, { itemKey: "docs", text: "文档" }, { itemKey: "pricing", text: "价格" }]} defaultSelectedKeys={["home"]} /></Section>
          <Section name="Sidebar"><div className="acme-scroll-x" style={{ border: "1px solid var(--semi-color-border)", borderRadius: 8 }}><Nav isCollapsed={collapsed} onCollapseChange={setCollapsed} defaultSelectedKeys={["dashboard"]} defaultOpenKeys={["ws"]} style={{ height: 320 }} header={{ logo: <span className="acme-brand-mark">A</span>, text: "Acme" }} footer={{ collapseButton: true }} items={[{ itemKey: "ws", text: "工作区", icon: <Icon name="grid" />, items: nav.slice(0, 3).map((item) => ({ itemKey: item.key, text: item.label, icon: <Icon name={item.icon} /> })) }, ...nav.slice(4).map((item) => ({ itemKey: item.key, text: item.label, icon: <Icon name={item.icon} /> }))]} /></div></Section>
          <Section name="CommandPalette"><Demo><Button theme="light" icon={<Icon name="search" />} onClick={() => Modal.info({ title: "命令面板", icon: null, footer: null, content: <div><Input prefix={<Icon name="search" />} placeholder="输入命令或搜索..." autoFocus /><List size="small" dataSource={nav} renderItem={(item) => <List.Item main={<span className="acme-row"><Icon name={item.icon} />{item.label}</span>} extra={<Text type="tertiary" code>{item.path}</Text>} />} /></div> })}>打开命令面板 <Text type="tertiary" code>⌘K</Text></Button></Demo></Section>
          <Section name="Grid"><Layout><div className="acme-grid" style={{ gridTemplateColumns: "repeat(12, minmax(0, 1fr))", gap: 8 }}>{[6, 6, 4, 4, 4, 3, 3, 3, 3].map((span, index) => <div key={index} className="acme-demo-box" style={{ gridColumn: `span ${span}`, padding: 8, textAlign: "center", background: "var(--semi-color-primary-light-default)", borderRadius: 4 }}><Text size="small">{span}</Text></div>)}</div></Layout><Text type="tertiary" size="small">Semi Row/Col 栅格在 375px 下按列堆叠，上例用 CSS Grid 展示等价 12 栏。</Text></Section>
          <Section name="Stack"><Space><Button>水平</Button><Button>Space</Button></Space><Divider margin={8} /><Space vertical align="start" spacing="tight"><Tag>垂直</Tag><Tag>Space</Tag></Space><Divider margin={8} /><Space wrap spacing="loose">{["紧凑", "宽松", "自动换行", "Space", "wrap"].map((item) => <Tag key={item} color="blue">{item}</Tag>)}</Space></Section>
          <Section name="Layout"><Layout style={{ border: "1px solid var(--semi-color-border)", borderRadius: 8, overflow: "hidden" }}><Layout.Header style={{ padding: 12, background: "var(--semi-color-fill-0)" }}>Header</Layout.Header><Layout><Layout.Sider className="acme-desktop-only" style={{ padding: 12, background: "var(--semi-color-fill-1)" }}>Sider</Layout.Sider><Layout.Content style={{ padding: 12, minHeight: 80 }}>Content</Layout.Content></Layout><Layout.Footer style={{ padding: 12, background: "var(--semi-color-fill-0)" }}>Footer</Layout.Footer></Layout></Section>
          <Section name="Container"><div className="acme-landing-inner" style={{ border: "1px dashed var(--semi-color-border)", padding: 12, borderRadius: 8, maxWidth: 640 }}><Text type="secondary">Semi 无 Container 组件；使用 max-width + margin auto 的居中容器（同落地页）。</Text></div></Section>
          <Section name="AspectRatio"><div className="acme-grid-3 acme-grid">{["16 / 9", "4 / 3", "1 / 1"].map((ratio) => <div key={ratio} style={{ aspectRatio: ratio, background: "var(--semi-color-fill-0)", borderRadius: 8, display: "grid", placeItems: "center" }}><Text type="tertiary">{ratio}</Text></div>)}</div></Section>
          <Section name="Resizable"><Resizable defaultSize={{ width: 260, height: 120 }} minWidth={160} maxWidth="100%" style={{ border: "1px solid var(--semi-color-border)", borderRadius: 8, padding: 12 }}><Text type="secondary">拖动右下角调整尺寸</Text></Resizable></Section>
          <Section name="ScrollArea"><div className="acme-row" style={{ alignItems: "flex-start" }}><div style={{ height: 140, width: 240, overflowY: "auto", border: "1px solid var(--semi-color-border)", borderRadius: 8, padding: 8 }}>{orders.map((order) => <div key={order.id} style={{ padding: "4px 0" }}><Text>{order.id} · {order.customer}</Text></div>)}</div><ScrollList header="ScrollList" style={{ width: 160 }}><ScrollItem mode="wheel" cycled list={["09", "10", "11", "12", "13"].map((value) => ({ value, text: `${value}:00` }))} selectedIndex={2} /></ScrollList></div></Section>
          <Section name="Accordion"><Collapse accordion defaultActiveKey="1"><Collapse.Panel header="什么是 Semi Design？" itemKey="1"><Text type="secondary">抖音前端团队维护的企业级设计系统。</Text></Collapse.Panel><Collapse.Panel header="支持暗色模式吗？" itemKey="2"><Text type="secondary">支持，通过 body[theme-mode=dark] 切换。</Text></Collapse.Panel><Collapse.Panel header="禁用面板" itemKey="3" disabled /></Collapse><Collapsible isOpen style={{ marginTop: 12 }}><Text type="tertiary" size="small">Collapsible：无样式的折叠容器。</Text></Collapsible></Section>
          <Section name="ThemeProvider"><Demo><ConfigProvider direction="rtl"><Button theme="solid" icon={<Icon name="arrow-right" />}>RTL 按钮</Button></ConfigProvider><Text type="secondary">ConfigProvider 提供 locale / direction / getPopupContainer；主题通过 body[theme-mode] + CSS 变量切换（见顶栏按钮）。</Text></Demo></Section>
          <Section name="Watermark" />
          <Section name="FloatButton"><Demo><FloatButton icon={<Icon name="plus" />} style={{ position: "static" }} aria-label="新增" /><FloatButton shape="square" colorful icon={<Icon name="message-circle" />} style={{ position: "static" }} aria-label="反馈" /><FloatButton size="small" icon={<Icon name="circle-help" />} badge={{ count: 3 }} style={{ position: "static" }} aria-label="帮助" /><FloatButtonGroup style={{ position: "static" }} shape="square" items={[{ value: "settings", icon: <Icon name="settings" />, content: "设置" }, { value: "bell", icon: <Icon name="bell" />, content: "通知" }]} /></Demo></Section>
          <Section name="Kbd"><Demo><Text code>⌘</Text><Text code>K</Text><Text type="tertiary">Semi 无 Kbd 组件，用 Typography code 样式组合。</Text><Space><Tag size="small" type="ghost" style={{ fontFamily: "monospace" }}>Ctrl</Tag><Tag size="small" type="ghost" style={{ fontFamily: "monospace" }}>Shift</Tag><Tag size="small" type="ghost" style={{ fontFamily: "monospace" }}>P</Tag></Space></Demo></Section>
          <Section name="Code"><Text code>const total = orders.reduce((sum, o) =&gt; sum + o.amount, 0)</Text><div style={{ marginTop: 8, overflowX: "auto" }}><CodeHighlight language="sql" code={"SELECT date_trunc('month', created_at) AS m, sum(amount)\nFROM orders WHERE status = 'paid'\nGROUP BY 1 ORDER BY 1 DESC LIMIT 2;"} /></div></Section>
          <Section name="Divider"><Text>上</Text><Divider /><Text>下</Text><Divider align="left">左对齐文字</Divider><Divider dashed>虚线</Divider><div className="acme-row"><Text>A</Text><Divider layout="vertical" /><Text>B</Text><Divider layout="vertical" /><Text>C</Text></div></Section>
          <Section name="Link"><Demo><Text link={{ href: "#c-Typography" }}>页内链接</Text><Text link underline>下划线</Text><Text link disabled>禁用</Text><Link to="/">React Router Link</Link><Text icon={<Icon name="link" />} link={{ href: "#c-Link" }}>带图标</Text></Demo></Section>
          <OverflowList items={contract.components.slice(0, 20).map((name) => ({ key: name }))} renderMode="collapse" visibleItemRenderer={(item) => <Tag key={String(item.key)} size="small">{String(item.key)}</Tag>} overflowRenderer={(items) => <Tag size="small" color="blue">+{items.length}</Tag>} />
        </div>
      </div>
    </div>
  )
}
