import type { ComponentType } from "react"
import { Icon as GalleryIcon } from "@ui-gallery/icons-react"
import {
  ActivityIcon,
  AddIcon,
  ApiIcon,
  AppIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  AttachIcon,
  BrowseIcon,
  BrowseOffIcon,
  CalendarIcon,
  CartIcon,
  ChartBarIcon,
  ChatIcon,
  ChatBubbleIcon,
  CheckIcon,
  CheckCircleIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CloseIcon,
  CopyIcon,
  DashboardIcon,
  DeleteIcon,
  DownloadIcon,
  EditIcon,
  EllipsisIcon,
  ErrorCircleIcon,
  FileAddIcon,
  FilterIcon,
  HeartIcon,
  HelpCircleIcon,
  HomeIcon,
  InternetIcon,
  LayersIcon,
  LinkIcon,
  LoadingIcon,
  LockOnIcon,
  LoginIcon,
  LogoGithubIcon,
  LogoutIcon,
  MenuIcon,
  MicrophoneIcon,
  MoonIcon,
  PlayIcon,
  MoreIcon,
  NotificationIcon,
  RefreshIcon,
  RemoveIcon,
  RobotIcon,
  RocketIcon,
  SearchIcon,
  SecuredIcon,
  SendIcon,
  SettingIcon,
  StarIcon,
  SunnyIcon,
  TagIcon,
  TimeIcon,
  UploadIcon,
  UserIcon,
  UsergroupIcon,
  ViewListIcon,
  ViewModuleIcon,
} from "tdesign-icons-react"

export type IconFamily = "native" | "lucide" | "tabler" | "phosphor" | "heroicons"

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyIcon = ComponentType<any>

const native: Record<string, AnyIcon> = {
  activity: ActivityIcon,
  "alert-circle": ErrorCircleIcon,
  archive: LayersIcon,
  "arrow-down": ArrowDownIcon,
  "arrow-left": ArrowLeftIcon,
  "arrow-right": ArrowRightIcon,
  "arrow-up": ArrowUpIcon,
  "bar-chart": ChartBarIcon,
  bell: NotificationIcon,
  bot: RobotIcon,
  boxes: AppIcon,
  calendar: CalendarIcon,
  check: CheckIcon,
  "check-circle": CheckCircleIcon,
  "chevron-down": ChevronDownIcon,
  "chevron-left": ChevronLeftIcon,
  "chevron-right": ChevronRightIcon,
  "chevron-up": ChevronUpIcon,
  "circle-help": HelpCircleIcon,
  clipboard: CopyIcon,
  clock: TimeIcon,
  copy: CopyIcon,
  download: DownloadIcon,
  edit: EditIcon,
  "ellipsis-horizontal": EllipsisIcon,
  eye: BrowseIcon,
  "eye-off": BrowseOffIcon,
  "file-plus": FileAddIcon,
  filter: FilterIcon,
  github: LogoGithubIcon,
  globe: InternetIcon,
  grid: ViewModuleIcon,
  heart: HeartIcon,
  home: HomeIcon,
  "layout-dashboard": DashboardIcon,
  link: LinkIcon,
  list: ViewListIcon,
  loader: LoadingIcon,
  lock: LockOnIcon,
  "log-in": LoginIcon,
  "log-out": LogoutIcon,
  menu: MenuIcon,
  "message-circle": ChatBubbleIcon,
  "message-square": ChatIcon,
  mic: MicrophoneIcon,
  minus: RemoveIcon,
  "more-horizontal": MoreIcon,
  moon: MoonIcon,
  paperclip: AttachIcon,
  pencil: EditIcon,
  play: PlayIcon,
  plus: AddIcon,
  plug: ApiIcon,
  refresh: RefreshIcon,
  search: SearchIcon,
  send: SendIcon,
  settings: SettingIcon,
  shield: SecuredIcon,
  "shopping-cart": CartIcon,
  sliders: FilterIcon,
  sparkles: RocketIcon,
  star: StarIcon,
  sun: SunnyIcon,
  tag: TagIcon,
  trash: DeleteIcon,
  upload: UploadIcon,
  user: UserIcon,
  users: UsergroupIcon,
  x: CloseIcon,
  zap: RocketIcon,
}

export function iconFamily(): IconFamily {
  const value = new URLSearchParams(window.location.search).get("icons")
  return value === "lucide" || value === "tabler" || value === "phosphor" || value === "heroicons" ? value : "native"
}

export function Icon({ name, size = 16, className }: { name: string; size?: number; className?: string }) {
  if (iconFamily() !== "native") return <GalleryIcon name={name} size={size} className={className} />
  const Component = native[name] ?? HelpCircleIcon
  return <Component size={size} className={className} aria-hidden="true" />
}
