export type CoverageStatus = "implemented" | "composed" | "missing"

const implemented = [
  "Typography",
  "Button",
  "ButtonGroup",
  "IconButton",
  "Input",
  "Textarea",
  "NumberInput",
  "Select",
  "Checkbox",
  "Radio",
  "Switch",
  "Slider",
  "DatePicker",
  "DateRangePicker",
  "PinInput",
  "Table",
  "Card",
  "Avatar",
  "AvatarGroup",
  "Badge",
  "Tag",
  "Calendar",
  "Carousel",
  "Empty",
  "Tooltip",
  "Popover",
  "Segmented",
  "Alert",
  "Toast",
  "Notification",
  "Dialog",
  "Drawer",
  "Progress",
  "Skeleton",
  "Spinner",
  "Menu",
  "Dropdown",
  "Breadcrumb",
  "Tabs",
  "Pagination",
  "Navbar",
  "Sidebar",
  "CommandPalette",
  "AspectRatio",
  "Resizable",
  "ScrollArea",
  "Accordion",
  "ThemeProvider",
  "Kbd",
  "Divider",
  "Link",
]
const composed = [
  "MultiSelect",
  "Combobox",
  "Autocomplete",
  "Rating",
  "TimePicker",
  "Upload",
  "Cascader",
  "Form",
  "DataGrid",
  "Descriptions",
  "List",
  "Statistic",
  "Timeline",
  "Image",
  "Result",
  "Popconfirm",
  "Steps",
  "Anchor",
  "BackTop",
  "Grid",
  "Stack",
  "Layout",
  "Container",
  "FloatButton",
  "Code",
]
const missing = [
  "ColorPicker",
  "Transfer",
  "Mention",
  "Tree",
  "QRCode",
  "Affix",
  "Watermark",
  "Tour",
]
export const coverage: Record<string, CoverageStatus> = Object.fromEntries([
  ...implemented.map((name) => [name, "implemented"]),
  ...composed.map((name) => [name, "composed"]),
  ...missing.map((name) => [name, "missing"]),
]) as Record<string, CoverageStatus>
