import { Link } from "react-router-dom"
import { Icon } from "@ui-gallery/icons-react"
import landing from "@ui-gallery/spec/mock/landing.json"
import plans from "@ui-gallery/spec/mock/plans.json"
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion"
import { AspectRatio } from "@/components/ui/aspect-ratio"
import { Avatar, AvatarFallback } from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Carousel, CarouselContent, CarouselItem, CarouselNext, CarouselPrevious } from "@/components/ui/carousel"
import { NavigationMenu, NavigationMenuItem, NavigationMenuLink, NavigationMenuList } from "@/components/ui/navigation-menu"
import { Separator } from "@/components/ui/separator"

export function LandingPage() {
  return (
    <div className="min-h-svh">
      <header className="border-b"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-4 py-4 sm:px-6"><Link className="flex items-center gap-2 font-semibold no-underline" to="/"><span className="grid size-8 place-items-center rounded-lg bg-primary text-primary-foreground">A</span>Acme Console</Link><NavigationMenu className="hidden md:flex"><NavigationMenuList><NavigationMenuItem><NavigationMenuLink href="#features">产品</NavigationMenuLink></NavigationMenuItem><NavigationMenuItem><NavigationMenuLink href="#pricing">价格</NavigationMenuLink></NavigationMenuItem><NavigationMenuItem><NavigationMenuLink href="#faq">FAQ</NavigationMenuLink></NavigationMenuItem></NavigationMenuList></NavigationMenu><div className="flex items-center gap-2"><Button variant="ghost" asChild><Link to="/login">登录</Link></Button><Button asChild><Link to="/login">开始使用</Link></Button></div></div></header>
      <main>
        <section className="mx-auto grid max-w-7xl gap-12 px-4 py-20 sm:px-6 lg:grid-cols-2 lg:items-center lg:py-32"><div className="space-y-6"><Badge variant="secondary">ACME CONSOLE · 2026</Badge><h1 className="max-w-3xl text-5xl font-semibold tracking-tight sm:text-7xl">{landing.hero.title}</h1><p className="max-w-xl text-lg text-muted-foreground">{landing.hero.subtitle}</p><div className="flex flex-wrap gap-3"><Button size="lg" asChild><Link to="/login">{landing.hero.primary}<Icon name="arrow-right" /></Link></Button><Button size="lg" variant="outline">{landing.hero.secondary}</Button></div><div className="flex items-center gap-3 text-sm text-muted-foreground"><div className="flex -space-x-2">{["林", "王", "A", "M"].map((name) => <Avatar className="size-8 border-2 border-background" key={name}><AvatarFallback>{name}</AvatarFallback></Avatar>)}</div>{landing.hero.social}</div></div><Card><CardContent className="p-3"><AspectRatio ratio={1.1} className="rounded-lg bg-muted p-4"><div className="grid h-full grid-cols-[100px_1fr] gap-4"><div className="rounded-lg bg-border" /><div className="grid gap-4"><div className="rounded-lg bg-card shadow-sm" /><div className="grid grid-cols-3 gap-3"><div className="rounded-lg bg-card" /><div className="rounded-lg bg-card" /><div className="rounded-lg bg-card" /></div></div></div></AspectRatio></CardContent></Card></section>
        <section className="border-y bg-muted/30 px-4 py-8"><div className="mx-auto grid max-w-6xl grid-cols-2 gap-6 text-center text-sm font-medium text-muted-foreground sm:grid-cols-6">{["Northwind", "Contoso", "Globex", "Fabrikam", "Initech", "Umbrella"].map((name) => <span key={name}>{name}</span>)}</div></section>
        <section id="features" className="mx-auto max-w-7xl space-y-10 px-4 py-20 sm:px-6"><div className="mx-auto max-w-2xl space-y-3 text-center"><p className="text-sm text-muted-foreground">为团队打造</p><h2 className="text-3xl font-semibold">一个地方，完成所有工作</h2><p className="text-muted-foreground">从数据到决策，让每一步都更清晰。</p></div><div className="grid gap-4 md:grid-cols-3">{landing.features.map((item) => <Card key={item.title}><CardHeader><div className="mb-2 grid size-10 place-items-center rounded-lg bg-muted"><Icon name={item.icon} /></div><CardTitle>{item.title}</CardTitle></CardHeader><CardContent className="text-sm text-muted-foreground">{item.desc}</CardContent></Card>)}</div></section>
        <section className="mx-auto max-w-6xl space-y-12 px-4 py-10 sm:px-6">{["看见全局", "自动化协作", "AI 就在身边"].map((title, index) => <div className="grid items-center gap-8 md:grid-cols-2" key={title}><div className={index % 2 ? "md:order-2" : ""}><Badge variant="outline">0{index + 1} / WORKSPACE</Badge><h2 className="mt-4 text-3xl font-semibold">{title}</h2><p className="mt-3 text-muted-foreground">把分散的信息汇聚为有用的洞察，让团队快速行动并持续交付。</p><Button variant="link" className="mt-3 px-0">了解更多<Icon name="arrow-right" /></Button></div><Card className={index % 2 ? "md:order-1" : ""}><CardContent className="p-3"><AspectRatio ratio={1.5} className="grid place-items-center rounded-lg bg-muted"><Icon name={landing.features[index + 1].icon} size={52} /></AspectRatio></CardContent></Card></div>)}</section>
        <section className="border-y py-10"><div className="mx-auto grid max-w-6xl grid-cols-2 gap-6 px-4 text-center sm:grid-cols-4">{landing.numbers.map((item) => <div key={item.label}><p className="text-3xl font-semibold">{item.value}</p><p className="text-sm text-muted-foreground">{item.label}</p></div>)}</div></section>
        <section id="pricing" className="mx-auto max-w-7xl space-y-10 px-4 py-20 sm:px-6"><div className="text-center"><h2 className="text-3xl font-semibold">选择适合你的方案</h2><p className="mt-2 text-muted-foreground">简单透明，随时升级。</p></div><div className="grid gap-4 md:grid-cols-3">{plans.map((plan) => <Card key={plan.name} className={plan.recommended ? "border-primary" : ""}><CardHeader><div className="flex items-center justify-between"><CardTitle>{plan.name}</CardTitle>{plan.recommended ? <Badge>最受欢迎</Badge> : null}</div><p className="text-3xl font-semibold">{plan.price === null ? "定制" : plan.price === 0 ? "免费" : `¥${plan.price}`}<span className="text-sm font-normal text-muted-foreground">{plan.price ? " / 月" : ""}</span></p></CardHeader><CardContent className="space-y-4"><p className="text-sm text-muted-foreground">{plan.features.join(" · ")}</p><Button className="w-full" variant={plan.recommended ? "default" : "outline"}>开始使用</Button></CardContent></Card>)}</div></section>
        <section className="mx-auto max-w-5xl space-y-8 px-4 py-12 sm:px-6"><div className="text-center"><h2 className="text-3xl font-semibold">他们已经在改变工作方式</h2></div><Carousel className="mx-auto max-w-full overflow-hidden" opts={{ loop: true }}><CarouselContent>{landing.testimonials.map((item) => <CarouselItem className="md:basis-1/2" key={item.name}><Card><CardContent className="space-y-4 p-6"><p className="text-lg">“{item.quote}”</p><div className="flex items-center gap-3"><Avatar><AvatarFallback>{item.name.slice(0, 1)}</AvatarFallback></Avatar><div><p className="font-medium">{item.name}</p><p className="text-sm text-muted-foreground">{item.company}</p></div></div></CardContent></Card></CarouselItem>)}</CarouselContent><CarouselPrevious /><CarouselNext /></Carousel></section>
        <section id="faq" className="mx-auto max-w-3xl space-y-6 px-4 py-20 sm:px-6"><h2 className="text-center text-3xl font-semibold">常见问题</h2><Accordion type="single" collapsible>{landing.faq.map((item) => <AccordionItem value={item.q} key={item.q}><AccordionTrigger>{item.q}</AccordionTrigger><AccordionContent>{item.a}</AccordionContent></AccordionItem>)}</Accordion></section>
        <Separator /><section className="mx-4 my-12 rounded-2xl bg-primary px-6 py-16 text-center text-primary-foreground sm:mx-auto sm:max-w-6xl"><h2 className="text-3xl font-semibold">准备好让团队更高效了吗？</h2><p className="mt-3 opacity-80">从今天开始，把工作放进一个控制台。</p><Button className="mt-6" variant="secondary" size="lg" asChild><Link to="/login">免费开始<Icon name="arrow-right" /></Link></Button></section>
      </main>
      <footer className="border-t"><div className="mx-auto flex max-w-7xl flex-col gap-3 px-4 py-8 text-sm text-muted-foreground sm:flex-row sm:items-center sm:justify-between sm:px-6"><span>© 2026 Acme Console</span><div className="flex gap-4"><a href="#features">产品</a><a href="#pricing">价格</a><a href="#faq">帮助中心</a></div></div></footer>
    </div>
  )
}
