// Generated by scripts/gen-icons.mjs — do not edit by hand.
import bootstrap_activity from "bootstrap-icons/icons/activity.svg?raw"
import lucide_activity from "lucide-static/icons/activity.svg?raw"
import tabler_activity from "@tabler/icons/outline/activity.svg?raw"
import phosphor_activity from "@phosphor-icons/core/assets/regular/pulse.svg?raw"
import heroicons_activity from "heroicons/24/outline/chart-bar.svg?raw"
import bootstrap_alert_circle from "bootstrap-icons/icons/exclamation-circle.svg?raw"
import lucide_alert_circle from "lucide-static/icons/circle-alert.svg?raw"
import tabler_alert_circle from "@tabler/icons/outline/alert-circle.svg?raw"
import phosphor_alert_circle from "@phosphor-icons/core/assets/regular/warning-circle.svg?raw"
import heroicons_alert_circle from "heroicons/24/outline/exclamation-circle.svg?raw"
import bootstrap_archive from "bootstrap-icons/icons/archive.svg?raw"
import lucide_archive from "lucide-static/icons/archive.svg?raw"
import tabler_archive from "@tabler/icons/outline/archive.svg?raw"
import phosphor_archive from "@phosphor-icons/core/assets/regular/archive.svg?raw"
import heroicons_archive from "heroicons/24/outline/archive-box.svg?raw"
import bootstrap_arrow_down from "bootstrap-icons/icons/arrow-down.svg?raw"
import lucide_arrow_down from "lucide-static/icons/arrow-down.svg?raw"
import tabler_arrow_down from "@tabler/icons/outline/arrow-down.svg?raw"
import phosphor_arrow_down from "@phosphor-icons/core/assets/regular/arrow-down.svg?raw"
import heroicons_arrow_down from "heroicons/24/outline/arrow-down.svg?raw"
import bootstrap_arrow_left from "bootstrap-icons/icons/arrow-left.svg?raw"
import lucide_arrow_left from "lucide-static/icons/arrow-left.svg?raw"
import tabler_arrow_left from "@tabler/icons/outline/arrow-left.svg?raw"
import phosphor_arrow_left from "@phosphor-icons/core/assets/regular/arrow-left.svg?raw"
import heroicons_arrow_left from "heroicons/24/outline/arrow-left.svg?raw"
import bootstrap_arrow_right from "bootstrap-icons/icons/arrow-right.svg?raw"
import lucide_arrow_right from "lucide-static/icons/arrow-right.svg?raw"
import tabler_arrow_right from "@tabler/icons/outline/arrow-right.svg?raw"
import phosphor_arrow_right from "@phosphor-icons/core/assets/regular/arrow-right.svg?raw"
import heroicons_arrow_right from "heroicons/24/outline/arrow-right.svg?raw"
import bootstrap_arrow_up from "bootstrap-icons/icons/arrow-up.svg?raw"
import lucide_arrow_up from "lucide-static/icons/arrow-up.svg?raw"
import tabler_arrow_up from "@tabler/icons/outline/arrow-up.svg?raw"
import phosphor_arrow_up from "@phosphor-icons/core/assets/regular/arrow-up.svg?raw"
import heroicons_arrow_up from "heroicons/24/outline/arrow-up.svg?raw"
import bootstrap_bar_chart from "bootstrap-icons/icons/bar-chart.svg?raw"
import lucide_bar_chart from "lucide-static/icons/chart-column.svg?raw"
import tabler_bar_chart from "@tabler/icons/outline/chart-bar.svg?raw"
import phosphor_bar_chart from "@phosphor-icons/core/assets/regular/chart-bar.svg?raw"
import heroicons_bar_chart from "heroicons/24/outline/chart-bar.svg?raw"
import bootstrap_bell from "bootstrap-icons/icons/bell.svg?raw"
import lucide_bell from "lucide-static/icons/bell.svg?raw"
import tabler_bell from "@tabler/icons/outline/bell.svg?raw"
import phosphor_bell from "@phosphor-icons/core/assets/regular/bell.svg?raw"
import heroicons_bell from "heroicons/24/outline/bell.svg?raw"
import bootstrap_bot from "bootstrap-icons/icons/robot.svg?raw"
import lucide_bot from "lucide-static/icons/bot.svg?raw"
import tabler_bot from "@tabler/icons/outline/robot.svg?raw"
import phosphor_bot from "@phosphor-icons/core/assets/regular/robot.svg?raw"
import heroicons_bot from "heroicons/24/outline/cpu-chip.svg?raw"
import bootstrap_boxes from "bootstrap-icons/icons/boxes.svg?raw"
import lucide_boxes from "lucide-static/icons/boxes.svg?raw"
import tabler_boxes from "@tabler/icons/outline/box.svg?raw"
import phosphor_boxes from "@phosphor-icons/core/assets/regular/cube.svg?raw"
import heroicons_boxes from "heroicons/24/outline/rectangle-group.svg?raw"
import bootstrap_calendar from "bootstrap-icons/icons/calendar3.svg?raw"
import lucide_calendar from "lucide-static/icons/calendar-days.svg?raw"
import tabler_calendar from "@tabler/icons/outline/calendar.svg?raw"
import phosphor_calendar from "@phosphor-icons/core/assets/regular/calendar.svg?raw"
import heroicons_calendar from "heroicons/24/outline/calendar-days.svg?raw"
import bootstrap_check from "bootstrap-icons/icons/check-lg.svg?raw"
import lucide_check from "lucide-static/icons/check.svg?raw"
import tabler_check from "@tabler/icons/outline/check.svg?raw"
import phosphor_check from "@phosphor-icons/core/assets/regular/check.svg?raw"
import heroicons_check from "heroicons/24/outline/check.svg?raw"
import bootstrap_check_circle from "bootstrap-icons/icons/check-circle.svg?raw"
import lucide_check_circle from "lucide-static/icons/circle-check.svg?raw"
import tabler_check_circle from "@tabler/icons/outline/circle-check.svg?raw"
import phosphor_check_circle from "@phosphor-icons/core/assets/regular/check-circle.svg?raw"
import heroicons_check_circle from "heroicons/24/outline/check-circle.svg?raw"
import bootstrap_chevron_down from "bootstrap-icons/icons/chevron-down.svg?raw"
import lucide_chevron_down from "lucide-static/icons/chevron-down.svg?raw"
import tabler_chevron_down from "@tabler/icons/outline/chevron-down.svg?raw"
import phosphor_chevron_down from "@phosphor-icons/core/assets/regular/caret-down.svg?raw"
import heroicons_chevron_down from "heroicons/24/outline/chevron-down.svg?raw"
import bootstrap_chevron_left from "bootstrap-icons/icons/chevron-left.svg?raw"
import lucide_chevron_left from "lucide-static/icons/chevron-left.svg?raw"
import tabler_chevron_left from "@tabler/icons/outline/chevron-left.svg?raw"
import phosphor_chevron_left from "@phosphor-icons/core/assets/regular/caret-left.svg?raw"
import heroicons_chevron_left from "heroicons/24/outline/chevron-left.svg?raw"
import bootstrap_chevron_right from "bootstrap-icons/icons/chevron-right.svg?raw"
import lucide_chevron_right from "lucide-static/icons/chevron-right.svg?raw"
import tabler_chevron_right from "@tabler/icons/outline/chevron-right.svg?raw"
import phosphor_chevron_right from "@phosphor-icons/core/assets/regular/caret-right.svg?raw"
import heroicons_chevron_right from "heroicons/24/outline/chevron-right.svg?raw"
import bootstrap_chevron_up from "bootstrap-icons/icons/chevron-up.svg?raw"
import lucide_chevron_up from "lucide-static/icons/chevron-up.svg?raw"
import tabler_chevron_up from "@tabler/icons/outline/chevron-up.svg?raw"
import phosphor_chevron_up from "@phosphor-icons/core/assets/regular/caret-up.svg?raw"
import heroicons_chevron_up from "heroicons/24/outline/chevron-up.svg?raw"
import bootstrap_circle_help from "bootstrap-icons/icons/question-circle.svg?raw"
import lucide_circle_help from "lucide-static/icons/circle-question-mark.svg?raw"
import tabler_circle_help from "@tabler/icons/outline/help-circle.svg?raw"
import phosphor_circle_help from "@phosphor-icons/core/assets/regular/question.svg?raw"
import heroicons_circle_help from "heroicons/24/outline/question-mark-circle.svg?raw"
import bootstrap_clipboard from "bootstrap-icons/icons/clipboard.svg?raw"
import lucide_clipboard from "lucide-static/icons/clipboard.svg?raw"
import tabler_clipboard from "@tabler/icons/outline/clipboard.svg?raw"
import phosphor_clipboard from "@phosphor-icons/core/assets/regular/clipboard.svg?raw"
import heroicons_clipboard from "heroicons/24/outline/clipboard.svg?raw"
import bootstrap_clock from "bootstrap-icons/icons/clock.svg?raw"
import lucide_clock from "lucide-static/icons/clock-3.svg?raw"
import tabler_clock from "@tabler/icons/outline/clock.svg?raw"
import phosphor_clock from "@phosphor-icons/core/assets/regular/clock.svg?raw"
import heroicons_clock from "heroicons/24/outline/clock.svg?raw"
import bootstrap_copy from "bootstrap-icons/icons/copy.svg?raw"
import lucide_copy from "lucide-static/icons/copy.svg?raw"
import tabler_copy from "@tabler/icons/outline/copy.svg?raw"
import phosphor_copy from "@phosphor-icons/core/assets/regular/copy.svg?raw"
import heroicons_copy from "heroicons/24/outline/document-duplicate.svg?raw"
import bootstrap_credit_card from "bootstrap-icons/icons/credit-card.svg?raw"
import lucide_credit_card from "lucide-static/icons/credit-card.svg?raw"
import tabler_credit_card from "@tabler/icons/outline/credit-card.svg?raw"
import phosphor_credit_card from "@phosphor-icons/core/assets/regular/credit-card.svg?raw"
import heroicons_credit_card from "heroicons/24/outline/credit-card.svg?raw"
import bootstrap_download from "bootstrap-icons/icons/download.svg?raw"
import lucide_download from "lucide-static/icons/download.svg?raw"
import tabler_download from "@tabler/icons/outline/download.svg?raw"
import phosphor_download from "@phosphor-icons/core/assets/regular/download-simple.svg?raw"
import heroicons_download from "heroicons/24/outline/arrow-down-tray.svg?raw"
import bootstrap_edit from "bootstrap-icons/icons/pencil-square.svg?raw"
import lucide_edit from "lucide-static/icons/square-pen.svg?raw"
import tabler_edit from "@tabler/icons/outline/edit.svg?raw"
import phosphor_edit from "@phosphor-icons/core/assets/regular/pencil-simple-line.svg?raw"
import heroicons_edit from "heroicons/24/outline/pencil-square.svg?raw"
import bootstrap_eye from "bootstrap-icons/icons/eye.svg?raw"
import lucide_eye from "lucide-static/icons/eye.svg?raw"
import tabler_eye from "@tabler/icons/outline/eye.svg?raw"
import phosphor_eye from "@phosphor-icons/core/assets/regular/eye.svg?raw"
import heroicons_eye from "heroicons/24/outline/eye.svg?raw"
import bootstrap_eye_off from "bootstrap-icons/icons/eye-slash.svg?raw"
import lucide_eye_off from "lucide-static/icons/eye-off.svg?raw"
import tabler_eye_off from "@tabler/icons/outline/eye-off.svg?raw"
import phosphor_eye_off from "@phosphor-icons/core/assets/regular/eye-slash.svg?raw"
import heroicons_eye_off from "heroicons/24/outline/eye-slash.svg?raw"
import bootstrap_file_plus from "bootstrap-icons/icons/file-earmark-plus.svg?raw"
import lucide_file_plus from "lucide-static/icons/file-plus.svg?raw"
import tabler_file_plus from "@tabler/icons/outline/file-plus.svg?raw"
import phosphor_file_plus from "@phosphor-icons/core/assets/regular/file-plus.svg?raw"
import heroicons_file_plus from "heroicons/24/outline/document-plus.svg?raw"
import bootstrap_filter from "bootstrap-icons/icons/funnel.svg?raw"
import lucide_filter from "lucide-static/icons/funnel.svg?raw"
import tabler_filter from "@tabler/icons/outline/filter.svg?raw"
import phosphor_filter from "@phosphor-icons/core/assets/regular/funnel.svg?raw"
import heroicons_filter from "heroicons/24/outline/funnel.svg?raw"
import bootstrap_github from "bootstrap-icons/icons/github.svg?raw"
import lucide_github from "lucide-static/icons/code-xml.svg?raw"
import tabler_github from "@tabler/icons/outline/brand-github.svg?raw"
import phosphor_github from "@phosphor-icons/core/assets/regular/github-logo.svg?raw"
import heroicons_github from "heroicons/24/outline/code-bracket.svg?raw"
import bootstrap_globe from "bootstrap-icons/icons/globe.svg?raw"
import lucide_globe from "lucide-static/icons/globe.svg?raw"
import tabler_globe from "@tabler/icons/outline/world.svg?raw"
import phosphor_globe from "@phosphor-icons/core/assets/regular/globe.svg?raw"
import heroicons_globe from "heroicons/24/outline/globe-alt.svg?raw"
import bootstrap_google from "bootstrap-icons/icons/google.svg?raw"
import lucide_google from "lucide-static/icons/at-sign.svg?raw"
import tabler_google from "@tabler/icons/outline/brand-google.svg?raw"
import phosphor_google from "@phosphor-icons/core/assets/regular/google-logo.svg?raw"
import heroicons_google from "heroicons/24/outline/at-symbol.svg?raw"
import bootstrap_grid from "bootstrap-icons/icons/grid.svg?raw"
import lucide_grid from "lucide-static/icons/grid-2x2.svg?raw"
import tabler_grid from "@tabler/icons/outline/layout-grid.svg?raw"
import phosphor_grid from "@phosphor-icons/core/assets/regular/grid-four.svg?raw"
import heroicons_grid from "heroicons/24/outline/squares-2x2.svg?raw"
import bootstrap_heart from "bootstrap-icons/icons/heart.svg?raw"
import lucide_heart from "lucide-static/icons/heart.svg?raw"
import tabler_heart from "@tabler/icons/outline/heart.svg?raw"
import phosphor_heart from "@phosphor-icons/core/assets/regular/heart.svg?raw"
import heroicons_heart from "heroicons/24/outline/heart.svg?raw"
import bootstrap_home from "bootstrap-icons/icons/house.svg?raw"
import lucide_home from "lucide-static/icons/house.svg?raw"
import tabler_home from "@tabler/icons/outline/home.svg?raw"
import phosphor_home from "@phosphor-icons/core/assets/regular/house.svg?raw"
import heroicons_home from "heroicons/24/outline/home.svg?raw"
import bootstrap_inbox from "bootstrap-icons/icons/inbox.svg?raw"
import lucide_inbox from "lucide-static/icons/inbox.svg?raw"
import tabler_inbox from "@tabler/icons/outline/inbox.svg?raw"
import phosphor_inbox from "@phosphor-icons/core/assets/regular/tray.svg?raw"
import heroicons_inbox from "heroicons/24/outline/inbox.svg?raw"
import bootstrap_layout_dashboard from "bootstrap-icons/icons/speedometer2.svg?raw"
import lucide_layout_dashboard from "lucide-static/icons/layout-dashboard.svg?raw"
import tabler_layout_dashboard from "@tabler/icons/outline/layout-dashboard.svg?raw"
import phosphor_layout_dashboard from "@phosphor-icons/core/assets/regular/squares-four.svg?raw"
import heroicons_layout_dashboard from "heroicons/24/outline/squares-2x2.svg?raw"
import bootstrap_link from "bootstrap-icons/icons/link-45deg.svg?raw"
import lucide_link from "lucide-static/icons/link-2.svg?raw"
import tabler_link from "@tabler/icons/outline/link.svg?raw"
import phosphor_link from "@phosphor-icons/core/assets/regular/link.svg?raw"
import heroicons_link from "heroicons/24/outline/link.svg?raw"
import bootstrap_list from "bootstrap-icons/icons/list-ul.svg?raw"
import lucide_list from "lucide-static/icons/list.svg?raw"
import tabler_list from "@tabler/icons/outline/list.svg?raw"
import phosphor_list from "@phosphor-icons/core/assets/regular/list.svg?raw"
import heroicons_list from "heroicons/24/outline/list-bullet.svg?raw"
import bootstrap_loader from "bootstrap-icons/icons/arrow-repeat.svg?raw"
import lucide_loader from "lucide-static/icons/loader-circle.svg?raw"
import tabler_loader from "@tabler/icons/outline/loader-2.svg?raw"
import phosphor_loader from "@phosphor-icons/core/assets/regular/circle-notch.svg?raw"
import heroicons_loader from "heroicons/24/outline/arrow-path.svg?raw"
import bootstrap_lock from "bootstrap-icons/icons/lock.svg?raw"
import lucide_lock from "lucide-static/icons/lock.svg?raw"
import tabler_lock from "@tabler/icons/outline/lock.svg?raw"
import phosphor_lock from "@phosphor-icons/core/assets/regular/lock.svg?raw"
import heroicons_lock from "heroicons/24/outline/lock-closed.svg?raw"
import bootstrap_log_in from "bootstrap-icons/icons/box-arrow-in-right.svg?raw"
import lucide_log_in from "lucide-static/icons/log-in.svg?raw"
import tabler_log_in from "@tabler/icons/outline/login.svg?raw"
import phosphor_log_in from "@phosphor-icons/core/assets/regular/sign-in.svg?raw"
import heroicons_log_in from "heroicons/24/outline/arrow-right-on-rectangle.svg?raw"
import bootstrap_log_out from "bootstrap-icons/icons/box-arrow-right.svg?raw"
import lucide_log_out from "lucide-static/icons/log-out.svg?raw"
import tabler_log_out from "@tabler/icons/outline/logout.svg?raw"
import phosphor_log_out from "@phosphor-icons/core/assets/regular/sign-out.svg?raw"
import heroicons_log_out from "heroicons/24/outline/arrow-left-on-rectangle.svg?raw"
import bootstrap_mail from "bootstrap-icons/icons/envelope.svg?raw"
import lucide_mail from "lucide-static/icons/mail.svg?raw"
import tabler_mail from "@tabler/icons/outline/mail.svg?raw"
import phosphor_mail from "@phosphor-icons/core/assets/regular/envelope-simple.svg?raw"
import heroicons_mail from "heroicons/24/outline/envelope.svg?raw"
import bootstrap_menu from "bootstrap-icons/icons/list.svg?raw"
import lucide_menu from "lucide-static/icons/menu.svg?raw"
import tabler_menu from "@tabler/icons/outline/menu-2.svg?raw"
import phosphor_menu from "@phosphor-icons/core/assets/regular/list.svg?raw"
import heroicons_menu from "heroicons/24/outline/bars-3.svg?raw"
import bootstrap_message_circle from "bootstrap-icons/icons/chat.svg?raw"
import lucide_message_circle from "lucide-static/icons/message-circle.svg?raw"
import tabler_message_circle from "@tabler/icons/outline/message-circle.svg?raw"
import phosphor_message_circle from "@phosphor-icons/core/assets/regular/chat-circle.svg?raw"
import heroicons_message_circle from "heroicons/24/outline/chat-bubble-oval-left.svg?raw"
import bootstrap_message_square from "bootstrap-icons/icons/chat-square-text.svg?raw"
import lucide_message_square from "lucide-static/icons/message-square.svg?raw"
import tabler_message_square from "@tabler/icons/outline/message.svg?raw"
import phosphor_message_square from "@phosphor-icons/core/assets/regular/chat-text.svg?raw"
import heroicons_message_square from "heroicons/24/outline/chat-bubble-left.svg?raw"
import bootstrap_mic from "bootstrap-icons/icons/mic.svg?raw"
import lucide_mic from "lucide-static/icons/mic.svg?raw"
import tabler_mic from "@tabler/icons/outline/microphone.svg?raw"
import phosphor_mic from "@phosphor-icons/core/assets/regular/microphone.svg?raw"
import heroicons_mic from "heroicons/24/outline/microphone.svg?raw"
import bootstrap_minus from "bootstrap-icons/icons/dash-lg.svg?raw"
import lucide_minus from "lucide-static/icons/minus.svg?raw"
import tabler_minus from "@tabler/icons/outline/minus.svg?raw"
import phosphor_minus from "@phosphor-icons/core/assets/regular/minus.svg?raw"
import heroicons_minus from "heroicons/24/outline/minus.svg?raw"
import bootstrap_moon from "bootstrap-icons/icons/moon-stars.svg?raw"
import lucide_moon from "lucide-static/icons/moon.svg?raw"
import tabler_moon from "@tabler/icons/outline/moon.svg?raw"
import phosphor_moon from "@phosphor-icons/core/assets/regular/moon.svg?raw"
import heroicons_moon from "heroicons/24/outline/moon.svg?raw"
import bootstrap_more_horizontal from "bootstrap-icons/icons/three-dots.svg?raw"
import lucide_more_horizontal from "lucide-static/icons/ellipsis.svg?raw"
import tabler_more_horizontal from "@tabler/icons/outline/dots.svg?raw"
import phosphor_more_horizontal from "@phosphor-icons/core/assets/regular/dots-three.svg?raw"
import heroicons_more_horizontal from "heroicons/24/outline/ellipsis-horizontal.svg?raw"
import bootstrap_paperclip from "bootstrap-icons/icons/paperclip.svg?raw"
import lucide_paperclip from "lucide-static/icons/paperclip.svg?raw"
import tabler_paperclip from "@tabler/icons/outline/paperclip.svg?raw"
import phosphor_paperclip from "@phosphor-icons/core/assets/regular/paperclip.svg?raw"
import heroicons_paperclip from "heroicons/24/outline/paper-clip.svg?raw"
import bootstrap_pencil from "bootstrap-icons/icons/pencil.svg?raw"
import lucide_pencil from "lucide-static/icons/pencil.svg?raw"
import tabler_pencil from "@tabler/icons/outline/pencil.svg?raw"
import phosphor_pencil from "@phosphor-icons/core/assets/regular/pencil.svg?raw"
import heroicons_pencil from "heroicons/24/outline/pencil.svg?raw"
import bootstrap_play from "bootstrap-icons/icons/play.svg?raw"
import lucide_play from "lucide-static/icons/play.svg?raw"
import tabler_play from "@tabler/icons/outline/player-play.svg?raw"
import phosphor_play from "@phosphor-icons/core/assets/regular/play.svg?raw"
import heroicons_play from "heroicons/24/outline/play.svg?raw"
import bootstrap_plug from "bootstrap-icons/icons/plug.svg?raw"
import lucide_plug from "lucide-static/icons/plug.svg?raw"
import tabler_plug from "@tabler/icons/outline/plug.svg?raw"
import phosphor_plug from "@phosphor-icons/core/assets/regular/plugs.svg?raw"
import heroicons_plug from "heroicons/24/outline/bolt.svg?raw"
import bootstrap_plus from "bootstrap-icons/icons/plus-lg.svg?raw"
import lucide_plus from "lucide-static/icons/plus.svg?raw"
import tabler_plus from "@tabler/icons/outline/plus.svg?raw"
import phosphor_plus from "@phosphor-icons/core/assets/regular/plus.svg?raw"
import heroicons_plus from "heroicons/24/outline/plus.svg?raw"
import bootstrap_refresh from "bootstrap-icons/icons/arrow-clockwise.svg?raw"
import lucide_refresh from "lucide-static/icons/refresh-cw.svg?raw"
import tabler_refresh from "@tabler/icons/outline/refresh.svg?raw"
import phosphor_refresh from "@phosphor-icons/core/assets/regular/arrows-clockwise.svg?raw"
import heroicons_refresh from "heroicons/24/outline/arrow-path.svg?raw"
import bootstrap_search from "bootstrap-icons/icons/search.svg?raw"
import lucide_search from "lucide-static/icons/search.svg?raw"
import tabler_search from "@tabler/icons/outline/search.svg?raw"
import phosphor_search from "@phosphor-icons/core/assets/regular/magnifying-glass.svg?raw"
import heroicons_search from "heroicons/24/outline/magnifying-glass.svg?raw"
import bootstrap_send from "bootstrap-icons/icons/send.svg?raw"
import lucide_send from "lucide-static/icons/send.svg?raw"
import tabler_send from "@tabler/icons/outline/send.svg?raw"
import phosphor_send from "@phosphor-icons/core/assets/regular/paper-plane-tilt.svg?raw"
import heroicons_send from "heroicons/24/outline/paper-airplane.svg?raw"
import bootstrap_settings from "bootstrap-icons/icons/gear.svg?raw"
import lucide_settings from "lucide-static/icons/settings.svg?raw"
import tabler_settings from "@tabler/icons/outline/settings.svg?raw"
import phosphor_settings from "@phosphor-icons/core/assets/regular/gear.svg?raw"
import heroicons_settings from "heroicons/24/outline/cog-6-tooth.svg?raw"
import bootstrap_shield from "bootstrap-icons/icons/shield-check.svg?raw"
import lucide_shield from "lucide-static/icons/shield.svg?raw"
import tabler_shield from "@tabler/icons/outline/shield.svg?raw"
import phosphor_shield from "@phosphor-icons/core/assets/regular/shield.svg?raw"
import heroicons_shield from "heroicons/24/outline/shield-check.svg?raw"
import bootstrap_shopping_cart from "bootstrap-icons/icons/cart.svg?raw"
import lucide_shopping_cart from "lucide-static/icons/shopping-cart.svg?raw"
import tabler_shopping_cart from "@tabler/icons/outline/shopping-cart.svg?raw"
import phosphor_shopping_cart from "@phosphor-icons/core/assets/regular/shopping-cart.svg?raw"
import heroicons_shopping_cart from "heroicons/24/outline/shopping-cart.svg?raw"
import bootstrap_sliders from "bootstrap-icons/icons/sliders.svg?raw"
import lucide_sliders from "lucide-static/icons/sliders-horizontal.svg?raw"
import tabler_sliders from "@tabler/icons/outline/adjustments-horizontal.svg?raw"
import phosphor_sliders from "@phosphor-icons/core/assets/regular/sliders-horizontal.svg?raw"
import heroicons_sliders from "heroicons/24/outline/adjustments-horizontal.svg?raw"
import bootstrap_sparkles from "bootstrap-icons/icons/stars.svg?raw"
import lucide_sparkles from "lucide-static/icons/sparkles.svg?raw"
import tabler_sparkles from "@tabler/icons/outline/sparkles.svg?raw"
import phosphor_sparkles from "@phosphor-icons/core/assets/regular/sparkle.svg?raw"
import heroicons_sparkles from "heroicons/24/outline/sparkles.svg?raw"
import bootstrap_star from "bootstrap-icons/icons/star.svg?raw"
import lucide_star from "lucide-static/icons/star.svg?raw"
import tabler_star from "@tabler/icons/outline/star.svg?raw"
import phosphor_star from "@phosphor-icons/core/assets/regular/star.svg?raw"
import heroicons_star from "heroicons/24/outline/star.svg?raw"
import bootstrap_star_fill from "bootstrap-icons/icons/star-fill.svg?raw"
import lucide_star_fill from "lucide-static/icons/star.svg?raw"
import tabler_star_fill from "@tabler/icons/outline/star.svg?raw"
import phosphor_star_fill from "@phosphor-icons/core/assets/regular/star.svg?raw"
import heroicons_star_fill from "heroicons/24/outline/star.svg?raw"
import bootstrap_sun from "bootstrap-icons/icons/sun.svg?raw"
import lucide_sun from "lucide-static/icons/sun.svg?raw"
import tabler_sun from "@tabler/icons/outline/sun.svg?raw"
import phosphor_sun from "@phosphor-icons/core/assets/regular/sun.svg?raw"
import heroicons_sun from "heroicons/24/outline/sun.svg?raw"
import bootstrap_tag from "bootstrap-icons/icons/tag.svg?raw"
import lucide_tag from "lucide-static/icons/tag.svg?raw"
import tabler_tag from "@tabler/icons/outline/tag.svg?raw"
import phosphor_tag from "@phosphor-icons/core/assets/regular/tag.svg?raw"
import heroicons_tag from "heroicons/24/outline/tag.svg?raw"
import bootstrap_trash from "bootstrap-icons/icons/trash.svg?raw"
import lucide_trash from "lucide-static/icons/trash-2.svg?raw"
import tabler_trash from "@tabler/icons/outline/trash.svg?raw"
import phosphor_trash from "@phosphor-icons/core/assets/regular/trash.svg?raw"
import heroicons_trash from "heroicons/24/outline/trash.svg?raw"
import bootstrap_upload from "bootstrap-icons/icons/cloud-upload.svg?raw"
import lucide_upload from "lucide-static/icons/upload.svg?raw"
import tabler_upload from "@tabler/icons/outline/upload.svg?raw"
import phosphor_upload from "@phosphor-icons/core/assets/regular/upload-simple.svg?raw"
import heroicons_upload from "heroicons/24/outline/cloud-arrow-up.svg?raw"
import bootstrap_user from "bootstrap-icons/icons/person.svg?raw"
import lucide_user from "lucide-static/icons/user.svg?raw"
import tabler_user from "@tabler/icons/outline/user.svg?raw"
import phosphor_user from "@phosphor-icons/core/assets/regular/user.svg?raw"
import heroicons_user from "heroicons/24/outline/user.svg?raw"
import bootstrap_users from "bootstrap-icons/icons/people.svg?raw"
import lucide_users from "lucide-static/icons/users.svg?raw"
import tabler_users from "@tabler/icons/outline/users.svg?raw"
import phosphor_users from "@phosphor-icons/core/assets/regular/users.svg?raw"
import heroicons_users from "heroicons/24/outline/user-group.svg?raw"
import bootstrap_wechat from "bootstrap-icons/icons/wechat.svg?raw"
import lucide_wechat from "lucide-static/icons/message-circle.svg?raw"
import tabler_wechat from "@tabler/icons/outline/brand-wechat.svg?raw"
import phosphor_wechat from "@phosphor-icons/core/assets/regular/wechat-logo.svg?raw"
import heroicons_wechat from "heroicons/24/outline/chat-bubble-left-right.svg?raw"
import bootstrap_x from "bootstrap-icons/icons/x-lg.svg?raw"
import lucide_x from "lucide-static/icons/x.svg?raw"
import tabler_x from "@tabler/icons/outline/x.svg?raw"
import phosphor_x from "@phosphor-icons/core/assets/regular/x.svg?raw"
import heroicons_x from "heroicons/24/outline/x-mark.svg?raw"
import bootstrap_zap from "bootstrap-icons/icons/lightning-charge.svg?raw"
import lucide_zap from "lucide-static/icons/zap.svg?raw"
import tabler_zap from "@tabler/icons/outline/bolt.svg?raw"
import phosphor_zap from "@phosphor-icons/core/assets/regular/lightning.svg?raw"
import heroicons_zap from "heroicons/24/outline/bolt.svg?raw"

export type IconName = "activity" | "alert-circle" | "archive" | "arrow-down" | "arrow-left" | "arrow-right" | "arrow-up" | "bar-chart" | "bell" | "bot" | "boxes" | "calendar" | "check" | "check-circle" | "chevron-down" | "chevron-left" | "chevron-right" | "chevron-up" | "circle-help" | "clipboard" | "clock" | "copy" | "credit-card" | "download" | "edit" | "eye" | "eye-off" | "file-plus" | "filter" | "github" | "globe" | "google" | "grid" | "heart" | "home" | "inbox" | "layout-dashboard" | "link" | "list" | "loader" | "lock" | "log-in" | "log-out" | "mail" | "menu" | "message-circle" | "message-square" | "mic" | "minus" | "moon" | "more-horizontal" | "paperclip" | "pencil" | "play" | "plug" | "plus" | "refresh" | "search" | "send" | "settings" | "shield" | "shopping-cart" | "sliders" | "sparkles" | "star" | "star-fill" | "sun" | "tag" | "trash" | "upload" | "user" | "users" | "wechat" | "x" | "zap"
export type IconFamily = "bootstrap" | "lucide" | "tabler" | "phosphor" | "heroicons"
export const iconMap: Record<IconFamily, Record<IconName, string>> = {
  bootstrap: {
  "activity": bootstrap_activity,
  "alert-circle": bootstrap_alert_circle,
  "archive": bootstrap_archive,
  "arrow-down": bootstrap_arrow_down,
  "arrow-left": bootstrap_arrow_left,
  "arrow-right": bootstrap_arrow_right,
  "arrow-up": bootstrap_arrow_up,
  "bar-chart": bootstrap_bar_chart,
  "bell": bootstrap_bell,
  "bot": bootstrap_bot,
  "boxes": bootstrap_boxes,
  "calendar": bootstrap_calendar,
  "check": bootstrap_check,
  "check-circle": bootstrap_check_circle,
  "chevron-down": bootstrap_chevron_down,
  "chevron-left": bootstrap_chevron_left,
  "chevron-right": bootstrap_chevron_right,
  "chevron-up": bootstrap_chevron_up,
  "circle-help": bootstrap_circle_help,
  "clipboard": bootstrap_clipboard,
  "clock": bootstrap_clock,
  "copy": bootstrap_copy,
  "credit-card": bootstrap_credit_card,
  "download": bootstrap_download,
  "edit": bootstrap_edit,
  "eye": bootstrap_eye,
  "eye-off": bootstrap_eye_off,
  "file-plus": bootstrap_file_plus,
  "filter": bootstrap_filter,
  "github": bootstrap_github,
  "globe": bootstrap_globe,
  "google": bootstrap_google,
  "grid": bootstrap_grid,
  "heart": bootstrap_heart,
  "home": bootstrap_home,
  "inbox": bootstrap_inbox,
  "layout-dashboard": bootstrap_layout_dashboard,
  "link": bootstrap_link,
  "list": bootstrap_list,
  "loader": bootstrap_loader,
  "lock": bootstrap_lock,
  "log-in": bootstrap_log_in,
  "log-out": bootstrap_log_out,
  "mail": bootstrap_mail,
  "menu": bootstrap_menu,
  "message-circle": bootstrap_message_circle,
  "message-square": bootstrap_message_square,
  "mic": bootstrap_mic,
  "minus": bootstrap_minus,
  "moon": bootstrap_moon,
  "more-horizontal": bootstrap_more_horizontal,
  "paperclip": bootstrap_paperclip,
  "pencil": bootstrap_pencil,
  "play": bootstrap_play,
  "plug": bootstrap_plug,
  "plus": bootstrap_plus,
  "refresh": bootstrap_refresh,
  "search": bootstrap_search,
  "send": bootstrap_send,
  "settings": bootstrap_settings,
  "shield": bootstrap_shield,
  "shopping-cart": bootstrap_shopping_cart,
  "sliders": bootstrap_sliders,
  "sparkles": bootstrap_sparkles,
  "star": bootstrap_star,
  "star-fill": bootstrap_star_fill,
  "sun": bootstrap_sun,
  "tag": bootstrap_tag,
  "trash": bootstrap_trash,
  "upload": bootstrap_upload,
  "user": bootstrap_user,
  "users": bootstrap_users,
  "wechat": bootstrap_wechat,
  "x": bootstrap_x,
  "zap": bootstrap_zap,
  },
  lucide: {
  "activity": lucide_activity,
  "alert-circle": lucide_alert_circle,
  "archive": lucide_archive,
  "arrow-down": lucide_arrow_down,
  "arrow-left": lucide_arrow_left,
  "arrow-right": lucide_arrow_right,
  "arrow-up": lucide_arrow_up,
  "bar-chart": lucide_bar_chart,
  "bell": lucide_bell,
  "bot": lucide_bot,
  "boxes": lucide_boxes,
  "calendar": lucide_calendar,
  "check": lucide_check,
  "check-circle": lucide_check_circle,
  "chevron-down": lucide_chevron_down,
  "chevron-left": lucide_chevron_left,
  "chevron-right": lucide_chevron_right,
  "chevron-up": lucide_chevron_up,
  "circle-help": lucide_circle_help,
  "clipboard": lucide_clipboard,
  "clock": lucide_clock,
  "copy": lucide_copy,
  "credit-card": lucide_credit_card,
  "download": lucide_download,
  "edit": lucide_edit,
  "eye": lucide_eye,
  "eye-off": lucide_eye_off,
  "file-plus": lucide_file_plus,
  "filter": lucide_filter,
  "github": lucide_github,
  "globe": lucide_globe,
  "google": lucide_google,
  "grid": lucide_grid,
  "heart": lucide_heart,
  "home": lucide_home,
  "inbox": lucide_inbox,
  "layout-dashboard": lucide_layout_dashboard,
  "link": lucide_link,
  "list": lucide_list,
  "loader": lucide_loader,
  "lock": lucide_lock,
  "log-in": lucide_log_in,
  "log-out": lucide_log_out,
  "mail": lucide_mail,
  "menu": lucide_menu,
  "message-circle": lucide_message_circle,
  "message-square": lucide_message_square,
  "mic": lucide_mic,
  "minus": lucide_minus,
  "moon": lucide_moon,
  "more-horizontal": lucide_more_horizontal,
  "paperclip": lucide_paperclip,
  "pencil": lucide_pencil,
  "play": lucide_play,
  "plug": lucide_plug,
  "plus": lucide_plus,
  "refresh": lucide_refresh,
  "search": lucide_search,
  "send": lucide_send,
  "settings": lucide_settings,
  "shield": lucide_shield,
  "shopping-cart": lucide_shopping_cart,
  "sliders": lucide_sliders,
  "sparkles": lucide_sparkles,
  "star": lucide_star,
  "star-fill": lucide_star_fill,
  "sun": lucide_sun,
  "tag": lucide_tag,
  "trash": lucide_trash,
  "upload": lucide_upload,
  "user": lucide_user,
  "users": lucide_users,
  "wechat": lucide_wechat,
  "x": lucide_x,
  "zap": lucide_zap,
  },
  tabler: {
  "activity": tabler_activity,
  "alert-circle": tabler_alert_circle,
  "archive": tabler_archive,
  "arrow-down": tabler_arrow_down,
  "arrow-left": tabler_arrow_left,
  "arrow-right": tabler_arrow_right,
  "arrow-up": tabler_arrow_up,
  "bar-chart": tabler_bar_chart,
  "bell": tabler_bell,
  "bot": tabler_bot,
  "boxes": tabler_boxes,
  "calendar": tabler_calendar,
  "check": tabler_check,
  "check-circle": tabler_check_circle,
  "chevron-down": tabler_chevron_down,
  "chevron-left": tabler_chevron_left,
  "chevron-right": tabler_chevron_right,
  "chevron-up": tabler_chevron_up,
  "circle-help": tabler_circle_help,
  "clipboard": tabler_clipboard,
  "clock": tabler_clock,
  "copy": tabler_copy,
  "credit-card": tabler_credit_card,
  "download": tabler_download,
  "edit": tabler_edit,
  "eye": tabler_eye,
  "eye-off": tabler_eye_off,
  "file-plus": tabler_file_plus,
  "filter": tabler_filter,
  "github": tabler_github,
  "globe": tabler_globe,
  "google": tabler_google,
  "grid": tabler_grid,
  "heart": tabler_heart,
  "home": tabler_home,
  "inbox": tabler_inbox,
  "layout-dashboard": tabler_layout_dashboard,
  "link": tabler_link,
  "list": tabler_list,
  "loader": tabler_loader,
  "lock": tabler_lock,
  "log-in": tabler_log_in,
  "log-out": tabler_log_out,
  "mail": tabler_mail,
  "menu": tabler_menu,
  "message-circle": tabler_message_circle,
  "message-square": tabler_message_square,
  "mic": tabler_mic,
  "minus": tabler_minus,
  "moon": tabler_moon,
  "more-horizontal": tabler_more_horizontal,
  "paperclip": tabler_paperclip,
  "pencil": tabler_pencil,
  "play": tabler_play,
  "plug": tabler_plug,
  "plus": tabler_plus,
  "refresh": tabler_refresh,
  "search": tabler_search,
  "send": tabler_send,
  "settings": tabler_settings,
  "shield": tabler_shield,
  "shopping-cart": tabler_shopping_cart,
  "sliders": tabler_sliders,
  "sparkles": tabler_sparkles,
  "star": tabler_star,
  "star-fill": tabler_star_fill,
  "sun": tabler_sun,
  "tag": tabler_tag,
  "trash": tabler_trash,
  "upload": tabler_upload,
  "user": tabler_user,
  "users": tabler_users,
  "wechat": tabler_wechat,
  "x": tabler_x,
  "zap": tabler_zap,
  },
  phosphor: {
  "activity": phosphor_activity,
  "alert-circle": phosphor_alert_circle,
  "archive": phosphor_archive,
  "arrow-down": phosphor_arrow_down,
  "arrow-left": phosphor_arrow_left,
  "arrow-right": phosphor_arrow_right,
  "arrow-up": phosphor_arrow_up,
  "bar-chart": phosphor_bar_chart,
  "bell": phosphor_bell,
  "bot": phosphor_bot,
  "boxes": phosphor_boxes,
  "calendar": phosphor_calendar,
  "check": phosphor_check,
  "check-circle": phosphor_check_circle,
  "chevron-down": phosphor_chevron_down,
  "chevron-left": phosphor_chevron_left,
  "chevron-right": phosphor_chevron_right,
  "chevron-up": phosphor_chevron_up,
  "circle-help": phosphor_circle_help,
  "clipboard": phosphor_clipboard,
  "clock": phosphor_clock,
  "copy": phosphor_copy,
  "credit-card": phosphor_credit_card,
  "download": phosphor_download,
  "edit": phosphor_edit,
  "eye": phosphor_eye,
  "eye-off": phosphor_eye_off,
  "file-plus": phosphor_file_plus,
  "filter": phosphor_filter,
  "github": phosphor_github,
  "globe": phosphor_globe,
  "google": phosphor_google,
  "grid": phosphor_grid,
  "heart": phosphor_heart,
  "home": phosphor_home,
  "inbox": phosphor_inbox,
  "layout-dashboard": phosphor_layout_dashboard,
  "link": phosphor_link,
  "list": phosphor_list,
  "loader": phosphor_loader,
  "lock": phosphor_lock,
  "log-in": phosphor_log_in,
  "log-out": phosphor_log_out,
  "mail": phosphor_mail,
  "menu": phosphor_menu,
  "message-circle": phosphor_message_circle,
  "message-square": phosphor_message_square,
  "mic": phosphor_mic,
  "minus": phosphor_minus,
  "moon": phosphor_moon,
  "more-horizontal": phosphor_more_horizontal,
  "paperclip": phosphor_paperclip,
  "pencil": phosphor_pencil,
  "play": phosphor_play,
  "plug": phosphor_plug,
  "plus": phosphor_plus,
  "refresh": phosphor_refresh,
  "search": phosphor_search,
  "send": phosphor_send,
  "settings": phosphor_settings,
  "shield": phosphor_shield,
  "shopping-cart": phosphor_shopping_cart,
  "sliders": phosphor_sliders,
  "sparkles": phosphor_sparkles,
  "star": phosphor_star,
  "star-fill": phosphor_star_fill,
  "sun": phosphor_sun,
  "tag": phosphor_tag,
  "trash": phosphor_trash,
  "upload": phosphor_upload,
  "user": phosphor_user,
  "users": phosphor_users,
  "wechat": phosphor_wechat,
  "x": phosphor_x,
  "zap": phosphor_zap,
  },
  heroicons: {
  "activity": heroicons_activity,
  "alert-circle": heroicons_alert_circle,
  "archive": heroicons_archive,
  "arrow-down": heroicons_arrow_down,
  "arrow-left": heroicons_arrow_left,
  "arrow-right": heroicons_arrow_right,
  "arrow-up": heroicons_arrow_up,
  "bar-chart": heroicons_bar_chart,
  "bell": heroicons_bell,
  "bot": heroicons_bot,
  "boxes": heroicons_boxes,
  "calendar": heroicons_calendar,
  "check": heroicons_check,
  "check-circle": heroicons_check_circle,
  "chevron-down": heroicons_chevron_down,
  "chevron-left": heroicons_chevron_left,
  "chevron-right": heroicons_chevron_right,
  "chevron-up": heroicons_chevron_up,
  "circle-help": heroicons_circle_help,
  "clipboard": heroicons_clipboard,
  "clock": heroicons_clock,
  "copy": heroicons_copy,
  "credit-card": heroicons_credit_card,
  "download": heroicons_download,
  "edit": heroicons_edit,
  "eye": heroicons_eye,
  "eye-off": heroicons_eye_off,
  "file-plus": heroicons_file_plus,
  "filter": heroicons_filter,
  "github": heroicons_github,
  "globe": heroicons_globe,
  "google": heroicons_google,
  "grid": heroicons_grid,
  "heart": heroicons_heart,
  "home": heroicons_home,
  "inbox": heroicons_inbox,
  "layout-dashboard": heroicons_layout_dashboard,
  "link": heroicons_link,
  "list": heroicons_list,
  "loader": heroicons_loader,
  "lock": heroicons_lock,
  "log-in": heroicons_log_in,
  "log-out": heroicons_log_out,
  "mail": heroicons_mail,
  "menu": heroicons_menu,
  "message-circle": heroicons_message_circle,
  "message-square": heroicons_message_square,
  "mic": heroicons_mic,
  "minus": heroicons_minus,
  "moon": heroicons_moon,
  "more-horizontal": heroicons_more_horizontal,
  "paperclip": heroicons_paperclip,
  "pencil": heroicons_pencil,
  "play": heroicons_play,
  "plug": heroicons_plug,
  "plus": heroicons_plus,
  "refresh": heroicons_refresh,
  "search": heroicons_search,
  "send": heroicons_send,
  "settings": heroicons_settings,
  "shield": heroicons_shield,
  "shopping-cart": heroicons_shopping_cart,
  "sliders": heroicons_sliders,
  "sparkles": heroicons_sparkles,
  "star": heroicons_star,
  "star-fill": heroicons_star_fill,
  "sun": heroicons_sun,
  "tag": heroicons_tag,
  "trash": heroicons_trash,
  "upload": heroicons_upload,
  "user": heroicons_user,
  "users": heroicons_users,
  "wechat": heroicons_wechat,
  "x": heroicons_x,
  "zap": heroicons_zap,
  },
}
