<script setup lang="ts">
import landing from '@ui-gallery/spec/mock/landing.json'
import plans from '@ui-gallery/spec/mock/plans.json'
import { RouterLink } from 'vue-router'
import Icon from '@/components/Icon.vue'
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion'
import { AspectRatio } from '@/components/ui/aspect-ratio'
import { Avatar, AvatarFallback } from '@/components/ui/avatar'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Separator } from '@/components/ui/separator'

</script>

<template>
  <div class="min-h-svh">
    <header class="border-b"><div class="mx-auto flex max-w-7xl items-center justify-between gap-4 px-4 py-4 sm:px-6"><RouterLink class="flex items-center gap-2 font-semibold no-underline" to="/"><span class="grid size-8 place-items-center rounded-lg bg-primary text-primary-foreground">A</span>Acme Console</RouterLink><nav class="hidden items-center gap-6 text-sm md:flex"><a href="#features">产品</a><a href="#pricing">价格</a><a href="#faq">FAQ</a></nav><div class="flex items-center gap-2"><Button variant="ghost" as-child><RouterLink to="/login">登录</RouterLink></Button><Button as-child><RouterLink to="/login">开始使用</RouterLink></Button></div></div></header>
    <main>
      <section class="mx-auto grid max-w-7xl gap-12 px-4 py-20 sm:px-6 lg:grid-cols-2 lg:items-center lg:py-32"><div class="space-y-6"><Badge variant="secondary">ACME CONSOLE · 2026</Badge><h1 class="max-w-3xl text-5xl font-semibold tracking-tight sm:text-7xl">{{ landing.hero.title }}</h1><p class="max-w-xl text-lg text-muted-foreground">{{ landing.hero.subtitle }}</p><div class="flex flex-wrap gap-3"><Button size="lg" as-child><RouterLink to="/login">{{ landing.hero.primary }}<Icon name="arrow-right" /></RouterLink></Button><Button size="lg" variant="outline">{{ landing.hero.secondary }}</Button></div><div class="flex items-center gap-3 text-sm text-muted-foreground"><div class="flex -space-x-2"><Avatar v-for="name in ['林', '王', 'A', 'M']" :key="name" class="size-8 border-2 border-background"><AvatarFallback>{{ name }}</AvatarFallback></Avatar></div>{{ landing.hero.social }}</div></div><Card><CardContent class="p-3"><AspectRatio :ratio="1.1" class="rounded-lg bg-muted p-4"><div class="grid h-full grid-cols-[100px_1fr] gap-4"><div class="rounded-lg bg-border" /><div class="grid gap-4"><div class="rounded-lg bg-card shadow-sm" /><div class="grid grid-cols-3 gap-3"><div v-for="n in 3" :key="n" class="rounded-lg bg-card" /></div></div></div></AspectRatio></CardContent></Card></section>
      <section class="border-y py-10"><div class="mx-auto grid max-w-6xl grid-cols-2 gap-6 px-4 text-center sm:grid-cols-4"><div v-for="item in landing.numbers" :key="item.label"><p class="text-3xl font-semibold">{{ item.value }}</p><p class="text-sm text-muted-foreground">{{ item.label }}</p></div></div></section>
      <section id="features" class="mx-auto max-w-7xl space-y-10 px-4 py-20 sm:px-6"><div class="mx-auto max-w-2xl space-y-3 text-center"><p class="text-sm text-muted-foreground">为团队打造</p><h2 class="text-3xl font-semibold">一个地方，完成所有工作</h2><p class="text-muted-foreground">从数据到决策，让每一步都更清晰。</p></div><div class="grid gap-4 md:grid-cols-3"><Card v-for="item in landing.features" :key="item.title"><CardHeader><div class="mb-2 grid size-10 place-items-center rounded-lg bg-muted"><Icon :name="item.icon" /></div><CardTitle>{{ item.title }}</CardTitle></CardHeader><CardContent class="text-sm text-muted-foreground">{{ item.desc }}</CardContent></Card></div></section>
      <section class="mx-auto max-w-6xl space-y-12 px-4 py-10 sm:px-6"><div v-for="(title, index) in ['看见全局', '自动化协作', 'AI 就在身边']" :key="title" class="grid items-center gap-8 md:grid-cols-2"><div :class="index % 2 ? 'md:order-2' : ''"><Badge variant="outline">0{{ index + 1 }} / WORKSPACE</Badge><h2 class="mt-4 text-3xl font-semibold">{{ title }}</h2><p class="mt-3 text-muted-foreground">把分散的信息汇聚为有用的洞察，让团队快速行动并持续交付。</p><Button variant="link" class="mt-3 px-0">了解更多<Icon name="arrow-right" /></Button></div><Card :class="index % 2 ? 'md:order-1' : ''"><CardContent class="p-3"><AspectRatio :ratio="1.5" class="grid place-items-center rounded-lg bg-muted"><Icon :name="landing.features[index + 1]?.icon ?? 'sparkles'" :size="52" /></AspectRatio></CardContent></Card></div></section>
      <section id="pricing" class="mx-auto max-w-7xl space-y-10 px-4 py-20 sm:px-6"><div class="text-center"><h2 class="text-3xl font-semibold">选择适合你的方案</h2><p class="mt-2 text-muted-foreground">简单透明，随时升级。</p></div><div class="grid gap-4 md:grid-cols-3"><Card v-for="plan in plans" :key="plan.name" :class="plan.recommended ? 'border-primary' : ''"><CardHeader><div class="flex items-center justify-between"><CardTitle>{{ plan.name }}</CardTitle><Badge v-if="plan.recommended">最受欢迎</Badge></div><p class="text-3xl font-semibold">{{ plan.price === null ? '定制' : plan.price === 0 ? '免费' : `¥${plan.price}` }}<span v-if="plan.price" class="text-sm font-normal text-muted-foreground"> / 月</span></p></CardHeader><CardContent class="space-y-4"><p class="text-sm text-muted-foreground">{{ plan.features.join(' · ') }}</p><Button class="w-full" :variant="plan.recommended ? 'default' : 'outline'">开始使用</Button></CardContent></Card></div></section>
      <section class="mx-auto max-w-5xl space-y-8 px-4 py-12 sm:px-6"><h2 class="text-center text-3xl font-semibold">他们已经在改变工作方式</h2><div class="grid gap-4 md:grid-cols-2"><Card v-for="item in landing.testimonials" :key="item.name"><CardContent class="space-y-4 p-6"><p class="text-lg">“{{ item.quote }}”</p><div class="flex items-center gap-3"><Avatar><AvatarFallback>{{ item.name.slice(0, 1) }}</AvatarFallback></Avatar><div><p class="font-medium">{{ item.name }}</p><p class="text-sm text-muted-foreground">{{ item.company }}</p></div></div></CardContent></Card></div></section>
      <section id="faq" class="mx-auto max-w-3xl space-y-6 px-4 py-20 sm:px-6"><h2 class="text-center text-3xl font-semibold">常见问题</h2><Accordion type="single" collapsible><AccordionItem v-for="item in landing.faq" :key="item.q" :value="item.q"><AccordionTrigger>{{ item.q }}</AccordionTrigger><AccordionContent>{{ item.a }}</AccordionContent></AccordionItem></Accordion></section>
      <Separator /><section class="mx-4 my-12 rounded-2xl bg-primary px-6 py-16 text-center text-primary-foreground sm:mx-auto sm:max-w-6xl"><h2 class="text-3xl font-semibold">准备好让团队更高效了吗？</h2><p class="mt-3 opacity-80">从今天开始，把工作放进一个控制台。</p><Button class="mt-6" variant="secondary" size="lg" as-child><RouterLink to="/login">免费开始<Icon name="arrow-right" /></RouterLink></Button></section>
    </main>
    <footer class="border-t"><div class="mx-auto flex max-w-7xl flex-col gap-3 px-4 py-8 text-sm text-muted-foreground sm:flex-row sm:items-center sm:justify-between sm:px-6"><span>© 2026 Acme Console</span><div class="flex gap-4"><a href="#features">产品</a><a href="#pricing">价格</a><a href="#faq">帮助中心</a></div></div></footer>
  </div>
</template>
