<script setup lang="ts">
import { computed, ref } from 'vue'
import { useMediaQuery } from '@vueuse/core'
import sessions from '@ui-gallery/spec/mock/sessions.json'
import team from '@ui-gallery/spec/mock/team.json'
import plans from '@ui-gallery/spec/mock/plans.json'
import invoices from '@ui-gallery/spec/mock/invoices.json'
import Icon from '@/components/Icon.vue'
import PageHeader from '@/components/PageHeader.vue'
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from '@/components/ui/alert-dialog'
import { Avatar, AvatarFallback } from '@/components/ui/avatar'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Separator } from '@/components/ui/separator'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Switch } from '@/components/ui/switch'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'

const tab = ref('profile')
const isDesktop = useMediaQuery('(min-width: 1024px)')
const confirmation = ref('')
const inviteEmail = ref('')
const inviteSent = ref(false)
const teamRoles = ref<Record<string, string>>(Object.fromEntries(team.map((member) => [member.email, member.role])))
const canDelete = computed(() => confirmation.value === 'DELETE')
function invite() {
  inviteSent.value = !!inviteEmail.value.trim()
}
</script>

<template>
  <div class="space-y-6">
    <PageHeader title="设置" description="管理你的账户、团队与订阅设置。" />
    <Tabs v-model="tab" :orientation="isDesktop ? 'vertical' : 'horizontal'" class="gap-6 lg:grid lg:grid-cols-[200px_minmax(0,1fr)]">
      <TabsList class="w-full flex-wrap lg:h-auto lg:w-full lg:flex-col lg:items-stretch"><TabsTrigger value="profile" class="min-h-10 lg:justify-start">个人资料</TabsTrigger><TabsTrigger value="security" class="min-h-10 lg:justify-start">账号安全</TabsTrigger><TabsTrigger value="notifications" class="min-h-10 lg:justify-start">通知</TabsTrigger><TabsTrigger value="team" class="min-h-10 lg:justify-start">团队</TabsTrigger><TabsTrigger value="billing" class="min-h-10 lg:justify-start">计费</TabsTrigger></TabsList>
      <div class="min-w-0">
        <TabsContent value="profile"><Card><CardHeader><CardTitle>个人资料</CardTitle><CardDescription>更新你的公开账户信息。</CardDescription></CardHeader><CardContent class="space-y-6"><div class="flex items-center gap-4"><Avatar class="size-16"><AvatarFallback class="text-xl">林</AvatarFallback></Avatar><div><p class="font-medium">林晓</p><p class="text-sm text-muted-foreground">admin@acme.dev</p></div><Button variant="outline" class="ml-auto min-h-10">更换头像</Button></div><Separator /><div class="grid gap-4 sm:grid-cols-2"><label class="space-y-2 text-sm font-medium">姓名<Input model-value="林晓" /></label><label class="space-y-2 text-sm font-medium">邮箱<Input model-value="admin@acme.dev" /></label><label class="space-y-2 text-sm font-medium">语言<Select default-value="zh"><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="zh">简体中文</SelectItem><SelectItem value="en">English</SelectItem></SelectContent></Select></label><label class="space-y-2 text-sm font-medium">时区<Select default-value="china"><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="china">中国时区</SelectItem><SelectItem value="utc">UTC</SelectItem></SelectContent></Select></label><label class="space-y-2 text-sm font-medium sm:col-span-2">简介<textarea class="flex min-h-24 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" placeholder="介绍一下你自己" /></label><label class="space-y-2 text-sm font-medium sm:col-span-2">职位<Input model-value="产品负责人" /></label></div><Button>保存更改</Button></CardContent></Card></TabsContent>
        <TabsContent value="security"><div class="grid gap-4"><Card><CardHeader><CardTitle>安全设置</CardTitle><CardDescription>保护你的账户与登录会话。</CardDescription></CardHeader><CardContent class="space-y-5"><div class="flex items-center justify-between rounded-lg border p-4"><div><p class="font-medium">双因素认证</p><p class="text-sm text-muted-foreground">登录时要求额外的验证码</p></div><Switch default-checked /></div><div class="rounded-lg border border-dashed p-6 text-center text-sm text-muted-foreground">二维码占位 · 使用身份验证器扫描</div><Dialog><DialogTrigger as-child><Button variant="outline">修改密码</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>修改密码</DialogTitle><DialogDescription>设置一个新的账户密码。</DialogDescription></DialogHeader><div class="space-y-3"><Input type="password" placeholder="当前密码" /><Input type="password" placeholder="新密码" /></div><DialogFooter><DialogClose as-child><Button variant="outline">取消</Button></DialogClose><Button>保存</Button></DialogFooter></DialogContent></Dialog></CardContent></Card><Card><CardHeader><CardTitle>登录会话</CardTitle></CardHeader><CardContent class="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>设备</TableHead><TableHead>位置</TableHead><TableHead>状态</TableHead></TableRow></TableHeader><TableBody><TableRow v-for="session in sessions" :key="session.device"><TableCell>{{ session.device }}</TableCell><TableCell>{{ session.location }}</TableCell><TableCell><Badge>{{ session.current ? '当前会话' : '已登录' }}</Badge></TableCell></TableRow></TableBody></Table></CardContent></Card></div></TabsContent>
        <TabsContent value="notifications"><Card><CardHeader><CardTitle>通知偏好</CardTitle><CardDescription>选择你希望接收的通知。</CardDescription></CardHeader><CardContent class="space-y-4"><ToggleGroup type="single" default-value="email" class="w-full justify-start"><ToggleGroupItem value="email" class="min-h-10">邮件</ToggleGroupItem><ToggleGroupItem value="push" class="min-h-10">推送</ToggleGroupItem><ToggleGroupItem value="in-app" class="min-h-10">站内</ToggleGroupItem></ToggleGroup><div v-for="(label, index) in ['项目更新', '账单提醒', '团队活动', '产品新闻']" :key="label" class="flex items-center justify-between border-b pb-4 last:border-0"><div><p class="font-medium">{{ label }}</p><p class="text-sm text-muted-foreground">通过所选渠道接收重要提醒</p></div><Switch :default-checked="index < 3" /></div></CardContent></Card></TabsContent>
        <TabsContent value="team"><Card><CardHeader><CardTitle>团队成员</CardTitle><CardDescription>管理团队访问权限。</CardDescription></CardHeader><CardContent class="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>成员</TableHead><TableHead>角色</TableHead><TableHead>最近活跃</TableHead><TableHead class="text-right">操作</TableHead></TableRow></TableHeader><TableBody><TableRow v-for="member in team" :key="member.email"><TableCell><div class="flex items-center gap-2"><Avatar class="size-8"><AvatarFallback>{{ member.name.slice(0, 1) }}</AvatarFallback></Avatar>{{ member.name }}</div></TableCell><TableCell><Select v-model="teamRoles[member.email]"><SelectTrigger class="w-32"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="owner">所有者</SelectItem><SelectItem value="admin">管理员</SelectItem><SelectItem value="member">成员</SelectItem><SelectItem value="viewer">只读</SelectItem></SelectContent></Select></TableCell><TableCell>{{ member.lastActive }}</TableCell><TableCell class="text-right"><Button variant="ghost" size="sm" class="min-h-10">移除</Button></TableCell></TableRow></TableBody></Table><div class="mt-4 flex flex-col gap-2 sm:flex-row"><Input v-model="inviteEmail" placeholder="邀请成员邮箱" /><Button class="min-h-10" @click="invite"><Icon name="plus" />邀请</Button></div><p v-if="inviteSent" class="mt-2 text-sm text-muted-foreground">邀请已发送</p></CardContent></Card></TabsContent>
        <TabsContent value="billing"><div class="grid gap-4"><Card><CardHeader><CardTitle>订阅方案</CardTitle><CardDescription>当前与可用方案。</CardDescription></CardHeader><CardContent class="grid gap-3 sm:grid-cols-3"><div v-for="plan in plans" :key="plan.name" class="rounded-lg border p-4"><div class="flex items-center justify-between"><p class="font-medium">{{ plan.name }}</p><Badge v-if="plan.recommended">推荐</Badge></div><p class="mt-2 text-2xl font-semibold">{{ plan.price === null ? '定制' : plan.price === 0 ? '免费' : `¥${plan.price}` }}</p><p class="mt-2 text-sm text-muted-foreground">{{ plan.features.join(' · ') }}</p></div></CardContent></Card><Card><CardHeader><CardTitle>发票记录</CardTitle></CardHeader><CardContent class="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>编号</TableHead><TableHead>日期</TableHead><TableHead>金额</TableHead></TableRow></TableHeader><TableBody><TableRow v-for="invoice in invoices" :key="invoice.id"><TableCell>{{ invoice.id }}</TableCell><TableCell>{{ invoice.date }}</TableCell><TableCell>¥{{ invoice.amount }}</TableCell></TableRow></TableBody></Table></CardContent></Card><Card class="border-destructive/50"><CardHeader><CardTitle>危险区</CardTitle><CardDescription>删除账户将永久移除全部数据。</CardDescription></CardHeader><CardContent><AlertDialog><AlertDialogTrigger as-child><Button variant="destructive">删除账户</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>确定删除账户？</AlertDialogTitle><AlertDialogDescription>请输入 DELETE 以确认，此操作将永久删除全部数据。</AlertDialogDescription></AlertDialogHeader><Input v-model="confirmation" placeholder="输入 DELETE" /><AlertDialogFooter><AlertDialogCancel>取消</AlertDialogCancel><AlertDialogAction :disabled="!canDelete">确认删除</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></CardContent></Card></div></TabsContent>
      </div>
    </Tabs>
  </div>
</template>
