import {
  Activity,
  AlertCircle,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  BarChart3,
  Bell,
  Bot,
  Boxes,
  CalendarDays,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleHelp,
  Clipboard,
  Clock3,
  Copy,
  Download,
  Edit3,
  Ellipsis,
  FilePlus,
  Filter,
  Globe,
  Grid2X2,
  Heart,
  Home,
  LayoutDashboard,
  Link2,
  List,
  LoaderCircle,
  Lock,
  LogIn,
  LogOut,
  Menu,
  MessageCircle,
  MessageSquare,
  Mic,
  Minus,
  MoreHorizontal,
  Moon,
  Paperclip,
  Pencil,
  Play,
  Plus,
  Plug,
  RefreshCw,
  Search,
  Send,
  Settings,
  Shield,
  ShoppingCart,
  SlidersHorizontal,
  Sparkles,
  Star,
  Sun,
  Tag,
  Trash2,
  Upload,
  User,
  Users,
  X,
  Zap,
} from "lucide-solid"
import {
  IconActivity,
  IconAlertCircle,
  IconArchive,
  IconArrowDown,
  IconArrowLeft,
  IconArrowRight,
  IconArrowUp,
  IconBell,
  IconBox,
  IconCalendar,
  IconChartBar,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconClipboard,
  IconClock,
  IconCopy,
  IconDots,
  IconDownload,
  IconEdit,
  IconExternalLink,
  IconFilePlus,
  IconFilter,
  IconGlobe,
  IconGrid3x3,
  IconHeart,
  IconHome,
  IconInfoCircle,
  IconLayoutDashboard,
  IconLink,
  IconList,
  IconLoader2,
  IconLock,
  IconLogin,
  IconLogout,
  IconMenu2,
  IconMessage,
  IconMessageCircle,
  IconMicrophone,
  IconMinus,
  IconMoon,
  IconPaperclip,
  IconPencil,
  IconPlayerPlay,
  IconPlus,
  IconRefresh,
  IconSearch,
  IconSend,
  IconSettings,
  IconShield,
  IconShoppingCart,
  IconSparkles,
  IconStar,
  IconSun,
  IconTag,
  IconTrash,
  IconUpload,
  IconUser,
  IconUsers,
  IconX,
  IconZzz,
  IconAdjustmentsHorizontal,
} from "@tabler/icons-solidjs"
import {
  Archive as PhArchive,
  ArrowDown as PhArrowDown,
  ArrowLeft as PhArrowLeft,
  ArrowRight as PhArrowRight,
  ArrowUp as PhArrowUp,
  Bell as PhBell,
  Calendar as PhCalendar,
  CaretDown as PhCaretDown,
  CaretLeft as PhCaretLeft,
  CaretRight as PhCaretRight,
  CaretUp as PhCaretUp,
  ChatCircle as PhChatCircle,
  ChatText as PhChatText,
  Check as PhCheck,
  CheckCircle as PhCheckCircle,
  ChartBar as PhChartBar,
  Clipboard as PhClipboard,
  Clock as PhClock,
  Copy as PhCopy,
  Cube as PhBoxes,
  DotsThree as PhDotsThree,
  DownloadSimple as PhDownload,
  Faders as PhFaders,
  FilePlus as PhFilePlus,
  Gear as PhGear,
  Globe as PhGlobe,
  GridFour as PhGridFour,
  Heart as PhHeart,
  House as PhHouse,
  Lightning as PhLightning,
  Link as PhLink,
  List as PhList,
  Lock as PhLock,
  MagicWand as PhMagicWand,
  MagnifyingGlass as PhMagnifyingGlass,
  Microphone as PhMicrophone,
  Minus as PhMinus,
  Moon as PhMoon,
  Paperclip as PhPaperclip,
  Pencil as PhPencil,
  Play as PhPlay,
  Plus as PhPlus,
  Plugs as PhPlugs,
  Power as PhPower,
  Pulse as PhPulse,
  Repeat as PhRepeat,
  PaperPlaneTilt as PhSend,
  Shield as PhShield,
  ShoppingCart as PhShoppingCart,
  SlidersHorizontal as PhSliders,
  Sparkle as PhSparkle,
  Star as PhStar,
  Sun as PhSun,
  Tag as PhTag,
  Trash as PhTrash,
  UploadSimple as PhUpload,
  User as PhUser,
  Users as PhUsers,
  X as PhX,
} from "phosphor-solid-js"
import { Icon as HeroIcon } from "solid-heroicons"
import {
  arrowDown as heroArrowDown,
  arrowLeft as heroArrowLeft,
  arrowRight as heroArrowRight,
  arrowUp as heroArrowUp,
  bell as heroBell,
  calendarDays as heroCalendar,
  chartBar as heroChart,
  check as heroCheck,
  chevronDown as heroChevronDown,
  chevronLeft as heroChevronLeft,
  chevronRight as heroChevronRight,
  chevronUp as heroChevronUp,
  clipboard as heroClipboard,
  clock as heroClock,
  cloudArrowUp as heroUpload,
  cog_6Tooth as heroSettings,
  ellipsisHorizontal as heroDots,
  folderPlus as heroFilePlus,
  funnel as heroFilter,
  globeAlt as heroGlobe,
  home as heroHome,
  informationCircle as heroInfo,
  link as heroLink,
  listBullet as heroList,
  lockClosed as heroLock,
  magnifyingGlass as heroSearch,
  megaphone as heroMegaphone,
  microphone as heroMicrophone,
  minus as heroMinus,
  moon as heroMoon,
  paperClip as heroPaperclip,
  pencil as heroPencil,
  play as heroPlay,
  plus as heroPlus,
  power as heroPower,
  rectangleGroup as heroBoxes,
  rocketLaunch as heroRocket,
  server as heroServer,
  share as heroShare,
  shoppingCart as heroCart,
  sparkles as heroSparkles,
  star as heroStar,
  sun as heroSun,
  tag as heroTag,
  trash as heroTrash,
  user as heroUser,
  userGroup as heroUsers,
  xMark as heroX,
} from "solid-heroicons/outline"
import { Show, type Component } from "solid-js"
import { Dynamic } from "solid-js/web"

type IconProps = {
  name: string
  size?: number | string
  class?: string
}
type HeroPath = Parameters<typeof HeroIcon>[0]["path"]

const lucide: Record<string, unknown> = {
  activity: Activity,
  "alert-circle": AlertCircle,
  archive: Archive,
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  "bar-chart": BarChart3,
  bell: Bell,
  bot: Bot,
  boxes: Boxes,
  calendar: CalendarDays,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "circle-help": CircleHelp,
  "help-circle": CircleHelp,
  clipboard: Clipboard,
  clock: Clock3,
  copy: Copy,
  download: Download,
  edit: Edit3,
  "ellipsis-horizontal": Ellipsis,
  "file-plus": FilePlus,
  folder: Archive,
  filter: Filter,
  globe: Globe,
  github: Globe,
  grid: Grid2X2,
  heart: Heart,
  home: Home,
  inbox: Archive,
  info: CircleHelp,
  "layout-dashboard": LayoutDashboard,
  mail: MessageCircle,
  eye: CircleHelp,
  "eye-off": CircleHelp,
  link: Link2,
  "link-2": Link2,
  list: List,
  loader: LoaderCircle,
  lock: Lock,
  "log-in": LogIn,
  "log-out": LogOut,
  menu: Menu,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  mic: Mic,
  minus: Minus,
  "more-horizontal": MoreHorizontal,
  moon: Moon,
  paperclip: Paperclip,
  pencil: Pencil,
  play: Play,
  plus: Plus,
  plug: Plug,
  refresh: RefreshCw,
  search: Search,
  send: Send,
  settings: Settings,
  shield: Shield,
  "shopping-cart": ShoppingCart,
  sliders: SlidersHorizontal,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  tag: Tag,
  trash: Trash2,
  type: List,
  upload: Upload,
  user: User,
  users: Users,
  x: X,
  zap: Zap,
  "qr-code": Grid2X2,
  image: Grid2X2,
  file: Clipboard,
  layers: Boxes,
  rocket: Zap,
  quote: MessageSquare,
  "alert-triangle": AlertCircle,
  "circle-check": Check,
  "circle-x": X,
  "arrow-up-right": ArrowRight,
  "credit-card": Clipboard,
  "chevrons-up-down": ChevronDown,
  "panel-left": List,
}

const tabler: Record<string, unknown> = {
  activity: IconActivity,
  "alert-circle": IconAlertCircle,
  archive: IconArchive,
  "arrow-down": IconArrowDown,
  "arrow-left": IconArrowLeft,
  "arrow-right": IconArrowRight,
  "arrow-up": IconArrowUp,
  "bar-chart": IconChartBar,
  bell: IconBell,
  bot: IconZzz,
  boxes: IconBox,
  calendar: IconCalendar,
  check: IconCheck,
  "chevron-down": IconChevronDown,
  "chevron-left": IconChevronLeft,
  "chevron-right": IconChevronRight,
  "chevron-up": IconChevronUp,
  "circle-help": IconInfoCircle,
  "help-circle": IconInfoCircle,
  clipboard: IconClipboard,
  clock: IconClock,
  copy: IconCopy,
  download: IconDownload,
  edit: IconEdit,
  "ellipsis-horizontal": IconDots,
  "file-plus": IconFilePlus,
  folder: IconArchive,
  filter: IconFilter,
  globe: IconGlobe,
  github: IconGlobe,
  grid: IconGrid3x3,
  heart: IconHeart,
  home: IconHome,
  inbox: IconArchive,
  info: IconInfoCircle,
  "layout-dashboard": IconLayoutDashboard,
  mail: IconMessage,
  eye: IconInfoCircle,
  "eye-off": IconInfoCircle,
  link: IconLink,
  "link-2": IconLink,
  list: IconList,
  loader: IconLoader2,
  lock: IconLock,
  "log-in": IconLogin,
  "log-out": IconLogout,
  menu: IconMenu2,
  "message-circle": IconMessageCircle,
  "message-square": IconMessage,
  mic: IconMicrophone,
  minus: IconMinus,
  "more-horizontal": IconDots,
  moon: IconMoon,
  paperclip: IconPaperclip,
  pencil: IconPencil,
  play: IconPlayerPlay,
  plus: IconPlus,
  plug: IconExternalLink,
  refresh: IconRefresh,
  search: IconSearch,
  send: IconSend,
  settings: IconSettings,
  shield: IconShield,
  "shopping-cart": IconShoppingCart,
  sliders: IconAdjustmentsHorizontal,
  sparkles: IconSparkles,
  star: IconStar,
  sun: IconSun,
  tag: IconTag,
  trash: IconTrash,
  type: IconList,
  upload: IconUpload,
  user: IconUser,
  users: IconUsers,
  x: IconX,
  zap: IconZzz,
  "qr-code": IconGrid3x3,
  image: IconGrid3x3,
  file: IconClipboard,
  layers: IconBox,
  rocket: IconZzz,
  quote: IconMessage,
  "alert-triangle": IconAlertCircle,
  "circle-check": IconCheck,
  "circle-x": IconX,
  "arrow-up-right": IconExternalLink,
  "credit-card": IconClipboard,
  "chevrons-up-down": IconChevronDown,
  "panel-left": IconList,
}

const phosphor: Record<string, unknown> = {
  activity: PhPulse,
  "alert-circle": PhCheckCircle,
  archive: PhArchive,
  "arrow-down": PhArrowDown,
  "arrow-left": PhArrowLeft,
  "arrow-right": PhArrowRight,
  "arrow-up": PhArrowUp,
  "bar-chart": PhChartBar,
  bell: PhBell,
  bot: PhMagicWand,
  boxes: PhBoxes,
  calendar: PhCalendar,
  check: PhCheck,
  "chevron-down": PhCaretDown,
  "chevron-left": PhCaretLeft,
  "chevron-right": PhCaretRight,
  "chevron-up": PhCaretUp,
  "circle-help": PhCheckCircle,
  "help-circle": PhCheckCircle,
  clipboard: PhClipboard,
  clock: PhClock,
  copy: PhCopy,
  download: PhDownload,
  edit: PhPencil,
  "ellipsis-horizontal": PhDotsThree,
  "file-plus": PhFilePlus,
  folder: PhArchive,
  filter: PhFaders,
  globe: PhGlobe,
  github: PhGlobe,
  grid: PhGridFour,
  heart: PhHeart,
  home: PhHouse,
  inbox: PhArchive,
  info: PhCheckCircle,
  "layout-dashboard": PhGridFour,
  mail: PhChatCircle,
  eye: PhCheckCircle,
  "eye-off": PhCheckCircle,
  link: PhLink,
  "link-2": PhLink,
  list: PhList,
  loader: PhRepeat,
  lock: PhLock,
  "log-in": PhPower,
  "log-out": PhPower,
  menu: PhList,
  "message-circle": PhChatCircle,
  "message-square": PhChatText,
  mic: PhMicrophone,
  minus: PhMinus,
  "more-horizontal": PhDotsThree,
  moon: PhMoon,
  paperclip: PhPaperclip,
  pencil: PhPencil,
  play: PhPlay,
  plus: PhPlus,
  plug: PhPlugs,
  refresh: PhRepeat,
  search: PhMagnifyingGlass,
  send: PhSend,
  settings: PhGear,
  shield: PhShield,
  "shopping-cart": PhShoppingCart,
  sliders: PhSliders,
  sparkles: PhSparkle,
  star: PhStar,
  sun: PhSun,
  tag: PhTag,
  trash: PhTrash,
  type: PhList,
  upload: PhUpload,
  user: PhUser,
  users: PhUsers,
  x: PhX,
  zap: PhLightning,
  "qr-code": PhGridFour,
  image: PhGridFour,
  file: PhClipboard,
  layers: PhBoxes,
  rocket: PhLightning,
  quote: PhChatText,
  "alert-triangle": PhCheckCircle,
  "circle-check": PhCheckCircle,
  "circle-x": PhX,
  "arrow-up-right": PhArrowUp,
  "credit-card": PhClipboard,
  "chevrons-up-down": PhCaretDown,
  "panel-left": PhList,
}

const heroicons: Record<string, HeroPath> = {
  activity: heroChart,
  "alert-circle": heroInfo,
  archive: heroList,
  "arrow-down": heroArrowDown,
  "arrow-left": heroArrowLeft,
  "arrow-right": heroArrowRight,
  "arrow-up": heroArrowUp,
  "bar-chart": heroChart,
  bell: heroBell,
  bot: heroSparkles,
  boxes: heroBoxes,
  calendar: heroCalendar,
  check: heroCheck,
  "chevron-down": heroChevronDown,
  "chevron-left": heroChevronLeft,
  "chevron-right": heroChevronRight,
  "chevron-up": heroChevronUp,
  "circle-help": heroInfo,
  "help-circle": heroInfo,
  clipboard: heroClipboard,
  clock: heroClock,
  copy: heroClipboard,
  download: heroUpload,
  edit: heroPencil,
  "ellipsis-horizontal": heroDots,
  "file-plus": heroFilePlus,
  folder: heroList,
  filter: heroFilter,
  globe: heroGlobe,
  github: heroGlobe,
  grid: heroList,
  heart: heroStar,
  home: heroHome,
  inbox: heroList,
  info: heroInfo,
  "layout-dashboard": heroHome,
  mail: heroMegaphone,
  eye: heroInfo,
  "eye-off": heroInfo,
  link: heroLink,
  "link-2": heroLink,
  list: heroList,
  loader: heroArrowRight,
  lock: heroLock,
  "log-in": heroPower,
  "log-out": heroPower,
  menu: heroList,
  "message-circle": heroList,
  "message-square": heroList,
  mic: heroMicrophone,
  minus: heroMinus,
  "more-horizontal": heroDots,
  moon: heroMoon,
  paperclip: heroPaperclip,
  pencil: heroPencil,
  play: heroPlay,
  plus: heroPlus,
  plug: heroShare,
  refresh: heroArrowRight,
  search: heroSearch,
  send: heroMegaphone,
  settings: heroSettings,
  shield: heroServer,
  "shopping-cart": heroCart,
  sliders: heroSettings,
  sparkles: heroSparkles,
  star: heroStar,
  sun: heroSun,
  tag: heroTag,
  trash: heroTrash,
  type: heroList,
  upload: heroUpload,
  user: heroUser,
  users: heroUsers,
  x: heroX,
  zap: heroRocket,
  "qr-code": heroBoxes,
  image: heroBoxes,
  file: heroClipboard,
  layers: heroBoxes,
  rocket: heroRocket,
  quote: heroMegaphone,
  "alert-triangle": heroInfo,
  "circle-check": heroCheck,
  "circle-x": heroX,
  "arrow-up-right": heroArrowRight,
  "credit-card": heroClipboard,
  "chevrons-up-down": heroChevronDown,
  "panel-left": heroList,
}

export const iconNames = Object.keys(lucide)
const warnedMissing = new Set<string>()

function family() {
  if (typeof window === "undefined") return "lucide"
  const params = new URLSearchParams(window.location.search)
  const value = params.get("icons") ?? params.get("icon")
  return value === "tabler" || value === "phosphor" || value === "heroicons"
    ? value
    : "lucide"
}

export function Icon(props: IconProps) {
  const selected = family()
  const map = selected === "tabler" ? tabler : selected === "phosphor" ? phosphor : selected === "heroicons" ? heroicons : lucide
  if (!(props.name in map) && !warnedMissing.has(`${selected}:${props.name}`)) {
    warnedMissing.add(`${selected}:${props.name}`)
    console.warn(`[Icon] Missing icon "${props.name}" in ${selected} family`)
  }
  return (
    <Show
      when={selected === "heroicons"}
      fallback={
        <Dynamic
          component={
            ((selected === "tabler"
              ? tabler
              : selected === "phosphor"
                ? phosphor
              : lucide)[props.name] ??
              lucide["circle-help"]) as Component<Record<string, unknown>>
          }
          size={props.size}
          class={props.class}
          aria-hidden="true"
        />
      }
    >
      <HeroIcon
        path={heroicons[props.name] ?? heroicons["circle-help"]}
        width={props.size}
        height={props.size}
        class={props.class}
        aria-hidden="true"
      />
    </Show>
  )
}
