export type CoverageStatus = "implemented" | "composed" | "missing"
// implemented = daisyUI 自带组件类；composed = 用 daisyUI 类 + Tailwind 组合；missing = 无对应且不可合理组合
export const coverage: Record<string, CoverageStatus> = {
  Typography: "composed",
  Button: "implemented",
  ButtonGroup: "implemented",
  IconButton: "implemented",
  Input: "implemented",
  Textarea: "implemented",
  NumberInput: "composed",
  Select: "implemented",
  MultiSelect: "composed",
  Combobox: "composed",
  Autocomplete: "composed",
  Checkbox: "implemented",
  Radio: "implemented",
  Switch: "implemented",
  Slider: "implemented",
  Rating: "implemented",
  DatePicker: "composed",
  TimePicker: "composed",
  DateRangePicker: "composed",
  ColorPicker: "composed",
  Upload: "implemented",
  Cascader: "composed",
  Transfer: "composed",
  Mention: "composed",
  PinInput: "implemented",
  Form: "implemented",
  Table: "implemented",
  DataGrid: "composed",
  Descriptions: "composed",
  List: "implemented",
  Card: "implemented",
  Avatar: "implemented",
  AvatarGroup: "implemented",
  Badge: "implemented",
  Tag: "composed",
  Statistic: "implemented",
  Timeline: "implemented",
  Tree: "composed",
  Calendar: "composed",
  Image: "composed",
  Carousel: "implemented",
  Empty: "composed",
  Tooltip: "implemented",
  Popover: "composed",
  QRCode: "missing",
  Segmented: "composed",
  Alert: "implemented",
  Toast: "implemented",
  Notification: "composed",
  Dialog: "implemented",
  Drawer: "implemented",
  Progress: "implemented",
  Skeleton: "implemented",
  Spinner: "implemented",
  Result: "composed",
  Popconfirm: "composed",
  Menu: "implemented",
  Dropdown: "implemented",
  Breadcrumb: "implemented",
  Tabs: "implemented",
  Pagination: "composed",
  Steps: "implemented",
  Anchor: "composed",
  BackTop: "composed",
  Affix: "composed",
  Navbar: "implemented",
  Sidebar: "composed",
  CommandPalette: "composed",
  Grid: "composed",
  Stack: "composed",
  Layout: "composed",
  Container: "composed",
  AspectRatio: "composed",
  Resizable: "missing",
  ScrollArea: "composed",
  Accordion: "implemented",
  ThemeProvider: "implemented",
  Watermark: "missing",
  Tour: "missing",
  FloatButton: "implemented",
  Kbd: "implemented",
  Code: "implemented",
  Divider: "implemented",
  Link: "implemented",
}

// daisyUI 5.7 自带但 contract 未列出的组件，在 /components 「daisyUI 补充」分节展示
export const daisyExtras = [
  "Chat", "Countdown", "Diff", "Dock", "Filter", "Hero", "Indicator", "Mask", "Mockup", "RadialProgress", "Status", "Swap", "ThemeController", "Join", "Stack", "Fieldset", "Label", "Validator", "Footer", "Aura", "Hover3D", "HoverGallery", "MegaMenu", "TextRotate", "Glass",
]
