import * as bootstrap from "bootstrap"
import { icon } from "../lib/icons"
import { avatar, each, esc, money } from "../lib/html"
import { activity, orders, stats, team, STATUS_COLOR, STATUS_LABEL } from "../lib/data"
import { coverage, type ComponentName, type Coverage } from "../coverage"
import type { PageResult } from "./types"

const COLORS = ["primary", "secondary", "success", "danger", "warning", "info", "light", "dark"] as const
const SIZES = [["sm", "小"], ["", "默认"], ["lg", "大"]] as const
const COVER_BADGE: Record<Coverage, string> = { implemented: "text-bg-success", composed: "text-bg-info", missing: "text-bg-secondary" }
const COVER_LABEL: Record<Coverage, string> = { implemented: "原生", composed: "组合", missing: "缺失" }

const missing = (why: string) => `<div class="alert alert-secondary d-flex gap-2 mb-0" role="note">${icon("alert-circle")}<div><strong>Bootstrap 5 未提供。</strong> ${why}</div></div>`
const row = (cls = "") => `<div class="d-flex flex-wrap align-items-center gap-2 ${cls}">`

const demos: Record<ComponentName, () => string> = {
  Typography: () => `<h1 class="h1">标题 H1</h1><h2 class="h2">标题 H2</h2><h3 class="h3">标题 H3</h3><h4 class="h4">标题 H4</h4><h5 class="h5">标题 H5</h5><h6 class="h6">标题 H6</h6><p class="display-6">Display 6</p><p class="lead">Lead 段落文字，用于强调开头。</p><p>正文段落 <strong>加粗</strong> <em>斜体</em> <u>下划线</u> <s>删除</s> <mark>高亮</mark> <small>小号</small> <abbr title="Hypertext">abbr</abbr>。</p><blockquote class="blockquote"><p>引用文字。</p><footer class="blockquote-footer">出自 <cite>某人</cite></footer></blockquote><p class="text-body-secondary mb-0">text-body-secondary · <span class="text-body-tertiary">tertiary</span> · <span class="text-primary">primary</span> · <span class="text-danger">danger</span> · <span class="fw-light">light</span> · <span class="fst-italic">italic</span> · <span class="text-uppercase">upper</span> · <span class="font-monospace">mono</span></p>`,
  Button: () => `${row("mb-3")}${each(COLORS, (c) => `<button type="button" class="btn btn-${c}">${c}</button>`)}<button type="button" class="btn btn-link">link</button></div>${row("mb-3")}${each(COLORS, (c) => `<button type="button" class="btn btn-outline-${c}">${c}</button>`)}</div>${row("mb-3")}${each(SIZES, ([s, l]) => `<button type="button" class="btn btn-primary ${s ? `btn-${s}` : ""}">${l}</button>`)}<button type="button" class="btn btn-primary" disabled>禁用</button><button type="button" class="btn btn-primary active" aria-pressed="true">激活</button><button type="button" class="btn btn-primary" disabled><span class="spinner-border spinner-border-sm me-1" aria-hidden="true"></span>加载中</button><button type="button" class="btn btn-primary">${icon("plus")} 带图标</button><button type="button" class="btn btn-primary rounded-pill">胶囊</button></div><div class="d-grid gap-2 d-md-block"><button type="button" class="btn btn-outline-primary">块级/自适应</button></div>`,
  ButtonGroup: () => `${row("mb-3")}<div class="btn-group" role="group" aria-label="基础"><button type="button" class="btn btn-primary">左</button><button type="button" class="btn btn-primary">中</button><button type="button" class="btn btn-primary">右</button></div><div class="btn-group" role="group"><button type="button" class="btn btn-outline-secondary">${icon("arrow-left")}</button><button type="button" class="btn btn-outline-secondary">${icon("arrow-right")}</button></div>${each(SIZES, ([s, l]) => `<div class="btn-group ${s ? `btn-group-${s}` : ""}" role="group"><button type="button" class="btn btn-outline-primary">${l}</button><button type="button" class="btn btn-outline-primary">${l}</button></div>`)}</div>${row()}<div class="btn-group" role="group" aria-label="单选按钮组">${each(["日", "周", "月"], (t, i) => `<input type="radio" class="btn-check" name="bg-radio" id="bgr${i}" autocomplete="off" ${i === 0 ? "checked" : ""}><label class="btn btn-outline-primary" for="bgr${i}">${t}</label>`)}</div><div class="btn-group-vertical" role="group"><button type="button" class="btn btn-secondary">上</button><button type="button" class="btn btn-secondary">下</button></div><div class="btn-group"><button type="button" class="btn btn-primary">操作</button><button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false"><span class="visually-hidden">切换</span></button><ul class="dropdown-menu"><li><a class="dropdown-item" href="#">选项</a></li></ul></div></div>`,
  IconButton: () => `${row()}${each(SIZES, ([s]) => `<button type="button" class="btn btn-primary ${s ? `btn-${s}` : ""}" aria-label="添加">${icon("plus")}</button>`)}<button type="button" class="btn btn-outline-secondary" aria-label="编辑">${icon("edit")}</button><button type="button" class="btn btn-outline-danger" aria-label="删除">${icon("trash")}</button><button type="button" class="btn btn-light rounded-circle" aria-label="设置">${icon("settings")}</button><button type="button" class="btn btn-link text-body" aria-label="更多">${icon("more-horizontal")}</button><button type="button" class="btn btn-primary" disabled aria-label="禁用">${icon("lock")}</button><button type="button" class="btn-close" aria-label="关闭"></button></div>`,
  Input: () => `<div class="row g-3">${each(SIZES, ([s, l]) => `<div class="col-md-4"><input type="text" class="form-control ${s ? `form-control-${s}` : ""}" placeholder="${l}" aria-label="${l}"></div>`)}<div class="col-md-4"><input type="text" class="form-control" value="禁用" disabled aria-label="禁用"></div><div class="col-md-4"><input type="text" class="form-control" value="只读" readonly aria-label="只读"></div><div class="col-md-4"><input type="text" class="form-control-plaintext" value="纯文本" readonly aria-label="纯文本"></div><div class="col-md-4"><input type="text" class="form-control is-valid" value="有效值" aria-label="有效"><div class="valid-feedback">看起来不错。</div></div><div class="col-md-4"><input type="text" class="form-control is-invalid" value="无效值" aria-label="无效"><div class="invalid-feedback">请修正该字段。</div></div><div class="col-md-4"><div class="input-group"><span class="input-group-text">${icon("search")}</span><input type="search" class="form-control" placeholder="带前缀"><button class="btn btn-outline-secondary" type="button">搜索</button></div></div><div class="col-md-4"><div class="form-floating"><input type="email" class="form-control" id="flEmail" placeholder="name@example.com"><label for="flEmail">浮动标签</label></div></div><div class="col-md-4"><div class="input-group"><span class="input-group-text">¥</span><input type="text" class="form-control" aria-label="金额"><span class="input-group-text">.00</span></div></div><div class="col-md-4"><input type="password" class="form-control" value="password" aria-label="密码"></div></div>`,
  Textarea: () => `<div class="row g-3"><div class="col-md-6"><textarea class="form-control" rows="3" placeholder="默认多行文本"></textarea></div><div class="col-md-6"><div class="form-floating"><textarea class="form-control" id="flTa" style="height:88px" placeholder="留言"></textarea><label for="flTa">浮动标签</label></div></div><div class="col-md-6"><textarea class="form-control is-invalid" rows="2">超出字数限制</textarea><div class="invalid-feedback">最多 200 字。</div></div><div class="col-md-6"><textarea class="form-control" rows="2" disabled>禁用</textarea></div></div>`,
  NumberInput: () => `${row()}<input type="number" class="form-control w-auto" value="10" min="0" max="100" step="1" aria-label="数字"><div class="input-group w-auto"><button class="btn btn-outline-secondary" type="button" data-step="-1" aria-label="减少">${icon("minus")}</button><input type="number" class="form-control text-center" value="1" min="0" style="width:5rem" aria-label="数量" id="numQty"><button class="btn btn-outline-secondary" type="button" data-step="1" aria-label="增加">${icon("plus")}</button></div><div class="input-group input-group-sm w-auto"><input type="number" class="form-control" value="99" aria-label="价格"><span class="input-group-text">元</span></div><input type="number" class="form-control w-auto" value="5" disabled aria-label="禁用"></div>`,
  Select: () => `<div class="row g-3">${each(SIZES, ([s, l]) => `<div class="col-md-4"><select class="form-select ${s ? `form-select-${s}` : ""}" aria-label="${l}"><option selected>${l}尺寸</option><option>选项一</option><option>选项二</option></select></div>`)}<div class="col-md-4"><select class="form-select" disabled aria-label="禁用"><option>禁用</option></select></div><div class="col-md-4"><select class="form-select is-invalid" aria-label="无效"><option>请选择</option></select><div class="invalid-feedback">必选。</div></div><div class="col-md-4"><div class="form-floating"><select class="form-select" id="flSel"><option>华东</option><option>华北</option></select><label for="flSel">区域</label></div></div></div>`,
  MultiSelect: () => `<div class="row g-3"><div class="col-md-6"><select class="form-select" multiple size="4" aria-label="多选">${each(team, (m) => `<option ${m.role === "admin" ? "selected" : ""}>${esc(m.name)}</option>`)}</select><div class="form-text">原生 &lt;select multiple&gt;，Ctrl/⌘ 多选</div></div><div class="col-md-6"><div class="form-control d-flex flex-wrap gap-1 align-items-center" style="min-height:2.4rem">${each(team.slice(0, 3), (m) => `<span class="badge text-bg-primary d-inline-flex align-items-center gap-1">${esc(m.name)}<button type="button" class="btn-close btn-close-white" style="font-size:.5em" aria-label="移除"></button></span>`)}<input class="border-0 bg-transparent flex-grow-1" style="outline:none;min-width:4rem" placeholder="添加…" aria-label="添加成员"></div><div class="form-text">badge + input 组合的标签式多选</div></div></div>`,
  Combobox: () => `<div class="row g-3"><div class="col-md-6"><input class="form-control" list="cbList" placeholder="输入或选择城市" aria-label="城市"><datalist id="cbList"><option value="上海"><option value="北京"><option value="深圳"><option value="杭州"></datalist></div><div class="col-md-6"><div class="dropdown"><input class="form-control dropdown-toggle" data-bs-toggle="dropdown" placeholder="Dropdown 版组合框" aria-label="组合框"><ul class="dropdown-menu w-100">${each(["上海", "北京", "深圳"], (c) => `<li><button class="dropdown-item" type="button">${c}</button></li>`)}</ul></div></div></div>`,
  Autocomplete: () => `<div class="input-group"><span class="input-group-text">${icon("search")}</span><input class="form-control" list="acList" placeholder="搜索成员（datalist 自动完成）" aria-label="搜索成员"><datalist id="acList">${each(team, (m) => `<option value="${esc(m.name)}">${esc(m.email)}</option>`)}</datalist></div>`,
  Checkbox: () => `${row()}<div class="form-check"><input class="form-check-input" type="checkbox" id="ck1"><label class="form-check-label" for="ck1">未选</label></div><div class="form-check"><input class="form-check-input" type="checkbox" id="ck2" checked><label class="form-check-label" for="ck2">已选</label></div><div class="form-check"><input class="form-check-input" type="checkbox" id="ck3" data-indeterminate><label class="form-check-label" for="ck3">半选</label></div><div class="form-check"><input class="form-check-input" type="checkbox" id="ck4" disabled><label class="form-check-label" for="ck4">禁用</label></div><div class="form-check"><input class="form-check-input" type="checkbox" id="ck5" checked disabled><label class="form-check-label" for="ck5">禁用已选</label></div><div class="form-check form-check-inline"><input class="form-check-input is-invalid" type="checkbox" id="ck6"><label class="form-check-label" for="ck6">无效</label></div><input type="checkbox" class="btn-check" id="ck7" autocomplete="off"><label class="btn btn-outline-primary btn-sm" for="ck7">按钮式</label><div class="form-check form-check-reverse"><input class="form-check-input" type="checkbox" id="ck8"><label class="form-check-label" for="ck8">反向</label></div></div>`,
  Radio: () => `${row()}${each(["默认", "已选", "禁用"], (l, i) => `<div class="form-check"><input class="form-check-input" type="radio" name="rd" id="rd${i}" ${i === 1 ? "checked" : ""} ${i === 2 ? "disabled" : ""}><label class="form-check-label" for="rd${i}">${l}</label></div>`)}<div class="form-check form-check-inline"><input class="form-check-input" type="radio" name="rd2" id="rd3"><label class="form-check-label" for="rd3">行内</label></div><div class="btn-group btn-group-sm">${each(["A", "B"], (l, i) => `<input type="radio" class="btn-check" name="rd3" id="rdb${i}" ${i === 0 ? "checked" : ""}><label class="btn btn-outline-secondary" for="rdb${i}">按钮 ${l}</label>`)}</div></div>`,
  Switch: () => `${row()}<div class="form-check form-switch"><input class="form-check-input" type="checkbox" role="switch" id="sw1"><label class="form-check-label" for="sw1">关闭</label></div><div class="form-check form-switch"><input class="form-check-input" type="checkbox" role="switch" id="sw2" checked><label class="form-check-label" for="sw2">开启</label></div><div class="form-check form-switch"><input class="form-check-input" type="checkbox" role="switch" id="sw3" disabled><label class="form-check-label" for="sw3">禁用</label></div><div class="form-check form-switch fs-4"><input class="form-check-input" type="checkbox" role="switch" id="sw4" checked><label class="form-check-label fs-6" for="sw4">大号</label></div><div class="form-check form-switch form-check-reverse"><input class="form-check-input" type="checkbox" role="switch" id="sw5"><label class="form-check-label" for="sw5">反向</label></div></div>`,
  Slider: () => `<div class="row g-3"><div class="col-md-6"><label for="rg1" class="form-label">默认 <output id="rg1out">50</output></label><input type="range" class="form-range" id="rg1" value="50" data-output="rg1out"></div><div class="col-md-6"><label for="rg2" class="form-label">步进 (step=10)</label><input type="range" class="form-range" id="rg2" min="0" max="100" step="10" value="30"></div><div class="col-md-6"><label for="rg3" class="form-label">禁用</label><input type="range" class="form-range" id="rg3" disabled value="70"></div><div class="col-md-6"><label class="form-label">区间（两个 range 组合）</label><div class="d-flex gap-2 align-items-center"><input type="range" class="form-range" value="20" aria-label="最小"><input type="range" class="form-range" value="80" aria-label="最大"></div></div></div>`,
  Rating: () => `${row()}<div class="btn-group" role="radiogroup" aria-label="评分">${each([1, 2, 3, 4, 5], (n) => `<input type="radio" class="btn-check" name="rating" id="rt${n}" ${n === 4 ? "checked" : ""}><label class="btn btn-link p-1 text-warning fs-4" for="rt${n}" title="${n} 星">${icon(n <= 4 ? "star-fill" : "star")}</label>`)}</div><span class="text-warning fs-5">${each([1, 2, 3], () => icon("star-fill"))}${each([1, 2], () => icon("star"))}</span><span class="text-body-secondary">3.0 · 只读</span><span class="text-danger fs-5">${each([1, 2, 3, 4, 5], () => icon("heart"))}</span></div>`,
  DatePicker: () => `${row()}<input type="date" class="form-control w-auto" value="2026-09-05" aria-label="日期"><input type="date" class="form-control form-control-sm w-auto" aria-label="小号"><input type="month" class="form-control w-auto" value="2026-09" aria-label="月份"><input type="date" class="form-control w-auto" disabled aria-label="禁用"></div><div class="form-text">原生 &lt;input type=date&gt; + .form-control（Bootstrap 无内置日历面板）</div>`,
  TimePicker: () => `${row()}<input type="time" class="form-control w-auto" value="09:30" aria-label="时间"><input type="time" class="form-control w-auto" step="1" value="09:30:00" aria-label="含秒"><input type="datetime-local" class="form-control w-auto" value="2026-09-05T09:30" aria-label="日期时间"></div>`,
  DateRangePicker: () => `<div class="input-group" style="max-width:420px"><span class="input-group-text">${icon("calendar")}</span><input type="date" class="form-control" value="2026-09-01" aria-label="开始"><span class="input-group-text">至</span><input type="date" class="form-control" value="2026-09-30" aria-label="结束"></div>`,
  ColorPicker: () => `${row()}<input type="color" class="form-control form-control-color" value="#0d6efd" title="选择颜色" aria-label="颜色"><input type="color" class="form-control form-control-color" value="#dc3545" aria-label="颜色 2"><input type="color" class="form-control form-control-color" value="#198754" disabled aria-label="禁用"><div class="input-group w-auto"><input type="color" class="form-control form-control-color" value="#6f42c1" aria-label="颜色"><input type="text" class="form-control" value="#6f42c1" style="width:7rem" aria-label="十六进制"></div></div>`,
  Upload: () => `<div class="row g-3"><div class="col-md-6"><label for="up1" class="form-label">默认</label><input class="form-control" type="file" id="up1"><label for="up2" class="form-label mt-3">多文件 · 小号</label><input class="form-control form-control-sm" type="file" id="up2" multiple><label for="up3" class="form-label mt-3">禁用</label><input class="form-control" type="file" id="up3" disabled></div><div class="col-md-6"><div class="border border-2 rounded-3 p-4 text-center text-body-secondary bg-body-tertiary" style="border-style:dashed!important"><div class="fs-1">${icon("upload")}</div><div>拖拽文件到此处，或 <a href="#">点击上传</a></div><small>支持 PNG/JPG/PDF，≤ 10 MB</small></div><ul class="list-group list-group-flush mt-2"><li class="list-group-item d-flex align-items-center gap-2 px-0">${icon("file-plus")}<span class="flex-grow-1 text-truncate">report.pdf</span><div class="progress flex-grow-1" style="height:6px;max-width:120px" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"><div class="progress-bar" style="width:60%"></div></div><small>60%</small></li><li class="list-group-item d-flex align-items-center gap-2 px-0 text-success">${icon("check-circle")}<span class="flex-grow-1 text-truncate text-body">logo.png</span><button type="button" class="btn btn-sm btn-link text-danger p-0" aria-label="删除">${icon("trash")}</button></li></ul></div></div>`,
  Cascader: () => `<div class="row g-2"><div class="col-4"><select class="form-select" aria-label="省"><option>浙江</option><option>广东</option></select></div><div class="col-4"><select class="form-select" aria-label="市"><option>杭州</option><option>宁波</option></select></div><div class="col-4"><select class="form-select" aria-label="区"><option>西湖区</option><option>余杭区</option></select></div></div><div class="form-text">级联：三个联动 .form-select</div>`,
  Transfer: () => `<div class="row g-2 align-items-center"><div class="col"><div class="card"><div class="card-header py-2 small d-flex justify-content-between"><span>源列表</span><span class="text-body-secondary">3/5</span></div><div class="list-group list-group-flush" style="max-height:160px;overflow:auto">${each(team, (m, i) => `<label class="list-group-item d-flex gap-2 py-1"><input class="form-check-input" type="checkbox" ${i < 3 ? "checked" : ""}>${esc(m.name)}</label>`)}</div></div></div><div class="col-auto d-flex flex-column gap-2"><button type="button" class="btn btn-outline-secondary btn-sm" aria-label="移入">${icon("chevron-right")}</button><button type="button" class="btn btn-outline-secondary btn-sm" disabled aria-label="移出">${icon("chevron-left")}</button></div><div class="col"><div class="card"><div class="card-header py-2 small">目标列表</div><div class="list-group list-group-flush"><div class="list-group-item text-body-secondary small text-center py-4">暂无</div></div></div></div></div>`,
  Mention: () => missing("Bootstrap 无 @提及 输入组件；需要额外的联想弹层与 caret 定位逻辑，未在本应用中拼装。"),
  PinInput: () => `<div class="d-flex gap-2" role="group" aria-label="验证码">${each([1, 2, 3, 4, 5, 6], (n) => `<input type="text" inputmode="numeric" maxlength="1" class="form-control form-control-lg text-center pin-input" value="${n <= 3 ? n : ""}" aria-label="第 ${n} 位">`)}</div>`,
  Form: () => `<form class="row g-3 needs-validation" novalidate><div class="col-md-6"><label for="fmName" class="form-label">姓名</label><input class="form-control" id="fmName" required></div><div class="col-md-6"><label for="fmEmail" class="form-label">邮箱</label><input type="email" class="form-control" id="fmEmail" required><div class="invalid-feedback">请输入有效邮箱</div></div><div class="col-12"><div class="form-check"><input class="form-check-input" type="checkbox" id="fmAgree" required><label class="form-check-label" for="fmAgree">同意条款</label><div class="invalid-feedback">必须勾选</div></div></div><div class="col-12"><div class="row g-2 align-items-center"><label for="fmH" class="col-sm-2 col-form-label">水平布局</label><div class="col-sm-10"><input class="form-control" id="fmH"></div></div></div><div class="col-12 d-flex gap-2"><button class="btn btn-primary" type="submit">提交（触发校验）</button><button class="btn btn-outline-secondary" type="reset">重置</button></div></form>`,
  Table: () => `<div class="table-responsive"><table class="table table-hover table-striped align-middle"><caption>最近订单（table-striped table-hover）</caption><thead class="table-light"><tr><th>订单</th><th>客户</th><th>状态</th><th class="text-end">金额</th></tr></thead><tbody>${each(orders.slice(0, 4), (o) => `<tr><td><code>${o.id}</code></td><td>${esc(o.customer)}</td><td><span class="badge text-bg-${STATUS_COLOR[o.status]}">${STATUS_LABEL[o.status]}</span></td><td class="text-end">${money(o.amount)}</td></tr>`)}<tr class="table-active"><td colspan="3">选中行 .table-active</td><td class="text-end">—</td></tr></tbody></table></div>${row()}<table class="table table-sm table-bordered w-auto mb-0"><tr><td>table-sm</td><td>bordered</td></tr></table><table class="table table-dark w-auto mb-0"><tr><td>table-dark</td></tr></table><table class="table table-borderless w-auto mb-0"><tr><td>borderless</td></tr></table></div>`,
  DataGrid: () => `<div class="table-responsive border rounded" style="max-height:220px"><table class="table table-sm table-hover mb-0 align-middle" style="min-width:700px"><thead class="table-light sticky-top"><tr><th style="width:2rem"><input class="form-check-input" type="checkbox" aria-label="全选"></th><th class="text-nowrap">订单 <span class="text-body-tertiary">${icon("arrow-up")}</span></th><th>客户</th><th>渠道</th><th>状态</th><th class="text-end">金额</th><th></th></tr></thead><tbody>${each(orders.slice(0, 6), (o, i) => `<tr class="${i === 1 ? "table-primary" : ""}"><td><input class="form-check-input" type="checkbox" ${i === 1 ? "checked" : ""} aria-label="选择"></td><td><code>${o.id}</code></td><td class="text-nowrap">${esc(o.customer)}</td><td>${esc(o.channel)}</td><td><span class="badge rounded-pill text-bg-${STATUS_COLOR[o.status]}">${STATUS_LABEL[o.status]}</span></td><td class="text-end">${money(o.amount)}</td><td class="text-end"><button type="button" class="btn btn-sm btn-link p-0" aria-label="更多">${icon("more-horizontal")}</button></td></tr>`)}</tbody></table></div><div class="form-text">粘性表头 + 选择列 + 排序标记 + 横向滚动的组合 DataGrid</div>`,
  Descriptions: () => `<dl class="row mb-0 border rounded p-3"><dt class="col-sm-3">订单号</dt><dd class="col-sm-9"><code>${orders[0].id}</code></dd><dt class="col-sm-3">客户</dt><dd class="col-sm-9">${esc(orders[0].customer)}</dd><dt class="col-sm-3">状态</dt><dd class="col-sm-9"><span class="badge text-bg-${STATUS_COLOR[orders[0].status]}">${STATUS_LABEL[orders[0].status]}</span></dd><dt class="col-sm-3">金额</dt><dd class="col-sm-9 mb-0">${money(orders[0].amount)}</dd></dl>`,
  List: () => `<div class="row g-3"><div class="col-md-6"><ul class="list-group"><li class="list-group-item active" aria-current="true">激活项</li><li class="list-group-item">普通项</li><li class="list-group-item disabled" aria-disabled="true">禁用项</li><li class="list-group-item d-flex justify-content-between align-items-center">带角标<span class="badge text-bg-primary rounded-pill">14</span></li><li class="list-group-item list-group-item-success">success 上下文</li></ul></div><div class="col-md-6"><div class="list-group">${each(activity.slice(0, 3), (a) => `<a href="#" class="list-group-item list-group-item-action d-flex gap-2 align-items-start">${avatar(a.user, 32)}<div class="min-w-0"><div class="fw-medium text-truncate">${esc(a.user)}</div><small class="text-body-secondary">${esc(a.action)} · ${esc(a.time)}</small></div></a>`)}</div><ol class="list-group list-group-numbered mt-3"><li class="list-group-item">有序列表</li><li class="list-group-item">第二项</li></ol></div></div>`,
  Card: () => `<div class="row g-3"><div class="col-md-4"><div class="card h-100"><div class="ratio ratio-16x9 card-img-top bg-body-tertiary d-flex align-items-center justify-content-center text-body-tertiary"><div class="d-flex align-items-center justify-content-center fs-1">${icon("grid")}</div></div><div class="card-body"><h5 class="card-title">带图卡片</h5><p class="card-text">卡片正文内容。</p><a href="#" class="btn btn-primary btn-sm">操作</a></div></div></div><div class="col-md-4"><div class="card h-100"><div class="card-header">页头</div><div class="card-body"><h5 class="card-title">标题</h5><h6 class="card-subtitle mb-2 text-body-secondary">副标题</h6><p class="card-text">页头页脚卡片。</p></div><div class="card-footer text-body-secondary">页脚</div></div></div><div class="col-md-4"><div class="card text-bg-primary h-100"><div class="card-body"><h5 class="card-title">彩色卡片</h5><p class="card-text">text-bg-primary</p></div></div><div class="card border-success mt-2"><div class="card-body text-success py-2">border-success</div></div></div></div>`,
  Avatar: () => `${row()}${each([24, 32, 40, 56], (s) => avatar("林晓", s))}<span class="rounded bg-primary text-white d-inline-flex align-items-center justify-content-center" style="width:40px;height:40px">${icon("user")}</span><span class="rounded-circle bg-success-subtle text-success d-inline-flex align-items-center justify-content-center fs-4" style="width:40px;height:40px">${icon("bot")}</span><span class="position-relative d-inline-flex">${avatar("Alex Chen", 40)}<span class="position-absolute bottom-0 end-0 p-1 bg-success border border-light rounded-circle"><span class="visually-hidden">在线</span></span></span></div>`,
  AvatarGroup: () => `<div class="d-flex align-items-center">${each(team.slice(0, 4), (m, i) => `<span class="d-inline-flex" style="margin-left:${i ? -10 : 0}px">${avatar(m.name, 36, "border border-2 border-body")}</span>`)}<span class="d-inline-flex" style="margin-left:-10px">${avatar("+3", 36, "border border-2 border-body bg-body-tertiary")}</span></div>`,
  Badge: () => `${row("mb-2")}${each(COLORS, (c) => `<span class="badge text-bg-${c}">${c}</span>`)}</div>${row("mb-2")}${each(COLORS, (c) => `<span class="badge rounded-pill text-bg-${c}">${c}</span>`)}</div>${row()}<h4 class="mb-0">标题 <span class="badge text-bg-secondary">New</span></h4><button type="button" class="btn btn-primary position-relative">收件箱 <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">9+<span class="visually-hidden">未读</span></span></button><button type="button" class="btn btn-outline-secondary position-relative">${icon("bell")}<span class="position-absolute top-0 start-100 translate-middle p-1 bg-danger border border-light rounded-circle"><span class="visually-hidden">新通知</span></span></button><span class="badge bg-primary-subtle text-primary-emphasis rounded-pill">subtle</span></div>`,
  Tag: () => `${row()}${each(["设计", "前端", "紧急"], (t, i) => `<span class="badge rounded-pill ${["text-bg-light border", "text-bg-primary", "text-bg-danger"][i]} d-inline-flex align-items-center gap-1 fs-6 fw-normal">${icon("tag")}${t}<button type="button" class="btn-close ${i ? "btn-close-white" : ""}" style="font-size:.6em" aria-label="移除"></button></span>`)}<span class="badge bg-success-subtle text-success-emphasis border border-success-subtle fs-6 fw-normal">${icon("check")} 已完成</span><span class="badge bg-warning-subtle text-warning-emphasis border border-warning-subtle fs-6 fw-normal">待处理</span><button type="button" class="btn btn-sm btn-outline-secondary rounded-pill">${icon("plus")} 添加标签</button></div>`,
  Statistic: () => `<div class="row g-3">${each(stats, (s) => `<div class="col-6 col-lg-3"><div class="card"><div class="card-body"><div class="text-body-secondary small">${esc(s.label)}</div><div class="h3 mb-0">${"unit" in s && s.unit === "CNY" ? money(s.value) : s.value.toLocaleString("zh-CN")}</div><small class="${s.delta >= 0 ? "text-success" : "text-danger"}">${icon(s.delta >= 0 ? "arrow-up" : "arrow-down")} ${Math.abs(s.delta)}%</small></div></div></div>`)}</div>`,
  Timeline: () => `<ul class="list-unstyled mb-0 position-relative ps-4 border-start ms-2">${each(activity.slice(0, 4), (a, i) => `<li class="position-relative mb-3"><span class="position-absolute top-0 start-0 translate-middle-x rounded-circle ${i === 0 ? "bg-primary" : "bg-secondary-subtle border"}" style="width:12px;height:12px;left:-1.55rem!important;margin-top:4px"></span><div class="fw-medium">${esc(a.user)} <span class="fw-normal text-body-secondary">${esc(a.action)}</span></div><small class="text-body-secondary">${esc(a.time)}</small></li>`)}</ul>`,
  Tree: () => `<ul class="list-unstyled mb-0"><li><button class="btn btn-sm btn-link text-body text-decoration-none p-0 d-inline-flex align-items-center gap-1" type="button" data-bs-toggle="collapse" data-bs-target="#tree1" aria-expanded="true" aria-controls="tree1">${icon("chevron-down")}${icon("inbox")} 产品</button><ul class="list-unstyled ps-4 collapse show" id="tree1"><li><button class="btn btn-sm btn-link text-body text-decoration-none p-0 d-inline-flex align-items-center gap-1" type="button" data-bs-toggle="collapse" data-bs-target="#tree2" aria-expanded="false" aria-controls="tree2">${icon("chevron-right")}${icon("inbox")} 订单</button><ul class="list-unstyled ps-4 collapse" id="tree2"><li class="py-1 d-flex align-items-center gap-1"><div class="form-check mb-0"><input class="form-check-input" type="checkbox" id="tr1" checked><label class="form-check-label" for="tr1">列表</label></div></li><li class="py-1"><div class="form-check mb-0"><input class="form-check-input" type="checkbox" id="tr2"><label class="form-check-label" for="tr2">详情</label></div></li></ul></li><li class="py-1 ps-4 d-flex align-items-center gap-1 text-primary">${icon("list")} 客户（已选中）</li><li class="py-1 ps-4 d-flex align-items-center gap-1 text-body-tertiary">${icon("list")} 已归档（禁用）</li></ul></li></ul><div class="form-text">Collapse + 嵌套列表组合</div>`,
  Calendar: () => {
    const days = ["一", "二", "三", "四", "五", "六", "日"]
    return `<div class="card" style="max-width:360px"><div class="card-header d-flex justify-content-between align-items-center py-2"><button type="button" class="btn btn-sm btn-link text-body" aria-label="上月">${icon("chevron-left")}</button><strong>2026 年 9 月</strong><button type="button" class="btn btn-sm btn-link text-body" aria-label="下月">${icon("chevron-right")}</button></div><div class="card-body p-2"><div class="row row-cols-7 g-0 text-center small text-body-secondary">${each(days, (d) => `<div class="col py-1">${d}</div>`)}</div><div class="row row-cols-7 g-1 text-center">${each(Array.from({ length: 35 }, (_, i) => i - 1), (d) => `<div class="col"><button type="button" class="btn btn-sm w-100 ${d === 5 ? "btn-primary" : d >= 14 && d <= 18 ? "btn-primary bg-opacity-25 border-0 text-body" : d < 1 || d > 30 ? "text-body-tertiary" : "btn-light"}" ${d < 1 || d > 30 ? "disabled" : ""}>${d < 1 ? 31 + d : d > 30 ? d - 30 : d}</button></div>`)}</div></div></div>`
  },
  Image: () => `${row()}<div class="ratio ratio-4x3 img-thumbnail bg-body-tertiary d-flex align-items-center justify-content-center text-body-tertiary" style="width:160px"><div class="d-flex align-items-center justify-content-center fs-1">${icon("grid")}</div></div><div class="rounded-3 bg-body-tertiary d-flex align-items-center justify-content-center text-body-tertiary" style="width:120px;height:120px">${icon("grid", "fs-1")}</div><div class="rounded-circle bg-body-tertiary d-flex align-items-center justify-content-center text-body-tertiary" style="width:120px;height:120px">${icon("grid", "fs-1")}</div><figure class="figure mb-0"><div class="figure-img rounded bg-body-tertiary d-flex align-items-center justify-content-center text-body-tertiary" style="width:120px;height:80px">${icon("grid", "fs-2")}</div><figcaption class="figure-caption">带说明的 figure</figcaption></figure></div><div class="form-text">.img-fluid / .img-thumbnail / .rounded；不使用外部图片，用占位块演示</div>`,
  Carousel: () => `<div id="demoCarousel" class="carousel slide carousel-dark" data-bs-ride="false"><div class="carousel-indicators">${each([0, 1, 2], (i) => `<button type="button" data-bs-target="#demoCarousel" data-bs-slide-to="${i}" class="${i === 0 ? "active" : ""}" aria-label="第 ${i + 1} 张" ${i === 0 ? 'aria-current="true"' : ""}></button>`)}</div><div class="carousel-inner rounded-3">${each(["primary", "success", "info"], (c, i) => `<div class="carousel-item ${i === 0 ? "active" : ""}"><div class="bg-${c}-subtle d-flex align-items-center justify-content-center" style="height:220px"><span class="display-4 text-${c}">${icon("grid")}</span></div><div class="carousel-caption d-none d-md-block"><h5>幻灯 ${i + 1}</h5><p>说明文字</p></div></div>`)}</div><button class="carousel-control-prev" type="button" data-bs-target="#demoCarousel" data-bs-slide="prev"><span class="carousel-control-prev-icon" aria-hidden="true"></span><span class="visually-hidden">上一张</span></button><button class="carousel-control-next" type="button" data-bs-target="#demoCarousel" data-bs-slide="next"><span class="carousel-control-next-icon" aria-hidden="true"></span><span class="visually-hidden">下一张</span></button></div>`,
  Empty: () => `<div class="row g-3"><div class="col-md-6"><div class="border rounded-3 p-5 text-center text-body-secondary"><div class="display-5 text-body-tertiary">${icon("inbox")}</div><h5 class="text-body mt-2">暂无数据</h5><p class="mb-3">还没有任何订单，创建一个开始吧。</p><button type="button" class="btn btn-primary btn-sm">${icon("plus")} 新建订单</button></div></div><div class="col-md-6"><div class="border rounded-3 p-5 text-center text-body-secondary"><div class="display-5 text-body-tertiary">${icon("search")}</div><h5 class="text-body mt-2">无匹配结果</h5><p class="mb-0">试试其他关键词。</p></div></div></div>`,
  Tooltip: () => `${row()}${each(["top", "right", "bottom", "left"], (p) => `<button type="button" class="btn btn-outline-secondary" data-bs-toggle="tooltip" data-bs-placement="${p}" data-bs-title="${p} 提示">${p}</button>`)}<button type="button" class="btn btn-outline-secondary" data-bs-toggle="tooltip" data-bs-html="true" data-bs-title="<em>HTML</em> <b>提示</b>">HTML</button><span class="text-body-secondary" data-bs-toggle="tooltip" data-bs-title="图标说明">${icon("circle-help")}</span><button type="button" class="btn btn-outline-secondary" data-bs-toggle="tooltip" data-bs-custom-class="tooltip-lg" data-bs-title="较长的提示文字，会自动换行显示">长文本</button></div>`,
  Popover: () => `${row()}${each(["top", "right", "bottom", "left"], (p) => `<button type="button" class="btn btn-outline-primary" data-bs-toggle="popover" data-bs-placement="${p}" data-bs-title="标题" data-bs-content="${p} 方向的 Popover 内容。">${p}</button>`)}<button type="button" class="btn btn-outline-primary" data-bs-toggle="popover" data-bs-trigger="focus" data-bs-content="失焦即关闭">focus 触发</button><button type="button" class="btn btn-outline-primary" data-bs-toggle="popover" data-bs-trigger="hover focus" data-bs-content="悬停显示">hover 触发</button></div>`,
  QRCode: () => missing("Bootstrap 无二维码生成能力，需引入第三方编码库；本应用用占位块表示。") + `<div class="mt-3 border rounded-3 d-inline-flex align-items-center justify-content-center bg-body-tertiary text-body-tertiary" style="width:128px;height:128px">${icon("grid", "display-4")}</div>`,
  Segmented: () => `${row()}<div class="btn-group" role="group" aria-label="分段">${each(["日", "周", "月"], (t, i) => `<input type="radio" class="btn-check" name="seg1" id="seg1${i}" ${i === 1 ? "checked" : ""}><label class="btn btn-outline-secondary" for="seg1${i}">${t}</label>`)}</div><div class="btn-group btn-group-sm" role="group">${each(["list", "grid"] as const, (t, i) => `<input type="radio" class="btn-check" name="seg2" id="seg2${i}" ${i === 0 ? "checked" : ""}><label class="btn btn-outline-secondary" for="seg2${i}" aria-label="${t}">${icon(t)}</label>`)}</div><div class="btn-group btn-group-lg" role="group">${each(["A", "B", "C"], (t, i) => `<input type="radio" class="btn-check" name="seg3" id="seg3${i}" ${i === 2 ? "disabled" : ""} ${i === 0 ? "checked" : ""}><label class="btn btn-outline-primary" for="seg3${i}">${t}</label>`)}</div><ul class="nav nav-pills bg-body-tertiary rounded p-1 gap-1"><li class="nav-item"><a class="nav-link active py-1" href="#">概览</a></li><li class="nav-item"><a class="nav-link py-1" href="#">明细</a></li></ul></div>`,
  Alert: () => `${each(COLORS, (c) => `<div class="alert alert-${c} d-flex align-items-center gap-2 py-2" role="alert">${icon("alert-circle")}<div>${c} 提示，带 <a href="#" class="alert-link">链接</a>。</div></div>`)}<div class="alert alert-warning alert-dismissible fade show" role="alert"><h5 class="alert-heading">带标题可关闭</h5><p class="mb-0">点击右侧关闭按钮可移除此提示。</p><button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="关闭"></button></div>`,
  Toast: () => `${row("mb-3")}<button type="button" class="btn btn-primary" data-toast="success">成功 Toast</button><button type="button" class="btn btn-danger" data-toast="danger">错误 Toast</button><button type="button" class="btn btn-outline-secondary" data-toast="plain">带标题 Toast</button></div><div class="toast show" role="status" aria-live="polite" aria-atomic="true"><div class="toast-header">${icon("bell", "text-primary me-2")}<strong class="me-auto">系统通知</strong><small>刚刚</small><button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="关闭"></button></div><div class="toast-body">这是一个静态展示的 Toast。</div></div><div class="toast-container position-fixed top-0 end-0 p-3" id="demoToasts"></div>`,
  Notification: () => `<div class="d-flex flex-column gap-2" style="max-width:380px">${each([["success", "check-circle", "部署成功", "v2.3.1 已上线"], ["warning", "alert-circle", "配额提醒", "API 用量已达 85%"], ["danger", "x", "支付失败", "请更换支付方式"]] as const, ([c, ic, t, d]) => `<div class="toast show align-items-start border-${c}" role="alert" aria-live="assertive" aria-atomic="true"><div class="d-flex p-3 gap-2"><span class="text-${c} fs-5">${icon(ic)}</span><div class="flex-grow-1"><div class="fw-semibold">${t}</div><div class="text-body-secondary small">${d}</div><div class="mt-2 d-flex gap-2"><button type="button" class="btn btn-sm btn-${c}">查看</button><button type="button" class="btn btn-sm btn-link text-body-secondary p-0 px-1" data-bs-dismiss="toast">忽略</button></div></div><button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="关闭"></button></div></div>`)}</div>`,
  Dialog: () => `${row()}<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#dlg1">默认</button><button type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#dlg2">居中 · 小</button><button type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#dlg3">大 · 可滚动</button><button type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#dlg4">全屏</button><button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#dlg5">静态背景</button></div>
  <div class="modal fade" id="dlg1" tabindex="-1" aria-labelledby="dlg1t" aria-hidden="true"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="dlg1t">默认对话框</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="关闭"></button></div><div class="modal-body">Modal 内容。</div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">取消</button><button type="button" class="btn btn-primary" data-bs-dismiss="modal">确定</button></div></div></div></div>
  <div class="modal fade" id="dlg2" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-sm modal-dialog-centered"><div class="modal-content"><div class="modal-body text-center py-4"><div class="display-6 text-warning">${icon("alert-circle")}</div><h5>确认操作？</h5><p class="text-body-secondary">此操作不可撤销。</p><div class="d-flex gap-2 justify-content-center"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">取消</button><button type="button" class="btn btn-danger" data-bs-dismiss="modal">删除</button></div></div></div></div></div>
  <div class="modal fade" id="dlg3" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">可滚动</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="关闭"></button></div><div class="modal-body">${each(Array.from({ length: 12 }), (_, i) => `<p>第 ${i + 1} 段内容。</p>`)}</div><div class="modal-footer"><button type="button" class="btn btn-primary" data-bs-dismiss="modal">关闭</button></div></div></div></div>
  <div class="modal fade" id="dlg4" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-fullscreen"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">全屏</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="关闭"></button></div><div class="modal-body">全屏 modal。</div></div></div></div>
  <div class="modal fade" id="dlg5" tabindex="-1" data-bs-backdrop="static" data-bs-keyboard="false" aria-hidden="true"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">静态背景</h5></div><div class="modal-body">点击遮罩不会关闭。</div><div class="modal-footer"><button type="button" class="btn btn-primary" data-bs-dismiss="modal">知道了</button></div></div></div></div>`,
  Drawer: () => `${row()}${each(["start", "end", "top", "bottom"], (p) => `<button type="button" class="btn btn-outline-primary" data-bs-toggle="offcanvas" data-bs-target="#oc-${p}" aria-controls="oc-${p}">${p}</button><div class="offcanvas offcanvas-${p}" tabindex="-1" id="oc-${p}" aria-labelledby="oc-${p}-t"><div class="offcanvas-header border-bottom"><h5 class="offcanvas-title" id="oc-${p}-t">Offcanvas ${p}</h5><button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="关闭"></button></div><div class="offcanvas-body">抽屉内容。</div></div>`)}<button type="button" class="btn btn-outline-secondary" data-bs-toggle="offcanvas" data-bs-target="#oc-scroll" aria-controls="oc-scroll">无遮罩可滚动</button><div class="offcanvas offcanvas-end" data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1" id="oc-scroll"><div class="offcanvas-header border-bottom"><h5 class="offcanvas-title">无遮罩</h5><button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="关闭"></button></div><div class="offcanvas-body">背景页面仍可滚动。</div></div></div>`,
  Progress: () => `<div class="d-flex flex-column gap-3">${each([25, 50, 75, 100], (v, i) => `<div class="progress" role="progressbar" aria-label="进度 ${v}%" aria-valuenow="${v}" aria-valuemin="0" aria-valuemax="100"><div class="progress-bar ${["", "bg-success", "bg-warning", "bg-danger"][i]}" style="width:${v}%">${v}%</div></div>`)}<div class="progress" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="height:4px"><div class="progress-bar" style="width:60%"></div></div><div class="progress" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="height:24px"><div class="progress-bar progress-bar-striped progress-bar-animated" style="width:45%">条纹动画</div></div><div class="progress-stacked"><div class="progress" role="progressbar" style="width:30%"><div class="progress-bar">30</div></div><div class="progress" role="progressbar" style="width:20%"><div class="progress-bar bg-success">20</div></div><div class="progress" role="progressbar" style="width:15%"><div class="progress-bar bg-info">15</div></div></div><div class="d-flex align-items-center gap-3"><svg width="72" height="72" viewBox="0 0 36 36" class="flex-shrink-0" role="img" aria-label="环形进度 72%"><circle cx="18" cy="18" r="15.9" fill="none" stroke="var(--bs-secondary-bg)" stroke-width="3"/><circle cx="18" cy="18" r="15.9" fill="none" stroke="var(--bs-primary)" stroke-width="3" stroke-dasharray="72 28" stroke-linecap="round" transform="rotate(-90 18 18)"/><text x="18" y="21" text-anchor="middle" font-size="8" fill="currentColor">72%</text></svg><span class="text-body-secondary small">环形进度（SVG 组合）</span></div></div>`,
  Skeleton: () => `<div class="row g-3"><div class="col-md-6"><div class="card" aria-hidden="true"><div class="card-body"><h5 class="card-title placeholder-glow"><span class="placeholder col-6"></span></h5><p class="card-text placeholder-glow"><span class="placeholder col-7"></span> <span class="placeholder col-4"></span> <span class="placeholder col-4"></span> <span class="placeholder col-6"></span></p><a class="btn btn-primary disabled placeholder col-4" aria-disabled="true"></a></div></div></div><div class="col-md-6"><div class="d-flex gap-2 align-items-center mb-3 placeholder-wave" aria-hidden="true"><span class="placeholder rounded-circle" style="width:40px;height:40px"></span><div class="flex-grow-1"><span class="placeholder col-5 d-block mb-1"></span><span class="placeholder col-8 d-block placeholder-sm"></span></div></div><p class="placeholder-glow mb-0" aria-hidden="true"><span class="placeholder col-12 placeholder-lg"></span><span class="placeholder col-12"></span><span class="placeholder col-12 placeholder-xs"></span><span class="placeholder col-8 bg-primary"></span></p></div></div>`,
  Spinner: () => `${row()}${each(COLORS, (c) => `<div class="spinner-border text-${c}" role="status"><span class="visually-hidden">加载中</span></div>`)}</div>${row("mt-3")}${each(COLORS.slice(0, 4), (c) => `<div class="spinner-grow text-${c}" role="status"><span class="visually-hidden">加载中</span></div>`)}<div class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></div><div class="spinner-border" style="width:3rem;height:3rem" role="status" aria-hidden="true"></div><button class="btn btn-primary" type="button" disabled><span class="spinner-border spinner-border-sm me-1" aria-hidden="true"></span>加载中…</button></div>`,
  Result: () => `<div class="row g-3">${each([["success", "check-circle", "提交成功", "我们已收到你的申请。"], ["danger", "x", "提交失败", "网络错误，请重试。"], ["warning", "alert-circle", "403 无权限", "请联系管理员开通。"], ["secondary", "search", "404 未找到", "页面不存在。"]] as const, ([c, ic, t, d]) => `<div class="col-md-6 col-xl-3"><div class="text-center border rounded-3 p-4 h-100"><div class="display-4 text-${c}">${icon(ic)}</div><h5 class="mt-2">${t}</h5><p class="text-body-secondary">${d}</p><button type="button" class="btn btn-${c === "secondary" ? "primary" : c} btn-sm">${c === "danger" ? "重试" : "返回"}</button></div></div>`)}</div>`,
  Popconfirm: () => `${row()}<button type="button" class="btn btn-outline-danger" data-bs-toggle="popover" data-bs-html="true" data-bs-sanitize="false" data-bs-trigger="click" data-bs-title="确定删除？" data-bs-content="<div class='d-flex gap-2 justify-content-end'><button type='button' class='btn btn-sm btn-outline-secondary' data-pop-close>取消</button><button type='button' class='btn btn-sm btn-danger' data-pop-close>删除</button></div>">${icon("trash")} 删除（Popconfirm）</button><button type="button" class="btn btn-outline-secondary" data-bs-toggle="popover" data-bs-html="true" data-bs-sanitize="false" data-bs-placement="bottom" data-bs-title="归档此项？" data-bs-content="<button type='button' class='btn btn-sm btn-primary w-100' data-pop-close>确认</button>">${icon("archive")} 归档</button></div>`,
  Menu: () => `<div class="row g-3"><div class="col-md-4"><div class="list-group">${each([["home", "首页", true], ["shopping-cart", "订单", false], ["users", "客户", false], ["settings", "设置", false]] as const, ([ic, l, a]) => `<a href="#" class="list-group-item list-group-item-action d-flex align-items-center gap-2 ${a ? "active" : ""}" ${a ? 'aria-current="true"' : ""}>${icon(ic)}${l}${l === "订单" ? '<span class="badge text-bg-danger rounded-pill ms-auto">3</span>' : ""}</a>`)}<span class="list-group-item disabled text-body-tertiary d-flex align-items-center gap-2">${icon("lock")}禁用项</span></div></div><div class="col-md-8"><ul class="nav nav-underline mb-3"><li class="nav-item"><a class="nav-link active" aria-current="page" href="#">概览</a></li><li class="nav-item"><a class="nav-link" href="#">分析</a></li><li class="nav-item dropdown"><a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">更多</a><ul class="dropdown-menu"><li><a class="dropdown-item" href="#">子项</a></li></ul></li><li class="nav-item"><a class="nav-link disabled" aria-disabled="true">禁用</a></li></ul><ul class="nav flex-column nav-pills"><li class="nav-item"><a class="nav-link active" href="#">纵向菜单 · 激活</a></li><li class="nav-item"><a class="nav-link" href="#">纵向菜单</a></li></ul></div></div>`,
  Dropdown: () => `${row()}<div class="dropdown"><button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">默认</button><ul class="dropdown-menu"><li><h6 class="dropdown-header">分组标题</h6></li><li><a class="dropdown-item d-flex align-items-center gap-2" href="#">${icon("edit")}编辑</a></li><li><a class="dropdown-item active" href="#">激活项</a></li><li><a class="dropdown-item disabled" aria-disabled="true">禁用项</a></li><li><hr class="dropdown-divider"></li><li><a class="dropdown-item text-danger" href="#">删除</a></li></ul></div><div class="dropdown"><button class="btn btn-outline-secondary dropdown-toggle btn-sm" type="button" data-bs-toggle="dropdown" aria-expanded="false">小号</button><ul class="dropdown-menu"><li><a class="dropdown-item" href="#">项</a></li></ul></div><div class="dropup"><button class="btn btn-outline-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">向上</button><ul class="dropdown-menu"><li><a class="dropdown-item" href="#">项</a></li></ul></div><div class="dropend"><button class="btn btn-outline-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">向右</button><ul class="dropdown-menu"><li><a class="dropdown-item" href="#">项</a></li></ul></div><div class="dropdown"><button class="btn btn-outline-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false">含表单</button><form class="dropdown-menu p-3" style="min-width:240px"><div class="mb-2"><input class="form-control form-control-sm" placeholder="搜索"></div><div class="form-check"><input class="form-check-input" type="checkbox" id="ddck"><label class="form-check-label" for="ddck">记住</label></div></form></div><div class="dropdown"><button class="btn btn-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">深色菜单</button><ul class="dropdown-menu dropdown-menu-end" data-bs-theme="dark"><li><a class="dropdown-item" href="#">深色项</a></li></ul></div></div>`,
  Breadcrumb: () => `<nav aria-label="面包屑"><ol class="breadcrumb mb-2"><li class="breadcrumb-item"><a href="#">首页</a></li><li class="breadcrumb-item"><a href="#">订单</a></li><li class="breadcrumb-item active" aria-current="page">ORD-1001</li></ol></nav><nav aria-label="带图标" style="--bs-breadcrumb-divider: '›'"><ol class="breadcrumb mb-0"><li class="breadcrumb-item"><a href="#" class="d-inline-flex align-items-center gap-1">${icon("home")}首页</a></li><li class="breadcrumb-item"><a href="#">设置</a></li><li class="breadcrumb-item active" aria-current="page">团队</li></ol></nav>`,
  Tabs: () => `<ul class="nav nav-tabs" role="tablist">${each(["概览", "明细", "设置", "禁用"], (t, i) => `<li class="nav-item" role="presentation"><button class="nav-link ${i === 0 ? "active" : ""} ${i === 3 ? "disabled" : ""}" data-bs-toggle="tab" data-bs-target="#ctab${i}" type="button" role="tab" aria-selected="${i === 0}">${t}</button></li>`)}</ul><div class="tab-content border border-top-0 rounded-bottom p-3 mb-3">${each(["概览内容", "明细内容", "设置内容"], (t, i) => `<div class="tab-pane fade ${i === 0 ? "show active" : ""}" id="ctab${i}" role="tabpanel">${t}</div>`)}</div>${row()}<ul class="nav nav-pills"><li class="nav-item"><a class="nav-link active" href="#">Pills</a></li><li class="nav-item"><a class="nav-link" href="#">第二</a></li></ul><ul class="nav nav-underline"><li class="nav-item"><a class="nav-link active" href="#">Underline</a></li><li class="nav-item"><a class="nav-link" href="#">第二</a></li></ul><ul class="nav nav-pills flex-column"><li class="nav-item"><a class="nav-link active" href="#">纵向</a></li><li class="nav-item"><a class="nav-link" href="#">纵向</a></li></ul><ul class="nav nav-tabs nav-fill flex-grow-1"><li class="nav-item"><a class="nav-link active" href="#">fill</a></li><li class="nav-item"><a class="nav-link" href="#">fill</a></li></ul></div>`,
  Pagination: () => `${each(SIZES, ([s]) => `<nav aria-label="分页 ${s}"><ul class="pagination ${s ? `pagination-${s}` : ""} mb-2 flex-wrap"><li class="page-item disabled"><a class="page-link" aria-disabled="true">«</a></li><li class="page-item active" aria-current="page"><a class="page-link" href="#">1</a></li><li class="page-item"><a class="page-link" href="#">2</a></li><li class="page-item"><a class="page-link" href="#">3</a></li><li class="page-item disabled"><span class="page-link">…</span></li><li class="page-item"><a class="page-link" href="#">12</a></li><li class="page-item"><a class="page-link" href="#">»</a></li></ul></nav>`)}<div class="d-flex flex-wrap align-items-center gap-2 text-body-secondary small">共 120 条 · 每页 <select class="form-select form-select-sm w-auto" aria-label="每页条数"><option>10</option><option>20</option></select> 条 · 跳至 <input type="number" class="form-control form-control-sm" style="width:4rem" value="1" aria-label="页码"> 页</div>`,
  Steps: () => `<ol class="d-flex list-unstyled align-items-center gap-2 mb-3 overflow-auto">${each(["基本信息", "详细配置", "确认", "完成"], (t, i) => `<li class="d-flex align-items-center gap-2 flex-shrink-0 ${i < 3 ? "flex-grow-1" : ""}"><span class="rounded-circle d-inline-flex align-items-center justify-content-center fw-semibold ${i < 1 ? "bg-success text-white" : i === 1 ? "bg-primary text-white" : "bg-body-tertiary text-body-secondary border"}" style="width:32px;height:32px">${i < 1 ? icon("check") : i + 1}</span><span class="${i === 1 ? "fw-semibold" : "text-body-secondary"} text-nowrap">${t}</span>${i < 3 ? `<span class="flex-grow-1 border-top ${i < 1 ? "border-success" : ""}" style="min-width:24px"></span>` : ""}</li>`)}</ol><div class="progress mb-3" role="progressbar" aria-label="步骤进度" aria-valuenow="2" aria-valuemin="0" aria-valuemax="4" style="height:6px"><div class="progress-bar" style="width:50%"></div></div><ul class="list-unstyled ps-4 border-start ms-3 mb-0 d-md-none">${each(["基本信息 ✓", "详细配置（当前）", "确认"], (t) => `<li class="mb-2 small">${t}</li>`)}</ul><div class="form-text">Bootstrap 无 Steps 组件，用 flex + 圆形角标 + progress 组合</div>`,
  Anchor: () => `<div class="row g-3"><div class="col-4"><nav id="anchorNav" class="flex-column align-items-stretch nav nav-pills"><a class="nav-link py-1" href="#anc1">第一节</a><a class="nav-link py-1" href="#anc2">第二节</a><a class="nav-link py-1" href="#anc3">第三节</a></nav></div><div class="col-8"><div data-bs-spy="scroll" data-bs-target="#anchorNav" data-bs-smooth-scroll="true" class="overflow-auto border rounded p-3 scrollspy-demo" style="height:180px" tabindex="0"><h6 id="anc1">第一节</h6><p>${"内容 ".repeat(40)}</p><h6 id="anc2">第二节</h6><p>${"内容 ".repeat(40)}</p><h6 id="anc3">第三节</h6><p>${"内容 ".repeat(40)}</p></div></div></div><div class="form-text">Scrollspy 原生组件</div>`,
  BackTop: () => `${row()}<button type="button" class="btn btn-primary rounded-circle shadow d-inline-flex align-items-center justify-content-center" style="width:44px;height:44px" data-action="back-top" aria-label="回到顶部">${icon("arrow-up")}</button><span class="text-body-secondary small">.position-fixed.bottom-0.end-0 + window.scrollTo 组合，页面右下角有实例</span></div>`,
  Affix: () => `<div class="border rounded overflow-auto" style="height:160px"><div class="sticky-top bg-warning-subtle border-bottom px-3 py-2 fw-semibold">sticky-top 固定头（Affix）</div>${each(Array.from({ length: 10 }), (_, i) => `<p class="px-3 mb-2">滚动内容 ${i + 1}</p>`)}</div>`,
  Navbar: () => `<nav class="navbar navbar-expand-md bg-body-tertiary border rounded mb-3"><div class="container-fluid"><a class="navbar-brand d-flex align-items-center gap-2" href="#">${icon("boxes")} Brand</a><button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nbDemo" aria-controls="nbDemo" aria-expanded="false" aria-label="切换导航"><span class="navbar-toggler-icon"></span></button><div class="collapse navbar-collapse" id="nbDemo"><ul class="navbar-nav me-auto"><li class="nav-item"><a class="nav-link active" aria-current="page" href="#">首页</a></li><li class="nav-item"><a class="nav-link" href="#">产品</a></li><li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">更多</a><ul class="dropdown-menu"><li><a class="dropdown-item" href="#">子项</a></li></ul></li><li class="nav-item"><a class="nav-link disabled" aria-disabled="true">禁用</a></li></ul><form class="d-flex gap-2" role="search"><input class="form-control" type="search" placeholder="搜索" aria-label="搜索"><button class="btn btn-outline-primary" type="submit">搜索</button></form></div></div></nav><nav class="navbar bg-dark border rounded" data-bs-theme="dark"><div class="container-fluid"><span class="navbar-brand">深色 Navbar</span><span class="navbar-text">navbar-text</span></div></nav>`,
  Sidebar: () => `<div class="d-flex border rounded overflow-hidden" style="height:260px"><div class="d-flex flex-column flex-shrink-0 p-3 bg-body-tertiary border-end" style="width:200px"><span class="fw-semibold mb-3 d-flex align-items-center gap-2">${icon("boxes")} Acme</span><ul class="nav nav-pills flex-column mb-auto gap-1">${each([["home", "概览", true], ["shopping-cart", "订单", false], ["users", "团队", false]] as const, ([ic, l, a]) => `<li class="nav-item"><a href="#" class="nav-link d-flex align-items-center gap-2 ${a ? "active" : "link-body-emphasis"}" ${a ? 'aria-current="page"' : ""}>${icon(ic)}${l}</a></li>`)}</ul><hr><div class="d-flex align-items-center gap-2 small">${avatar("林晓", 28)}林晓</div></div><div class="d-flex flex-column flex-shrink-0 py-3 bg-body-tertiary border-end text-center" style="width:56px"><ul class="nav nav-pills flex-column mb-auto gap-1 px-2">${each(["home", "shopping-cart", "users"] as const, (ic, i) => `<li><a href="#" class="nav-link py-2 px-0 ${i === 0 ? "active" : "link-body-emphasis"}" aria-label="${ic}">${icon(ic)}</a></li>`)}</ul></div><div class="p-3 text-body-secondary small">展开态与折叠态两种侧栏（nav-pills 纵向组合）</div></div>`,
  CommandPalette: () => `<button type="button" class="btn btn-outline-secondary d-inline-flex align-items-center gap-2" data-bs-toggle="modal" data-bs-target="#cmdk">${icon("search")} 搜索命令… <kbd class="ms-2">⌘K</kbd></button><div class="modal fade" id="cmdk" tabindex="-1" aria-label="命令面板" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="p-2 border-bottom"><div class="input-group"><span class="input-group-text border-0 bg-transparent">${icon("search")}</span><input class="form-control border-0 shadow-none" placeholder="输入命令或搜索…" autofocus aria-label="命令"></div></div><div class="modal-body p-2"><div class="small text-body-secondary px-2 py-1">页面</div><div class="list-group list-group-flush">${each([["home", "概览"], ["shopping-cart", "订单"], ["settings", "设置"]] as const, ([ic, l], i) => `<button type="button" class="list-group-item list-group-item-action d-flex align-items-center gap-2 rounded ${i === 0 ? "active" : ""}">${icon(ic)}${l}<kbd class="ms-auto">↵</kbd></button>`)}</div><div class="small text-body-secondary px-2 py-1 mt-2">操作</div><div class="list-group list-group-flush"><button type="button" class="list-group-item list-group-item-action d-flex align-items-center gap-2 rounded">${icon("moon")}切换深色模式</button></div></div><div class="modal-footer py-1 small text-body-secondary justify-content-start gap-3"><span><kbd>↑</kbd><kbd>↓</kbd> 选择</span><span><kbd>↵</kbd> 打开</span><span><kbd>Esc</kbd> 关闭</span></div></div></div></div>`,
  Grid: () => `<div class="row g-2 text-center small mb-2">${each([12], () => `<div class="col-12"><div class="bg-primary-subtle rounded py-2">col-12</div></div>`)}${each([6, 6], (c) => `<div class="col-${c}"><div class="bg-primary-subtle rounded py-2">col-${c}</div></div>`)}${each([4, 4, 4], (c) => `<div class="col-md-${c}"><div class="bg-primary-subtle rounded py-2">col-md-${c}</div></div>`)}${each([3, 3, 3, 3], (c) => `<div class="col-6 col-lg-${c}"><div class="bg-primary-subtle rounded py-2">col-6 col-lg-${c}</div></div>`)}<div class="col"><div class="bg-success-subtle rounded py-2">col</div></div><div class="col-auto"><div class="bg-success-subtle rounded py-2 px-3">col-auto</div></div><div class="col"><div class="bg-success-subtle rounded py-2">col</div></div></div><div class="row row-cols-2 row-cols-md-4 g-2 text-center small">${each([1, 2, 3, 4], (n) => `<div class="col"><div class="bg-info-subtle rounded py-2">row-cols ${n}</div></div>`)}</div>`,
  Stack: () => `<div class="row g-3"><div class="col-md-6"><div class="vstack gap-2"><div class="bg-body-tertiary border rounded p-2">vstack 1</div><div class="bg-body-tertiary border rounded p-2">vstack 2</div><div class="bg-body-tertiary border rounded p-2">vstack 3</div></div></div><div class="col-md-6"><div class="hstack gap-2"><div class="bg-body-tertiary border rounded p-2">hstack</div><div class="bg-body-tertiary border rounded p-2 ms-auto">ms-auto</div><div class="vr"></div><div class="bg-body-tertiary border rounded p-2">end</div></div></div></div>`,
  Layout: () => `<div class="border rounded overflow-hidden" style="height:220px"><div class="d-flex flex-column h-100"><header class="bg-body-tertiary border-bottom px-3 py-2 small fw-semibold">Header</header><div class="d-flex flex-grow-1 min-h-0"><aside class="bg-body-tertiary border-end p-2 small d-none d-sm-block" style="width:120px">Sider</aside><main class="flex-grow-1 p-3 small">Content（flex 布局组合）</main></div><footer class="bg-body-tertiary border-top px-3 py-2 small">Footer</footer></div></div>`,
  Container: () => `<div class="container border rounded py-2 text-center small mb-2 bg-body-tertiary">.container（响应式定宽）</div><div class="container-fluid border rounded py-2 text-center small mb-2 bg-body-tertiary">.container-fluid</div><div class="container-md border rounded py-2 text-center small bg-body-tertiary">.container-md</div>`,
  AspectRatio: () => `<div class="row g-3">${each(["1x1", "4x3", "16x9", "21x9"], (r) => `<div class="col-6 col-md-3"><div class="ratio ratio-${r} bg-body-tertiary border rounded"><div class="d-flex align-items-center justify-content-center small text-body-secondary">ratio-${r}</div></div></div>`)}</div>`,
  Resizable: () => missing("Bootstrap 无可拖拽分栏组件，需自行编写拖拽逻辑；此处用 CSS resize 演示原生浏览器能力。") + `<div class="mt-3 border rounded p-3 bg-body-tertiary small" style="resize:both;overflow:auto;min-height:80px;max-width:100%">可用右下角拖动改变大小（浏览器原生 CSS resize，非 Bootstrap）</div>`,
  ScrollArea: () => `<div class="row g-3"><div class="col-md-6"><div class="overflow-auto border rounded p-3" style="height:140px">${each(Array.from({ length: 12 }), (_, i) => `<p class="mb-1 small">纵向滚动内容 ${i + 1}</p>`)}</div></div><div class="col-md-6"><div class="overflow-x-auto border rounded p-3 text-nowrap"><div class="d-inline-flex gap-2">${each(Array.from({ length: 12 }), (_, i) => `<span class="badge text-bg-secondary p-3">横向 ${i + 1}</span>`)}</div></div></div></div>`,
  Accordion: () => `<div class="accordion mb-3" id="acc1">${each(["第一项", "第二项", "第三项"], (t, i) => `<div class="accordion-item"><h2 class="accordion-header"><button class="accordion-button ${i ? "collapsed" : ""}" type="button" data-bs-toggle="collapse" data-bs-target="#acc1-${i}" aria-expanded="${i === 0}" aria-controls="acc1-${i}">${t}</button></h2><div id="acc1-${i}" class="accordion-collapse collapse ${i ? "" : "show"}" data-bs-parent="#acc1"><div class="accordion-body">${t}内容。</div></div></div>`)}</div><div class="accordion accordion-flush" id="acc2">${each(["Flush 样式 A", "Flush 样式 B"], (t, i) => `<div class="accordion-item"><h2 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#acc2-${i}" aria-expanded="false" aria-controls="acc2-${i}">${t}</button></h2><div id="acc2-${i}" class="accordion-collapse collapse"><div class="accordion-body">可同时展开多个（无 data-bs-parent）。</div></div></div>`)}</div>`,
  ThemeProvider: () => `${row()}<button type="button" class="btn btn-outline-secondary" data-action="toggle-theme">${icon("sun")} / ${icon("moon")} 切换全局主题</button><div class="p-3 border rounded" data-bs-theme="dark"><span class="me-2">局部 data-bs-theme="dark"</span><button type="button" class="btn btn-primary btn-sm">按钮</button> <span class="badge text-bg-light">badge</span></div><div class="p-3 border rounded" data-bs-theme="light"><span class="me-2">局部 data-bs-theme="light"</span><button type="button" class="btn btn-primary btn-sm">按钮</button></div><div class="form-text w-100">通过 ?theme=light|dark 或 &lt;html data-bs-theme&gt; 控制；Bootstrap 5.3 原生色彩模式</div></div>`,
  Watermark: () => missing("Bootstrap 无水印组件；需要 canvas 生成平铺背景，未在本应用中拼装。"),
  Tour: () => missing("Bootstrap 无引导（Tour）组件；虽可用 Popover 逐步引导，但缺少遮罩、步骤管理，未拼装。"),
  FloatButton: () => `<div class="position-relative border rounded bg-body-tertiary" style="height:160px"><div class="position-absolute bottom-0 end-0 p-3 d-flex flex-column gap-2 align-items-end"><button type="button" class="btn btn-light border rounded-circle shadow-sm d-inline-flex align-items-center justify-content-center" style="width:40px;height:40px" aria-label="帮助">${icon("circle-help")}</button><button type="button" class="btn btn-light border rounded-circle shadow-sm d-inline-flex align-items-center justify-content-center" style="width:40px;height:40px" aria-label="消息">${icon("message-circle")}</button><button type="button" class="btn btn-primary rounded-circle shadow d-inline-flex align-items-center justify-content-center" style="width:48px;height:48px" aria-label="新建">${icon("plus")}</button></div></div>`,
  Kbd: () => `<p class="mb-0">按 <kbd>Ctrl</kbd> + <kbd>C</kbd> 复制；<kbd><kbd>⌘</kbd> + <kbd>K</kbd></kbd> 打开命令面板；<kbd>Esc</kbd> 关闭。</p>`,
  Code: () => `<p>行内代码 <code>&lt;section&gt;</code>、变量 <var>y</var> = <var>mx</var> + <var>b</var>、输出 <samp>Done.</samp></p><pre class="bg-body-tertiary border rounded p-3 mb-2 user-select-all"><code>npm i bootstrap@5.3.8
import * as bootstrap from "bootstrap"</code></pre><pre class="bg-dark text-light rounded p-3 mb-0" data-bs-theme="dark"><code>SELECT * FROM orders WHERE status = 'paid';</code></pre>`,
  Divider: () => `<p class="mb-1">上方内容</p><hr><p class="mb-1">默认 hr</p><hr class="border border-primary border-2 opacity-75"><p class="mb-1">彩色加粗</p><hr class="border-dashed" style="border-top:1px dashed var(--bs-border-color);opacity:1"><div class="d-flex align-items-center gap-2 my-3"><hr class="flex-grow-1"><span class="text-body-secondary small">带文字分隔</span><hr class="flex-grow-1"></div><div class="hstack gap-3"><span>左</span><div class="vr"></div><span>竖线 .vr</span><div class="vr"></div><span>右</span></div>`,
  Link: () => `${row()}<a href="#">默认链接</a>${each(COLORS, (c) => `<a href="#" class="link-${c}">link-${c}</a>`)}<a href="#" class="link-body-emphasis">body-emphasis</a></div>${row("mt-2")}<a href="#" class="link-offset-2 link-underline link-underline-opacity-25 link-underline-opacity-100-hover">下划线偏移+悬停</a><a href="#" class="link-underline-opacity-0">无下划线</a><a href="#" class="icon-link">图标链接 ${icon("arrow-right")}</a><a class="stretched-link" href="#">stretched-link</a><a href="#" class="disabled pe-none text-body-tertiary" aria-disabled="true">禁用链接</a></div>`,
}

export function renderComponents(): PageResult {
  const names = Object.keys(coverage) as ComponentName[]
  const counts = names.reduce<Record<Coverage, number>>((acc, n) => { acc[coverage[n]]++; return acc }, { implemented: 0, composed: 0, missing: 0 })
  const html = `<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4">
    <div><h1 class="h3 mb-1">组件总览</h1><p class="text-body-secondary mb-0">contract.json 共 ${names.length} 个组件：${each(["implemented", "composed", "missing"] as Coverage[], (c) => `<span class="badge ${COVER_BADGE[c]} me-1">${COVER_LABEL[c]} ${counts[c]}</span>`)}</p></div>
    <div class="input-group" style="max-width:320px"><span class="input-group-text">${icon("search")}</span><input type="search" class="form-control" id="compFilter" placeholder="筛选组件…" aria-label="筛选组件"></div>
  </div>
  <div class="row g-3">
    <nav class="col-xl-2 d-none d-xl-block"><div class="sticky-top" style="top:80px;max-height:calc(100vh - 96px);overflow:auto"><ul class="nav nav-pills flex-column small gap-0" id="compNav">${each(names, (n) => `<li class="nav-item"><a class="nav-link py-1 px-2 d-flex align-items-center gap-2" href="#c-${n}" data-comp-nav="${n}"><span class="rounded-circle d-inline-block ${COVER_BADGE[coverage[n]]}" style="width:8px;height:8px"></span>${n}</a></li>`)}</ul></div></nav>
    <div class="col-xl-10">${each(names, (n) => `<section class="card mb-3 comp-section" id="c-${n}" data-comp="${n.toLowerCase()}" data-cover="${coverage[n]}"><div class="card-header d-flex align-items-center gap-2 flex-wrap"><h2 class="h5 mb-0">${n}</h2><span class="badge ${COVER_BADGE[coverage[n]]}">${COVER_LABEL[coverage[n]]} · ${coverage[n]}</span></div><div class="card-body">${demos[n]()}</div></section>`)}</div>
  </div>
  <button type="button" class="btn btn-primary rounded-circle shadow position-fixed bottom-0 end-0 m-4 d-inline-flex align-items-center justify-content-center" style="width:44px;height:44px;z-index:1030" data-action="back-top" aria-label="回到顶部">${icon("arrow-up")}</button>`

  const mount = (root: HTMLElement) => {
    root.querySelectorAll<HTMLInputElement>("[data-indeterminate]").forEach((el) => { el.indeterminate = true })
    root.querySelectorAll<HTMLInputElement>("input[type=range][data-output]").forEach((el) => el.addEventListener("input", () => { root.querySelector(`#${el.dataset.output}`)!.textContent = el.value }))
    root.querySelectorAll<HTMLButtonElement>("[data-step]").forEach((b) => b.addEventListener("click", () => { const q = root.querySelector<HTMLInputElement>("#numQty")!; q.stepUp(Number(b.dataset.step)) }))
    root.querySelectorAll<HTMLInputElement>(".pin-input").forEach((el, i, all) => el.addEventListener("input", () => { if (el.value && all[i + 1]) all[i + 1].focus() }))
    root.querySelectorAll<HTMLFormElement>(".needs-validation").forEach((f) => f.addEventListener("submit", (e) => { e.preventDefault(); f.classList.add("was-validated") }))
    const toasts = root.querySelector<HTMLElement>("#demoToasts")!
    root.querySelectorAll<HTMLButtonElement>("[data-toast]").forEach((b) => b.addEventListener("click", () => {
      const kind = b.dataset.toast
      toasts.insertAdjacentHTML("beforeend", kind === "plain"
        ? `<div class="toast" role="status" aria-live="polite" aria-atomic="true"><div class="toast-header">${icon("bell", "text-primary me-2")}<strong class="me-auto">通知</strong><small>刚刚</small><button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="关闭"></button></div><div class="toast-body">带标题的 Toast 内容。</div></div>`
        : `<div class="toast align-items-center text-bg-${kind} border-0" role="status" aria-live="polite" aria-atomic="true"><div class="d-flex"><div class="toast-body">${kind === "success" ? "操作成功" : "操作失败，请重试"}</div><button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="关闭"></button></div></div>`)
      const el = toasts.lastElementChild as HTMLElement
      el.addEventListener("hidden.bs.toast", () => el.remove())
      new bootstrap.Toast(el, { delay: 2500 }).show()
    }))
    root.addEventListener("click", (e) => {
      const t = e.target as HTMLElement
      if (t.closest("[data-pop-close]")) root.querySelectorAll<HTMLElement>('[data-bs-toggle="popover"]').forEach((p) => bootstrap.Popover.getInstance(p)?.hide())
      if (t.closest('[data-action="back-top"]')) window.scrollTo({ top: 0, behavior: "smooth" })
    })
    const filter = root.querySelector<HTMLInputElement>("#compFilter")!
    filter.addEventListener("input", () => {
      const q = filter.value.trim().toLowerCase()
      root.querySelectorAll<HTMLElement>(".comp-section").forEach((s) => { s.classList.toggle("d-none", !!q && !s.dataset.comp!.includes(q) && !s.dataset.cover!.includes(q)) })
    })
    root.querySelectorAll<HTMLElement>('[data-bs-spy="scroll"]').forEach((el) => new bootstrap.ScrollSpy(el))
    root.querySelectorAll<HTMLElement>(".carousel").forEach((el) => new bootstrap.Carousel(el))
    return () => root.querySelectorAll<HTMLElement>('[data-bs-spy="scroll"], .carousel').forEach((el) => { bootstrap.ScrollSpy.getInstance(el)?.dispose(); bootstrap.Carousel.getInstance(el)?.dispose() })
  }
  return { html, mount }
}
