import { useEffect, useState, type CSSProperties } from "react"
import { Icon } from "@ui-gallery/icons-react"
import contract from "@ui-gallery/spec/contract.json"
import { coverage, daisyExtras, type CoverageStatus } from "../coverage"
import { useTheme } from "../App"
import { PageHeader } from "./shared"

const colors = ["neutral", "primary", "secondary", "accent", "info", "success", "warning", "error"] as const
const sizes = ["xs", "sm", "md", "lg", "xl"] as const
type Color = (typeof colors)[number]
type Size = (typeof sizes)[number]

// Tailwind v4 只扫描源码中的完整类名字面量，因此 variant 类名必须静态写出，不能模板拼接。
const btnColor: Record<Color, string> = { neutral: "btn btn-neutral", primary: "btn btn-primary", secondary: "btn btn-secondary", accent: "btn btn-accent", info: "btn btn-info", success: "btn btn-success", warning: "btn btn-warning", error: "btn btn-error" }
const btnSize: Record<Size, string> = { xs: "btn btn-xs", sm: "btn btn-sm", md: "btn btn-md", lg: "btn btn-lg", xl: "btn btn-xl" }
const badgeColor: Record<Color, string> = { neutral: "badge badge-neutral", primary: "badge badge-primary", secondary: "badge badge-secondary", accent: "badge badge-accent", info: "badge badge-info", success: "badge badge-success", warning: "badge badge-warning", error: "badge badge-error" }
const badgeSize: Record<Size, string> = { xs: "badge badge-xs", sm: "badge badge-sm", md: "badge badge-md", lg: "badge badge-lg", xl: "badge badge-xl" }
const checkboxColor: Record<Color, string> = { neutral: "checkbox checkbox-neutral", primary: "checkbox checkbox-primary", secondary: "checkbox checkbox-secondary", accent: "checkbox checkbox-accent", info: "checkbox checkbox-info", success: "checkbox checkbox-success", warning: "checkbox checkbox-warning", error: "checkbox checkbox-error" }
const radioColor: Record<Color, string> = { neutral: "radio radio-neutral", primary: "radio radio-primary", secondary: "radio radio-secondary", accent: "radio radio-accent", info: "radio radio-info", success: "radio radio-success", warning: "radio radio-warning", error: "radio radio-error" }
const toggleColor: Record<Color, string> = { neutral: "toggle toggle-neutral", primary: "toggle toggle-primary", secondary: "toggle toggle-secondary", accent: "toggle toggle-accent", info: "toggle toggle-info", success: "toggle toggle-success", warning: "toggle toggle-warning", error: "toggle toggle-error" }
const rangeColor: Record<Color, string> = { neutral: "range range-neutral", primary: "range range-primary", secondary: "range range-secondary", accent: "range range-accent", info: "range range-info", success: "range range-success", warning: "range range-warning", error: "range range-error" }
const statusColor: Record<Color, string> = { neutral: "status status-neutral", primary: "status status-primary", secondary: "status status-secondary", accent: "status status-accent", info: "status status-info", success: "status status-success", warning: "status status-warning", error: "status status-error" }
const alertColor = { info: "alert alert-info", success: "alert alert-success", warning: "alert alert-warning", error: "alert alert-error" } as const
const loadingType = { spinner: "loading loading-spinner", dots: "loading loading-dots", ring: "loading loading-ring", ball: "loading loading-ball", bars: "loading loading-bars", infinity: "loading loading-infinity" } as const
const scrollHint = <p className="mt-1 text-xs text-base-content/60 sm:hidden">← 左右滑动查看更多 →</p>

function Demo({ name }: { name: string }) {
  const status = coverage[name] as CoverageStatus
  if (status === "missing") return <div className="rounded-box border border-dashed border-warning p-4 text-sm">daisyUI 无此组件（missing）</div>
  if (name === "Button") return <div className="space-y-3"><div className="flex flex-wrap gap-2">{colors.map((color) => <button className={btnColor[color]} key={color}>{color}</button>)}</div><div className="flex flex-wrap gap-2">{["", "btn-outline", "btn-dash", "btn-soft", "btn-ghost", "btn-link"].map((style) => <button className={`btn ${style}`} key={style}>{style ? style.replace("btn-", "") : "default"}</button>)}</div><div className="flex flex-wrap items-center gap-2">{sizes.map((size) => <button className={btnSize[size]} key={size}>{size}</button>)}<button className="btn btn-wide">宽按钮</button><button className="btn btn-block max-w-xs">块按钮</button><button className="btn btn-primary"><span className="loading loading-spinner loading-sm" />加载中</button><button className="btn btn-active">active</button><button className="btn" disabled>disabled</button></div></div>
  if (name === "IconButton") return <div className="space-y-3"><div className="flex flex-wrap items-center gap-2">{sizes.map((size) => <button className={`${btnSize[size]} btn-square`} aria-label={`加号 ${size}`} key={size}><Icon name="plus" size={size === "xs" ? 12 : size === "sm" ? 14 : size === "lg" ? 20 : size === "xl" ? 24 : 16} /></button>)}</div><div className="flex flex-wrap items-center gap-2"><button className="btn btn-circle btn-primary" aria-label="收藏"><Icon name="heart" /></button><button className="btn btn-circle btn-outline" aria-label="设置"><Icon name="settings" /></button><button className="btn btn-circle btn-ghost" aria-label="更多"><Icon name="more-horizontal" /></button><button className="btn btn-circle btn-soft btn-error" aria-label="删除"><Icon name="trash" /></button><button className="btn btn-circle" aria-label="禁用" disabled><Icon name="lock" /></button></div></div>
  if (name === "ButtonGroup") return <div className="space-y-3"><div className="join"><button className="btn join-item">保存</button><button className="btn join-item btn-active">发布</button><button className="btn join-item">取消</button></div><div className="join"><button className="btn btn-outline join-item"><Icon name="arrow-left" size={14} /></button><button className="btn btn-outline join-item">1</button><button className="btn btn-outline btn-active join-item">2</button><button className="btn btn-outline join-item"><Icon name="arrow-right" size={14} /></button></div><div className="join join-vertical"><button className="btn btn-primary join-item">上</button><button className="btn btn-primary join-item">中</button><button className="btn btn-primary join-item">下</button></div></div>
  if (name === "Badge" || name === "Tag") return <div className="flex flex-wrap gap-2">{colors.map((color) => <span className={badgeColor[color]} key={color}>{color}</span>)}{sizes.map((size) => <span className={badgeSize[size]} key={size}>{size}</span>)}</div>
  if (name === "Typography" || name === "Code") return <div className="space-y-3"><h1 className="text-3xl font-bold">标题一级</h1><h2 className="text-2xl font-bold">标题二级</h2><h3 className="text-xl font-semibold">标题三级</h3><p>正文与辅助说明文字。</p><blockquote className="border-l-4 border-primary pl-3">这是一段引用。</blockquote><code className="rounded bg-base-200 px-2 py-1 text-sm">const console = "Acme"</code><ul className="list-disc pl-5"><li>列表一</li><li>列表二</li></ul></div>
  if (name === "Input") return <div className="space-y-2"><div className="flex flex-wrap items-center gap-2"><input className="input input-xs" placeholder="xs" /><input className="input input-sm" placeholder="sm" /><input className="input" placeholder="md" /><input className="input input-lg" placeholder="lg" /></div><div className="flex flex-wrap gap-2"><input className="input input-ghost" placeholder="ghost" /><input className="input input-primary" placeholder="primary" /><input className="input input-error" defaultValue="错误状态" aria-invalid /><label className="input"><Icon name="search" size={15} /><input placeholder="带图标" /></label><input className="input" disabled placeholder="disabled" /></div></div>
  if (name === "NumberInput") return <div className="flex flex-wrap items-center gap-2"><input className="input w-32" type="number" defaultValue={12} min={0} max={99} aria-label="数量" /><div className="join"><button className="btn join-item" aria-label="减少"><Icon name="minus" size={14} /></button><input className="input join-item w-20 text-center" type="number" defaultValue={1} aria-label="步进数量" /><button className="btn join-item" aria-label="增加"><Icon name="plus" size={14} /></button></div><label className="input w-40"><span className="label">¥</span><input type="number" placeholder="金额" /></label></div>
  if (name === "Autocomplete") return <div className="space-y-2"><label className="input w-full"><Icon name="search" size={15} /><input list="autocomplete-demo" placeholder="输入城市，如「上」" /></label><datalist id="autocomplete-demo"><option value="上海" /><option value="深圳" /><option value="杭州" /></datalist><ul className="menu w-full rounded-box border border-base-300 bg-base-100 p-1 text-sm"><li><a><span className="text-primary">上</span>海</a></li><li><a><span className="text-primary">上</span>饶</a></li></ul></div>
  if (name === "Mention") return <div className="space-y-2"><textarea className="textarea w-full" defaultValue="请 @林晓 看一下这周的报告" aria-label="含提及的输入" /><ul className="menu w-52 rounded-box border border-base-300 bg-base-100 p-1 text-sm"><li className="menu-title">@ 提及成员</li><li><a className="menu-active"><div className="avatar avatar-placeholder"><div className="w-6 rounded-full bg-primary text-primary-content"><span className="text-xs">林</span></div></div>林晓</a></li><li><a><div className="avatar avatar-placeholder"><div className="w-6 rounded-full bg-secondary text-secondary-content"><span className="text-xs">王</span></div></div>王子涵</a></li></ul></div>
  if (name === "Textarea") return <textarea className="textarea textarea-bordered w-full" placeholder="多行文本..." />
  if (name === "Select" || name === "MultiSelect") return <div className="flex flex-wrap gap-2"><select className="select select-bordered"><option>选择选项</option><option>选项一</option><option>选项二</option></select>{name === "MultiSelect" ? <select className="select select-bordered h-24" multiple defaultValue={["one"]}><option value="one">选项一</option><option value="two">选项二</option></select> : null}</div>
  if (name === "Combobox") return <div className="dropdown"><label tabIndex={0} className="input"><input placeholder="搜索并选择" /><Icon name="chevron-down" size={15} /></label><ul tabIndex={0} className="dropdown-content menu z-10 w-52 rounded-box bg-base-100 p-2 shadow"><li><a className="menu-active">林晓</a></li><li><a>王子涵</a></li><li><a>Alex Chen</a></li></ul></div>
  if (name === "Cascader") return <div className="flex flex-wrap gap-2"><div className="dropdown"><button tabIndex={0} className="btn btn-outline">华东 / 上海 <Icon name="chevron-down" size={14} /></button><ul tabIndex={0} className="dropdown-content menu z-10 w-40 rounded-box bg-base-100 p-2 shadow"><li><a className="menu-active">华东 <Icon name="chevron-right" size={14} className="ml-auto" /></a></li><li><a>华南 <Icon name="chevron-right" size={14} className="ml-auto" /></a></li></ul></div><ul className="menu menu-horizontal rounded-box bg-base-200"><li><a className="menu-active">华东</a></li><li><a>上海</a></li><li><a>浦东</a></li></ul></div>
  if (name === "Popover") return <div className="flex flex-wrap gap-2"><div className="dropdown dropdown-hover"><button tabIndex={0} className="btn btn-outline">悬停 Popover</button><div tabIndex={0} className="dropdown-content card card-border z-10 w-56 bg-base-100 shadow"><div className="card-body p-4 text-sm"><h4 className="font-semibold">林晓</h4><p>产品负责人 · 上海</p></div></div></div><div className="dropdown dropdown-top dropdown-end"><button tabIndex={0} className="btn">向上弹出</button><div tabIndex={0} className="dropdown-content card z-10 w-48 bg-neutral text-neutral-content shadow"><div className="card-body p-3 text-sm">点击触发的 Popover。</div></div></div></div>
  if (name === "Checkbox") return <div className="flex flex-wrap gap-4">{colors.slice(1).map((color) => <label className="label gap-2" key={color}><input type="checkbox" className={checkboxColor[color]} defaultChecked={color === "primary"} />{color}</label>)}</div>
  if (name === "Radio") return <div className="flex flex-wrap gap-4">{colors.slice(1).map((color) => <label className="label gap-2" key={color}><input type="radio" name="radio-demo" className={radioColor[color]} defaultChecked={color === "primary"} />{color}</label>)}</div>
  if (name === "Switch") return <div className="flex flex-wrap gap-3">{colors.slice(1).map((color) => <input type="checkbox" className={toggleColor[color]} defaultChecked key={color} />)}</div>
  if (name === "Slider" || name === "Range") return <div className="space-y-3">{colors.slice(1).map((color) => <input type="range" className={`${rangeColor[color]} w-full`} defaultValue={60} key={color} />)}</div>
  if (name === "Rating") return <div className="rating rating-lg"><input type="radio" name="rating-demo" className="mask mask-star-2 bg-warning" /><input type="radio" name="rating-demo" className="mask mask-star-2 bg-warning" /><input type="radio" name="rating-demo" className="mask mask-star-2 bg-warning" defaultChecked /><input type="radio" name="rating-demo" className="mask mask-star-2 bg-warning" /><input type="radio" name="rating-demo" className="mask mask-star-2 bg-warning" /></div>
  if (["DatePicker", "TimePicker", "DateRangePicker"].includes(name)) return <div className="join"><input className="input input-bordered join-item" type={name === "TimePicker" ? "time" : "date"} /><input className="input input-bordered join-item" type="date" /></div>
  if (name === "ColorPicker") return <input type="color" className="h-10 w-20 rounded-btn border border-base-300" defaultValue="#888888" />
  if (name === "Upload") return <div className="space-y-3"><input type="file" className="file-input file-input-bordered w-full" /><div className="rounded-box border border-dashed p-5 text-center"><Icon name="upload" className="mx-auto" />拖拽文件到这里</div></div>
  if (name === "PinInput") return <div className="flex gap-2">{[1, 2, 3, 4, 5].map((item) => <input className="input input-bordered w-10 text-center" maxLength={1} key={item} />)}</div>
  if (name === "Form") return <fieldset className="fieldset"><legend className="fieldset-legend">字段标签</legend><input className="input input-bordered" placeholder="字段值" /><p className="fieldset-label">帮助文案</p></fieldset>
  if (name === "Table") return <div className="overflow-x-auto"><table className="table table-zebra"><thead><tr><th>名称</th><th>状态</th><th>金额</th></tr></thead><tbody>{["ORD-2401", "ORD-2402"].map((item) => <tr key={item}><td>{item}</td><td><span className="badge badge-success">已支付</span></td><td>¥99</td></tr>)}<tr className="hover:bg-base-300"><td>ORD-2403</td><td><span className="badge badge-warning">待处理</span></td><td>¥120</td></tr></tbody></table></div>
  if (name === "DataGrid") return <div className="overflow-x-auto rounded-box border border-base-300"><table className="table table-pin-rows table-pin-cols table-sm whitespace-nowrap"><thead><tr><th><input type="checkbox" className="checkbox" aria-label="全选" /></th><td>名称 <Icon name="chevron-up" size={12} className="inline" /></td><td>负责人</td><td>状态</td><td>金额</td><th /></tr></thead><tbody>{[["ORD-2401", "林晓", "已支付", "¥99"], ["ORD-2402", "王子涵", "待处理", "¥120"], ["ORD-2403", "Alex Chen", "已退款", "¥45"]].map(([id, owner, status, amount], index) => <tr key={id} className={index === 0 ? "bg-base-200" : ""}><th><input type="checkbox" className="checkbox" defaultChecked={index === 0} aria-label={`选择 ${id}`} /></th><td>{id}</td><td>{owner}</td><td><span className={`badge badge-sm ${status === "已支付" ? "badge-success" : status === "待处理" ? "badge-warning" : "badge-ghost"}`}>{status}</span></td><td className="text-right">{amount}</td><th><button className="btn btn-ghost btn-square" aria-label="行操作"><Icon name="more-horizontal" size={14} /></button></th></tr>)}</tbody></table></div>
  if (name === "Descriptions") return <div className="overflow-x-auto"><table className="table table-sm"><tbody><tr><th>状态</th><td>已完成</td></tr><tr><th>负责人</th><td>林晓</td></tr></tbody></table></div>
  if (name === "List") return <ul className="list rounded-box border border-base-300"><li className="list-row">项目更新 <span className="badge">新</span></li><li className="list-row">账单提醒</li></ul>
  if (name === "Card") return <div className="space-y-3"><div className="card card-border bg-base-100"><div className="card-body"><h3 className="card-title">卡片标题 <span className="badge badge-secondary">新</span></h3><p>Card 内容与操作。</p><div className="card-actions justify-end"><button className="btn btn-primary">查看</button></div></div></div><div className="card card-side card-sm bg-base-200"><figure className="grid w-24 place-items-center bg-base-300"><Icon name="globe" size={24} /></figure><div className="card-body"><h3 className="card-title">侧向紧凑卡片</h3><p>card-side · card-sm</p></div></div><div className="card image-full card-xs bg-neutral"><figure className="bg-neutral" /><div className="card-body text-neutral-content"><h3 className="card-title">image-full</h3><p>覆盖式卡片</p></div></div></div>
  if (name === "Statistic") return <div className="stats stats-vertical w-full border border-base-300"><div className="stat"><div className="stat-figure text-primary"><Icon name="bar-chart" size={28} /></div><div className="stat-title">本月收入</div><div className="stat-value text-primary">¥128,430</div><div className="stat-desc">↗︎ 12.4% 较上月</div></div><div className="stat"><div className="stat-figure text-secondary"><Icon name="users" size={28} /></div><div className="stat-title">活跃用户</div><div className="stat-value text-secondary">2,480</div><div className="stat-desc">↘︎ 3% 较上周</div></div><div className="stat"><div className="stat-title">完成率</div><div className="stat-value">86%</div><div className="stat-desc"><progress className="progress progress-success w-24" value={86} max={100} /></div><div className="stat-actions"><button className="btn btn-xs btn-success">查看详情</button></div></div></div>
  if (name === "Avatar") return <div className="flex flex-wrap items-end gap-3"><div className="avatar avatar-placeholder"><div className="w-8 rounded-full bg-neutral text-neutral-content"><span className="text-xs">小</span></div></div><div className="avatar avatar-placeholder"><div className="w-12 rounded-full bg-primary text-primary-content"><span>林</span></div></div><div className="avatar avatar-placeholder"><div className="w-16 rounded-box bg-secondary text-secondary-content"><span className="text-xl">王</span></div></div><div className="avatar avatar-placeholder avatar-online"><div className="w-12 rounded-full bg-accent text-accent-content"><span>在</span></div></div><div className="avatar avatar-placeholder avatar-offline"><div className="w-12 rounded-full bg-base-300"><span>离</span></div></div><div className="avatar avatar-placeholder"><div className="w-12 rounded-full bg-info text-info-content ring-2 ring-primary ring-offset-2 ring-offset-base-100"><span>环</span></div></div></div>
  if (name === "AvatarGroup") return <div className="space-y-3"><div className="avatar-group -space-x-4"><div className="avatar avatar-placeholder"><div className="w-12 bg-primary text-primary-content"><span>林</span></div></div><div className="avatar avatar-placeholder"><div className="w-12 bg-secondary text-secondary-content"><span>王</span></div></div><div className="avatar avatar-placeholder"><div className="w-12 bg-accent text-accent-content"><span>A</span></div></div><div className="avatar avatar-placeholder"><div className="w-12 bg-neutral text-neutral-content"><span>+3</span></div></div></div><div className="avatar-group -space-x-2"><div className="avatar avatar-placeholder"><div className="w-8 bg-primary text-primary-content"><span className="text-xs">林</span></div></div><div className="avatar avatar-placeholder"><div className="w-8 bg-secondary text-secondary-content"><span className="text-xs">王</span></div></div><div className="avatar avatar-placeholder"><div className="w-8 bg-neutral text-neutral-content"><span className="text-xs">+9</span></div></div></div></div>
  if (name === "Timeline") return <ul className="timeline timeline-vertical timeline-compact">{["创建项目", "邀请团队", "完成发布"].map((item, index) => <li key={item}>{index > 0 ? <hr /> : null}<div className="timeline-start">{item}</div><div className="timeline-middle"><Icon name="check" size={14} /></div>{index < 2 ? <hr /> : null}</li>)}</ul>
  if (name === "Tree") return <ul className="menu rounded-box bg-base-200"><li><details open><summary>项目</summary><ul><li><a>文档</a></li><li><a>资源</a></li></ul></details></li></ul>
  if (name === "Calendar") return <div className="grid grid-cols-7 gap-1 text-center text-sm">{["一", "二", "三", "四", "五", "六", "日", ...Array.from({ length: 28 }, (_, index) => String(index + 1))].map((item, index) => <button className="btn btn-ghost btn-sm" key={`${item}-${index}`}>{item}</button>)}</div>
  if (name === "Image") return <figure className="max-w-xs"><div className="grid aspect-video place-items-center rounded-box bg-base-300"><Icon name="globe" size={32} /></div><figcaption className="text-center text-sm">Image 占位</figcaption></figure>
  if (name === "Carousel") return <div><div className="carousel carousel-center w-full space-x-2 rounded-box">{["第一张", "第二张", "第三张"].map((item, index) => <div className="carousel-item w-4/5" id={`carousel-${index}`} key={item}><div className={`grid h-32 w-full place-items-center rounded-box ${index % 2 ? "bg-base-300" : "bg-base-200"}`}>{item}</div></div>)}</div><div className="mt-2 flex justify-center gap-2">{[0, 1, 2].map((index) => <a className="btn btn-xs" href={`#carousel-${index}`} key={index}>{index + 1}</a>)}</div>{scrollHint}</div>
  if (name === "Empty") return <div className="hero rounded-box border border-dashed py-8"><div className="hero-content text-center"><div><Icon name="inbox" size={32} className="mx-auto" /><h3 className="mt-2 font-semibold">暂无内容</h3><p className="text-sm text-base-content/60">这里还没有数据。</p></div></div></div>
  if (name === "Tooltip") return <button className="tooltip btn btn-outline" data-tip="Tooltip 内容">悬停查看</button>
  if (name === "Segmented") return <div className="join"><button className="btn join-item btn-active">日</button><button className="btn join-item">周</button><button className="btn join-item">月</button></div>
  if (name === "Alert") return <div className="space-y-2">{(Object.keys(alertColor) as (keyof typeof alertColor)[]).map((color) => <div className={alertColor[color]} key={color}><Icon name="circle-help" size={16} />提示信息 <button className="btn btn-xs">操作</button></div>)}</div>
  if (name === "Toast" || name === "Notification") return <div className="toast toast-end static"><div className="alert alert-success"><Icon name="check" size={16} />操作成功</div></div>
  if (name === "Dialog") return <DialogDemo name={name} />
  if (name === "Popconfirm") return <PopconfirmDemo />
  if (name === "Drawer") return <div className="space-y-2"><div className="drawer h-40 overflow-hidden rounded-box border border-base-300"><input id="drawer-start" type="checkbox" className="drawer-toggle" /><div className="drawer-content grid place-items-center p-3"><label htmlFor="drawer-start" className="btn btn-outline">左侧 Drawer</label></div><div className="drawer-side absolute h-full"><label htmlFor="drawer-start" className="drawer-overlay" aria-label="关闭" /><div className="min-h-full w-40 bg-base-200 p-4 text-sm">drawer-start</div></div></div><div className="drawer drawer-end h-40 overflow-hidden rounded-box border border-base-300"><input id="drawer-end" type="checkbox" className="drawer-toggle" /><div className="drawer-content grid place-items-center p-3"><label htmlFor="drawer-end" className="btn btn-outline">右侧 Drawer</label></div><div className="drawer-side absolute h-full"><label htmlFor="drawer-end" className="drawer-overlay" aria-label="关闭" /><div className="min-h-full w-40 bg-base-200 p-4 text-sm">drawer-end</div></div></div><div className="drawer drawer-open h-32 overflow-hidden rounded-box border border-base-300"><input id="drawer-open" type="checkbox" className="drawer-toggle" /><div className="drawer-content p-3 text-sm">drawer-open：常驻侧栏</div><div className="drawer-side"><div className="min-h-full w-32 bg-base-200 p-3 text-sm">常驻</div></div></div></div>
  if (name === "Progress") return <div className="space-y-3"><progress className="progress progress-primary w-full" value="65" max="100" /><div className="radial-progress text-primary" style={{ "--value": 65 } as CSSProperties}>65%</div><ul className="steps steps-vertical"><li className="step step-primary">完成</li><li className="step step-primary">处理中</li><li className="step">待办</li></ul></div>
  if (name === "Skeleton") return <div className="space-y-2"><div className="skeleton h-4 w-2/3" /><div className="skeleton h-4 w-1/2" /><div className="skeleton h-20 w-full" /></div>
  if (name === "Spinner") return <div className="flex flex-wrap gap-4">{(Object.keys(loadingType) as (keyof typeof loadingType)[]).map((type) => <span className="flex items-center gap-1" key={type}><span className={loadingType[type]} />{type}</span>)}</div>
  if (name === "Result") return <div className="hero rounded-box bg-base-200 py-8"><div className="hero-content text-center"><div><div className="status status-success status-lg" /><h3 className="mt-2 font-bold">操作成功</h3></div></div></div>
  if (name === "Menu") return <div className="space-y-3"><ul className="menu menu-horizontal rounded-box bg-base-200"><li><a className="menu-active">概览</a></li><li><a>订单</a></li><li><a className="menu-disabled">禁用</a></li><li><details><summary>更多</summary><ul className="z-10 w-32 bg-base-200 p-2"><li><a>子项一</a></li><li><a>子项二</a></li></ul></details></li></ul><div className="flex flex-wrap gap-3"><ul className="menu menu-xs w-40 rounded-box bg-base-200"><li className="menu-title">menu-xs</li><li><a>概览</a></li><li><a className="menu-focus">焦点态</a></li></ul><ul className="menu menu-lg w-40 rounded-box bg-base-200"><li className="menu-title">menu-lg</li><li><a>概览</a></li><li><a className="menu-active">选中态</a></li></ul></div></div>
  if (name === "Sidebar") return <div className="flex gap-3"><ul className="menu w-48 rounded-box bg-base-200"><li className="menu-title">工作区</li><li><a className="menu-active"><Icon name="home" size={15} />概览</a></li><li><a><Icon name="shopping-cart" size={15} />订单 <span className="badge badge-sm badge-primary ml-auto">3</span></a></li><li><details open><summary><Icon name="settings" size={15} />设置</summary><ul><li><a>个人资料</a></li><li><a>团队</a></li></ul></details></li></ul><ul className="menu rounded-box bg-base-200"><li><a className="tooltip tooltip-right menu-active" data-tip="概览" aria-label="概览"><Icon name="home" size={16} /></a></li><li><a className="tooltip tooltip-right" data-tip="订单" aria-label="订单"><Icon name="shopping-cart" size={16} /></a></li><li><a className="tooltip tooltip-right" data-tip="设置" aria-label="设置"><Icon name="settings" size={16} /></a></li></ul></div>
  if (name === "Dropdown") return <div className="dropdown"><button tabIndex={0} className="btn btn-outline">打开菜单</button><ul tabIndex={0} className="dropdown-content menu rounded-box bg-base-100 p-2 shadow"><li><a>编辑</a></li><li><a>删除</a></li></ul></div>
  if (name === "Breadcrumb") return <div className="breadcrumbs"><ul><li><a>首页</a></li><li><a>设置</a></li><li>账户</li></ul></div>
  if (name === "Tabs") return <div className="space-y-3">{[["tabs tabs-box", "tabs-box"], ["tabs tabs-border", "tabs-border"], ["tabs tabs-lift", "tabs-lift"], ["tabs tabs-box tabs-sm", "tabs-sm"]].map(([cls, label]) => <div role="tablist" className={cls} key={label}><button role="tab" className="tab tab-active">{label}</button><button role="tab" className="tab">详情</button><button role="tab" className="tab tab-disabled" aria-disabled>禁用</button></div>)}</div>
  if (name === "Pagination") return <div className="join"><button className="btn join-item">上一页</button><button className="btn join-item btn-active">1</button><button className="btn join-item">下一页</button></div>
  if (name === "Steps") return <ul className="steps steps-vertical"><li className="step step-primary">基本信息</li><li className="step step-primary">配置选项</li><li className="step">确认提交</li></ul>
  if (name === "Anchor") return <ul className="menu menu-sm"><li><a href="#component-Button">Button</a></li><li><a href="#component-Input">Input</a></li></ul>
  if (name === "BackTop") return <div className="space-y-3"><p className="text-sm text-base-content/60">页面滚动超过 300px 后，右下角出现固定回顶按钮；下方为按钮样式示例。</p><button className="btn btn-primary btn-circle" aria-label="回到顶部" onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}><Icon name="arrow-up" size={16} /></button></div>
  if (name === "Affix") return <div className="sticky top-16 rounded-box bg-base-200 p-3">sticky top-16</div>
  if (name === "Navbar") return <div className="navbar rounded-box border border-base-300"><span className="font-semibold">导航栏</span><button className="btn btn-primary ml-auto">操作</button></div>
  if (name === "CommandPalette") return <CommandPaletteDemo />
  if (name === "Transfer") return <TransferDemo />
  if (name === "Grid") return <div className="grid grid-cols-3 gap-2 rounded-box bg-base-200 p-3 text-center text-xs"><div className="col-span-2 rounded-box bg-base-300 py-4">col-span-2</div><div className="rounded-box bg-base-300 py-4">1</div><div className="rounded-box bg-base-300 py-4">1</div><div className="rounded-box bg-base-300 py-4">1</div><div className="rounded-box bg-base-300 py-4">1</div></div>
  if (name === "Stack") return <div className="flex flex-wrap gap-4"><div className="stack"><div className="grid size-24 place-items-center rounded-box bg-primary text-primary-content">1</div><div className="grid size-24 place-items-center rounded-box bg-secondary text-secondary-content">2</div><div className="grid size-24 place-items-center rounded-box bg-accent text-accent-content">3</div></div><div className="stack stack-top"><div className="grid size-24 place-items-center rounded-box bg-neutral text-neutral-content">stack-top</div><div className="grid size-24 place-items-center rounded-box bg-base-300">2</div></div><div className="flex flex-col gap-2 text-xs"><div className="rounded-box bg-base-300 px-3 py-2">flex-col 纵向</div><div className="rounded-box bg-base-300 px-3 py-2">gap-2</div></div></div>
  if (name === "Layout") return <div className="grid h-40 grid-cols-[4rem_1fr] grid-rows-[2rem_1fr_1.5rem] gap-1 rounded-box bg-base-200 p-2 text-xs"><div className="col-span-2 grid place-items-center rounded-box bg-base-300">Header</div><div className="grid place-items-center rounded-box bg-base-300">Side</div><div className="grid place-items-center rounded-box bg-base-100">Content</div><div className="col-span-2 grid place-items-center rounded-box bg-base-300">Footer</div></div>
  if (name === "Container") return <div className="rounded-box bg-base-200 p-2"><div className="container mx-auto max-w-xs rounded-box border border-dashed border-base-content/30 bg-base-100 p-3 text-center text-xs">container mx-auto max-w-xs</div></div>
  if (name === "ScrollArea") return <div className="h-32 overflow-y-auto rounded-box border border-base-300 p-3 text-sm">{Array.from({ length: 12 }, (_, index) => <p key={index} className="py-1">滚动行 {index + 1}</p>)}</div>
  if (name === "AspectRatio") return <div className="flex flex-wrap gap-3 text-xs"><div className="grid aspect-video w-40 place-items-center rounded-box bg-base-300">16 / 9</div><div className="grid aspect-square w-24 place-items-center rounded-box bg-base-300">1 / 1</div><div className="grid aspect-[4/3] w-32 place-items-center rounded-box bg-base-300">4 / 3</div></div>
  if (name === "Accordion") return <div className="join join-vertical w-full"><div className="collapse collapse-arrow join-item border border-base-300"><input type="radio" name="accordion" defaultChecked /><div className="collapse-title">Accordion 项目</div><div className="collapse-content">内容</div></div><div className="collapse collapse-plus join-item border border-base-300"><input type="radio" name="accordion" /><div className="collapse-title">另一个项目</div><div className="collapse-content">内容</div></div></div>
  if (name === "ThemeProvider") return <ThemeControllerDemo />
  if (name === "FloatButton") return <button className="btn btn-primary btn-circle"><Icon name="plus" /></button>
  if (name === "Kbd") return <div className="flex gap-2"><kbd className="kbd">⌘</kbd><kbd className="kbd kbd-lg">K</kbd></div>
  if (name === "Divider") return <div className="space-y-3"><div className="divider">或</div><div className="divider divider-primary">primary</div><div className="divider divider-start">divider-start</div><div className="flex h-16 w-full"><div className="grid flex-1 place-items-center rounded-box bg-base-200">左</div><div className="divider divider-horizontal">竖直</div><div className="grid flex-1 place-items-center rounded-box bg-base-200">右</div></div></div>
  if (name === "Link") return <a className="link link-primary" href="#component-Link">链接组件示例</a>
  return <div className="rounded-box bg-base-200 p-4 text-sm">使用 daisyUI 类名组合实现 {name}。</div>
}

function CommandPaletteDemo() {
  const [open, setOpen] = useState(false)
  const palette = <><label className="input w-full"><Icon name="search" size={15} /><input placeholder="搜索命令..." /><kbd className="kbd kbd-sm">⌘K</kbd></label><ul className="menu mt-2 w-full p-0"><li className="menu-title">常用</li><li><a><Icon name="settings" size={15} />打开设置</a></li><li><a><Icon name="plus" size={15} />创建项目</a></li><li><a><Icon name="users" size={15} />邀请成员</a></li></ul></>
  return <div className="space-y-3"><div className="rounded-box border border-base-300 bg-base-100 p-3 shadow-sm">{palette}</div><button className="btn btn-outline" onClick={() => setOpen(true)}>以 Modal 打开</button>{open ? <dialog open className="modal modal-top sm:modal-middle" onClose={() => setOpen(false)}><div className="modal-box max-w-md p-4">{palette}<div className="modal-action mt-3"><button className="btn btn-sm" onClick={() => setOpen(false)}>关闭</button></div></div><div className="modal-backdrop" onClick={() => setOpen(false)} /></dialog> : null}</div>
}

function TransferDemo() {
  const [right, setRight] = useState<string[]>(["王子涵"])
  const all = ["林晓", "王子涵", "Alex Chen", "Maria"]
  const [picked, setPicked] = useState<string[]>([])
  const left = all.filter((item) => !right.includes(item))
  const toggle = (item: string) => setPicked((value) => (value.includes(item) ? value.filter((x) => x !== item) : [...value, item]))
  const box = (title: string, items: string[]) => <div className="min-w-0 flex-1 rounded-box border border-base-300"><div className="border-b border-base-300 px-3 py-2 text-sm font-medium">{title} <span className="badge badge-sm badge-ghost">{items.length}</span></div><ul className="menu menu-sm w-full p-1">{items.length ? items.map((item) => <li key={item}><label className="label cursor-pointer gap-2"><input type="checkbox" className="checkbox checkbox-xs" checked={picked.includes(item)} onChange={() => toggle(item)} />{item}</label></li>) : <li className="px-3 py-2 text-xs text-base-content/60">暂无</li>}</ul></div>
  return <div className="flex items-stretch gap-2">{box("可选成员", left)}<div className="flex flex-col justify-center gap-2"><button className="btn btn-square btn-sm" aria-label="移入" onClick={() => { setRight((value) => [...value, ...picked.filter((item) => left.includes(item))]); setPicked([]) }}><Icon name="chevron-right" size={14} /></button><button className="btn btn-square btn-sm" aria-label="移出" onClick={() => { setRight((value) => value.filter((item) => !picked.includes(item))); setPicked([]) }}><Icon name="chevron-left" size={14} /></button></div>{box("已选成员", right)}</div>
}

const dialogVariants = { middle: { label: "居中", className: "modal" }, top: { label: "顶部", className: "modal modal-top" }, bottom: { label: "底部", className: "modal modal-bottom" }, danger: { label: "危险操作", className: "modal" } } as const
type DialogVariant = keyof typeof dialogVariants

function DialogDemo({ name }: { name: string }) {
  const [open, setOpen] = useState<DialogVariant | null>(null)
  const variant = open ? dialogVariants[open] : null
  return <><div className="flex flex-wrap gap-2">{(Object.keys(dialogVariants) as DialogVariant[]).map((key) => <button className={`btn ${key === "danger" ? "btn-error btn-outline" : "btn-outline"}`} key={key} onClick={() => setOpen(key)}>{dialogVariants[key].label}</button>)}</div>{open && variant ? <dialog open className={variant.className} aria-labelledby="dialog-demo-title"><div className="modal-box"><form method="dialog"><button className="btn btn-circle btn-ghost absolute right-2 top-2" aria-label="关闭" onClick={() => setOpen(null)}><Icon name="x" size={16} /></button></form><h3 id="dialog-demo-title" className="text-lg font-bold">{open === "danger" ? "删除此项目？" : `${name} · ${variant.label}`}</h3><p className="py-4">{open === "danger" ? "删除后无法恢复，请再次确认。" : "这是一个可交互的 daisyUI dialog，Esc 或点击遮罩可关闭。"}</p><div className="modal-action"><button className="btn" onClick={() => setOpen(null)}>取消</button><button className={`btn ${open === "danger" ? "btn-error" : "btn-primary"}`} onClick={() => setOpen(null)}>{open === "danger" ? "确认删除" : "确认"}</button></div></div><div className="modal-backdrop" onClick={() => setOpen(null)} /></dialog> : null}</>
}

function PopconfirmDemo() {
  const [result, setResult] = useState<string | null>(null)
  return <div className="flex flex-wrap items-center gap-3"><div className="dropdown dropdown-top"><button tabIndex={0} className="btn btn-outline btn-error"><Icon name="trash" size={14} />删除</button><div tabIndex={0} className="dropdown-content card card-border z-10 w-60 bg-base-100 shadow"><div className="card-body p-4 text-sm"><p className="flex items-center gap-2"><Icon name="alert-circle" size={16} className="text-warning" />确定删除该记录？</p><div className="card-actions justify-end"><button className="btn btn-sm" onClick={() => setResult("已取消")}>取消</button><button className="btn btn-sm btn-error" onClick={() => setResult("已删除")}>确定</button></div></div></div></div>{result ? <span className="badge badge-ghost">{result}</span> : null}</div>
}

function ThemeControllerDemo() {
  const { setTheme, theme } = useTheme()
  return <label className="label cursor-pointer justify-start gap-3"><input type="checkbox" className="toggle theme-controller" value="dark" checked={theme === "dark"} onChange={(event) => setTheme(event.target.checked ? "dark" : "light")} />主题：{theme}</label>
}

function ExtraDemo({ name }: { name: string }) {
  if (name === "Chat") return <div className="space-y-2"><div className="chat chat-start"><div className="chat-bubble">chat-start</div></div><div className="chat chat-end"><div className="chat-bubble chat-bubble-primary">chat-end</div></div></div>
  if (name === "Countdown") return <span className="countdown text-3xl"><span style={{ "--value": 24 } as CSSProperties} /></span>
  if (name === "Diff") return <div className="diff aspect-video"><div className="diff-item-1"><div className="grid place-content-center bg-primary text-primary-content">前</div></div><div className="diff-item-2"><div className="grid place-content-center bg-secondary text-secondary-content">后</div></div><div className="diff-resizer" /></div>
  if (name === "Dock") return <div className="dock static"><button><Icon name="home" /></button><button className="dock-active"><Icon name="search" /></button><button><Icon name="settings" /></button></div>
  if (name === "Filter") return <form className="filter" onSubmit={(event) => event.preventDefault()}><input className="btn btn-square" type="reset" value="×" aria-label="重置筛选" /><input className="btn" type="radio" name="filter-demo" aria-label="已支付" /><input className="btn" type="radio" name="filter-demo" aria-label="待处理" /><input className="btn" type="radio" name="filter-demo" aria-label="已退款" /></form>
  if (name === "Hero") return <div className="hero rounded-box bg-base-200 py-8"><div className="hero-content text-center"><h3 className="text-2xl font-bold">Hero 内容</h3></div></div>
  if (name === "Indicator") return <div className="indicator"><span className="indicator-item badge badge-secondary">新</span><div className="grid size-20 place-items-center rounded-box bg-base-200">内容</div></div>
  if (name === "Mask") return <div className="flex gap-3"><div className="mask mask-squircle size-16 bg-primary" /><div className="mask mask-hexagon size-16 bg-secondary" /><div className="mask mask-star-2 size-16 bg-accent" /></div>
  if (name === "Mockup") return <div className="mockup-code"><pre data-prefix="$"><code>pnpm build</code></pre></div>
  if (name === "RadialProgress") return <div className="radial-progress text-primary" style={{ "--value": 70 } as CSSProperties}>70%</div>
  if (name === "Status") return <div className="flex gap-3">{colors.map((color) => <span className={statusColor[color]} key={color} title={color} />)}</div>
  if (name === "Swap") return <label className="swap swap-rotate"><input type="checkbox" /><span className="swap-off text-2xl">☀</span><span className="swap-on text-2xl">☾</span></label>
  if (name === "ThemeController") return <ThemeControllerDemo />
  if (name === "Join") return <div className="join"><button className="btn join-item">左</button><button className="btn join-item">中</button><button className="btn join-item">右</button></div>
  if (name === "Stack") return <div className="stack"><div className="grid size-24 place-items-center rounded-box bg-primary text-primary-content">1</div><div className="grid size-24 place-items-center rounded-box bg-secondary text-secondary-content">2</div></div>
  if (name === "Fieldset" || name === "Label" || name === "Validator") return <fieldset className="fieldset"><legend className="fieldset-legend">{name}</legend><input className="input input-bordered validator" placeholder="示例输入" /><p className="validator-hint">帮助文字</p></fieldset>
  if (name === "Footer") return <footer className="footer rounded-box bg-base-200 p-6"><nav><h6 className="footer-title">资源</h6><a>文档</a><a>帮助</a></nav></footer>
  if (name === "Aura") return <div className="flex flex-wrap items-center gap-4"><div className="aura aura-holo"><button className="btn">aura-holo</button></div><div className="aura aura-glow aura-lg"><div className="card card-border w-40 bg-base-100"><div className="card-body p-4 text-sm">aura-glow 卡片</div></div></div><div className="aura aura-gold"><span className="badge badge-lg">aura-gold</span></div><div className="aura aura-silver"><input type="checkbox" className="toggle" defaultChecked aria-label="aura toggle" /></div></div>
  if (name === "Hover3D") return <div className="hover-3d w-44"><div className="card w-44 bg-primary text-primary-content shadow"><div className="card-body p-4"><h4 className="card-title text-base">Hover 3D</h4><p className="text-sm">悬停查看倾斜效果</p></div></div><div /><div /><div /><div /><div /><div /><div /><div /></div>
  if (name === "HoverGallery") return <figure className="hover-gallery w-full max-w-xs rounded-box">{["bg-primary text-primary-content", "bg-secondary text-secondary-content", "bg-accent text-accent-content", "bg-neutral text-neutral-content"].map((cls, index) => <div className={`grid aspect-video place-items-center ${cls}`} key={cls}>图 {index + 1}（横向悬停切换）</div>)}</figure>
  if (name === "MegaMenu") return <nav className="megamenu megamenu-wide rounded-box bg-base-200"><button className="btn btn-ghost" popoverTarget="megamenu-product">产品</button><div popover="auto" id="megamenu-product" className="dropdown menu w-72 rounded-box bg-base-100 p-3 shadow"><div className="grid grid-cols-2 gap-2 text-sm"><div><h4 className="menu-title">分析</h4><ul className="menu p-0"><li><a>仪表盘</a></li><li><a>报表</a></li></ul></div><div><h4 className="menu-title">协作</h4><ul className="menu p-0"><li><a>团队</a></li><li><a>权限</a></li></ul></div></div></div><button className="btn btn-ghost" popoverTarget="megamenu-price">价格</button><div popover="auto" id="megamenu-price" className="dropdown menu w-56 rounded-box bg-base-100 p-3 shadow"><ul className="menu p-0 text-sm"><li><a>免费版</a></li><li><a>团队版</a></li><li><a>企业版</a></li></ul></div><span className="megamenu-active" /></nav>
  if (name === "TextRotate") return <p className="text-xl font-semibold">为团队提供 <span className="text-rotate text-primary"><span><span>更快的协作</span><span>更清晰的数据</span><span>更安心的权限</span></span></span></p>
  if (name === "Glass") return <div className="rounded-box bg-gradient-to-br from-primary to-secondary p-6"><div className="card glass w-full"><div className="card-body text-sm"><h4 className="card-title text-base">glass 卡片</h4><p>在渐变背景上的 glass 效果。</p><div className="card-actions justify-end"><button className="btn glass">glass 按钮</button></div></div></div></div>
  return <div className="rounded-box border border-dashed border-base-300 p-4 text-sm">{name} 组合示例</div>
}

export function ComponentsPage() {
  const [backTop, setBackTop] = useState(false)
  useEffect(() => { const handler = () => setBackTop(window.scrollY > 300); window.addEventListener("scroll", handler); return () => window.removeEventListener("scroll", handler) }, [])
  const names = contract.components as string[]
  return <div className="space-y-8"><PageHeader title="组件全集" description="daisyUI 官方组件、contract 覆盖与组合示例。" /><div id="component-index" className="flex flex-wrap gap-2">{names.map((name) => <a className="badge badge-outline link-hover" href={`#component-${name}`} key={name}>{name}<span className={`badge badge-xs ml-1 ${coverage[name] === "implemented" ? "badge-success" : coverage[name] === "composed" ? "badge-warning" : "badge-ghost"}`} /></a>)}</div><div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">{names.map((name) => <section className="card scroll-mt-20 border border-base-300 bg-base-100" id={`component-${name}`} key={name}><div className="card-body"><div className="flex items-center justify-between gap-2"><h2 className="card-title text-base">{name}</h2><span className={`badge ${coverage[name] === "implemented" ? "badge-success" : coverage[name] === "composed" ? "badge-warning" : "badge-ghost"}`}>{coverage[name]}</span></div><div className="mt-3">{<Demo name={name} />}</div></div></section>)}</div><section className="space-y-4"><div><h2 className="text-2xl font-bold">daisyUI 补充</h2><p className="text-sm text-base-content/60">contract 未列出的 daisyUI 组件与扩展示例。</p></div><div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">{daisyExtras.map((name) => <section className="card border border-base-300 bg-base-100" key={name}><div className="card-body"><h3 className="card-title text-base">{name}</h3><ExtraDemo name={name} /></div></section>)}</div></section>{backTop ? <button className="btn btn-primary btn-circle fixed bottom-4 right-4 z-30" onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}><Icon name="arrow-up" /></button> : null}</div>
}
