import { useState } from "react"
import { Area, AreaChart, Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis } from "recharts"
import { Icon } from "@ui-gallery/icons-react"
import activity from "@ui-gallery/spec/mock/activity.json"
import orders from "@ui-gallery/spec/mock/orders.json"
import series from "@ui-gallery/spec/mock/series.json"
import stats from "@ui-gallery/spec/mock/stats.json"
import tasks from "@ui-gallery/spec/mock/tasks.json"
import { PageHeader, SectionCard, StatusBadge, Avatar } from "./shared"

const palette = ["var(--color-primary)", "var(--color-secondary)", "var(--color-accent)", "var(--color-info)"]

export function DashboardPage() {
  const [period, setPeriod] = useState("日")
  const chartData = series.months.map((month, index) => ({ month, revenue: series.revenue[index], orders: series.orders[index] }))
  return (
    <div className="space-y-6">
      <PageHeader title="仪表盘" description="欢迎回来，林晓。这里是今天的业务概况。" action={<button className="btn btn-primary"><Icon name="plus" size={16} />新建项目</button>} />
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map((item) => <div className="stats border border-base-300 bg-base-100 shadow-sm" key={item.key}><div className="stat min-w-0"><div className="stat-title truncate">{item.label}</div><div className="stat-value text-2xl">{item.unit === "CNY" ? `¥${item.value.toLocaleString()}` : `${item.value}${item.unit ?? ""}`}</div><div className="stat-desc flex items-center gap-2"><span className={`badge badge-sm ${item.delta > 0 ? "badge-success" : "badge-error"}`}>{item.delta > 0 ? "+" : ""}{item.delta}%</span>同比</div><div className="mt-2 h-12"><ResponsiveContainer width="100%" height="100%" initialDimension={{ width: 240, height: 48 }}><AreaChart data={item.trend.map((value, index) => ({ value, index }))}><Area dataKey="value" stroke="currentColor" fill="currentColor" fillOpacity={0.12} /></AreaChart></ResponsiveContainer></div></div></div>)}</div>
      <div className="flex flex-wrap items-center justify-between gap-3"><div className="tabs tabs-box"><button className={`tab ${period === "日" ? "tab-active" : ""}`} onClick={() => setPeriod("日")}>日</button><button className={`tab ${period === "周" ? "tab-active" : ""}`} onClick={() => setPeriod("周")}>周</button><button className={`tab ${period === "月" ? "tab-active" : ""}`} onClick={() => setPeriod("月")}>月</button></div><span className="text-sm text-base-content/60">当前周期：{period}</span></div>
      <div className="grid gap-4 xl:grid-cols-[minmax(0,2fr)_minmax(280px,1fr)]"><SectionCard title="收入趋势" description="过去 7 个月的收入与订单"><div className="h-72"><ResponsiveContainer width="100%" height="100%" initialDimension={{ width: 640, height: 288 }}><AreaChart data={chartData}><XAxis dataKey="month" /><Tooltip /><Area dataKey="revenue" stroke="var(--color-primary)" fill="var(--color-primary)" fillOpacity={0.16} /><Area dataKey="orders" stroke="var(--color-secondary)" fill="var(--color-secondary)" fillOpacity={0.08} /></AreaChart></ResponsiveContainer></div></SectionCard><SectionCard title="渠道分布" description="订单来源占比"><div className="h-[260px] min-h-[260px] w-full"><ResponsiveContainer width="100%" height={260} initialDimension={{ width: 320, height: 260 }}><PieChart><Pie cx="50%" cy="50%" startAngle={90} endAngle={-270} isAnimationActive={false} data={series.byChannel} dataKey="value" nameKey="name" innerRadius={55} outerRadius={90}>{series.byChannel.map((entry, index) => <Cell fill={palette[index]} key={entry.name} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer></div></SectionCard></div>
      <div className="grid gap-4 xl:grid-cols-2"><SectionCard title="订单趋势" description="各月订单数量"><div className="h-64"><ResponsiveContainer width="100%" height="100%" initialDimension={{ width: 640, height: 256 }}><BarChart data={chartData}><XAxis dataKey="month" /><Tooltip /><Bar dataKey="orders" fill="var(--color-accent)" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></div></SectionCard><SectionCard title="任务进度" description="本周团队执行情况"><div className="space-y-5">{tasks.map((task) => <div key={task.title}><div className="mb-2 flex justify-between text-sm"><span>{task.title}</span><span className="text-base-content/60">{task.progress}% · {task.owner}</span></div><progress className="progress progress-primary w-full" value={task.progress} max="100" /></div>)}</div></SectionCard></div>
      <div className="grid gap-4 xl:grid-cols-2"><SectionCard title="最近订单" description="最新的业务交易"><p className="mb-1 text-xs text-base-content/60 xl:hidden">← 左右滑动查看全部列 →</p><div className="overflow-x-auto"><table className="table table-sm"><thead><tr><th>订单</th><th>客户</th><th>状态</th><th className="text-right">金额</th><th /></tr></thead><tbody>{orders.slice(0, 5).map((order) => <tr key={order.id}><td className="font-medium">{order.id}</td><td><div className="flex items-center gap-2"><Avatar name={order.customer} />{order.customer}</div></td><td><StatusBadge value={order.status} /></td><td className="text-right">¥{order.amount.toLocaleString()}</td><td><div className="dropdown dropdown-end"><button className="btn btn-ghost btn-square" aria-label="行操作"><Icon name="more-horizontal" size={15} /></button><ul tabIndex={0} className="dropdown-content menu z-10 w-32 rounded-box bg-base-100 p-2 shadow"><li><a>查看</a></li><li><a>编辑</a></li></ul></div></td></tr>)}</tbody></table></div></SectionCard><SectionCard title="团队动态" description="团队最近发生的事情"><ul className="timeline timeline-vertical timeline-compact">{activity.map((item, index) => <li key={`${item.user}-${index}`}>{index > 0 ? <hr /> : null}<div className="timeline-start text-xs text-base-content/60">{item.time}</div><div className="timeline-middle"><Icon name="check" size={14} /></div><div className="timeline-end mb-4 text-sm"><strong>{item.user}</strong> {item.action}</div>{index < activity.length - 1 ? <hr /> : null}</li>)}</ul></SectionCard></div>
      <SectionCard title="加载状态示例" description="用于演示页面加载期间的骨架屏"><div className="space-y-3"><div className="skeleton h-4 w-1/3" /><div className="skeleton h-4 w-2/3" /><div className="skeleton h-16 w-full" /></div></SectionCard>
    </div>
  )
}
