import { useEffect, useState } from "react"
import { useSearchParams } from "react-router-dom"
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, LineChart, Line, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts"
import { Avatar, Badge, Button, Card, Col, Grid, List, Message, Panel, Placeholder, Progress, Row, SegmentedControl, Stat, Table, Tabs, Tag, Text, Timeline } from "rsuite"
import { useMediaQuery } from "rsuite"
import activity from "@ui-gallery/spec/mock/activity.json"
import orders from "@ui-gallery/spec/mock/orders.json"
import series from "@ui-gallery/spec/mock/series.json"
import stats from "@ui-gallery/spec/mock/stats.json"
import tasks from "@ui-gallery/spec/mock/tasks.json"
import { Icon } from "@/components/icon"
import { PageHeader, StateSwitch, StatusBadge } from "./shared"

const chartData = series.months.map((month, index) => ({ month, revenue: series.revenue[index], orders: series.orders[index] }))
export function DashboardPage() {
  const [params] = useSearchParams()
  const state = params.get("state")
  const [loading, setLoading] = useState(true)
  const [isMobile] = useMediaQuery("(max-width: 767px)")
  useEffect(() => { if (state === "loading") return undefined; const timer = window.setTimeout(() => setLoading(false), 600); return () => window.clearTimeout(timer) }, [state])
  if (state === "empty") return <div className="page-stack"><PageHeader title="仪表盘" actions={<StateSwitch />} /><Panel bordered style={{ textAlign: "center", padding: 48 }}><Icon name="inbox" size={36} /><h3>暂无数据</h3><Text muted>还没有业务数据，先创建一个项目。</Text><br /><Button appearance="primary" style={{ marginTop: 16 }}>新建项目</Button></Panel></div>
  if (state === "error") return <div className="page-stack"><PageHeader title="仪表盘" actions={<StateSwitch />} /><Message type="error" showIcon>概览加载失败，请重试。 <Button size="sm" appearance="primary">重试</Button></Message></div>
  if (loading || state === "loading") return <div className="page-stack"><PageHeader title="仪表盘" description="欢迎回来，林晓。这里是今天的业务概况。" actions={<StateSwitch />} /><div className="demo-grid">{[1, 2, 3, 4].map((item) => <Panel bordered key={item}><Placeholder.Paragraph rows={2} active /></Panel>)}<Panel bordered><Placeholder.Graph active height={280} /></Panel><Panel bordered><Placeholder.Grid rows={5} columns={4} active /></Panel></div></div>
  return <div className="page-stack"><PageHeader title="仪表盘" description="欢迎回来，林晓。这里是今天的业务概况。" action={<Button appearance="primary"><Icon name="plus" /> 新建项目</Button>} actions={<StateSwitch />} />
    <Grid fluid><Row gutter={16}>{stats.map((item) => <Col xs={24} md={12} lg={6} key={item.key}><Panel bordered><Text muted>{item.label}</Text><Stat><Stat.Value value={item.value} /><Stat.Label>{item.unit ?? ""} <Tag color={item.delta > 0 ? "green" : "red"}>{item.delta > 0 ? "+" : ""}{item.delta}%</Tag></Stat.Label></Stat><ResponsiveContainer height={48} width="100%"><AreaChart data={item.trend.map((value, index) => ({ value, index }))}><Area isAnimationActive={false} dataKey="value" stroke="var(--rs-primary-500)" fill="var(--rs-primary-100)" /></AreaChart></ResponsiveContainer></Panel></Col>)}</Row></Grid>
    <Panel bordered header={<div style={{ display: "flex", justifyContent: "space-between" }}><strong>业务趋势</strong><SegmentedControl data={["日", "周", "月"].map((label) => ({ label, value: label }))} defaultValue="月" /></div>}><div className="chart-box"><ResponsiveContainer><LineChart data={chartData}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="month" /><YAxis /><Tooltip /><Legend formatter={(value) => <span style={{ color: "var(--rs-text-primary)" }}>{value}</span>} /><Line isAnimationActive={false} type="monotone" dataKey="revenue" stroke="var(--rs-primary-500)" /><Line isAnimationActive={false} type="monotone" dataKey="orders" stroke="var(--rs-orange-500)" /></LineChart></ResponsiveContainer></div></Panel>
    <Grid fluid><Row gutter={16}><Col xs={24} lg={12}><Panel bordered header="订单趋势"><div className="chart-box"><ResponsiveContainer><BarChart data={chartData}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="month" /><YAxis /><Tooltip /><Bar isAnimationActive={false} dataKey="orders" fill="var(--rs-blue-500)" /></BarChart></ResponsiveContainer></div></Panel></Col><Col xs={24} lg={12}><Panel bordered header="渠道分布"><div className="chart-box"><ResponsiveContainer><PieChart><Pie isAnimationActive={false} data={series.byChannel} dataKey="value" nameKey="name" innerRadius={55} outerRadius={90}>{series.byChannel.map((item, index) => <Cell key={item.name} fill={["#3498ff", "#34c759", "#ffb300", "#e94d8a"][index]} />)}</Pie><Tooltip /><Legend formatter={(value) => <span style={{ color: "var(--rs-text-primary)" }}>{value}</span>} /></PieChart></ResponsiveContainer></div></Panel></Col></Row></Grid>
    <Grid fluid><Row gutter={16}><Col xs={24} lg={14}><Panel bordered header="最近订单">{isMobile ? <List hover>{orders.slice(0, 5).map((rowData) => <List.Item key={rowData.id}><div style={{ display: "flex", alignItems: "center", gap: 8 }}><Avatar circle size="xs">{rowData.customer.slice(0, 1)}</Avatar><span style={{ flex: 1 }}><b>{rowData.customer}</b><br /><StatusBadge value={rowData.status} /></span><strong>¥{rowData.amount.toLocaleString()}</strong></div></List.Item>)}</List> : <div className="table-scroll"><Table data={orders.slice(0, 5)} rowKey="id" autoHeight><Table.Column width={130}><Table.HeaderCell>订单</Table.HeaderCell><Table.Cell dataKey="id" /></Table.Column><Table.Column flexGrow={1}><Table.HeaderCell>客户</Table.HeaderCell><Table.Cell>{(rowData) => <span><Avatar circle size="xs" style={{ marginRight: 8 }}>{rowData.customer.slice(0, 1)}</Avatar>{rowData.customer}</span>}</Table.Cell></Table.Column><Table.Column width={110}><Table.HeaderCell>状态</Table.HeaderCell><Table.Cell>{(rowData) => <StatusBadge value={rowData.status} />}</Table.Cell></Table.Column><Table.Column width={120} align="right"><Table.HeaderCell>金额</Table.HeaderCell><Table.Cell>{(rowData) => `¥${rowData.amount.toLocaleString()}`}</Table.Cell></Table.Column></Table></div>}</Panel></Col><Col xs={24} lg={10}><Panel bordered header="团队动态"><Timeline align="left">{activity.slice(0, 5).map((item, index) => <Timeline.Item key={`${item.user}-${index}`} time={item.time}><strong>{item.user}</strong> {item.action}</Timeline.Item>)}</Timeline></Panel></Col></Row></Grid>
    <Panel bordered header="任务进度">{tasks.map((task) => <div key={task.title} style={{ marginBottom: 14 }}><div style={{ display: "flex", justifyContent: "space-between" }}><span>{task.title}</span><Text muted>{task.progress}% · {task.owner}</Text></div><Progress.Line percent={task.progress} showInfo={false} /></div>)}</Panel>
    <Card bordered><Tabs defaultActiveKey="overview"><Tabs.Tab eventKey="overview" title="概览">数据已从本地 mock JSON 加载。</Tabs.Tab><Tabs.Tab eventKey="loading" title="加载状态"><Badge content="ready">Skeleton</Badge></Tabs.Tab></Tabs></Card>
  </div>
}
