import { useState } from "react"
import { Link } from "react-router-dom"
import { Accordion, Avatar, AvatarGroup, Button, Col, Container, Content, Drawer, Footer, Grid, Heading, Navbar, Nav, Panel, Row, SelectPicker, Stat, Tag, Text, Toggle } from "rsuite"
import landing from "@ui-gallery/spec/mock/landing.json"
import plans from "@ui-gallery/spec/mock/plans.json"
import { Icon } from "@/components/icon"

export function LandingPage() {
  const [drawer, setDrawer] = useState(false)
  const links = [{ id: "features", label: "功能" }, { id: "pricing", label: "价格" }, { id: "faq", label: "常见问题" }, { id: "footer", label: "文档" }, { id: "footer", label: "帮助" }]
  return <Container><Navbar><Navbar.Brand as={Link} to="/">Acme Console</Navbar.Brand><Nav className="desktop-only">{links.map((item, index) => <Nav.Item key={`${item.id}-${index}`} href={`#${item.id}`}>{item.label}</Nav.Item>)}</Nav><Nav pullRight><Button appearance="primary" size="lg" as={Link} to="/login">免费开始</Button><Button className="mobile-only" appearance="subtle" onClick={() => setDrawer(true)}><Icon name="menu" /></Button></Nav></Navbar><Drawer open={drawer} placement="left" onClose={() => setDrawer(false)}><Drawer.Header><Drawer.Title>导航</Drawer.Title></Drawer.Header><Drawer.Body><Nav vertical>{links.map((item, index) => <Nav.Item key={`${item.id}-${index}`} href={`#${item.id}`}>{item.label}</Nav.Item>)}</Nav></Drawer.Body></Drawer><Content>
    <section style={{ padding: "72px 16px", textAlign: "center" }}><Heading>{landing.hero.title}</Heading><Text muted style={{ display: "block", maxWidth: 620, margin: "16px auto", fontSize: 18 }}>{landing.hero.subtitle}</Text><div className="demo-row" style={{ justifyContent: "center" }}><Button appearance="primary" size="lg" as={Link} to="/login">{landing.hero.primary}</Button><Button size="lg" as={Link} to="#features">{landing.hero.secondary}</Button></div><div style={{ maxWidth: 900, height: 300, margin: "40px auto 20px", border: "1px solid var(--rs-border-primary)", background: "var(--rs-bg-well)", display: "grid", placeItems: "center" }}>产品截图占位</div><div style={{ display: "flex", justifyContent: "center", alignItems: "center", gap: 12 }}><AvatarGroup stack><Avatar circle>A</Avatar><Avatar circle>林</Avatar><Avatar circle>王</Avatar></AvatarGroup><Text muted>{landing.hero.social}</Text></div></section>
    <section style={{ padding: "32px 16px" }}><div className="demo-grid logo-cloud">{["A", "C", "F", "G", "I", "U"].map((name) => <Panel bordered key={name} style={{ textAlign: "center", color: "var(--rs-text-secondary)", background: "var(--rs-bg-well)" }}>{name} · LOGO</Panel>)}</div></section>
    <section id="features" style={{ padding: "48px 16px" }}><Heading level={2} style={{ textAlign: "center" }}>为团队而生</Heading><Grid fluid><Row gutter={16}>{landing.features.map((feature) => <Col xs={24} sm={12} md={8} key={feature.title}><Panel bordered style={{ height: "100%" }}><Icon name={feature.icon} size={24} /><Heading level={4}>{feature.title}</Heading><Text muted>{feature.desc}</Text></Panel></Col>)}</Row></Grid></section>
    {["看见全局", "自动化协作", "AI 就在身边"].map((title, index) => <section key={title} style={{ padding: "60px 16px" }}><Grid fluid><Row><Col xs={24} md={12}><div style={{ height: 220, background: "var(--rs-bg-well)", border: "1px solid var(--rs-border-primary)" }} /></Col><Col xs={24} md={12} style={{ padding: 24 }}><Tag color="blue">0{index + 1} / WORKSPACE</Tag><Heading level={2}>{title}</Heading><Text muted>在一个清晰的工作空间中，让信息、流程与团队保持同步。</Text></Col></Row></Grid></section>)}
    <section style={{ padding: "48px 16px", background: "var(--rs-bg-well)" }}><Grid fluid><Row>{landing.numbers.map((item) => <Col xs={12} sm={6} key={item.label}><Stat style={{ textAlign: "center" }}><Text size="lg">{item.value}</Text><Stat.Label>{item.label}</Stat.Label></Stat></Col>)}</Row></Grid></section>
    <section id="pricing" style={{ padding: "60px 16px" }}><Heading level={2} style={{ textAlign: "center" }}>选择适合你的方案</Heading><div style={{ textAlign: "center", margin: 16 }}><Toggle>按年计费</Toggle></div><Grid fluid><Row gutter={16}>{plans.map((plan) => <Col xs={24} md={8} key={plan.name}><Panel bordered header={<span>{plan.name} {plan.recommended ? <Tag color="green">最受欢迎</Tag> : null}</span>}><Heading level={3}>{plan.price === null ? "定制" : plan.price === 0 ? "免费" : `¥${plan.price}`}</Heading>{plan.features.map((feature) => <Text key={feature} style={{ display: "block", margin: "10px 0" }}><Icon name="check" /> {feature}</Text>)}<Button appearance={plan.recommended ? "primary" : "default"} block>开始使用</Button></Panel></Col>)}</Row></Grid></section>
    <section style={{ padding: "48px 16px" }}><Heading level={2} style={{ textAlign: "center" }}>他们已经在改变工作方式</Heading><Grid fluid><Row gutter={16}>{landing.testimonials.map((item) => <Col xs={24} sm={12} md={8} key={item.name}><Panel bordered><Text size="lg">“{item.quote}”</Text><div style={{ marginTop: 16 }}><Avatar circle size="sm">{item.name.slice(0, 1)}</Avatar> {item.name} · {item.company}</div></Panel></Col>)}</Row></Grid></section>
    <section id="faq" style={{ maxWidth: 800, margin: "0 auto", padding: "48px 16px" }}><Heading level={2}>常见问题</Heading><Accordion bordered>{landing.faq.map((item) => <Accordion.Panel header={item.q} key={item.q}>{item.a}</Accordion.Panel>)}</Accordion></section><section className="cta-banner"><Heading level={2}>准备好让团队更高效了吗？</Heading><Button appearance="default" size="lg" as={Link} to="/login">免费开始</Button></section>
  </Content><Footer id="footer" style={{ padding: 32, borderTop: "1px solid var(--rs-border-primary)" }}><Grid fluid><Row><Col xs={24} md={12}><b>Acme Console</b><p><Text muted>© 2026 Acme Console</Text></p></Col><Col xs={24} md={12}><div className="demo-row"><Link to="#features">产品</Link><Link to="#pricing">价格</Link><Link to="#faq">帮助中心</Link><SelectPicker size="sm" data={["简体中文", "English"].map((label) => ({ label, value: label }))} defaultValue="简体中文" /></div></Col></Row></Grid></Footer></Container>
}
