import type { ComponentType, CSSProperties } from "react"
import { Icon as GalleryIcon } from "@ui-gallery/icons-react"
import {
  IconActivity,
  IconAlertCircle,
  IconArchive,
  IconArrowDown,
  IconArrowLeft,
  IconArrowRight,
  IconArrowUp,
  IconArrowUpRight,
  IconArrowDownRight,
  IconBell,
  IconCheckCircleStroked,
  IconColumnsStroked,
  IconCreditCard,
  IconLikeThumb,
  IconRefresh2,
  IconUserAdd,
  IconWrench,
  IconBolt,
  IconBox,
  IconCalendar,
  IconCart,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconClock,
  IconClose,
  IconComment,
  IconConnectionPoint1,
  IconCopy,
  IconDelete,
  IconDownload,
  IconEdit,
  IconExit,
  IconEyeClosed,
  IconEyeOpened,
  IconFile,
  IconFilter,
  IconGithubLogo,
  IconGlobe,
  IconGridView,
  IconHelpCircle,
  IconHistogram,
  IconHome,
  IconImage,
  IconInbox,
  IconInfoCircle,
  IconKanban,
  IconLikeHeart,
  IconLink,
  IconList,
  IconLoading,
  IconLock,
  IconMail,
  IconMenu,
  IconMicrophone,
  IconMinus,
  IconMoon,
  IconMore,
  IconPaperclip,
  IconPlay,
  IconPlus,
  IconPriceTag,
  IconRefresh,
  IconSearch,
  IconSend,
  IconSetting,
  IconShield,
  IconSpin,
  IconStar,
  IconSun,
  IconTick,
  IconUpload,
  IconUser,
  IconUserGroup,
} from "@douyinfe/semi-icons"

type SemiIcon = ComponentType<{ style?: CSSProperties; className?: string; spin?: boolean }>

const native: Record<string, SemiIcon> = {
  activity: IconActivity,
  "alert-circle": IconAlertCircle,
  archive: IconArchive,
  "arrow-down": IconArrowDown,
  "arrow-left": IconArrowLeft,
  "arrow-right": IconArrowRight,
  "arrow-up": IconArrowUp,
  "bar-chart": IconHistogram,
  bell: IconBell,
  bot: IconComment,
  chrome: IconGlobe,
  "circle-check": IconCheckCircleStroked,
  columns: IconColumnsStroked,
  "credit-card": IconCreditCard,
  ellipsis: IconMore,
  "refresh-cw": IconRefresh2,
  "thumbs-up": IconLikeThumb,
  "trending-up": IconArrowUpRight,
  "trending-down": IconArrowDownRight,
  "user-plus": IconUserAdd,
  wrench: IconWrench,
  boxes: IconBox,
  calendar: IconCalendar,
  check: IconTick,
  "chevron-down": IconChevronDown,
  "chevron-left": IconChevronLeft,
  "chevron-right": IconChevronRight,
  "chevron-up": IconChevronUp,
  "circle-help": IconHelpCircle,
  clock: IconClock,
  copy: IconCopy,
  download: IconDownload,
  edit: IconEdit,
  eye: IconEyeOpened,
  "eye-off": IconEyeClosed,
  "file-plus": IconFile,
  filter: IconFilter,
  github: IconGithubLogo,
  globe: IconGlobe,
  grid: IconGridView,
  heart: IconLikeHeart,
  home: IconHome,
  image: IconImage,
  inbox: IconInbox,
  info: IconInfoCircle,
  "layout-dashboard": IconKanban,
  link: IconLink,
  list: IconList,
  loader: IconLoading,
  lock: IconLock,
  "log-in": IconUser,
  "log-out": IconExit,
  mail: IconMail,
  menu: IconMenu,
  "message-circle": IconComment,
  "message-square": IconComment,
  mic: IconMicrophone,
  minus: IconMinus,
  moon: IconMoon,
  "more-horizontal": IconMore,
  paperclip: IconPaperclip,
  play: IconPlay,
  plus: IconPlus,
  plug: IconConnectionPoint1,
  refresh: IconRefresh,
  search: IconSearch,
  send: IconSend,
  settings: IconSetting,
  shield: IconShield,
  "shopping-cart": IconCart,
  sliders: IconFilter,
  sparkles: IconBolt,
  spin: IconSpin,
  star: IconStar,
  sun: IconSun,
  tag: IconPriceTag,
  trash: IconDelete,
  upload: IconUpload,
  user: IconUser,
  users: IconUserGroup,
  x: IconClose,
  zap: IconBolt,
}

export type IconFamily = "native" | "lucide" | "tabler" | "phosphor" | "heroicons"

export function iconFamily(): IconFamily {
  if (typeof window === "undefined") return "native"
  const params = new URLSearchParams(window.location.search)
  const value = params.get("icons") ?? params.get("icon")
  return value === "lucide" || value === "tabler" || value === "phosphor" || value === "heroicons" ? value : "native"
}

export function Icon({ name, size = 16, className, spin }: { name: string; size?: number; className?: string; spin?: boolean }) {
  if (iconFamily() !== "native") return <GalleryIcon name={name} size={size} className={className} />
  const Component = native[name] ?? IconHelpCircle
  return <Component className={className} spin={spin} style={{ fontSize: size }} />
}
