import { useState } from "react"
import { Link } from "react-router-dom"
import { Alert, Button, Card, Col, Container, Form, InputGroup, Row } from "react-bootstrap"
import { Icon } from "@ui-gallery/icons-react"
import { LoadingButton } from "@/pages/shared"

export function LoginPage() {
  const [submitted, setSubmitted] = useState(false)
  const [email, setEmail] = useState("")
  const [password, setPassword] = useState("")
  const [showPassword, setShowPassword] = useState(false)
  const invalidEmail = submitted && !email
  const invalidPassword = submitted && password.length < 8
  return <Container fluid className="min-vh-100 d-flex align-items-center justify-content-center bg-body-tertiary py-5"><Row className="w-100 justify-content-center"><Col xs={12} sm={9} md={6} lg={4} xl={3}><Card className="shadow-sm"><Card.Body className="p-4"><div className="text-center mb-4"><Link to="/" className="text-decoration-none"><span className="bg-primary text-white rounded-3 px-2 py-1 fw-semibold me-2">A</span><span className="fw-semibold text-body">Acme Console</span></Link><h1 className="h4 mt-4">欢迎回来</h1><p className="text-secondary">登录以继续使用工作台</p></div>{submitted && (invalidEmail || invalidPassword) && <Alert variant="danger">请检查表单中的错误。</Alert>}<Form noValidate onSubmit={(event) => { event.preventDefault(); setSubmitted(true) }}><Form.Group className="mb-3"><Form.Label>邮箱</Form.Label><InputGroup hasValidation><InputGroup.Text><Icon name="user" /></InputGroup.Text><Form.Control type="email" value={email} onChange={(event) => setEmail(event.target.value)} isInvalid={invalidEmail} placeholder="name@example.com" /><Form.Control.Feedback type="invalid">请输入邮箱。</Form.Control.Feedback></InputGroup></Form.Group><Form.Group className="mb-3"><div className="d-flex justify-content-between"><Form.Label>密码</Form.Label><Link to="#" className="small">忘记密码？</Link></div><InputGroup hasValidation><InputGroup.Text><Icon name="lock" /></InputGroup.Text><Form.Control type={showPassword ? "text" : "password"} value={password} onChange={(event) => setPassword(event.target.value)} isInvalid={invalidPassword} placeholder="至少 8 个字符" /><Button type="button" variant="outline-secondary" onClick={() => setShowPassword(!showPassword)} aria-label={showPassword ? "隐藏密码" : "显示密码"}>{showPassword ? "隐藏" : "显示"}</Button><Form.Control.Feedback type="invalid">密码至少需要 8 个字符。</Form.Control.Feedback></InputGroup></Form.Group><Form.Check label="记住我" className="mb-3" /><LoadingButton loading={false}>登录</LoadingButton><div className="d-flex align-items-center gap-3 my-4"><hr className="flex-grow-1" /><span className="text-secondary small">或</span><hr className="flex-grow-1" /></div><div className="d-grid gap-2"><Button variant="outline-secondary" type="button"><Icon name="globe" className="me-2" />使用 Google 登录</Button><Button variant="outline-secondary" type="button"><Icon name="github" className="me-2" />使用 GitHub 登录</Button><Button variant="outline-secondary" type="button"><Icon name="message-square" className="me-2" />使用微信登录</Button></div></Form><p className="text-center text-secondary small mt-4 mb-0">还没有账号？ <Link to="/form">注册</Link></p></Card.Body></Card></Col></Row></Container>
}
