import type { ComponentType, FunctionComponent } from "react"
import { Icon as GalleryIcon } from "@ui-gallery/icons-react"
import {
  AlertIcon,
  ArchiveIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  BellIcon,
  BellFillIcon,
  BookIcon,
  BriefcaseIcon,
  CalendarIcon,
  CheckIcon,
  CheckCircleIcon,
  CheckCircleFillIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ClockIcon,
  CodeIcon,
  ColumnsIcon,
  CommentDiscussionIcon,
  CommentIcon,
  CopilotIcon,
  CopyIcon,
  CreditCardIcon,
  DashIcon,
  DeviceMobileIcon,
  DownloadIcon,
  EyeIcon,
  EyeClosedIcon,
  FileIcon,
  FileAddedIcon,
  FileDirectoryIcon,
  FilterIcon,
  GearIcon,
  GlobeIcon,
  GraphIcon,
  HashIcon,
  HeartIcon,
  HistoryIcon,
  HomeIcon,
  HourglassIcon,
  ImageIcon,
  InboxIcon,
  InfoIcon,
  KebabHorizontalIcon,
  KeyIcon,
  LinkIcon,
  ListUnorderedIcon,
  LocationIcon,
  LockIcon,
  MailIcon,
  MarkGithubIcon,
  MoonIcon,
  NumberIcon,
  OrganizationIcon,
  PackageIcon,
  PaintbrushIcon,
  PaperAirplaneIcon,
  PaperclipIcon,
  PasteIcon,
  PencilIcon,
  PeopleIcon,
  PersonIcon,
  PinIcon,
  PlayIcon,
  PlugIcon,
  PlusIcon,
  PulseIcon,
  QuestionIcon,
  RepoIcon,
  RocketIcon,
  RowsIcon,
  SearchIcon,
  ShieldIcon,
  ShieldCheckIcon,
  SidebarCollapseIcon,
  SidebarExpandIcon,
  SignInIcon,
  SignOutIcon,
  SlidersIcon,
  SortAscIcon,
  SortDescIcon,
  SparkleFillIcon,
  StarIcon,
  StarFillIcon,
  SunIcon,
  SyncIcon,
  TableIcon,
  TagIcon,
  TerminalIcon,
  ThreeBarsIcon,
  ToolsIcon,
  TrashIcon,
  TriangleDownIcon,
  TypographyIcon,
  UnmuteIcon,
  UploadIcon,
  VideoIcon,
  XIcon,
  XCircleIcon,
  ZapIcon,
} from "@primer/octicons-react"

type OcticonProps = { size?: number | "small" | "medium" | "large"; className?: string; fill?: string; "aria-label"?: string }
type Octicon = ComponentType<OcticonProps>

export const octicons: Record<string, Octicon> = {
  activity: PulseIcon,
  alert: AlertIcon,
  "alert-circle": AlertIcon,
  archive: ArchiveIcon,
  "arrow-down": ArrowDownIcon,
  "arrow-left": ArrowLeftIcon,
  "arrow-right": ArrowRightIcon,
  "arrow-up": ArrowUpIcon,
  "bar-chart": GraphIcon,
  bell: BellIcon,
  "bell-fill": BellFillIcon,
  book: BookIcon,
  bot: CopilotIcon,
  boxes: PackageIcon,
  briefcase: BriefcaseIcon,
  calendar: CalendarIcon,
  check: CheckIcon,
  "check-circle": CheckCircleIcon,
  "check-circle-fill": CheckCircleFillIcon,
  "chevron-down": ChevronDownIcon,
  "chevron-left": ChevronLeftIcon,
  "chevron-right": ChevronRightIcon,
  "chevron-up": ChevronUpIcon,
  "circle-help": QuestionIcon,
  clipboard: PasteIcon,
  clock: ClockIcon,
  code: CodeIcon,
  columns: ColumnsIcon,
  copy: CopyIcon,
  "credit-card": CreditCardIcon,
  "device-mobile": DeviceMobileIcon,
  download: DownloadIcon,
  edit: PencilIcon,
  "ellipsis-horizontal": KebabHorizontalIcon,
  eye: EyeIcon,
  "eye-off": EyeClosedIcon,
  file: FileIcon,
  "file-plus": FileAddedIcon,
  folder: FileDirectoryIcon,
  filter: FilterIcon,
  gear: GearIcon,
  globe: GlobeIcon,
  grid: TableIcon,
  hash: HashIcon,
  heart: HeartIcon,
  history: HistoryIcon,
  home: HomeIcon,
  hourglass: HourglassIcon,
  image: ImageIcon,
  inbox: InboxIcon,
  info: InfoIcon,
  "kebab-horizontal": KebabHorizontalIcon,
  key: KeyIcon,
  "layout-dashboard": RowsIcon,
  link: LinkIcon,
  list: ListUnorderedIcon,
  loader: SyncIcon,
  location: LocationIcon,
  lock: LockIcon,
  "log-in": SignInIcon,
  "log-out": SignOutIcon,
  mail: MailIcon,
  "mark-github": MarkGithubIcon,
  menu: ThreeBarsIcon,
  "message-circle": CommentIcon,
  "message-square": CommentDiscussionIcon,
  mic: UnmuteIcon,
  minus: DashIcon,
  "more-horizontal": KebabHorizontalIcon,
  moon: MoonIcon,
  number: NumberIcon,
  organization: OrganizationIcon,
  package: PackageIcon,
  paintbrush: PaintbrushIcon,
  paperclip: PaperclipIcon,
  pencil: PencilIcon,
  pin: PinIcon,
  play: PlayIcon,
  plus: PlusIcon,
  plug: PlugIcon,
  question: QuestionIcon,
  refresh: SyncIcon,
  repo: RepoIcon,
  rocket: RocketIcon,
  search: SearchIcon,
  send: PaperAirplaneIcon,
  settings: GearIcon,
  shield: ShieldIcon,
  "shield-check": ShieldCheckIcon,
  "shopping-cart": PackageIcon,
  "sidebar-collapse": SidebarCollapseIcon,
  "sidebar-expand": SidebarExpandIcon,
  sliders: SlidersIcon,
  "sort-asc": SortAscIcon,
  "sort-desc": SortDescIcon,
  sparkles: SparkleFillIcon,
  star: StarIcon,
  "star-fill": StarFillIcon,
  sun: SunIcon,
  tag: TagIcon,
  terminal: TerminalIcon,
  tools: ToolsIcon,
  "triangle-down": TriangleDownIcon,
  type: TypographyIcon,
  trash: TrashIcon,
  upload: UploadIcon,
  user: PersonIcon,
  users: PeopleIcon,
  video: VideoIcon,
  x: XIcon,
  "x-circle": XCircleIcon,
  zap: ZapIcon,
}

/** Octicon-only names mapped onto the shared adapter vocabulary when `?icons=` selects a third-party family. */
const adapterAliases: Record<string, string> = {
  alert: "alert-circle",
  "bell-fill": "bell",
  book: "archive",
  briefcase: "boxes",
  "check-circle": "check",
  "check-circle-fill": "check",
  code: "type",
  columns: "grid",
  "credit-card": "tag",
  "device-mobile": "grid",
  eye: "search",
  "eye-off": "minus",
  file: "file-plus",
  folder: "archive",
  gear: "settings",
  hash: "tag",
  history: "clock",
  hourglass: "clock",
  image: "grid",
  "kebab-horizontal": "more-horizontal",
  key: "lock",
  location: "globe",
  mail: "inbox",
  "mark-github": "globe",
  number: "list",
  organization: "users",
  package: "boxes",
  paintbrush: "pencil",
  pin: "tag",
  question: "circle-help",
  repo: "archive",
  rocket: "zap",
  "shield-check": "shield",
  "sidebar-collapse": "chevron-left",
  "sidebar-expand": "chevron-right",
  "sort-asc": "arrow-up",
  "sort-desc": "arrow-down",
  "star-fill": "star",
  terminal: "type",
  tools: "sliders",
  "triangle-down": "chevron-down",
  video: "play",
  "x-circle": "x",
}

export function iconFamily(): string {
  const value = new URLSearchParams(window.location.search).get("icons")
  return value === "lucide" || value === "tabler" || value === "phosphor" || value === "heroicons" ? value : "native"
}

export type IconProps = { name: string; size?: number; className?: string }

/** Octicons by default (Primer's native icon set); `?icons=lucide|tabler|phosphor|heroicons` routes to the shared adapter. */
export function Icon({ name, size = 16, className }: IconProps) {
  if (iconFamily() !== "native") return <GalleryIcon name={adapterAliases[name] ?? name} size={size} className={className} />
  const Component = octicons[name] ?? QuestionIcon
  return <Component size={size} className={className} />
}

export type IconComponent = FunctionComponent<OcticonProps>
const cache = new Map<string, IconComponent>()

/** Returns an Octicon-compatible function component for Primer visual props (`leadingVisual`, `icon`, ...). */
export function iconFor(name: string): IconComponent {
  const family = iconFamily()
  const key = `${family}:${name}`
  const cached = cache.get(key)
  if (cached) return cached
  let component: IconComponent
  if (family !== "native") {
    const adapterName = adapterAliases[name] ?? name
    component = (props) => <GalleryIcon name={adapterName} size={typeof props.size === "number" ? props.size : 16} className={props.className} />
  } else {
    const Native = octicons[name] ?? QuestionIcon
    component = (props) => <Native {...props} />
  }
  component.displayName = `Icon(${name})`
  cache.set(key, component)
  return component
}
