/* eslint-disable solid/prefer-for */
import { createSignal, For } from "solid-js"
import landing from "@ui-gallery/spec/mock/landing.json"
import plans from "@ui-gallery/spec/mock/plans.json"
import { Icon } from "@/icons"
import { Avatar } from "@/ui/avatar"
import { Badge } from "@/ui/badge"
import { Button } from "@/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/ui/card"
import { Drawer } from "@/ui/dialog"
import { Select } from "@/ui/select"
import { Switch } from "@/ui/switch"
import { Accordion } from "@/ui/accordion"

export function LandingPage() {
  const [menu, setMenu] = createSignal(false)
  const [yearly, setYearly] = createSignal(false)
  const price = (value: number | null) => value === null ? "联系我们" : `¥${yearly() ? value * 10 : value}/${yearly() ? "年" : "月"}`
  return <div class="min-h-screen overflow-x-hidden bg-white text-zinc-950 dark:bg-zinc-950 dark:text-zinc-50">
    <header class="sticky top-0 z-30 border-b border-zinc-200 bg-white/90 backdrop-blur dark:border-zinc-800 dark:bg-zinc-950/90"><div class="mx-auto flex h-16 max-w-6xl items-center gap-6 px-4 sm:px-6"><a href="#" class="flex items-center gap-2 font-semibold"><span class="grid size-8 place-items-center rounded-lg bg-zinc-900 text-white dark:bg-zinc-100 dark:text-zinc-900">A</span>Acme</a><nav class="hidden flex-1 items-center justify-center gap-5 text-sm text-zinc-600 md:flex dark:text-zinc-300"><For each={["产品", "定价", "客户", "文档", "博客"]}>{(item) => <a href={`#${item}`} class="inline-flex min-h-10 items-center px-1 hover:text-zinc-950 dark:hover:text-zinc-50">{item}</a>}</For></nav><Button class="hidden md:inline-flex">开始使用</Button><Button variant="ghost" size="icon" class="md:hidden" aria-label="打开菜单" onClick={() => setMenu(true)}><Icon name="menu" /></Button></div></header>
    <Drawer open={menu()} onOpenChange={setMenu} title="Acme" description="导航"><nav class="grid gap-1"><For each={["产品", "定价", "客户", "文档", "博客"]}>{(item) => <a href={`#${item}`} class="flex min-h-11 items-center rounded-md px-3">{item}</a>}</For></nav></Drawer>
    <main>
      <section class="mx-auto grid max-w-6xl gap-10 px-4 py-20 sm:px-6 lg:grid-cols-2 lg:items-center lg:py-28"><div><h1 class="text-4xl font-bold tracking-tight sm:text-6xl">{landing.hero.title}</h1><p class="mt-5 max-w-xl text-lg text-zinc-600 dark:text-zinc-300">{landing.hero.subtitle}</p><div class="mt-8 flex flex-wrap gap-3"><Button>{landing.hero.primary}</Button><Button variant="outline">{landing.hero.secondary}</Button></div><div class="mt-8 flex items-center gap-3"><div class="flex -space-x-2"><For each={["林", "陈", "王", "赵", "周"]}>{(initial) => <Avatar name={initial} class="ring-2 ring-white dark:ring-zinc-950" />}</For></div><span class="text-sm text-zinc-600 dark:text-zinc-400">{landing.hero.social}</span></div></div><div class="rounded-3xl border border-zinc-200 bg-zinc-100 p-8 dark:border-zinc-800 dark:bg-zinc-900"><div class="aspect-video rounded-2xl bg-gradient-to-br from-blue-600 to-indigo-900" /></div></section>
      <section class="border-y border-zinc-200 py-8 dark:border-zinc-800"><div class="mx-auto grid max-w-6xl grid-cols-2 gap-3 px-4 sm:grid-cols-3 lg:grid-cols-6 sm:px-6"><For each={[1, 2, 3, 4, 5, 6]}>{() => <div class="grid h-14 place-items-center rounded-lg bg-zinc-100 text-xs font-semibold text-zinc-600 dark:bg-zinc-900 dark:text-zinc-400">LOGO</div>}</For></div></section>
      <section class="mx-auto max-w-6xl px-4 py-20 sm:px-6"><h2 class="text-center text-3xl font-bold">为团队而生</h2><div class="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><For each={landing.features}>{(feature) => <Card><CardHeader><Icon name={feature.icon} size={22} class="text-blue-600" /><CardTitle>{feature.title}</CardTitle></CardHeader><CardContent class="text-sm text-zinc-600 dark:text-zinc-300">{feature.desc}</CardContent></Card>}</For></div></section>
      <For each={landing.features.slice(0, 3)}>{(feature, index) => <section class="border-t border-zinc-200 py-16 dark:border-zinc-800"><div class={`mx-auto grid max-w-6xl gap-8 px-4 sm:px-6 md:grid-cols-2 md:items-center ${index() % 2 ? "md:[&>*:first-child]:order-2" : ""}`}><div class="aspect-video rounded-2xl bg-zinc-100 dark:bg-zinc-900" /><div><h2 class="text-2xl font-bold">{feature.title}</h2><p class="mt-3 text-zinc-600 dark:text-zinc-300">{feature.desc}</p></div></div></section>}</For>
      <section class="bg-zinc-900 py-14 text-white dark:bg-zinc-100 dark:text-zinc-900"><div class="mx-auto grid max-w-6xl grid-cols-2 gap-8 px-4 sm:grid-cols-4 sm:px-6"><For each={landing.numbers}>{(number) => <div><p class="text-3xl font-bold">{number.value}</p><p class="mt-1 text-sm opacity-70">{number.label}</p></div>}</For></div></section>
      <section id="定价" class="mx-auto max-w-6xl px-4 py-20 sm:px-6"><div class="flex flex-wrap items-center justify-between gap-4"><h2 class="text-3xl font-bold">简单透明的定价</h2><Switch label="按年计费" checked={yearly()} onChange={setYearly} /></div><div class="mt-8 grid gap-4 lg:grid-cols-3"><For each={plans}>{(plan) => <Card class={plan.recommended ? "border-blue-600" : ""}><CardHeader><div class="flex justify-between"><CardTitle>{plan.name}</CardTitle>{plan.recommended ? <Badge>推荐</Badge> : null}</div><p class="text-2xl font-bold">{price(plan.price)}</p></CardHeader><CardContent class="grid gap-3">{plan.features.map((feature) => <p class="text-sm">✓ {feature}</p>)}<Button variant={plan.recommended ? "primary" : "outline"}>选择计划</Button></CardContent></Card>}</For></div></section>
      <section class="mx-auto max-w-6xl px-4 py-16 sm:px-6"><div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><For each={landing.testimonials}>{(quote) => <Card><CardContent class="p-6"><p>“{quote.quote}”</p><p class="mt-5 text-sm text-zinc-500 dark:text-zinc-400">{quote.name} · {quote.company}</p></CardContent></Card>}</For></div></section>
      <section class="mx-auto max-w-3xl px-4 py-16 sm:px-6"><h2 class="text-center text-3xl font-bold">常见问题</h2><Accordion class="mt-8">{landing.faq.map((item) => <Accordion.Item value={item.q}><Accordion.Trigger class="flex w-full justify-between border-b py-4 text-left font-medium">{item.q}<span>+</span></Accordion.Trigger><Accordion.Content class="border-b py-4 text-sm text-zinc-600 dark:text-zinc-300">{item.a}</Accordion.Content></Accordion.Item>)}</Accordion></section>
      <section class="mx-4 rounded-3xl bg-blue-600 px-6 py-14 text-center text-white sm:mx-auto sm:max-w-6xl"><h2 class="text-3xl font-bold">准备好开始了吗？</h2><Button class="mt-6 bg-white text-blue-700">立即开始</Button></section>
    </main>
    <footer class="mx-auto grid max-w-6xl gap-8 border-t border-zinc-200 px-4 py-14 sm:grid-cols-2 lg:grid-cols-4 sm:px-6"><div><div class="font-semibold">Acme Console</div><p class="mt-3 max-w-xs text-sm text-zinc-500 dark:text-zinc-400">让团队在一个清晰的工作空间中协作。</p><div class="mt-5 flex gap-2"><Button variant="ghost" size="icon" aria-label="全球网站"><Icon name="globe" /></Button><Button variant="ghost" size="icon" aria-label="消息社区"><Icon name="message-circle" /></Button><Button variant="ghost" size="icon" aria-label="链接"><Icon name="link-2" /></Button><Button variant="ghost" size="icon" aria-label="邮件"><Icon name="mail" /></Button></div></div><For each={["产品", "公司", "资源"]}>{(title) => <div><p class="font-medium">{title}</p><div class="mt-3 grid text-sm text-zinc-600 dark:text-zinc-400"><a href="#" class="inline-flex min-h-10 items-center">概览</a><a href="#" class="inline-flex min-h-10 items-center">文档</a><a href="#" class="inline-flex min-h-10 items-center">联系</a></div></div>}</For><div><p class="font-medium">更多</p><div class="mt-3 grid text-sm text-zinc-600 dark:text-zinc-400"><a href="#" class="inline-flex min-h-10 items-center">博客</a><a href="#" class="inline-flex min-h-10 items-center">客户案例</a><a href="#" class="inline-flex min-h-10 items-center">帮助中心</a></div><Select label="语言" options={[{ value: "zh", label: "简体中文" }, { value: "en", label: "English" }]} value="zh" /><p class="mt-4 text-sm text-zinc-500 dark:text-zinc-400">© 2025 Acme Console</p></div></footer>
  </div>
}
