import { h, type Component, type FunctionalComponent } from "vue"
import {
  AppstoreOutlined,
  ArrowDownOutlined,
  ArrowUpOutlined,
  BarChartOutlined,
  BellOutlined,
  BulbFilled,
  BulbOutlined,
  CheckOutlined,
  CloseOutlined,
  CopyOutlined,
  DeleteOutlined,
  DownloadOutlined,
  EditOutlined,
  FileAddOutlined,
  FileTextOutlined,
  FilterOutlined,
  GithubOutlined,
  GlobalOutlined,
  LayoutOutlined,
  LinkOutlined,
  LockOutlined,
  LoginOutlined,
  MenuOutlined,
  MessageOutlined,
  MoreOutlined,
  PaperClipOutlined,
  PlusOutlined,
  QuestionCircleOutlined,
  ReloadOutlined,
  RobotOutlined,
  SafetyOutlined,
  SearchOutlined,
  SendOutlined,
  SettingOutlined,
  ShoppingCartOutlined,
  StarOutlined,
  TagOutlined,
  TeamOutlined,
  ThunderboltOutlined,
  UploadOutlined,
  UserOutlined,
} from "@ant-design/icons-vue"
import {
  ArrowDown,
  ArrowUp,
  BarChart3,
  Bell,
  Bot,
  Boxes,
  Check,
  CircleHelp,
  Copy,
  Download,
  Edit3,
  FilePlus,
  Filter,
  Globe,
  LayoutDashboard,
  Lock,
  LogIn,
  Menu,
  MessageSquare,
  Moon,
  MoreHorizontal,
  Paperclip,
  Plus,
  Plug,
  RefreshCw,
  Search,
  Send,
  Settings,
  Shield,
  ShoppingCart,
  Star,
  Sun,
  Tag,
  Trash2,
  Upload,
  User,
  Users,
  X,
  Zap,
} from "lucide-vue-next"
import {
  IconArrowDown,
  IconArrowUp,
  IconBell,
  IconChartBar,
  IconCheck,
  IconCopy,
  IconDots,
  IconDownload,
  IconEdit,
  IconFilePlus,
  IconFilter,
  IconHome,
  IconInfoCircle,
  IconLayoutDashboard,
  IconLink,
  IconLock,
  IconLogin,
  IconMenu2,
  IconMessage,
  IconMoon,
  IconPaperclip,
  IconPlus,
  IconRefresh,
  IconSearch,
  IconSend,
  IconSettings,
  IconShield,
  IconShoppingCart,
  IconSparkles,
  IconStar,
  IconSun,
  IconTag,
  IconTrash,
  IconUpload,
  IconUser,
  IconUsers,
  IconX,
} from "@tabler/icons-vue"
import {
  PhArrowDown,
  PhArrowUp,
  PhBell,
  PhChatText,
  PhCheck,
  PhClipboard,
  PhCopy,
  PhDotsThree,
  PhDownloadSimple as PhDownload,
  PhFaders,
  PhFilePlus,
  PhGear,
  PhGlobe,
  PhHouse,
  PhLightning,
  PhLock,
  PhMagicWand,
  PhMagnifyingGlass as PhSearch,
  PhMoon,
  PhPaperPlaneTilt as PhSend,
  PhPaperclip,
  PhPencil,
  PhPlugs,
  PhPlus,
  PhRepeat,
  PhShield,
  PhShoppingCart,
  PhSparkle,
  PhStar,
  PhSun,
  PhTag,
  PhTrash,
  PhUploadSimple as PhUpload,
  PhUser,
  PhUsers,
  PhX,
} from "@phosphor-icons/vue"
import {
  ArrowDownIcon,
  ArrowPathIcon,
  ArrowUpIcon,
  BellIcon,
  ChartBarIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ClipboardIcon,
  CloudArrowUpIcon,
  Cog6ToothIcon,
  EllipsisHorizontalIcon,
  FolderPlusIcon,
  FunnelIcon,
  GlobeAltIcon,
  HomeIcon,
  InformationCircleIcon,
  LinkIcon,
  ListBulletIcon,
  LockClosedIcon,
  MagnifyingGlassIcon,
  MoonIcon,
  PaperAirplaneIcon,
  PaperClipIcon,
  PencilIcon,
  PlusIcon,
  PowerIcon,
  RocketLaunchIcon,
  ShieldCheckIcon,
  ShoppingCartIcon,
  SparklesIcon,
  StarIcon,
  SunIcon,
  TagIcon,
  TrashIcon,
  UserGroupIcon,
  UserIcon,
  XMarkIcon,
} from "@heroicons/vue/24/outline"

type IconProps = { name: string; size?: number | string; spin?: boolean }

const native: Record<string, Component> = {
  "layout-dashboard": LayoutOutlined,
  "shopping-cart": ShoppingCartOutlined,
  "file-plus": FileAddOutlined,
  "message-square": MessageOutlined,
  boxes: AppstoreOutlined,
  globe: GlobalOutlined,
  settings: SettingOutlined,
  "log-in": LoginOutlined,
  zap: ThunderboltOutlined,
  shield: SafetyOutlined,
  "bar-chart": BarChartOutlined,
  bot: RobotOutlined,
  plug: LinkOutlined,
  search: SearchOutlined,
  bell: BellOutlined,
  menu: MenuOutlined,
  moon: BulbOutlined,
  sun: BulbFilled,
  user: UserOutlined,
  users: TeamOutlined,
  plus: PlusOutlined,
  check: CheckOutlined,
  x: CloseOutlined,
  copy: CopyOutlined,
  download: DownloadOutlined,
  edit: EditOutlined,
  trash: DeleteOutlined,
  refresh: ReloadOutlined,
  upload: UploadOutlined,
  send: SendOutlined,
  paperclip: PaperClipOutlined,
  filter: FilterOutlined,
  tag: TagOutlined,
  star: StarOutlined,
  "arrow-up": ArrowUpOutlined,
  "arrow-down": ArrowDownOutlined,
  "more-horizontal": MoreOutlined,
  "circle-help": QuestionCircleOutlined,
  "file-text": FileTextOutlined,
  lock: LockOutlined,
  github: GithubOutlined,
}

const lucide: Record<string, Component> = {
  "layout-dashboard": LayoutDashboard,
  "shopping-cart": ShoppingCart,
  "file-plus": FilePlus,
  "message-square": MessageSquare,
  boxes: Boxes,
  globe: Globe,
  settings: Settings,
  "log-in": LogIn,
  zap: Zap,
  shield: Shield,
  "bar-chart": BarChart3,
  bot: Bot,
  plug: Plug,
  search: Search,
  bell: Bell,
  menu: Menu,
  moon: Moon,
  sun: Sun,
  user: User,
  users: Users,
  plus: Plus,
  check: Check,
  x: X,
  copy: Copy,
  download: Download,
  edit: Edit3,
  trash: Trash2,
  refresh: RefreshCw,
  upload: Upload,
  send: Send,
  paperclip: Paperclip,
  filter: Filter,
  tag: Tag,
  star: Star,
  "arrow-up": ArrowUp,
  "arrow-down": ArrowDown,
  "more-horizontal": MoreHorizontal,
  "circle-help": CircleHelp,
  lock: Lock,
}

const tabler: Record<string, Component> = {
  "layout-dashboard": IconLayoutDashboard,
  "shopping-cart": IconShoppingCart,
  "file-plus": IconFilePlus,
  "message-square": IconMessage,
  boxes: IconHome,
  globe: IconHome,
  settings: IconSettings,
  "log-in": IconLogin,
  zap: IconSparkles,
  shield: IconShield,
  "bar-chart": IconChartBar,
  bot: IconSparkles,
  plug: IconLink,
  search: IconSearch,
  bell: IconBell,
  menu: IconMenu2,
  moon: IconMoon,
  sun: IconSun,
  user: IconUser,
  users: IconUsers,
  plus: IconPlus,
  check: IconCheck,
  x: IconX,
  copy: IconCopy,
  download: IconDownload,
  edit: IconEdit,
  trash: IconTrash,
  refresh: IconRefresh,
  upload: IconUpload,
  send: IconSend,
  paperclip: IconPaperclip,
  filter: IconFilter,
  tag: IconTag,
  star: IconStar,
  "arrow-up": IconArrowUp,
  "arrow-down": IconArrowDown,
  "more-horizontal": IconDots,
  "circle-help": IconInfoCircle,
  lock: IconLock,
}

const phosphor: Record<string, Component> = {
  "layout-dashboard": PhHouse,
  "shopping-cart": PhShoppingCart,
  "file-plus": PhFilePlus,
  "message-square": PhChatText,
  boxes: PhHouse,
  globe: PhGlobe,
  settings: PhGear,
  "log-in": PhMagicWand,
  zap: PhLightning,
  shield: PhShield,
  "bar-chart": PhSparkle,
  bot: PhMagicWand,
  plug: PhPlugs,
  search: PhSearch,
  bell: PhBell,
  menu: PhDotsThree,
  moon: PhMoon,
  sun: PhSun,
  user: PhUser,
  users: PhUsers,
  plus: PhPlus,
  check: PhCheck,
  x: PhX,
  copy: PhCopy,
  download: PhDownload,
  edit: PhPencil,
  trash: PhTrash,
  refresh: PhRepeat,
  upload: PhUpload,
  send: PhSend,
  paperclip: PhPaperclip,
  filter: PhFaders,
  tag: PhTag,
  star: PhStar,
  "arrow-up": PhArrowUp,
  "arrow-down": PhArrowDown,
  "more-horizontal": PhDotsThree,
  "circle-help": PhMagicWand,
  lock: PhLock,
  "file-text": PhClipboard,
}

const hero: Record<string, Component> = {
  "layout-dashboard": HomeIcon,
  "shopping-cart": ShoppingCartIcon,
  "file-plus": FolderPlusIcon,
  "message-square": ListBulletIcon,
  boxes: ListBulletIcon,
  globe: GlobeAltIcon,
  settings: Cog6ToothIcon,
  "log-in": PowerIcon,
  zap: RocketLaunchIcon,
  shield: ShieldCheckIcon,
  "bar-chart": ChartBarIcon,
  bot: SparklesIcon,
  plug: LinkIcon,
  search: MagnifyingGlassIcon,
  bell: BellIcon,
  menu: ListBulletIcon,
  moon: MoonIcon,
  sun: SunIcon,
  user: UserIcon,
  users: UserGroupIcon,
  plus: PlusIcon,
  check: CheckIcon,
  x: XMarkIcon,
  copy: ClipboardIcon,
  download: CloudArrowUpIcon,
  edit: PencilIcon,
  trash: TrashIcon,
  refresh: ArrowPathIcon,
  upload: CloudArrowUpIcon,
  send: PaperAirplaneIcon,
  paperclip: PaperClipIcon,
  filter: FunnelIcon,
  tag: TagIcon,
  star: StarIcon,
  "arrow-up": ArrowUpIcon,
  "arrow-down": ArrowDownIcon,
  "more-horizontal": EllipsisHorizontalIcon,
  "circle-help": InformationCircleIcon,
  "chevron-down": ChevronDownIcon,
  "chevron-left": ChevronLeftIcon,
  "chevron-right": ChevronRightIcon,
  "chevron-up": ChevronUpIcon,
  link: LinkIcon,
  lock: LockClosedIcon,
}

const selected: "native" | "lucide" | "tabler" | "phosphor" | "heroicons" = (() => {
  const params = new URLSearchParams(window.location.search)
  const value = params.get("icons") ?? params.get("icon")
  return value === "tabler" || value === "phosphor" || value === "heroicons" || value === "lucide" ? value : "native"
})()

function lookup(name: string): Component {
  if (selected === "tabler") return tabler[name] ?? IconInfoCircle
  if (selected === "phosphor") return phosphor[name] ?? PhMagicWand
  if (selected === "heroicons") return hero[name] ?? InformationCircleIcon
  if (selected === "lucide") return lucide[name] ?? CircleHelp
  return native[name] ?? QuestionCircleOutlined
}

export const Icon: FunctionalComponent<IconProps> = (props) => {
  const Component = lookup(props.name)
  const size = props.size ?? 16
  return h(Component, {
    style: { fontSize: `${size}px`, width: `${size}px`, height: `${size}px` },
    spin: props.spin,
  })
}

Icon.props = ["name", "size", "spin"]
