import { defineComponent, h, type Component, type PropType } from "vue"
import * as Arco from "@arco-design/web-vue/es/icon"
import * as Lucide from "lucide-vue-next"
import * as Tabler from "@tabler/icons-vue"
import * as Phosphor from "@phosphor-icons/vue"
import * as Hero from "@heroicons/vue/24/outline"

export type IconFamily = "native" | "lucide" | "tabler" | "phosphor" | "heroicons"
export const ICON_FAMILIES: IconFamily[] = ["native", "lucide", "tabler", "phosphor", "heroicons"]

type Table = Record<string, Component>

// Arco Design 自带图标体系（默认）
const native: Table = {
  "arrow-right": Arco.IconArrowRight,
  camera: Arco.IconCamera,
  "check-circle": Arco.IconCheckCircle,
  columns: Arco.IconLayout,
  "credit-card": Arco.IconWechatpay,
  "external-link": Arco.IconLaunch,
  "file-text": Arco.IconFile,
  grid: Arco.IconApps,
  "help-circle": Arco.IconQuestionCircle,
  monitor: Arco.IconDesktop,
  share: Arco.IconShareAlt,
  smartphone: Arco.IconMobile,
  smile: Arco.IconFaceSmileFill,
  terminal: Arco.IconCommand,
  "thumbs-down": Arco.IconThumbDown,
  "thumbs-up": Arco.IconThumbUp,
  "user-plus": Arco.IconUserAdd,
  "x-circle": Arco.IconCloseCircle,
  activity: Arco.IconBarChart,
  "alert-circle": Arco.IconExclamationCircle,
  archive: Arco.IconArchive,
  "arrow-down": Arco.IconArrowDown,
  "arrow-up": Arco.IconArrowRise,
  "bar-chart": Arco.IconBarChart,
  bell: Arco.IconNotification,
  bot: Arco.IconRobot,
  boxes: Arco.IconApps,
  calendar: Arco.IconCalendar,
  check: Arco.IconCheck,
  "chevron-down": Arco.IconDown,
  "chevron-left": Arco.IconLeft,
  "chevron-right": Arco.IconRight,
  "chevron-up": Arco.IconUp,
  "circle-help": Arco.IconQuestionCircle,
  clipboard: Arco.IconCopy,
  clock: Arco.IconClockCircle,
  code: Arco.IconCode,
  copy: Arco.IconCopy,
  download: Arco.IconDownload,
  edit: Arco.IconEdit,
  eye: Arco.IconEye,
  "eye-off": Arco.IconEyeInvisible,
  "file-plus": Arco.IconFile,
  filter: Arco.IconFilter,
  github: Arco.IconGithub,
  globe: Arco.IconPublic,
  heart: Arco.IconHeart,
  home: Arco.IconHome,
  inbox: Arco.IconArchive,
  info: Arco.IconInfoCircle,
  "layout-dashboard": Arco.IconDashboard,
  link: Arco.IconLink,
  list: Arco.IconList,
  loader: Arco.IconLoading,
  lock: Arco.IconLock,
  "log-in": Arco.IconImport,
  "log-out": Arco.IconExport,
  mail: Arco.IconEmail,
  menu: Arco.IconMenu,
  "message-circle": Arco.IconWechat,
  "message-square": Arco.IconMessage,
  mic: Arco.IconVoice,
  minus: Arco.IconMinus,
  moon: Arco.IconMoon,
  "more-horizontal": Arco.IconMore,
  paperclip: Arco.IconAttachment,
  play: Arco.IconPlayArrow,
  plug: Arco.IconCodeSandbox,
  plus: Arco.IconPlus,
  refresh: Arco.IconRefresh,
  search: Arco.IconSearch,
  send: Arco.IconSend,
  settings: Arco.IconSettings,
  shield: Arco.IconSafe,
  "shopping-cart": Arco.IconGift,
  sliders: Arco.IconSettings,
  sparkles: Arco.IconFire,
  star: Arco.IconStar,
  sun: Arco.IconSun,
  tag: Arco.IconTag,
  trash: Arco.IconDelete,
  upload: Arco.IconUpload,
  user: Arco.IconUser,
  users: Arco.IconUserGroup,
  x: Arco.IconClose,
  zap: Arco.IconThunderbolt,
  google: Arco.IconGoogle,
  wechat: Arco.IconWechat,
}

const lucide: Table = {
  "arrow-right": Lucide.ArrowRight,
  camera: Lucide.Camera,
  "check-circle": Lucide.CircleCheck,
  columns: Lucide.Columns3,
  "credit-card": Lucide.CreditCard,
  "external-link": Lucide.ExternalLink,
  "file-text": Lucide.FileText,
  grid: Lucide.LayoutGrid,
  "help-circle": Lucide.CircleHelp,
  monitor: Lucide.Monitor,
  share: Lucide.Share2,
  smartphone: Lucide.Smartphone,
  smile: Lucide.Smile,
  terminal: Lucide.Terminal,
  "thumbs-down": Lucide.ThumbsDown,
  "thumbs-up": Lucide.ThumbsUp,
  "user-plus": Lucide.UserPlus,
  "x-circle": Lucide.CircleX,
  activity: Lucide.Activity,
  "alert-circle": Lucide.CircleAlert,
  archive: Lucide.Archive,
  "arrow-down": Lucide.ArrowDown,
  "arrow-up": Lucide.ArrowUp,
  "bar-chart": Lucide.ChartColumn,
  bell: Lucide.Bell,
  bot: Lucide.Bot,
  boxes: Lucide.Boxes,
  calendar: Lucide.CalendarDays,
  check: Lucide.Check,
  "chevron-down": Lucide.ChevronDown,
  "chevron-left": Lucide.ChevronLeft,
  "chevron-right": Lucide.ChevronRight,
  "chevron-up": Lucide.ChevronUp,
  "circle-help": Lucide.CircleHelp,
  clipboard: Lucide.Clipboard,
  clock: Lucide.Clock3,
  code: Lucide.Code,
  copy: Lucide.Copy,
  download: Lucide.Download,
  edit: Lucide.Pencil,
  eye: Lucide.Eye,
  "eye-off": Lucide.EyeOff,
  "file-plus": Lucide.FilePlus,
  filter: Lucide.Filter,
  github: Lucide.Github,
  globe: Lucide.Globe,
  heart: Lucide.Heart,
  home: Lucide.House,
  inbox: Lucide.Inbox,
  info: Lucide.Info,
  "layout-dashboard": Lucide.LayoutDashboard,
  link: Lucide.Link2,
  list: Lucide.List,
  loader: Lucide.LoaderCircle,
  lock: Lucide.Lock,
  "log-in": Lucide.LogIn,
  "log-out": Lucide.LogOut,
  mail: Lucide.Mail,
  menu: Lucide.Menu,
  "message-circle": Lucide.MessageCircle,
  "message-square": Lucide.MessageSquare,
  mic: Lucide.Mic,
  minus: Lucide.Minus,
  moon: Lucide.Moon,
  "more-horizontal": Lucide.Ellipsis,
  paperclip: Lucide.Paperclip,
  play: Lucide.Play,
  plug: Lucide.Plug,
  plus: Lucide.Plus,
  refresh: Lucide.RefreshCw,
  search: Lucide.Search,
  send: Lucide.Send,
  settings: Lucide.Settings,
  shield: Lucide.Shield,
  "shopping-cart": Lucide.ShoppingCart,
  sliders: Lucide.SlidersHorizontal,
  sparkles: Lucide.Sparkles,
  star: Lucide.Star,
  sun: Lucide.Sun,
  tag: Lucide.Tag,
  trash: Lucide.Trash2,
  upload: Lucide.Upload,
  user: Lucide.User,
  users: Lucide.Users,
  x: Lucide.X,
  zap: Lucide.Zap,
  google: Lucide.Globe,
  wechat: Lucide.MessageCircle,
}

const tabler: Table = {
  "arrow-right": Tabler.IconArrowRight,
  camera: Tabler.IconCamera,
  "check-circle": Tabler.IconCircleCheck,
  columns: Tabler.IconColumns,
  "credit-card": Tabler.IconCreditCard,
  "external-link": Tabler.IconExternalLink,
  "file-text": Tabler.IconFileText,
  grid: Tabler.IconLayoutGrid,
  "help-circle": Tabler.IconHelpCircle,
  monitor: Tabler.IconDeviceDesktop,
  share: Tabler.IconShare,
  smartphone: Tabler.IconDeviceMobile,
  smile: Tabler.IconMoodSmile,
  terminal: Tabler.IconTerminal2,
  "thumbs-down": Tabler.IconThumbDown,
  "thumbs-up": Tabler.IconThumbUp,
  "user-plus": Tabler.IconUserPlus,
  "x-circle": Tabler.IconCircleX,
  activity: Tabler.IconActivity,
  "alert-circle": Tabler.IconAlertCircle,
  archive: Tabler.IconArchive,
  "arrow-down": Tabler.IconArrowDown,
  "arrow-up": Tabler.IconArrowUp,
  "bar-chart": Tabler.IconChartBar,
  bell: Tabler.IconBell,
  bot: Tabler.IconRobot,
  boxes: Tabler.IconBox,
  calendar: Tabler.IconCalendar,
  check: Tabler.IconCheck,
  "chevron-down": Tabler.IconChevronDown,
  "chevron-left": Tabler.IconChevronLeft,
  "chevron-right": Tabler.IconChevronRight,
  "chevron-up": Tabler.IconChevronUp,
  "circle-help": Tabler.IconHelpCircle,
  clipboard: Tabler.IconClipboard,
  clock: Tabler.IconClock,
  code: Tabler.IconCode,
  copy: Tabler.IconCopy,
  download: Tabler.IconDownload,
  edit: Tabler.IconEdit,
  eye: Tabler.IconEye,
  "eye-off": Tabler.IconEyeOff,
  "file-plus": Tabler.IconFilePlus,
  filter: Tabler.IconFilter,
  github: Tabler.IconBrandGithub,
  globe: Tabler.IconWorld,
  heart: Tabler.IconHeart,
  home: Tabler.IconHome,
  inbox: Tabler.IconInbox,
  info: Tabler.IconInfoCircle,
  "layout-dashboard": Tabler.IconLayoutDashboard,
  link: Tabler.IconLink,
  list: Tabler.IconList,
  loader: Tabler.IconLoader2,
  lock: Tabler.IconLock,
  "log-in": Tabler.IconLogin,
  "log-out": Tabler.IconLogout,
  mail: Tabler.IconMail,
  menu: Tabler.IconMenu2,
  "message-circle": Tabler.IconMessageCircle,
  "message-square": Tabler.IconMessage,
  mic: Tabler.IconMicrophone,
  minus: Tabler.IconMinus,
  moon: Tabler.IconMoon,
  "more-horizontal": Tabler.IconDots,
  paperclip: Tabler.IconPaperclip,
  play: Tabler.IconPlayerPlay,
  plug: Tabler.IconPlug,
  plus: Tabler.IconPlus,
  refresh: Tabler.IconRefresh,
  search: Tabler.IconSearch,
  send: Tabler.IconSend,
  settings: Tabler.IconSettings,
  shield: Tabler.IconShield,
  "shopping-cart": Tabler.IconShoppingCart,
  sliders: Tabler.IconAdjustmentsHorizontal,
  sparkles: Tabler.IconSparkles,
  star: Tabler.IconStar,
  sun: Tabler.IconSun,
  tag: Tabler.IconTag,
  trash: Tabler.IconTrash,
  upload: Tabler.IconUpload,
  user: Tabler.IconUser,
  users: Tabler.IconUsers,
  x: Tabler.IconX,
  zap: Tabler.IconBolt,
  google: Tabler.IconBrandGoogle,
  wechat: Tabler.IconBrandWechat,
}

const phosphor: Table = {
  "arrow-right": Phosphor.PhArrowRight,
  camera: Phosphor.PhCamera,
  "check-circle": Phosphor.PhCheckCircle,
  columns: Phosphor.PhColumns,
  "credit-card": Phosphor.PhCreditCard,
  "external-link": Phosphor.PhArrowSquareOut,
  "file-text": Phosphor.PhFileText,
  grid: Phosphor.PhGridFour,
  "help-circle": Phosphor.PhQuestion,
  monitor: Phosphor.PhDesktop,
  share: Phosphor.PhShareNetwork,
  smartphone: Phosphor.PhDeviceMobile,
  smile: Phosphor.PhSmiley,
  terminal: Phosphor.PhTerminal,
  "thumbs-down": Phosphor.PhThumbsDown,
  "thumbs-up": Phosphor.PhThumbsUp,
  "user-plus": Phosphor.PhUserPlus,
  "x-circle": Phosphor.PhXCircle,
  activity: Phosphor.PhPulse,
  "alert-circle": Phosphor.PhWarningCircle,
  archive: Phosphor.PhArchive,
  "arrow-down": Phosphor.PhArrowDown,
  "arrow-up": Phosphor.PhArrowUp,
  "bar-chart": Phosphor.PhChartBar,
  bell: Phosphor.PhBell,
  bot: Phosphor.PhRobot,
  boxes: Phosphor.PhCube,
  calendar: Phosphor.PhCalendar,
  check: Phosphor.PhCheck,
  "chevron-down": Phosphor.PhCaretDown,
  "chevron-left": Phosphor.PhCaretLeft,
  "chevron-right": Phosphor.PhCaretRight,
  "chevron-up": Phosphor.PhCaretUp,
  "circle-help": Phosphor.PhQuestion,
  clipboard: Phosphor.PhClipboard,
  clock: Phosphor.PhClock,
  code: Phosphor.PhCode,
  copy: Phosphor.PhCopy,
  download: Phosphor.PhDownloadSimple,
  edit: Phosphor.PhPencil,
  eye: Phosphor.PhEye,
  "eye-off": Phosphor.PhEyeSlash,
  "file-plus": Phosphor.PhFilePlus,
  filter: Phosphor.PhFunnel,
  github: Phosphor.PhGithubLogo,
  globe: Phosphor.PhGlobe,
  heart: Phosphor.PhHeart,
  home: Phosphor.PhHouse,
  inbox: Phosphor.PhTray,
  info: Phosphor.PhInfo,
  "layout-dashboard": Phosphor.PhSquaresFour,
  link: Phosphor.PhLink,
  list: Phosphor.PhList,
  loader: Phosphor.PhCircleNotch,
  lock: Phosphor.PhLock,
  "log-in": Phosphor.PhSignIn,
  "log-out": Phosphor.PhSignOut,
  mail: Phosphor.PhEnvelope,
  menu: Phosphor.PhList,
  "message-circle": Phosphor.PhChatCircle,
  "message-square": Phosphor.PhChatText,
  mic: Phosphor.PhMicrophone,
  minus: Phosphor.PhMinus,
  moon: Phosphor.PhMoon,
  "more-horizontal": Phosphor.PhDotsThree,
  paperclip: Phosphor.PhPaperclip,
  play: Phosphor.PhPlay,
  plug: Phosphor.PhPlugs,
  plus: Phosphor.PhPlus,
  refresh: Phosphor.PhArrowsClockwise,
  search: Phosphor.PhMagnifyingGlass,
  send: Phosphor.PhPaperPlaneTilt,
  settings: Phosphor.PhGear,
  shield: Phosphor.PhShieldCheck,
  "shopping-cart": Phosphor.PhShoppingCart,
  sliders: Phosphor.PhSlidersHorizontal,
  sparkles: Phosphor.PhSparkle,
  star: Phosphor.PhStar,
  sun: Phosphor.PhSun,
  tag: Phosphor.PhTag,
  trash: Phosphor.PhTrash,
  upload: Phosphor.PhUploadSimple,
  user: Phosphor.PhUser,
  users: Phosphor.PhUsers,
  x: Phosphor.PhX,
  zap: Phosphor.PhLightning,
  google: Phosphor.PhGlobe,
  wechat: Phosphor.PhChatCircle,
}

const heroicons: Table = {
  "arrow-right": Hero.ArrowRightIcon,
  camera: Hero.CameraIcon,
  "check-circle": Hero.CheckCircleIcon,
  columns: Hero.ViewColumnsIcon,
  "credit-card": Hero.CreditCardIcon,
  "external-link": Hero.ArrowTopRightOnSquareIcon,
  "file-text": Hero.DocumentTextIcon,
  grid: Hero.Squares2X2Icon,
  "help-circle": Hero.QuestionMarkCircleIcon,
  monitor: Hero.ComputerDesktopIcon,
  share: Hero.ShareIcon,
  smartphone: Hero.DevicePhoneMobileIcon,
  smile: Hero.FaceSmileIcon,
  terminal: Hero.CommandLineIcon,
  "thumbs-down": Hero.HandThumbDownIcon,
  "thumbs-up": Hero.HandThumbUpIcon,
  "user-plus": Hero.UserPlusIcon,
  "x-circle": Hero.XCircleIcon,
  activity: Hero.ChartBarIcon,
  "alert-circle": Hero.ExclamationCircleIcon,
  archive: Hero.ArchiveBoxIcon,
  "arrow-down": Hero.ArrowDownIcon,
  "arrow-up": Hero.ArrowUpIcon,
  "bar-chart": Hero.ChartBarIcon,
  bell: Hero.BellIcon,
  bot: Hero.CpuChipIcon,
  boxes: Hero.CubeIcon,
  calendar: Hero.CalendarDaysIcon,
  check: Hero.CheckIcon,
  "chevron-down": Hero.ChevronDownIcon,
  "chevron-left": Hero.ChevronLeftIcon,
  "chevron-right": Hero.ChevronRightIcon,
  "chevron-up": Hero.ChevronUpIcon,
  "circle-help": Hero.QuestionMarkCircleIcon,
  clipboard: Hero.ClipboardDocumentIcon,
  clock: Hero.ClockIcon,
  code: Hero.CodeBracketIcon,
  copy: Hero.ClipboardDocumentIcon,
  download: Hero.ArrowDownTrayIcon,
  edit: Hero.PencilIcon,
  eye: Hero.EyeIcon,
  "eye-off": Hero.EyeSlashIcon,
  "file-plus": Hero.DocumentPlusIcon,
  filter: Hero.FunnelIcon,
  github: Hero.CodeBracketIcon,
  globe: Hero.GlobeAltIcon,
  heart: Hero.HeartIcon,
  home: Hero.HomeIcon,
  inbox: Hero.InboxIcon,
  info: Hero.InformationCircleIcon,
  "layout-dashboard": Hero.Squares2X2Icon,
  link: Hero.LinkIcon,
  list: Hero.ListBulletIcon,
  loader: Hero.ArrowPathIcon,
  lock: Hero.LockClosedIcon,
  "log-in": Hero.ArrowRightOnRectangleIcon,
  "log-out": Hero.ArrowLeftOnRectangleIcon,
  mail: Hero.EnvelopeIcon,
  menu: Hero.Bars3Icon,
  "message-circle": Hero.ChatBubbleLeftIcon,
  "message-square": Hero.ChatBubbleLeftRightIcon,
  mic: Hero.MicrophoneIcon,
  minus: Hero.MinusIcon,
  moon: Hero.MoonIcon,
  "more-horizontal": Hero.EllipsisHorizontalIcon,
  paperclip: Hero.PaperClipIcon,
  play: Hero.PlayIcon,
  plug: Hero.PuzzlePieceIcon,
  plus: Hero.PlusIcon,
  refresh: Hero.ArrowPathIcon,
  search: Hero.MagnifyingGlassIcon,
  send: Hero.PaperAirplaneIcon,
  settings: Hero.Cog6ToothIcon,
  shield: Hero.ShieldCheckIcon,
  "shopping-cart": Hero.ShoppingCartIcon,
  sliders: Hero.AdjustmentsHorizontalIcon,
  sparkles: Hero.SparklesIcon,
  star: Hero.StarIcon,
  sun: Hero.SunIcon,
  tag: Hero.TagIcon,
  trash: Hero.TrashIcon,
  upload: Hero.ArrowUpTrayIcon,
  user: Hero.UserIcon,
  users: Hero.UserGroupIcon,
  x: Hero.XMarkIcon,
  zap: Hero.BoltIcon,
  google: Hero.GlobeAltIcon,
  wechat: Hero.ChatBubbleLeftIcon,
}

const families: Record<IconFamily, Table> = { native, lucide, tabler, phosphor, heroicons }

export function iconFamily(): IconFamily {
  if (typeof window === "undefined") return "native"
  const params = new URLSearchParams(window.location.search)
  const value = params.get("icons") ?? params.get("icon")
  return ICON_FAMILIES.includes(value as IconFamily) ? (value as IconFamily) : "native"
}

export function resolveIcon(name: string): Component {
  const table = families[iconFamily()]
  return table[name] ?? table["circle-help"] ?? Arco.IconQuestionCircle
}

export const Icon = defineComponent({
  name: "GalleryIcon",
  props: {
    name: { type: String as PropType<string>, required: true },
    size: { type: [Number, String] as PropType<number | string>, default: 16 },
    spin: { type: Boolean, default: false },
  },
  setup(props) {
    return () => {
      const family = iconFamily()
      const component = resolveIcon(props.name)
      const size = typeof props.size === "number" ? `${props.size}px` : props.size
      const base = {
        "aria-hidden": "true",
        class: ["gallery-icon", { "gallery-icon--spin": props.spin }],
        style: { width: size, height: size, fontSize: size },
      }
      if (family === "native") return h(component, { ...base, size: props.size, spin: props.spin })
      if (family === "lucide" || family === "tabler") return h(component, { ...base, size: props.size, strokeWidth: 1.75 })
      if (family === "phosphor") return h(component, { ...base, size: props.size })
      return h(component, base)
    }
  },
})
