import type { ComponentType, CSSProperties } from "react"
import { Icon as SharedIcon } from "@ui-gallery/icons-react"
import {
  IconApps,
  IconArchive,
  IconArrowDown,
  IconArrowLeft,
  IconArrowRight,
  IconArrowUp,
  IconCalendar,
  IconCheck,
  IconCheckCircle,
  IconClockCircle,
  IconCloseCircle,
  IconCopy,
  IconDashboard,
  IconDelete,
  IconDown,
  IconDownload,
  IconEdit,
  IconExclamationCircle,
  IconEye,
  IconEyeInvisible,
  IconFile,
  IconFilter,
  IconGithub,
  IconHeart,
  IconHome,
  IconImage,
  IconInfoCircle,
  IconLeft,
  IconLink,
  IconList,
  IconLoading,
  IconLock,
  IconMenu,
  IconMessage,
  IconMinus,
  IconMoon,
  IconMore,
  IconNotification,
  IconPlus,
  IconPublic,
  IconQuestionCircle,
  IconRefresh,
  IconRight,
  IconRobot,
  IconSafe,
  IconSearch,
  IconSend,
  IconSettings,
  IconShareExternal,
  IconStar,
  IconSun,
  IconTag,
  IconThunderbolt,
  IconUnorderedList,
  IconUp,
  IconUpload,
  IconUser,
  IconUserGroup,
  IconWechat,
  IconExport,
  IconAttachment,
} from "@arco-design/web-react/icon"

export type IconFamily = "native" | "lucide" | "tabler" | "phosphor" | "heroicons"

const shared: IconFamily[] = ["native", "lucide", "tabler", "phosphor", "heroicons"]

export function iconFamily(): IconFamily {
  if (typeof window === "undefined") return "lucide"
  const params = new URLSearchParams(window.location.search)
  const value = params.get("icons") ?? params.get("icon")
  return shared.includes(value as IconFamily) ? (value as IconFamily) : "lucide"
}

const native: Record<string, ComponentType<{ style?: CSSProperties; className?: string; spin?: boolean }>> = {
  activity: IconDashboard,
  "alert-circle": IconExclamationCircle,
  archive: IconArchive,
  "arrow-down": IconArrowDown,
  "arrow-left": IconArrowLeft,
  "arrow-right": IconArrowRight,
  "arrow-up": IconArrowUp,
  "bar-chart": IconDashboard,
  bell: IconNotification,
  bot: IconRobot,
  boxes: IconApps,
  calendar: IconCalendar,
  check: IconCheck,
  "check-circle": IconCheckCircle,
  "chevron-down": IconDown,
  "chevron-left": IconLeft,
  "chevron-right": IconRight,
  "chevron-up": IconUp,
  "circle-help": IconQuestionCircle,
  clipboard: IconCopy,
  clock: IconClockCircle,
  copy: IconCopy,
  download: IconDownload,
  edit: IconEdit,
  "ellipsis-horizontal": IconMore,
  eye: IconEye,
  "eye-off": IconEyeInvisible,
  export: IconExport,
  "file-plus": IconFile,
  filter: IconFilter,
  github: IconGithub,
  globe: IconPublic,
  grid: IconApps,
  heart: IconHeart,
  home: IconHome,
  image: IconImage,
  inbox: IconArchive,
  info: IconInfoCircle,
  "layout-dashboard": IconDashboard,
  link: IconLink,
  list: IconList,
  loader: IconLoading,
  lock: IconLock,
  "log-in": IconUser,
  "log-out": IconExport,
  menu: IconMenu,
  "message-circle": IconWechat,
  "message-square": IconMessage,
  minus: IconMinus,
  "more-horizontal": IconMore,
  moon: IconMoon,
  paperclip: IconAttachment,
  pencil: IconEdit,
  plus: IconPlus,
  plug: IconShareExternal,
  refresh: IconRefresh,
  search: IconSearch,
  send: IconSend,
  settings: IconSettings,
  shield: IconSafe,
  "shopping-cart": IconUnorderedList,
  sparkles: IconThunderbolt,
  star: IconStar,
  sun: IconSun,
  tag: IconTag,
  trash: IconDelete,
  upload: IconUpload,
  user: IconUser,
  users: IconUserGroup,
  x: IconCloseCircle,
  zap: IconThunderbolt,
}

export function Icon({ name, size = 16, className, spin }: { name: string; size?: number; className?: string; spin?: boolean }) {
  if (iconFamily() !== "native") return <SharedIcon name={name} size={size} className={className} />
  const Native = native[name] ?? IconQuestionCircle
  return <Native className={className} spin={spin} style={{ fontSize: size, verticalAlign: "-0.15em" }} />
}
