<script lang="ts">
  import type { Component } from "svelte"
  import {
    Activity,
    AlertCircle,
    Archive,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    BarChart3,
    Bell,
    Bot,
    Boxes,
    CalendarDays,
    Check,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    CircleHelp,
    Clipboard,
    Clock3,
    Copy,
    Edit3,
    Ellipsis,
    FilePlus,
    Filter,
    Globe,
    Grid2X2,
    Heart,
    Home,
    Inbox,
    Info,
    LayoutDashboard,
    Link2,
    List,
    LoaderCircle,
    Lock,
    LogIn,
    LogOut,
    Menu,
    MessageCircle,
    MessageSquare,
    Mic,
    Minus,
    MoreHorizontal,
    Moon,
    Paperclip,
    Pencil,
    Play,
    Plus,
    Plug,
    RefreshCw,
    Search,
    Send,
    Settings,
    Shield,
    ShoppingCart,
    SlidersHorizontal,
    Sparkles,
    Star,
    Sun,
    Tag,
    Trash2,
    Upload,
    User,
    Users,
    X,
    Zap,
  } from "@lucide/svelte"
  import {
    IconActivity,
    IconAlertCircle,
    IconArchive,
    IconArrowDown,
    IconArrowLeft,
    IconArrowRight,
    IconArrowUp,
    IconBell,
    IconBox,
    IconCalendar,
    IconCheck,
    IconChevronDown,
    IconChevronLeft,
    IconChevronRight,
    IconChevronUp,
    IconCopy,
    IconDots,
    IconEdit,
    IconFilePlus,
    IconFilter,
    IconGlobe,
    IconGrid3x3,
    IconHeart,
    IconHome,
    IconInfoCircle,
    IconLayoutDashboard,
    IconLink,
    IconList,
    IconLoader2,
    IconLock,
    IconLogin,
    IconLogout,
    IconMenu2,
    IconMessageCircle,
    IconMessage,
    IconMicrophone,
    IconMinus,
    IconMoon,
    IconPaperclip,
    IconPencil,
    IconPlayerPlay,
    IconPlus,
    IconPlug,
    IconRefresh,
    IconSearch,
    IconSend,
    IconSettings,
    IconShield,
    IconShoppingCart,
    IconAdjustmentsHorizontal,
    IconSparkles,
    IconStar,
    IconSun,
    IconTag,
    IconTrash,
    IconUpload,
    IconUser,
    IconUsers,
    IconX,
    IconBolt,
  } from "@tabler/icons-svelte"
  import {
    Pulse as PhActivity,
    Archive as PhArchive,
    ArrowDown as PhArrowDown,
    ArrowLeft as PhArrowLeft,
    ArrowRight as PhArrowRight,
    ArrowUp as PhArrowUp,
    Bell as PhBell,
    Calendar as PhCalendar,
    Check as PhCheck,
    ChatCircle as PhChatCircle,
    ChatText as PhChatText,
    Circle as PhCircle,
    Clock as PhClock,
    Copy as PhCopy,
    DotsThree as PhDotsThree,
    Gear as PhGear,
    Globe as PhGlobe,
    House as PhHouse,
    Info as PhInfo,
    Link as PhLink,
    List as PhList,
    MagnifyingGlass as PhMagnifyingGlass,
    Minus as PhMinus,
    Moon as PhMoon,
    Paperclip as PhPaperclip,
    Pencil as PhPencil,
    Play as PhPlay,
    Plus as PhPlus,
    Robot as PhRobot,
    Rocket as PhRocket,
    PaperPlaneTilt as PhSend,
    Shield as PhShield,
    ShoppingCart as PhShoppingCart,
    Sparkle as PhSparkle,
    Star as PhStar,
    Sun as PhSun,
    Tag as PhTag,
    Trash as PhTrash,
    UploadSimple as PhUploadSimple,
    User as PhUser,
    Users as PhUsers,
    X as PhX,
  } from "phosphor-svelte"
  import {
    ArrowDown as HArrowDown,
    ArrowLeft as HArrowLeft,
    ArrowRight as HArrowRight,
    ArrowUp as HArrowUp,
    ArchiveBox as HArchiveBox,
    Bell as HBell,
    CalendarDays as HCalendarDays,
    Check as HCheck,
    ChevronDown as HChevronDown,
    ChevronLeft as HChevronLeft,
    ChevronRight as HChevronRight,
    ChevronUp as HChevronUp,
    Clipboard as HClipboard,
    Cog6Tooth as HCog6Tooth,
    DocumentText as HDocumentText,
    EllipsisHorizontal as HEllipsisHorizontal,
    ExclamationCircle as HExclamationCircle,
    GlobeAlt as HGlobeAlt,
    Home as HHome,
    InformationCircle as HInformationCircle,
    Link as HLink,
    MagnifyingGlass as HMagnifyingGlass,
    Bars3 as HMenu,
    Moon as HMoon,
    Pencil as HPencil,
    Play as HPlay,
    Plus as HPlus,
    RocketLaunch as HRocketLaunch,
    ShieldCheck as HShieldCheck,
    ShoppingCart as HShoppingCart,
    Sparkles as HSparkles,
    Star as HStar,
    Sun as HSun,
    Tag as HTag,
    Trash as HTrash,
    ArrowUpTray as HUpload,
    User as HUser,
    UserGroup as HUserGroup,
    XMark as HXMark,
  } from "svelte-hero-icons"
  import { Icon as HeroIcon, type IconSource } from "svelte-hero-icons"

  type Family = "lucide" | "tabler" | "phosphor" | "heroicons"
  type IconComponent = Component<{ size?: number; width?: number; height?: number; class?: string }>
  type HeroSource = IconSource

  const lucide: Record<string, IconComponent> = {
    activity: Activity,
    "alert-circle": AlertCircle,
    archive: Archive,
    "arrow-down": ArrowDown,
    "arrow-left": ArrowLeft,
    "arrow-right": ArrowRight,
    "arrow-up": ArrowUp,
    "bar-chart": BarChart3,
    bell: Bell,
    bot: Bot,
    boxes: Boxes,
    calendar: CalendarDays,
    check: Check,
    "chevron-down": ChevronDown,
    "chevron-left": ChevronLeft,
    "chevron-right": ChevronRight,
    "chevron-up": ChevronUp,
    "circle-help": CircleHelp,
    clipboard: Clipboard,
    clock: Clock3,
    copy: Copy,
    edit: Edit3,
    "ellipsis-horizontal": Ellipsis,
    "file-plus": FilePlus,
    filter: Filter,
    globe: Globe,
    grid: Grid2X2,
    heart: Heart,
    home: Home,
    inbox: Inbox,
    info: Info,
    "layout-dashboard": LayoutDashboard,
    link: Link2,
    list: List,
    loader: LoaderCircle,
    lock: Lock,
    "log-in": LogIn,
    "log-out": LogOut,
    menu: Menu,
    "message-circle": MessageCircle,
    "message-square": MessageSquare,
    mic: Mic,
    minus: Minus,
    "more-horizontal": MoreHorizontal,
    moon: Moon,
    paperclip: Paperclip,
    pencil: Pencil,
    play: Play,
    plus: Plus,
    plug: Plug,
    refresh: RefreshCw,
    search: Search,
    send: Send,
    settings: Settings,
    shield: Shield,
    "shopping-cart": ShoppingCart,
    sliders: SlidersHorizontal,
    sparkles: Sparkles,
    star: Star,
    sun: Sun,
    tag: Tag,
    trash: Trash2,
    upload: Upload,
    user: User,
    users: Users,
    x: X,
    zap: Zap,
  }
  const tabler = {
    activity: IconActivity,
    "alert-circle": IconAlertCircle,
    archive: IconArchive,
    "arrow-down": IconArrowDown,
    "arrow-left": IconArrowLeft,
    "arrow-right": IconArrowRight,
    "arrow-up": IconArrowUp,
    bell: IconBell,
    boxes: IconBox,
    calendar: IconCalendar,
    check: IconCheck,
    "chevron-down": IconChevronDown,
    "chevron-left": IconChevronLeft,
    "chevron-right": IconChevronRight,
    "chevron-up": IconChevronUp,
    "circle-help": IconInfoCircle,
    clipboard: IconCopy,
    clock: IconActivity,
    copy: IconCopy,
    edit: IconEdit,
    "ellipsis-horizontal": IconDots,
    "file-plus": IconFilePlus,
    filter: IconFilter,
    globe: IconGlobe,
    grid: IconGrid3x3,
    heart: IconHeart,
    home: IconHome,
    inbox: IconBox,
    info: IconInfoCircle,
    "layout-dashboard": IconLayoutDashboard,
    link: IconLink,
    list: IconList,
    loader: IconLoader2,
    lock: IconLock,
    "log-in": IconLogin,
    "log-out": IconLogout,
    menu: IconMenu2,
    "message-circle": IconMessageCircle,
    "message-square": IconMessage,
    mic: IconMicrophone,
    minus: IconMinus,
    "more-horizontal": IconDots,
    moon: IconMoon,
    paperclip: IconPaperclip,
    pencil: IconPencil,
    play: IconPlayerPlay,
    plus: IconPlus,
    plug: IconPlug,
    refresh: IconRefresh,
    search: IconSearch,
    send: IconSend,
    settings: IconSettings,
    shield: IconShield,
    "shopping-cart": IconShoppingCart,
    sliders: IconAdjustmentsHorizontal,
    sparkles: IconSparkles,
    star: IconStar,
    sun: IconSun,
    tag: IconTag,
    trash: IconTrash,
    upload: IconUpload,
    user: IconUser,
    users: IconUsers,
    x: IconX,
    zap: IconBolt,
  }
  const phosphor = {
    activity: PhActivity,
    "alert-circle": PhCircle,
    archive: PhArchive,
    "arrow-down": PhArrowDown,
    "arrow-left": PhArrowLeft,
    "arrow-right": PhArrowRight,
    "arrow-up": PhArrowUp,
    bell: PhBell,
    bot: PhRobot,
    boxes: PhCircle,
    calendar: PhCalendar,
    check: PhCheck,
    "circle-help": PhCircle,
    clipboard: PhCopy,
    clock: PhClock,
    copy: PhCopy,
    edit: PhPencil,
    "ellipsis-horizontal": PhDotsThree,
    globe: PhGlobe,
    heart: PhStar,
    home: PhHouse,
    info: PhInfo,
    link: PhLink,
    list: PhList,
    loader: PhRocket,
    menu: PhList,
    "message-circle": PhChatCircle,
    "message-square": PhChatText,
    mic: PhChatCircle,
    minus: PhMinus,
    moon: PhMoon,
    paperclip: PhPaperclip,
    pencil: PhPencil,
    play: PhPlay,
    plus: PhPlus,
    plug: PhRocket,
    refresh: PhRocket,
    search: PhMagnifyingGlass,
    send: PhSend,
    settings: PhGear,
    shield: PhShield,
    "shopping-cart": PhShoppingCart,
    sparkles: PhSparkle,
    star: PhStar,
    sun: PhSun,
    tag: PhTag,
    trash: PhTrash,
    upload: PhUploadSimple,
    user: PhUser,
    users: PhUsers,
    x: PhX,
    zap: PhRocket,
  }
  const tablerIcons = tabler as unknown as Record<string, IconComponent>
  const phosphorIcons = phosphor as unknown as Record<string, IconComponent>
  const heroSources: Record<string, HeroSource> = {
    activity: HArchiveBox,
    "alert-circle": HExclamationCircle,
    archive: HArchiveBox,
    "arrow-down": HArrowDown,
    "arrow-left": HArrowLeft,
    "arrow-right": HArrowRight,
    "arrow-up": HArrowUp,
    bell: HBell,
    calendar: HCalendarDays,
    check: HCheck,
    "chevron-down": HChevronDown,
    "chevron-left": HChevronLeft,
    "chevron-right": HChevronRight,
    "chevron-up": HChevronUp,
    "circle-help": HInformationCircle,
    clipboard: HClipboard,
    clock: HInformationCircle,
    copy: HDocumentText,
    edit: HPencil,
    "ellipsis-horizontal": HEllipsisHorizontal,
    globe: HGlobeAlt,
    home: HHome,
    info: HInformationCircle,
    link: HLink,
    menu: HMenu,
    moon: HMoon,
    pencil: HPencil,
    play: HPlay,
    plus: HPlus,
    refresh: HRocketLaunch,
    search: HMagnifyingGlass,
    settings: HCog6Tooth,
    shield: HShieldCheck,
    "shopping-cart": HShoppingCart,
    sparkles: HSparkles,
    star: HStar,
    sun: HSun,
    tag: HTag,
    trash: HTrash,
    upload: HUpload,
    user: HUser,
    users: HUserGroup,
    x: HXMark,
    zap: HRocketLaunch,
  }

  let {
    name,
    size = 18,
    class: className = "",
  }: { name: string; size?: number; class?: string } = $props()
  const family = $derived.by<Family>(() => {
    const value = new URLSearchParams(window.location.search).get("icons")
    return value === "tabler" || value === "phosphor" || value === "heroicons" ? value : "lucide"
  })
  const selected = $derived(
    family === "lucide"
      ? (lucide[name] ?? lucide["circle-help"])
      : family === "tabler"
        ? (tablerIcons[name] ?? tablerIcons["circle-help"])
        : (phosphorIcons[name] ?? phosphorIcons["circle-help"])
  )
  const heroSource = $derived(heroSources[name] ?? heroSources["circle-help"])
</script>

{#if family === "heroicons"}
  <HeroIcon src={heroSource} width={size} height={size} class={className} aria-hidden="true" />
{:else}
  {@const Selected = selected}
  <Selected {size} width={size} height={size} class={className} />
{/if}
